---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iptvnator-backend
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: iptvnator-backend
  template:
    metadata:
      labels:
        app: iptvnator-backend
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: iptvnator-backend
          image: 4gray/iptvnator-backend:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          env:
            - name: CLIENT_URL
              value: https://iptvnator.${domain}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: http
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 1000m
              memory: 256Mi
