apiVersion: v1
data:
    password: ENC[AES256_GCM,data:N311GJEDuzFRj4wb,iv:y0lBxC5+nVgcLOWECWOjD6RBOrlTFqyn9hOIlLGOFUU=,tag:BNRyl/oTEhq7kUnKcugheQ==,type:str]
    username: ENC[AES256_GCM,data:D7dVInQQ+xC8ZiP5spwFvTUeOO5rs9bw16HRmw==,iv:zVtmU1Y4S+FYLI/VX2BEJkmO135sx9bsR7xkVqyBHH4=,tag:lao5Z2H4yQBy1IDavmymrA==,type:str]
kind: Secret
metadata:
    name: email
    namespace: sidekick
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-30T18:34:11Z'
    mac: ENC[AES256_GCM,data:0aG/JSYHvwYFWl4n8rd/Nx7zPIudZ/drNemOfDHfoQK4sPNfVx+7+2kXT422vs2xRCCi/t/r0/Dv4ecvVAXWNr51Uo3K01I6APDaFACm/xEVYomOdND363lD1HfNp7HT0UviYbmI5q+FtCR8+PMlwBKH9MVT6fhr1nF+AQaEV28=,iv:9+5KKEvz5K8GgR46u5693R0rry+vEj46uriBtXoNVlY=,tag:kfXXTZQkPHZVaIiU6tuIow==,type:str]
    pgp:
    -   created_at: '2026-09-30T18:34:10Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAq2E7Cyg9C04IS8SFcuFlFAslMDiEPMryJDOVGdGfLjsw
            4RASaz08IMPLBYX3hH2WjKXbgR2EmUXqlWxkfbMv5pLUuMy7ISvTyWBJ23XCVLPr
            0l4By61WzWqVD78KqHVPafOdzhgQQLaDMnfzhRCTypDOPWVb9rpaUcoKIPzb1h8Q
            JOCzF2tK/+uVt2GWs9AYP0COgeF7nT+RP7klMkIhbF6HpL/TjJpCurpAGNIyOJ8/
            =TYVg
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
