apiVersion: v1
data:
    password: ENC[AES256_GCM,data:EQDSCTudwWVyuVdS,iv:m+aDBlmjZT30kAFtyyEVauwR7o/tWzO5cljpV5Isge4=,tag:iBuV5EOh8lLlxdfwayDcIQ==,type:str]
    username: ENC[AES256_GCM,data:aSnar3H26viQw85f2TH4SSL52CSP69gPLGehKQ==,iv:yMk5W8NvP8bMn4g5g32m+E0whSgbbAgO6+adZ0W16d8=,tag:JEGw24a9a0C7+ZHKKTc/jQ==,type:str]
kind: Secret
metadata:
    name: email
    namespace: sidekick
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2023-09-11T16:31:55Z'
    mac: ENC[AES256_GCM,data:TMnWyygYV+K6R5++Oic1kYdWws3vHj33q85zLQTkg/b1md71PXiSJLq3rJV3AADk8SkUH2kV1XxL7yRiCTFT6d7Iiun2XqpUP0al3+jeAfyrdarZLsvLzmG46jDoTlGGh6HICoKOV0FzrpTKYLxLg36eL33Ci4KPCPwLf+hCzb0=,iv:WjMoF7ntj8NLQuGGpj+9sNkESgetaSBqtfb5oDFAIF4=,tag:o9Z+ZMMHmpRkgMCGl9bYPA==,type:str]
    pgp:
    -   created_at: '2023-09-11T16:31:51Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxv5FnUBLaS9AQ/9E8P+wUKHmmZxtRfxaWaW+f/I+1gNzvAMBLW80QfOR+NO
            mEuKtRb6sMgJOnytdW30GNMc265lXWqU1LGDP5F5fFsfCzSPr+Bu/BnVFa3qnavM
            09kdUXf/Umb3S3pAQwT+6CUL3h4b3/31WwYb1fOlnbEa90j3uE/1LbnWwz6PSRfi
            FybdKIeeNdYMUkSysRf6Qb2BpbLSQgCBjhRmCxhzIyyGW9UdSdu8fRgeYnovaLoY
            5ddQwBiaZOn9AczmlzalYBj/hA2ce0GZRB4IMWksVR1E5cdN/gSD4DbUCVPVPATs
            tCHKCmK91U1LIT2tPbZJv/sBAfyq1PIW1LYELzlDyKvVotIWpZBw1jNZUwKi1bFY
            VffWYdHlY687igG+MQ/HFFnjW9GYqXsZbaXt7EB9tMLHPkyi8Xr1J/UR/mLcNJ76
            i0eXaqx3EKjiGI/6uJ9TBqQ8Hq7RDLt0LBSRGwV/m88xZqnY6wVhu/9qaQExpCTK
            83yhqldoJzayCUS1VBRsrLSqs/4HicWZmbDbbw2ppAfWmtDHNRaEEItMJR5MM+9W
            9ojNeDVwagtdhLRevb3n6HWMQr5hFHYPJ4PKRj4DU/LHRCHr66aWTZvBnsFB2T6K
            5WWtat04k3uuzY2FJhhrKfLq04Vq2cfYk6YCMR913epbLpBjydy/NoCQcMWepjfS
            XAFSTea/N3s6TSU5RRtunxftZX0hBP23xLKhMGweCTE4p6ZDzu1ZAfMTRre0qex/
            GatTQtRNJbbMIs/efIaGLnAd7ZRFKyeD4K3+O7hogZ+hqkzrqWSdTtxppSVd
            =JSyS
            -----END PGP MESSAGE-----
        fp: 0BCA2EF044187A707E2507E54C4527913792AFD8
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
