apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adminer
  # - blocky
  # - browserless
  - cert-manager
  - cloudflared
  - cloudnativepg
  # - commander
  - external-dns
  # - fan-control
  - gatekeeper
  - grafana
  # - headlamp
  - http-echo
  # - jellyfin
  # - konflate
  - kube-state-metrics
  - kube-system
  - metrics-server
  # - nats
  - plex
  - pocket-id
  # - pod-gateway
  - proxmox
  # - radio
  - reloader
  - renovate
  # - rustfs
  # - sidekick
  - syslog
  - tailscale
  - valkey
  - vaultwarden
  - vaultwarden-kubernetes-secrets
  - victoria-logs
  - victoria-logs-collector
  - victoria-metrics
  # - whoami
