apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adminer
  - atuin
  # - blocky
  - browserless
  - cert-manager
  - cloudflared
  - cloudnativepg
  - commander
  - deluge
  - external-dns
  - external-services
  # - ferretdb
  # - freellmapi
  - gatekeeper
  - grafana
  - loki
  - alloy
  - http-echo
  - jellyfin
  - kaniko
  - konflate
  - kube-state-metrics
  - kube-system
  - maddy
  - metrics-server
  - nats
  - nfs-downloads
  # - omniroute
  # - plex
  - pocket-id
  - proxmox
  # - radio
  - rathole
  - redisinsight
  - reloader
  - renovate
  # - rustfs
  - samba
  - sftpgo
  - sidekick
  - syslog
  - tailscale
  - valkey
  - vaultwarden
  - victoria-logs
  - victoria-logs-collector
  - victoria-metrics
  - vpn-egress-gateway
  - whoami
  - zipkin
