apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - blocky
  # - browserless
  - cert-manager
  - cloudflared
  # - commander
  # - crossplane
  - external-dns
  - gatekeeper
  # - headlamp
  - http-echo
  # - konflate
  - kube-state-metrics
  - kube-system
  - metrics-server
  # - nats
  # - pod-gateway
  - proxmox
  - radio
  - reloader
  - renovate
  # - sidekick
  - syslog
  - tailscale
  - victoria-metrics
  # - whoami
