apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: csi-proxmox
resources:
  - https://raw.githubusercontent.com/sergelogvinov/proxmox-csi-plugin/main/docs/deploy/proxmox-csi-plugin.yml
  - secret.yaml
patches:
  - patch: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: csi-proxmox
        labels:
           bundle.cert-manager.io/inject: enabled
    target:
      kind: Namespace
      name: csi-proxmox
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            nodeSelector: null
            containers:
              - name: proxmox-csi-plugin-controller
                volumeMounts:
                  - mountPath: /etc/ssl/certs/ca-certs.pem
                    subPath: ca-certs.pem
                    name: tls
            affinity:
              nodeAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 1
                  preference:
                    matchExpressions:
                    - key: topology.kubernetes.io/region
                      operator: In
                      values:
                      - metal
            volumes:
              - name: tls
                configMap:
                  name: homelab-ca
                  defaultMode: 0644
            tolerations:
              - effect: NoSchedule
                key: node.kubernetes.io/nuc
                operator: Exists
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/name=proxmox-csi-plugin
  - patch: |
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: all
      spec:
        template:
          spec:
            affinity:
              nodeAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 1
                  preference:
                    matchExpressions:
                    - key: topology.kubernetes.io/region
                      operator: In
                      values:
                      - metal
            tolerations:
              - effect: NoSchedule
                key: node.kubernetes.io/nuc
                operator: Exists
    target:
      kind: DaemonSet
      labelSelector: app.kubernetes.io/name=proxmox-csi-plugin
