---
apiVersion: v1
stringData:
  config.yaml: |
    clusters:
      - url: https://proxmox.home.arpa/api2/json
        insecure: false
        token_id: "csi-proxmox@pve!csi-proxmox"
        token_secret: ""
        region: homelab
kind: Secret
metadata:
  name: creds
type: Opaque
