apiVersion: v1
stringData:
    config.yaml: ENC[AES256_GCM,data:+agMBRhRGeIWdbe4qbE3PO70k5gc3DhqRkSfAyQC0jHwxsnJ6Dcjp1cQqRzj31PB5nmrklT2w02BFzWu6/YmEa76d9VbCX3l1h4ZEo6QtZzu42YylHlMMkmt8DlwBof4rrle/cE9qtxp0+uJPSf7aCaJO0wq/VO1DwmGS4I17lAkNchuHJUwHklYDKDRV+w2QHHsbJkX0vF6e3zsR/Y+dAywjZlS5tXPNMpkPkmspJlGKREuc7TGu7BTIQ5p2gXtKKsueg==,iv:G3v+pVAcXIX23BPYMs8TQW5j05xnY/Bdgnksrn/oYFk=,tag:z+zFpQCh4r7O+fAifEEgXw==,type:str]
kind: Secret
metadata:
    name: proxmox-csi-plugin
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-12T12:52:49Z'
    mac: ENC[AES256_GCM,data:xagMVHAH0Rjxe80Ax7+9jQGArQ8PDevUj3BNZns/rpPbK3j6JfTIfIBvgY1EBxkcYSOosM64mIt9nujiCW0CTc1TDjUxvG4wptp9YtheHszVp0unC8EKbJVvcf02CkLdvuGTYBgdqvoc1RpJJTLTpBezE+ioHt4rlaHoJtkEIEQ=,iv:H8FGIURNrPndwJkbmZ4vSnakR6TyPcACi4Pj4ApBxOU=,tag:0fJk4F07NFv312S6zLAJbQ==,type:str]
    pgp:
    -   created_at: '2026-07-12T12:52:48Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAgLWDATM9RJqfx4cpFWk9mqcEgq1K03bduG8FM0C+Inww
            F4A0HAeBK7uEiDMAMffSFjoOL0GpLB2i0upAF5PpbB6KwLgm9fnQLAkflXLhbOP3
            0l4BYxa8bQooHtTAkGkdUQFx3XD6WEYp1ZOP7Le91FB5IaEMU9O1oBNXoLUXuKRC
            JE9TNNshc8F+hbZu8WpLsuSpDBgprgtal+fQUj+k+q3mUahFPq0EuWo5m1CMUeN1
            =sxFD
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
