apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: proxmoxroles.platform.shokohsc.com
spec:
  group: platform.shokohsc.com
  names:
    kind: ProxmoxRole
    plural: proxmoxroles
  claimNames:
    kind: ProxmoxRoleClaim
    plural: proxmoxroleclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                role:
                  type: string
                  description: Proxmox role name
                privileges:
                  type: array
                  items:
                    type: string
                  description: List of Proxmox privileges
              required:
                - role
                - privileges
