apiVersion: v1
stringData:
    TINYAUTH_AUTH_USERS: ENC[AES256_GCM,data:CJqq2UdJaRH8lpywQDkITuiLNnGAcOmEiyiVRPHHHGpPzLX90prQLxqrc+spsCpWz2elnGrwO3sKFG7YO85aeK72FV/Nw9+y,iv:ysGlwYt8lma0Md9iCiKIR1Z8MX59NXsHfXBWp9rGt6E=,tag:oJ/CSz2+JrmxzE6blqoNrg==,type:str]
    TINYAUTH_APPS_POCKETID_OAUTH_GROUPS: ENC[AES256_GCM,data:fzE+xvlE,iv:NaPSfw+6eDcvRDtry6pn7AEwp0scm3cKEc3DreCWXj8=,tag:uiud25xVdmsN9U//qn+DOA==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_NAME: ENC[AES256_GCM,data:5DLNaNlqypV+,iv:IJyhKjRgfy/xKICuDTlHzcemj3SmeMsLQdyWkrS5vIA=,tag:QSlT9BdLH6QYBkkmoWnP3w==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_SCOPES: ENC[AES256_GCM,data:jY2yFRdUK15+MWJ/USpPzH8LpWVP+XqZD2j2,iv:lngE1QvJtUjqjsnwm6seJg4LuponTds+5D2FKUq7aIw=,tag:/abF9b+j3GNmzngwIlQiPA==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID: ENC[AES256_GCM,data:iPqFEbHGNxWPMjWOc2HHjw9b3jAwu8/58EQQUtqVW5GfhwAM,iv:rAq/BtL1/t7hTBkq6gshpj3uu5YKkLub92/wiOF8NJA=,tag:038rFEGCQEUxKjeqpwqvfQ==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET: ENC[AES256_GCM,data:3tYChlX2Kw9uXPiNb05CYP62frPeYxDwe3lxNJhu9Ps=,iv:0DhqtNAn1sMPYXbjk+SD/NXAt4oXj+zbWeAiuCBAbY8=,tag:jhXkUfMmFCY4BNRlC3Bk8A==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_AUTHURL: ENC[AES256_GCM,data:crjFKwf2RP7m5pEsdRVfgpNv520Q2o+3XRYVBw5MnDd0f/VpXg==,iv:iQJIO/RTtg9mH071kP+yLU9r5imiom/ucLcJZEAIkQM=,tag:DPBcRXIhWOa8HdjbxHz6KQ==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_TOKENURL: ENC[AES256_GCM,data:Xnpzb7n3rOTFpgE5wXf+3auX3exggOR5uKbozF2I7oS/6Lw6T/jKxr6G,iv:0b9LyH/94UIqXN96VJvue6zQ/ovBCOZy2zGZpJCqzQw=,tag:O9TIvrBqLqRuzzspTkM1qg==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_USERINFOURL: ENC[AES256_GCM,data:Z+EQi2bgY8CNyPJ93Pbl4LqZOsNFo42p1WPRocMaZzC4tALG3RkvhlsB2G8t,iv:xutD0zeLrrbJB2UNGksatxs4rNmVAgeONlCbQ/6d/Oc=,tag:O5ACPx1hZuaQwfrHc9xQLA==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_REDIRECTURL: ENC[AES256_GCM,data:kipR5DeQVmKhVILP1c2z3IU/QOOdVrDRBIccKNTWJwiI4V6QkuxRVAJ3fTeZGBzNT5WFbjmHZw==,iv:+JJjYqWuwuF5A2DkkVn/dAD0JHwxLSVZYJu4b6K5AbA=,tag:r1miJtjbHFLFby2lE0ywkQ==,type:str]
kind: Secret
metadata:
    name: oidc
    namespace: tinyauth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-30T16:28:42Z'
    mac: ENC[AES256_GCM,data:/VIEIR8HPsuOCCSVR8Rp1Zh/pCw4UTCFoPzpl4QbT8G7RC6bY0kbBdl/7eaiikvqHxk4zIvOSpIch8Ivqg3oTbANpe3EZfqos9ehwWAm8swX+SPVRlQkC0xnOb0oDOTtHQfqfpjAjo2lARQMN6zsBUKCKwePERp7dwiqN2rGAAs=,iv:R4NXzPIDcSaIs6hqTj37YjIwAiH5AXngk18EPwZ9U1Y=,tag:tVg478yWn2SKvexKWkolng==,type:str]
    pgp:
    -   created_at: '2026-09-30T16:28:42Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdArxFY6RqtHN4p5ebL575nRWzKDKStp8VgSjVFrDYYVR4w
            /DHKtSKMfVbwyxQKSJJv4OVNJOT75Y6l5BtSpEMGia42JuTm+ZSU8H/gma415s2K
            0lEBwRvMsAjh1qJozt1KRSu6XTan/jY4ru4+jLLGKuNySEvmRsaMsL3MCbr7JU9I
            EQZvgHcjmvhY4fFThAw0caWUVyIS4D6aZahgQXcabz9HFRo=
            =36Sm
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
