apiVersion: v1
stringData:
    TINYAUTH_AUTH_USERS: ENC[AES256_GCM,data:fnkc7uhayfsHO/wA6Xu4f+jK9VXpIVtmvOw5B+ML14oOu8rahBjzDVjn3MhFN+bPwKv1gvSmnplHb+9lN9fwP3KqJBlKgHYo,iv:nr7211IQxikL+uFg3kOLo5yN3GqaH1+ow6g3GAQeE18=,tag:1FeaoRT4xv39qDznfRuaVQ==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_NAME: ENC[AES256_GCM,data:uEvqMrIQvK3N,iv:bR4PD44aeWfc9XD+SKyiiMVhJKu2aB8lgbRX1GhgVGg=,tag:miu+tHRzI6ZoKhVDAIqaVA==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_SCOPES: ENC[AES256_GCM,data:tCmPpuFJAdqOf8Gwh3elc/qJ6Pf7Q40Mtuit,iv:lwS1AQhIS8kPNwLlw2yqKF36xMVeaTObFTiIE9v+fWE=,tag:E6WE+I5eWh37OCa150IJsg==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID: ENC[AES256_GCM,data:d5tyfpwOMi7Zo4meYafuzv+dvZHwOyfIKC6f4bf3xF7DPXcR,iv:mF+kM6HPvmWBU7OcoWLE9nY2pHAkwTYk9LNBjptb/H8=,tag:p5L6pvwg0WqIPaL+ZdjWkQ==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET: ENC[AES256_GCM,data:es/usTlxhVEo5XV6tCL78wwrLDw2p+OzjnmHrNWBdAc=,iv:SctJvND/MpM1mI7vpoAdVxxO2l/vnWHadmGWp2PQmO0=,tag:31m329/hwb2eLWb35BkzlA==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_AUTHURL: ENC[AES256_GCM,data:InIQwCzldB7k+P/ZxGJ6L2c3nLhz/SRDBOL4S/yh2G0XjhAftA==,iv:oulVRvqQ9/GVBXqt+kHfV5Un8MxDfC69DacQR4BY+eI=,tag:Dj9XpCCPFczeR1F/OwyQVg==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_TOKENURL: ENC[AES256_GCM,data:OZ0HUusgQXV6jwuYv2fbDNRrp5X+RpwMrVoxdqGYo7rJcLl2ha+oHaze,iv:vqFmkF3QmZrMQwoqmuuC7v9Ok1ynylYljGkG4mbUZmk=,tag:iD7cZWHiOgIlH7OWIIaNHA==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_USERINFOURL: ENC[AES256_GCM,data:T2e/n1CikPIGJ/7IFSeumfOVEBOQjmLYr9mSTdHvOUYkiFuC5BItKTSWlDIx,iv:bSXW59nSvFu6nL8w3rAQfLZYpsmW92zLaTDa5EESED4=,tag:0MJriVNPdVx/j6zGNVxnGQ==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_REDIRECTURL: ENC[AES256_GCM,data:A/3siqz+qtTsQp8P7GHNhUSS+UXRiAx2Ll+aAHtzAs06BJKQny0Y7/oVPNnd21PVBDWOWkuWjSo=,iv:lh2UJ94Fo0nlRqxoKrDFrjWgLB3FIbIYUr4/hrSdQk0=,tag:3t3Z09Gl+mrX2BtMWmKCsQ==,type:str]
kind: Secret
metadata:
    name: oidc
    namespace: tinyauth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-30T15:44:27Z'
    mac: ENC[AES256_GCM,data:cJv9qfqNgBphQ4KJPLE7p+rRSCKf47/UvlZ6YOjVI8OXAru48ZosCIL841zAxaa8RBjgvxE8kZuYmiJIX2dEvgjFks7Hg4pRsDAjfPvyoNQARTujvI3x95lE/uAfPZt4zOCadgtp0KC9YjMd7phFdvt+hiIoVAK4D/EhIkDy8eo=,iv:w/NNgzmBd5dBdcxCysKKyhUON4kufVdl8fLiXx/BxxA=,tag:hrxWHrJRcmMtEQNqgzwc/g==,type:str]
    pgp:
    -   created_at: '2026-09-30T15:44:26Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAMfYzPZeTboub5z56PKa/szUzQ3wOg75ijJviugPLVykw
            9a0KJv2O+nuJzB2QfsyBiaQp8lQkjbE6MycIEGpyPkauDNCfX2qxvVQm1QTaEfqV
            0lwBTigCE5KfFWOXvIr9BxJpkFLZASO16HJCCgkbNnLZRLlq/JM9le9Qf4jeQX5H
            1AyBZJPxGWex4vj49GL49m/3oPWQXOeA+ZKJ1ifoIEdCUaM95l4u8CEIYoxgdA==
            =I4gb
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
