---
apiVersion: v1
stringData:
    TINYAUTH_AUTH_USERS: 'shokohsc:$$2a$$10$$Isj1P8zo6wgy029klfCd.Oe1.GUzEQJliAoB12FAzH3Vo7mqu0RJy'
    TINYAUTH_APPS_POCKETID_OAUTH_GROUPS: admins
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_NAME: "Pocket ID"
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_SCOPES: "openid email profile groups"
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID: f7997b10-8aa0-445f-b935-39a447fdb0e2
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET: hZHMB1BDKUwl3K96M5TNpeKywOiP1I0l
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_AUTHURL: https://pocket-id.home.arpa/authorize
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_TOKENURL: https://pocket-id.home.arpa/api/oidc/token
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_USERINFOURL: https://pocket-id.home.arpa/api/oidc/userinfo
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_REDIRECTURL: https://tinyauth.example.com/api/oauth/callback/pocketid
kind: Secret
metadata:
    name: oidc
    namespace: tinyauth