apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - provider-config.yaml
  - proxmoxidentity.yaml
  - secret.yaml
  - https://raw.githubusercontent.com/sergelogvinov/proxmox-cloud-controller-manager/main/docs/deploy/cloud-controller-manager-talos.yml
patches:
  - patch: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: kube-system
        labels:
          bundle.cert-manager.io/inject: enabled
    target:
      kind: Namespace
      name: kube-system
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            securityContext:
              runAsNonRoot: true
              runAsUser: 1000
              runAsGroup: 1000
              fsGroup: 1000
              seccompProfile:
                type: RuntimeDefault
            containers:
              - name: proxmox-cloud-controller-manager
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  runAsNonRoot: true
                  capabilities:
                    drop:
                      - ALL
                resources:
                  requests:
                    cpu: 50m
                    memory: 64Mi
                  limits:
                    cpu: 200m
                    memory: 128Mi
                volumeMounts:
                  - mountPath: /etc/ssl/certs/ca-certs.pem
                    subPath: ca-certs.pem
                    name: tls
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution: null
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 1
                    preference:
                      matchExpressions:
                        - key: topology.kubernetes.io/zone
                          operator: In
                          values:
                            - metal
            volumes:
              - name: cloud-config
                secret:
                  secretName: proxmox-cloud-controller-manager
              - name: tls
                configMap:
                  name: homelab-ca
                  defaultMode: 0644
            tolerations:
              - effect: NoSchedule
                key: node.kubernetes.io/nuc
                operator: Exists
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/name=proxmox-cloud-controller-manager
