apiVersion: platform.${publicDomain}/v1alpha1
kind: ProxmoxIdentity
metadata:
  name: proxmox-cloud-controller-manager
spec:
  user: proxmox-cloud-controller-manager@pve
  passwordSecretRef:
    namespace: kube-system
    name: proxmox-cloud-controller-manager-credentials
    key: password
  userGroups:
    - proxmox-cloud-controller-manager
  aclPath: /
  tokenName: proxmox-cloud-controller-manager
  groupName: proxmox-cloud-controller-manager
  roleName: proxmox-cloud-controller-manager
  privileges:
    - Sys.Audit
    - VM.Audit
    - VM.GuestAgent.Audit
  groupRoles:
    - proxmox-cloud-controller-manager
