apiVersion: v1
stringData:
    config.yaml: ENC[AES256_GCM,data:VW2oGKR6mRD3lDDve9EgyiJz22m3GRkb1QgsCkzAYGG0IF5lt/ZrOAhwsVZmwsAh/eJUABU5zGaUrg8j7oixGEVbDQBpFUj2TrEPbKng+vU22O0KjsE+6+t3CpVauKdckgk0mSKDskoYRoaFyrFUeWCs9fY4dyZGAnwzR85OEhjAq58GM6FFgJqqPlmmUywBDpoDLTXmj0NyJQ//NdZdl7PDx1EpkdRTmab0Hto92VX/fjIZ2uu4jZt39Es=,iv:TieT+aDpTZ6WMtoYzXcaHAUKZ6LPc1KDTwiUWgnNaz4=,tag:+jyUYGuVNcelVBEVzEO7xQ==,type:str]
kind: Secret
metadata:
    name: proxmox-cloud-controller-manager
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-27T19:16:56Z'
    mac: ENC[AES256_GCM,data:eu1Law8luQecnqhGtQO0sxOE9DaeSJbwjUc+htk1Ab7jIYEw9E34+XIhQN7rjflfOaQPl9OxB59c61HEPqNjb8HzwZzInUFmnIOVYKmrU4E6CR9sENxUvRGfQHPpiPLyVln5EgoeLNPK7da8swsc8t4VD1IlW/7ZuCd4XHLXJ5Y=,iv:cfUBKnNS/qtzdsbIfTy7HDV3VJWqrSLmtyPznkrWryM=,tag:Fp5Tf6SrxzmCOX4KZoou5Q==,type:str]
    pgp:
    -   created_at: '2026-07-27T19:16:54Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAuuG6QOlH3JyMlVLDrU5+LSN+nHUCIb6u6d3BFyzpCmUw
            BG9JsZGH251EG80E1uNPC1klP5uLB4CleTJNASAdhX2JoO7wzVHrYq4E7Twf6GY2
            0l4B+qhPfqeIPhH/gGJqGMKK4NojKM9IGk1W243OLufhfQVf/tjZtFMwgCFJ07yz
            O26VA4tu7VUsMSMj78VXW0SLgfVALHo9SGcq1q4syjOID4l6t1HJiLg4jkFXYIZq
            =4feM
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:CpEsZAqyAvwG2jiXoV2uMmsoUDT6KfYrxb+nhjni2e4=,iv:7sSdw0gkDaLifZcfmQtV7nN2Q0maA45d1ZD44wG0+1M=,tag:NhQNsaBOVhqq+rOZ8PRFKQ==,type:str]
    password: ENC[AES256_GCM,data:6pMUMxdQnwttvZ2d6q+kQm9iwkU++f7/nb3lxawAQSwN5Nmh,iv:Iyt5H0AIcfQ6hgDzhq/n39pBKGQ4hZfw/DoOL9nBXAE=,tag:Y0tQDpUELTkNVWZPXMlKfg==,type:str]
kind: Secret
metadata:
    name: proxmox-cloud-controller-manager-credentials
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-27T19:16:56Z'
    mac: ENC[AES256_GCM,data:eu1Law8luQecnqhGtQO0sxOE9DaeSJbwjUc+htk1Ab7jIYEw9E34+XIhQN7rjflfOaQPl9OxB59c61HEPqNjb8HzwZzInUFmnIOVYKmrU4E6CR9sENxUvRGfQHPpiPLyVln5EgoeLNPK7da8swsc8t4VD1IlW/7ZuCd4XHLXJ5Y=,iv:cfUBKnNS/qtzdsbIfTy7HDV3VJWqrSLmtyPznkrWryM=,tag:Fp5Tf6SrxzmCOX4KZoou5Q==,type:str]
    pgp:
    -   created_at: '2026-07-27T19:16:54Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAuuG6QOlH3JyMlVLDrU5+LSN+nHUCIb6u6d3BFyzpCmUw
            BG9JsZGH251EG80E1uNPC1klP5uLB4CleTJNASAdhX2JoO7wzVHrYq4E7Twf6GY2
            0l4B+qhPfqeIPhH/gGJqGMKK4NojKM9IGk1W243OLufhfQVf/tjZtFMwgCFJ07yz
            O26VA4tu7VUsMSMj78VXW0SLgfVALHo9SGcq1q4syjOID4l6t1HJiLg4jkFXYIZq
            =4feM
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
