apiVersion: v1
stringData:
    config.yaml: ENC[AES256_GCM,data:9rRvpwVJivy1QXvDS4PhBMR/q0zjxpzcOqZs6OiNdBkp7Svhuu9dkZqDtJe7hSzMvWRIQpxwJLRh/Ji0Mm6u1seWhIXi6P5/2NOt0Tcz50/xZ4YMR20Luv1OUZAqrZEKdQjefJrtgDQ6MUJaR+CX77zB7AH3rdVHSKOvm+OjopMz+46R6nvMMD77i7OyFqOb0E0unKqu5L2iMeYeIyMqz+ZmYVTobjWZ9mlZ,iv:BSFxunF7DLVzwbh+aOXof9QD1r6TxzosMAKbKZkmnSU=,tag:nN1taHEN9oezkezdk5iygA==,type:str]
kind: Secret
metadata:
    name: proxmox-cloud-controller-manager
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-27T17:49:16Z'
    mac: ENC[AES256_GCM,data:KLeuZ9SnxNogbxbGMz1u9GnWgfnXIrXudsFlNuvGMvnNK1K5qYaITzvHoqIMesxtXpxjFV4o6a0kOt2DHgyNvaUl3cgqZPypTZ/XWrZS9os+01owEbgl83cMRtaM4aRgTEE+c3wW6HG9t59l7hcNwEw07IfUr51s8mpvBJHEW0I=,iv:ySz9gQ4iEnZwuhbgSbFVyFD9xcd/tIT2skq4okywi9M=,tag:YezSZz8VKbEUOBsrmJpuxQ==,type:str]
    pgp:
    -   created_at: '2026-07-27T17:49:15Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAFqZorl4ozmToQVI9/E7EBnQd0zYHfLl795z0KHo9Pxgw
            L01g2SR3OY1cFWQ62iB2j7BNraSbvyfUYJ1UvbZE6gOYeaVUi0hFPp1rr3qOvmWF
            0l4BK7BXlP3Lfkhq9EyGiC30stGo83ypy1D3HOBtYMNkDI6pjMf1t4qrzm+tRAdy
            lg2Iuomaej8GzmST0wH7zL170qIkzFiPDC1n9P5+yxoM5CDy5/mV4Ooq+Op+EQs0
            =fJ1Z
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
