---
apiVersion: v1
stringData:
    config.yaml: ENC[AES256_GCM,data:LOAyUfuxOfisE9Bp+0BN/gHUQJVDsImeyYqsnw0IJd4A96skUDu4FQ8unBp5wMW51MzdMDQg3e7aNCYcl4oQhdakpnXDL9UclJ9p5nkYzRA5djVQfxwLS4ZOuP+s94KBU4FQ21YzOn7unswXejiAXnCMiprf/F/bBGFsQ41LYqgoHDeU5NCm6Bu3VPP0K9faAq4dmqwHWztRwK8i2+Bih1uFaXxEAHTUtdDPTkmHPaLC7Dnn1w==,iv:bz0gjZF+J3Gtiir//n33ltdjYLNgblyPRFNtZlRwn6Y=,tag:uBfEC7UUC+xw1Ysl2lcdwg==,type:str]
kind: Secret
metadata:
    name: proxmox-cloud-controller-manager
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-27T15:53:38Z'
    mac: ENC[AES256_GCM,data:CR00ycsUn+tmKti1DUb+m25OYQk31UKl3E8t1QmvDHuCNtdjauOzFN3bpP9mYxVfx/InwBjwoJnAS6Mb8t7FucoDubKhMPk+t89gkw1n8hGOsjxiVq5ny3j3Ye1zK25JZEV5TYslno13FtOcVc37EKvEDhGz6gg4xtiLwMHOb9Q=,iv:gh5wcsyNT9dUNBg2ER0la5mObI2CB69juG7RUR+zMok=,tag:GnJayEUKhwig4dDDjqqa8Q==,type:str]
    pgp:
    -   created_at: '2026-07-27T15:53:37Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA8s1CfkPSdEUcij1GYoUSyQjd7L/2V3/rJ3YSbf0hQi8w
            smSpkBXG+YwBDQihUmM4bVI2H9M1OKO8T1PntmIu9NXTW9N+rcdq9yiMznEixC6d
            0l4BhBkUQVdAzIKzseJ4HEp+G3uGvpsM5teTum7mGvxosv7aWwJKtMgZxW48kivF
            IVxCkOmPbPzhnMNQNkqMmM/75M6+MPu92AqyxeGsi+PumvsRZkWgWNhs5YaWm53Z
            =t0wZ
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
