apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      group: kubeopencode.io
      version: v1alpha1
      kind: Agent
      name: agent
    patch: |-
      - op: replace
        path: /metadata/name
        value: buzz
      - op: add
        path: /spec/templateRef
        value:
          name: homelab
      - op: add
        path: /spec/share/enabled
        value: false
      - op: add
        path: /spec/command
        value: ["opencode", "acp"]