---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cloudflare
  annotations:
    configmap.reloader.stakater.com/reload: common-env,config
spec:
  selector:
    matchLabels:
      app: cloudflare
  template:
    metadata:
      labels:
        app: cloudflare
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "3030"
    spec:
      containers:
        - name: cloudflare
          image: shokohsc/moleculer-sidekick
          envFrom:
            - configMapRef:
                name: common-env
          env:
            - name: SERVICES
              value: cloudflare
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare
                  key: token
            - name: DOMAIN
              valueFrom:
                secretKeyRef:
                  name: cloudflare
                  key: domain
          ports:
            - name: metrics
              containerPort: 3030
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: metrics
          livenessProbe:
            tcpSocket:
              port: metrics
          readinessProbe:
            httpGet:
              port: metrics
              path: /metrics
          resources:
            requests:
              cpu: 10m
              memory: 64M
            limits:
              cpu: 100m
              memory: 128M
