apiVersion: v1
data:
    domain: ENC[AES256_GCM,data:usK//dd8gw1C6mCw17nhAQ==,iv:nvm3GD84wMi0btlY84xLLSTzyISWti7glh1hV7AWcb8=,tag:QKvrFxl12LjLhNhBGqNbIg==,type:str]
    token: ENC[AES256_GCM,data:Pj2HWvC71f3E2/hYRXy1rRb6Z+w7sgBpnWSa6+PUE4EDo1PSlGOIThepNeTXbo5uPu7rtaU6q1Y=,iv:EzFv23J5QU2FO2LQNZaQ1G6gh0fW2nc0KLK8z9vUnzs=,tag:++xlTNRT8FxIT2hNjSVpvw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudflare
    namespace: sidekick
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2022-10-06T21:00:49Z'
    mac: ENC[AES256_GCM,data:Mgrl5a+JYuPS6NwSvP/eGx5HHwL0hhu4PBoKYjsXszAwYhUGmA+G62ZIrzuX741yHDFY1SBK02sfaxkj7mFTc1qa3b049owd/JPNAKGwEppykJ/74dT292AO4yq2VKy+vYoZIj0JuZa231okbSB+nQbGVUtNnibwXfR5v3v3gg8=,iv:kfl2nzRdMcDgKBZ50LA9qZIk/EUQS66of69c/NUpE50=,tag:8Mkw4xt8+lVrm+/F4LAPPw==,type:str]
    pgp:
    -   created_at: '2022-10-06T21:00:48Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxv5FnUBLaS9AQ/9EDMAY5cLklka8i3FoYGwVld+SV2GtNPxK2Xh26zzen5x
            bltzVLkrr/HCqp2iofpnuFYxI/5DG1TOBX8diof7d2/WD4akE3QEJXpG0KaYu+H+
            3rf46TIbn/bkGJShgWRjj1CldjElh39NBaZk57EnfNMN7fkZkkUGl2tpvMEVDvpF
            x95iGOpsy1ya2YIZmhCSkWy/dPzUFBKbot/RxkZEZrD/bflowPASgFSceNjz338M
            ssO/QCBptfLYonUWl4OPzKcXPzSurdQ6njISqW67kkVTYwHkynVZ4hbQAOGpDJsI
            eBxH+tGZb9o4PxyTY7qtJxyq3wqHJdlReOwJIp0ATgmXgb/rt0S3bFuW3zutKKk/
            KIU3YlkEq7t9SV0lDSvK2AYdtZQ7cqismJqkn/XEpNvgW9QIvDaw8LcR9DGAoxkc
            SuEvumakP6RaITwWdVV6Aed7pOxLvBOtqVBX7H6nHiZLKqeoYTd0JOkV805qXu+H
            Gk+UJ1H5ZGg3NxoUc1JuuJ+mUslYMg15zYtC6mdH5q16aHg1AQwP+PEOATy0cwmJ
            bpDpipaRTlcB7kG8OaekzHF+zp3ZCwArkcUJy3LS1CPJUpd+NHTO9j4INpAFB3Gw
            3Zkx15Pttohrir3L0bg+7ZsZ4m25j1+uKzKsk8nETJsC8JBW4XKx4DtQPAaBswjS
            XgHrvob8RmRWK6/OAIMfSLYrHmVrDp6saPbhbhYLp4OEMbTZldzerMLtKQb6dUku
            S5HgAM8j/p6COIT1ZLdaSZAm22osexHvahvAFKErp8Dh5QkkoUFhpENQZiOIdvU=
            =+mAS
            -----END PGP MESSAGE-----
        fp: 0BCA2EF044187A707E2507E54C4527913792AFD8
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
