# ---
# apiVersion: postgresql.cnpg.io/v1
# kind: Cluster
# metadata:
#   name: main
# spec:
#   instances: 3
#   storage:
#     size: 1Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: test
spec:
  instances: 1
  storage:
    size: 1Gi