apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system
resources:
  # - deployment.yaml
  # - service.yaml
  # - http-route.yaml
  # - rbac.yaml
  - cluster.yaml
  - routes.yaml
  - secret.yaml
  - database-roles/atuin.yaml
  - database-roles/maddy.yaml
  - database-roles/miniflux.yaml
  - database-roles/pocket-id.yaml
  - database-roles/prowlarr.yaml
  - database-roles/sftpgo.yaml
  - database-roles/vaultwarden.yaml
  # - pooler.yaml