apiVersion: v1
data:
    password: ENC[AES256_GCM,data:Q456cv8GT7WBJI3x,iv:l4rMGvmxQhextIPYrIurFC3/hi538zji/a0HQtswdFM=,tag:Cmq7FPOu+ZE9KQF9gfEemA==,type:str]
    username: ENC[AES256_GCM,data:d2+aVvfb5vGgMdyS,iv:fErIEg/3yHvwwif0pEqLvXNi+DmeQXseXQVCJeGixPo=,tag:r07Ye3vMZbMR8sSF2lZVfw==,type:str]
kind: Secret
metadata:
    name: postgres
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-23T17:24:00Z'
    mac: ENC[AES256_GCM,data:Oe4YP0+CZIARkpODguef5cWNQnwnx5Lopw/wXQZHDSP0fEvdwYKiVZGEaM7d/K5/EhEtMf42vmtVjFCDMb+i1AjV7qE/i0qYJDzGFXWe14XyyTmM4lnVhinFyKO9A9rpCwzVDypB6fTia60FI4ZuwTwmITTUZsHSY8uwG9gi3ls=,iv:YA/96awA3JXe6dWqJFOOrBCdyqAAKi5X1N16AkUmmlU=,tag:hfauIoSh6AbDZ+ih5XO71w==,type:str]
    pgp:
    -   created_at: '2026-09-23T17:23:59Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAXzaIBV+EATRaRIpNiCo6t5hDaEbyl/U3JwVLZeVO+WMw
            Hv3AhsKbKBtNavnnfZKmvRHqNHImfeU5hGusZvfJXrC1ISbe5W780ql+3ABXKkn4
            0lwBJNedbGyp9Azbzw/pSYmcziTr98uNKX0dpugJvIY9dAbSCuYwj06CVXNRLIG0
            ZYvxMe2O6noJzRB/dE3SY0BYQP+ZrXv5TlkVOooAp/dAt1OUjU3xxewoabZ6bA==
            =jYMW
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:TxjB8SuBEo0=,iv:dZ15LV6ArLxakOgeW/XIGdQ/isSqC9kafuorRSdS2Ig=,tag:y2ScZRVUsaeh6uGLDiSM4g==,type:str]
    password: ENC[AES256_GCM,data:bbnaWL7s9XA=,iv:fVoOrYF+eeyFGaXOiChpZaf4/B0PyefuSSZig4drR8k=,tag:1hZhf1waKFvNxrSV23Edmw==,type:str]
kind: Secret
metadata:
    name: atuin
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-23T17:24:00Z'
    mac: ENC[AES256_GCM,data:Oe4YP0+CZIARkpODguef5cWNQnwnx5Lopw/wXQZHDSP0fEvdwYKiVZGEaM7d/K5/EhEtMf42vmtVjFCDMb+i1AjV7qE/i0qYJDzGFXWe14XyyTmM4lnVhinFyKO9A9rpCwzVDypB6fTia60FI4ZuwTwmITTUZsHSY8uwG9gi3ls=,iv:YA/96awA3JXe6dWqJFOOrBCdyqAAKi5X1N16AkUmmlU=,tag:hfauIoSh6AbDZ+ih5XO71w==,type:str]
    pgp:
    -   created_at: '2026-09-23T17:23:59Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAXzaIBV+EATRaRIpNiCo6t5hDaEbyl/U3JwVLZeVO+WMw
            Hv3AhsKbKBtNavnnfZKmvRHqNHImfeU5hGusZvfJXrC1ISbe5W780ql+3ABXKkn4
            0lwBJNedbGyp9Azbzw/pSYmcziTr98uNKX0dpugJvIY9dAbSCuYwj06CVXNRLIG0
            ZYvxMe2O6noJzRB/dE3SY0BYQP+ZrXv5TlkVOooAp/dAt1OUjU3xxewoabZ6bA==
            =jYMW
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:WMQB4Cd6138YA+h/,iv:e6hEh8iExH4UDvdKSfTrKhyZnYiC+lCIl8r9Sc8krQ0=,tag:kEEiBK9a2jm7FmQWeUQXCQ==,type:str]
    password: ENC[AES256_GCM,data:bK641Ywlfcw2UMe4,iv:E3Pa5v7Qbp3hZzDEKpxuHYy7ScSVMBD3nyq9M0bssdw=,tag:IVgc/uBT6V1jEahApCjJvQ==,type:str]
kind: Secret
metadata:
    name: ferretdb
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-23T17:24:00Z'
    mac: ENC[AES256_GCM,data:Oe4YP0+CZIARkpODguef5cWNQnwnx5Lopw/wXQZHDSP0fEvdwYKiVZGEaM7d/K5/EhEtMf42vmtVjFCDMb+i1AjV7qE/i0qYJDzGFXWe14XyyTmM4lnVhinFyKO9A9rpCwzVDypB6fTia60FI4ZuwTwmITTUZsHSY8uwG9gi3ls=,iv:YA/96awA3JXe6dWqJFOOrBCdyqAAKi5X1N16AkUmmlU=,tag:hfauIoSh6AbDZ+ih5XO71w==,type:str]
    pgp:
    -   created_at: '2026-09-23T17:23:59Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAXzaIBV+EATRaRIpNiCo6t5hDaEbyl/U3JwVLZeVO+WMw
            Hv3AhsKbKBtNavnnfZKmvRHqNHImfeU5hGusZvfJXrC1ISbe5W780ql+3ABXKkn4
            0lwBJNedbGyp9Azbzw/pSYmcziTr98uNKX0dpugJvIY9dAbSCuYwj06CVXNRLIG0
            ZYvxMe2O6noJzRB/dE3SY0BYQP+ZrXv5TlkVOooAp/dAt1OUjU3xxewoabZ6bA==
            =jYMW
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:yKJpE10y05E=,iv:XBAptdxXB0KOiu8IE2AnqTn9ZWL6fKpmtcE3sIC+gug=,tag:t1b0gnFz9N1kdJ8B75pjhA==,type:str]
    password: ENC[AES256_GCM,data:7EtSgZG6kCE=,iv:FNkjvpfkiq9m+ehcJBV6ncos2YCeO7MB2nT6uW+/b9s=,tag:YQ7snKwxxfQkICvccrLuJw==,type:str]
kind: Secret
metadata:
    name: maddy
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-23T17:24:00Z'
    mac: ENC[AES256_GCM,data:Oe4YP0+CZIARkpODguef5cWNQnwnx5Lopw/wXQZHDSP0fEvdwYKiVZGEaM7d/K5/EhEtMf42vmtVjFCDMb+i1AjV7qE/i0qYJDzGFXWe14XyyTmM4lnVhinFyKO9A9rpCwzVDypB6fTia60FI4ZuwTwmITTUZsHSY8uwG9gi3ls=,iv:YA/96awA3JXe6dWqJFOOrBCdyqAAKi5X1N16AkUmmlU=,tag:hfauIoSh6AbDZ+ih5XO71w==,type:str]
    pgp:
    -   created_at: '2026-09-23T17:23:59Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAXzaIBV+EATRaRIpNiCo6t5hDaEbyl/U3JwVLZeVO+WMw
            Hv3AhsKbKBtNavnnfZKmvRHqNHImfeU5hGusZvfJXrC1ISbe5W780ql+3ABXKkn4
            0lwBJNedbGyp9Azbzw/pSYmcziTr98uNKX0dpugJvIY9dAbSCuYwj06CVXNRLIG0
            ZYvxMe2O6noJzRB/dE3SY0BYQP+ZrXv5TlkVOooAp/dAt1OUjU3xxewoabZ6bA==
            =jYMW
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:EV/lovckuwtSbWUd,iv:AxwwbsbAoyOt4APYsve3Tig1aB2hvvHXaVtREGFxQPc=,tag:qE+ydp/oKuVGbIlBZVXCpg==,type:str]
    password: ENC[AES256_GCM,data:WWgFwIaV8DuJIzpO,iv:yNJUoa4bB7DDakFGyDqqh87xrKAsYkByMr4TzGOj+a0=,tag:ZV51XD6+D/h6h6/q0low5A==,type:str]
kind: Secret
metadata:
    name: miniflux
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-23T17:24:00Z'
    mac: ENC[AES256_GCM,data:Oe4YP0+CZIARkpODguef5cWNQnwnx5Lopw/wXQZHDSP0fEvdwYKiVZGEaM7d/K5/EhEtMf42vmtVjFCDMb+i1AjV7qE/i0qYJDzGFXWe14XyyTmM4lnVhinFyKO9A9rpCwzVDypB6fTia60FI4ZuwTwmITTUZsHSY8uwG9gi3ls=,iv:YA/96awA3JXe6dWqJFOOrBCdyqAAKi5X1N16AkUmmlU=,tag:hfauIoSh6AbDZ+ih5XO71w==,type:str]
    pgp:
    -   created_at: '2026-09-23T17:23:59Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAXzaIBV+EATRaRIpNiCo6t5hDaEbyl/U3JwVLZeVO+WMw
            Hv3AhsKbKBtNavnnfZKmvRHqNHImfeU5hGusZvfJXrC1ISbe5W780ql+3ABXKkn4
            0lwBJNedbGyp9Azbzw/pSYmcziTr98uNKX0dpugJvIY9dAbSCuYwj06CVXNRLIG0
            ZYvxMe2O6noJzRB/dE3SY0BYQP+ZrXv5TlkVOooAp/dAt1OUjU3xxewoabZ6bA==
            =jYMW
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:oIZfUri/lDccwInR,iv:c6+vQkw4ZaRqy8b71rYAdsf/08c5gRAZ6lOCvYG6IcU=,tag:mjejXN+2DNTRdssOkiAsPw==,type:str]
    password: ENC[AES256_GCM,data:cgX/tp4HOV9isvjC,iv:Wp06IA0h5f5QxjQbPVMlEiKKgIRlgNYJmUAIDwI8gBM=,tag:/4tgW/7Hs3M+Z3lvj7B2/g==,type:str]
kind: Secret
metadata:
    name: pocket-id
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-23T17:24:00Z'
    mac: ENC[AES256_GCM,data:Oe4YP0+CZIARkpODguef5cWNQnwnx5Lopw/wXQZHDSP0fEvdwYKiVZGEaM7d/K5/EhEtMf42vmtVjFCDMb+i1AjV7qE/i0qYJDzGFXWe14XyyTmM4lnVhinFyKO9A9rpCwzVDypB6fTia60FI4ZuwTwmITTUZsHSY8uwG9gi3ls=,iv:YA/96awA3JXe6dWqJFOOrBCdyqAAKi5X1N16AkUmmlU=,tag:hfauIoSh6AbDZ+ih5XO71w==,type:str]
    pgp:
    -   created_at: '2026-09-23T17:23:59Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAXzaIBV+EATRaRIpNiCo6t5hDaEbyl/U3JwVLZeVO+WMw
            Hv3AhsKbKBtNavnnfZKmvRHqNHImfeU5hGusZvfJXrC1ISbe5W780ql+3ABXKkn4
            0lwBJNedbGyp9Azbzw/pSYmcziTr98uNKX0dpugJvIY9dAbSCuYwj06CVXNRLIG0
            ZYvxMe2O6noJzRB/dE3SY0BYQP+ZrXv5TlkVOooAp/dAt1OUjU3xxewoabZ6bA==
            =jYMW
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:s+WcgstnW+c=,iv:nzNCHd/eg0jFoy1uLJ+TDHinm7BoFJSWJkM80R+mMTw=,tag:DPO62fAz2bH0MlvTyYrtsg==,type:str]
    password: ENC[AES256_GCM,data:YWZ9N6Q0XyI=,iv:JiHfNzDO4dzU8WmfuSRdgbiQ/PppWZIQTpHqAMybqcM=,tag:Fuz40llv+nKqKNwyo9h5+w==,type:str]
kind: Secret
metadata:
    name: radarr
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-23T17:24:00Z'
    mac: ENC[AES256_GCM,data:Oe4YP0+CZIARkpODguef5cWNQnwnx5Lopw/wXQZHDSP0fEvdwYKiVZGEaM7d/K5/EhEtMf42vmtVjFCDMb+i1AjV7qE/i0qYJDzGFXWe14XyyTmM4lnVhinFyKO9A9rpCwzVDypB6fTia60FI4ZuwTwmITTUZsHSY8uwG9gi3ls=,iv:YA/96awA3JXe6dWqJFOOrBCdyqAAKi5X1N16AkUmmlU=,tag:hfauIoSh6AbDZ+ih5XO71w==,type:str]
    pgp:
    -   created_at: '2026-09-23T17:23:59Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAXzaIBV+EATRaRIpNiCo6t5hDaEbyl/U3JwVLZeVO+WMw
            Hv3AhsKbKBtNavnnfZKmvRHqNHImfeU5hGusZvfJXrC1ISbe5W780ql+3ABXKkn4
            0lwBJNedbGyp9Azbzw/pSYmcziTr98uNKX0dpugJvIY9dAbSCuYwj06CVXNRLIG0
            ZYvxMe2O6noJzRB/dE3SY0BYQP+ZrXv5TlkVOooAp/dAt1OUjU3xxewoabZ6bA==
            =jYMW
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:mHNMGYL4FD4=,iv:fezmalu5v1FFh0ZbnddrYxtKMakrzw8ct0Xklos1164=,tag:nE/u1gK9i4pZDG5Nx5a/2g==,type:str]
    password: ENC[AES256_GCM,data:pb4WbMCSL2Q=,iv:oeEaDMksEdunWLYwUl5Qiy4GI0+Bsn3goON5mphuTBo=,tag:7hLvDWvFA6E2Z1UW7YHe2w==,type:str]
kind: Secret
metadata:
    name: sonarr
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-23T17:24:00Z'
    mac: ENC[AES256_GCM,data:Oe4YP0+CZIARkpODguef5cWNQnwnx5Lopw/wXQZHDSP0fEvdwYKiVZGEaM7d/K5/EhEtMf42vmtVjFCDMb+i1AjV7qE/i0qYJDzGFXWe14XyyTmM4lnVhinFyKO9A9rpCwzVDypB6fTia60FI4ZuwTwmITTUZsHSY8uwG9gi3ls=,iv:YA/96awA3JXe6dWqJFOOrBCdyqAAKi5X1N16AkUmmlU=,tag:hfauIoSh6AbDZ+ih5XO71w==,type:str]
    pgp:
    -   created_at: '2026-09-23T17:23:59Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAXzaIBV+EATRaRIpNiCo6t5hDaEbyl/U3JwVLZeVO+WMw
            Hv3AhsKbKBtNavnnfZKmvRHqNHImfeU5hGusZvfJXrC1ISbe5W780ql+3ABXKkn4
            0lwBJNedbGyp9Azbzw/pSYmcziTr98uNKX0dpugJvIY9dAbSCuYwj06CVXNRLIG0
            ZYvxMe2O6noJzRB/dE3SY0BYQP+ZrXv5TlkVOooAp/dAt1OUjU3xxewoabZ6bA==
            =jYMW
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:WbUxgLediRDnrsuh,iv:LPmJjF3BBO1hzEWlU1jS2sVU5eom23ThIkyFRa4W2yo=,tag:IkAwLR7UtruRh5G9nec6yg==,type:str]
    password: ENC[AES256_GCM,data:M1vYYD/3mCaHelP4,iv:XAfyD+Vt4eGzhWYQwidyJWz2RiSA245YOU8CVAjJ9c8=,tag:qFL/ysB3+3HaBj3KOjrSjQ==,type:str]
kind: Secret
metadata:
    name: prowlarr
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-23T17:24:00Z'
    mac: ENC[AES256_GCM,data:Oe4YP0+CZIARkpODguef5cWNQnwnx5Lopw/wXQZHDSP0fEvdwYKiVZGEaM7d/K5/EhEtMf42vmtVjFCDMb+i1AjV7qE/i0qYJDzGFXWe14XyyTmM4lnVhinFyKO9A9rpCwzVDypB6fTia60FI4ZuwTwmITTUZsHSY8uwG9gi3ls=,iv:YA/96awA3JXe6dWqJFOOrBCdyqAAKi5X1N16AkUmmlU=,tag:hfauIoSh6AbDZ+ih5XO71w==,type:str]
    pgp:
    -   created_at: '2026-09-23T17:23:59Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAXzaIBV+EATRaRIpNiCo6t5hDaEbyl/U3JwVLZeVO+WMw
            Hv3AhsKbKBtNavnnfZKmvRHqNHImfeU5hGusZvfJXrC1ISbe5W780ql+3ABXKkn4
            0lwBJNedbGyp9Azbzw/pSYmcziTr98uNKX0dpugJvIY9dAbSCuYwj06CVXNRLIG0
            ZYvxMe2O6noJzRB/dE3SY0BYQP+ZrXv5TlkVOooAp/dAt1OUjU3xxewoabZ6bA==
            =jYMW
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:AbGrbeybUS0=,iv:lAGxo9HVNRNi/9iUrKQ/ArRPyLUPbiByYGCwh8lHkBQ=,tag:u54TuPihqFZ8sScxasY1Rw==,type:str]
    password: ENC[AES256_GCM,data:FbvI41ws7sY=,iv:bljDe9nezJKWpsudsdJZm7M+2i2ZuUPEkyI8ach92E0=,tag:6AmSZkBWcion/7az5eJYiA==,type:str]
kind: Secret
metadata:
    name: sftpgo
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-23T17:24:00Z'
    mac: ENC[AES256_GCM,data:Oe4YP0+CZIARkpODguef5cWNQnwnx5Lopw/wXQZHDSP0fEvdwYKiVZGEaM7d/K5/EhEtMf42vmtVjFCDMb+i1AjV7qE/i0qYJDzGFXWe14XyyTmM4lnVhinFyKO9A9rpCwzVDypB6fTia60FI4ZuwTwmITTUZsHSY8uwG9gi3ls=,iv:YA/96awA3JXe6dWqJFOOrBCdyqAAKi5X1N16AkUmmlU=,tag:hfauIoSh6AbDZ+ih5XO71w==,type:str]
    pgp:
    -   created_at: '2026-09-23T17:23:59Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAXzaIBV+EATRaRIpNiCo6t5hDaEbyl/U3JwVLZeVO+WMw
            Hv3AhsKbKBtNavnnfZKmvRHqNHImfeU5hGusZvfJXrC1ISbe5W780ql+3ABXKkn4
            0lwBJNedbGyp9Azbzw/pSYmcziTr98uNKX0dpugJvIY9dAbSCuYwj06CVXNRLIG0
            ZYvxMe2O6noJzRB/dE3SY0BYQP+ZrXv5TlkVOooAp/dAt1OUjU3xxewoabZ6bA==
            =jYMW
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:K5m79uDQ72bg16Y1WwWp6g==,iv:fEmJqcoZfL3F0eQePFjj04B8/OvdkurhdGw2RucUPAU=,tag:N+nsdSdSxhwuSqyt0aV5kw==,type:str]
    password: ENC[AES256_GCM,data:G6jKnr8Mr/8RzgaWX6no0Q==,iv:VMkrIbPZcVYaZW6SIikSGVuga7NUNizlJlbh97UlIqs=,tag:wKrFAMGcRc88/NV/hH9BqA==,type:str]
kind: Secret
metadata:
    name: vaultwarden
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-23T17:24:00Z'
    mac: ENC[AES256_GCM,data:Oe4YP0+CZIARkpODguef5cWNQnwnx5Lopw/wXQZHDSP0fEvdwYKiVZGEaM7d/K5/EhEtMf42vmtVjFCDMb+i1AjV7qE/i0qYJDzGFXWe14XyyTmM4lnVhinFyKO9A9rpCwzVDypB6fTia60FI4ZuwTwmITTUZsHSY8uwG9gi3ls=,iv:YA/96awA3JXe6dWqJFOOrBCdyqAAKi5X1N16AkUmmlU=,tag:hfauIoSh6AbDZ+ih5XO71w==,type:str]
    pgp:
    -   created_at: '2026-09-23T17:23:59Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAXzaIBV+EATRaRIpNiCo6t5hDaEbyl/U3JwVLZeVO+WMw
            Hv3AhsKbKBtNavnnfZKmvRHqNHImfeU5hGusZvfJXrC1ISbe5W780ql+3ABXKkn4
            0lwBJNedbGyp9Azbzw/pSYmcziTr98uNKX0dpugJvIY9dAbSCuYwj06CVXNRLIG0
            ZYvxMe2O6noJzRB/dE3SY0BYQP+ZrXv5TlkVOooAp/dAt1OUjU3xxewoabZ6bA==
            =jYMW
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:jEJ92mDYm0wZxXDw,iv:m3Lb9Pd9LebACYBdXlmLKLm0tkuZKwPuZ6TtDxrb8kM=,tag:5aG8qh9UGUIwxh268VMoxQ==,type:str]
    password: ENC[AES256_GCM,data:gpasj5iFADS1V5i6,iv:C77MFejtwdQusR02nIyeUznzEq6C4nreLgMNRLcA2w8=,tag:n77DEpK/65WYrs/1hoJYHw==,type:str]
kind: Secret
metadata:
    name: sidekick
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-23T17:24:00Z'
    mac: ENC[AES256_GCM,data:Oe4YP0+CZIARkpODguef5cWNQnwnx5Lopw/wXQZHDSP0fEvdwYKiVZGEaM7d/K5/EhEtMf42vmtVjFCDMb+i1AjV7qE/i0qYJDzGFXWe14XyyTmM4lnVhinFyKO9A9rpCwzVDypB6fTia60FI4ZuwTwmITTUZsHSY8uwG9gi3ls=,iv:YA/96awA3JXe6dWqJFOOrBCdyqAAKi5X1N16AkUmmlU=,tag:hfauIoSh6AbDZ+ih5XO71w==,type:str]
    pgp:
    -   created_at: '2026-09-23T17:23:59Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAXzaIBV+EATRaRIpNiCo6t5hDaEbyl/U3JwVLZeVO+WMw
            Hv3AhsKbKBtNavnnfZKmvRHqNHImfeU5hGusZvfJXrC1ISbe5W780ql+3ABXKkn4
            0lwBJNedbGyp9Azbzw/pSYmcziTr98uNKX0dpugJvIY9dAbSCuYwj06CVXNRLIG0
            ZYvxMe2O6noJzRB/dE3SY0BYQP+ZrXv5TlkVOooAp/dAt1OUjU3xxewoabZ6bA==
            =jYMW
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:DGDrp5CTBff0dTrzNj6GPQ==,iv:HBfOjAppzoeoVF/q8rxKsW3FqZ8Byxy4deu8q85xpVE=,tag:NOzDng/RpEeof69uLyPeWg==,type:str]
    password: ENC[AES256_GCM,data:gis9fiSmVXKisP+x8YXIgg==,iv:JmLbrzu+PzMtgs7ISXyIeiVumEQIwPbbhG7jo8A3xk4=,tag:um8KsBqAZvMn1NAIcvBm1Q==,type:str]
kind: Secret
metadata:
    name: kubeopencode
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-23T17:24:00Z'
    mac: ENC[AES256_GCM,data:Oe4YP0+CZIARkpODguef5cWNQnwnx5Lopw/wXQZHDSP0fEvdwYKiVZGEaM7d/K5/EhEtMf42vmtVjFCDMb+i1AjV7qE/i0qYJDzGFXWe14XyyTmM4lnVhinFyKO9A9rpCwzVDypB6fTia60FI4ZuwTwmITTUZsHSY8uwG9gi3ls=,iv:YA/96awA3JXe6dWqJFOOrBCdyqAAKi5X1N16AkUmmlU=,tag:hfauIoSh6AbDZ+ih5XO71w==,type:str]
    pgp:
    -   created_at: '2026-09-23T17:23:59Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAXzaIBV+EATRaRIpNiCo6t5hDaEbyl/U3JwVLZeVO+WMw
            Hv3AhsKbKBtNavnnfZKmvRHqNHImfeU5hGusZvfJXrC1ISbe5W780ql+3ABXKkn4
            0lwBJNedbGyp9Azbzw/pSYmcziTr98uNKX0dpugJvIY9dAbSCuYwj06CVXNRLIG0
            ZYvxMe2O6noJzRB/dE3SY0BYQP+ZrXv5TlkVOooAp/dAt1OUjU3xxewoabZ6bA==
            =jYMW
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:XAQ9jiwc96RoxVMn,iv:BtPINbDj3vOtLaZPsH71NSo3nkpwg9vDXDh+shzqTA0=,tag:12NzAjhz2O/9M6pwAnSMeA==,type:str]
    password: ENC[AES256_GCM,data:hW8fOYAiD2BcIvru,iv:6GyHXlapugtvhcHEtan/Kwejkoa5yzl4PvGtdePnvP8=,tag:VZLlW3KHJTM/Uw9Ia8tSMw==,type:str]
kind: Secret
metadata:
    name: spacebar
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-23T17:24:00Z'
    mac: ENC[AES256_GCM,data:Oe4YP0+CZIARkpODguef5cWNQnwnx5Lopw/wXQZHDSP0fEvdwYKiVZGEaM7d/K5/EhEtMf42vmtVjFCDMb+i1AjV7qE/i0qYJDzGFXWe14XyyTmM4lnVhinFyKO9A9rpCwzVDypB6fTia60FI4ZuwTwmITTUZsHSY8uwG9gi3ls=,iv:YA/96awA3JXe6dWqJFOOrBCdyqAAKi5X1N16AkUmmlU=,tag:hfauIoSh6AbDZ+ih5XO71w==,type:str]
    pgp:
    -   created_at: '2026-09-23T17:23:59Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAXzaIBV+EATRaRIpNiCo6t5hDaEbyl/U3JwVLZeVO+WMw
            Hv3AhsKbKBtNavnnfZKmvRHqNHImfeU5hGusZvfJXrC1ISbe5W780ql+3ABXKkn4
            0lwBJNedbGyp9Azbzw/pSYmcziTr98uNKX0dpugJvIY9dAbSCuYwj06CVXNRLIG0
            ZYvxMe2O6noJzRB/dE3SY0BYQP+ZrXv5TlkVOooAp/dAt1OUjU3xxewoabZ6bA==
            =jYMW
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
