apiVersion: v1
data:
    username: ENC[AES256_GCM,data:OvWEz/jkGZmUI0IE,iv:LN8RxIpcpkl1B4N+qGOPtO3i1804xDftWR1GtzFYIbc=,tag:XmcBAY0P96yRPzLMaRqxxw==,type:str]
    password: ENC[AES256_GCM,data:RLPv+QQ8wb/YXuPl,iv:gewP6FbFzVu68H6YaYnfi+bShmvDQxqCpLKzwEQls2I=,tag:VsEtmJ2UbtjEYRmp/hTJMg==,type:str]
kind: Secret
metadata:
    name: atuin
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-02T14:31:01Z'
    mac: ENC[AES256_GCM,data:7eUiVOscdnK39wxwyJ9kW8A6jowshKnqv6IsSxVvnlyrDw/fBcslE94IFmeGoxUpmM/KlIMFg8c6a4aC5+2Ott6KmsGrH5K1QVjBIunj39iN3scpyrMAwrxq9eezoc2wEHrOgp6fZVmekKjr+Oq/6tnFXbw2kjImd55kEMNQJnU=,iv:VOvvXYD/7LXWZHAR8Zk3OCvE8MIlVfItCoWdbzc7LcI=,tag:jCRnzlmygOYohlSnI6PZzw==,type:str]
    pgp:
    -   created_at: '2026-09-02T14:31:00Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAuvnlQtbZs4RKaza+fZDzMPEy2KjuGHm7EanUGKPV2kUw
            zkWFMiiv3jMyAHzv4Tt49MvMvVQsl0nN8DEvumOR+uwiDprzUqVyHzSV0SWq5ZIR
            0lwBuMCVRa0fCjUxHrT/SOQUfFrLw5AP1vgsHctkdiWQ9UnMsjng68YA3QeXtjqu
            QS6pvEbgRkdNO950VPxBEOhbrmmIoM1xuQcwGAujJ/Kn+Qysou6O+A8+kxcrnQ==
            =a1yp
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:v+KSmFOyz7s=,iv:jfSnrtdV6blCVoN1f/9C7EUSckDWloE5yiLLawTIBLs=,tag:WVbFRTvctttKU2mysR7c2Q==,type:str]
    password: ENC[AES256_GCM,data:bt2DGwkppQY=,iv:zZ/c8YK/bmZO73O+WheAcFxLMRTG+NyzAxfYTr7qRsg=,tag:g6Oeau9Rf8ELWKg+9eajng==,type:str]
kind: Secret
metadata:
    name: maddy
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-02T14:31:01Z'
    mac: ENC[AES256_GCM,data:7eUiVOscdnK39wxwyJ9kW8A6jowshKnqv6IsSxVvnlyrDw/fBcslE94IFmeGoxUpmM/KlIMFg8c6a4aC5+2Ott6KmsGrH5K1QVjBIunj39iN3scpyrMAwrxq9eezoc2wEHrOgp6fZVmekKjr+Oq/6tnFXbw2kjImd55kEMNQJnU=,iv:VOvvXYD/7LXWZHAR8Zk3OCvE8MIlVfItCoWdbzc7LcI=,tag:jCRnzlmygOYohlSnI6PZzw==,type:str]
    pgp:
    -   created_at: '2026-09-02T14:31:00Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAuvnlQtbZs4RKaza+fZDzMPEy2KjuGHm7EanUGKPV2kUw
            zkWFMiiv3jMyAHzv4Tt49MvMvVQsl0nN8DEvumOR+uwiDprzUqVyHzSV0SWq5ZIR
            0lwBuMCVRa0fCjUxHrT/SOQUfFrLw5AP1vgsHctkdiWQ9UnMsjng68YA3QeXtjqu
            QS6pvEbgRkdNO950VPxBEOhbrmmIoM1xuQcwGAujJ/Kn+Qysou6O+A8+kxcrnQ==
            =a1yp
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:n/PPVSYwKXKDVIEd,iv:d9H2IvXo22NgzInDClNX/CSpkpuFCpnBV4r3aUnraZU=,tag:WiziFqTwyB1aG7FCfTPpaQ==,type:str]
    password: ENC[AES256_GCM,data:q3Jyx5GdtOSqnHph,iv:rbXVdiuQAHOuCVn/MxJO3un6Dn/Z5KFtPJN6eeX6wPQ=,tag:KcXGWRKN65bz0CsrOPD8vQ==,type:str]
kind: Secret
metadata:
    name: miniflux
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-02T14:31:01Z'
    mac: ENC[AES256_GCM,data:7eUiVOscdnK39wxwyJ9kW8A6jowshKnqv6IsSxVvnlyrDw/fBcslE94IFmeGoxUpmM/KlIMFg8c6a4aC5+2Ott6KmsGrH5K1QVjBIunj39iN3scpyrMAwrxq9eezoc2wEHrOgp6fZVmekKjr+Oq/6tnFXbw2kjImd55kEMNQJnU=,iv:VOvvXYD/7LXWZHAR8Zk3OCvE8MIlVfItCoWdbzc7LcI=,tag:jCRnzlmygOYohlSnI6PZzw==,type:str]
    pgp:
    -   created_at: '2026-09-02T14:31:00Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAuvnlQtbZs4RKaza+fZDzMPEy2KjuGHm7EanUGKPV2kUw
            zkWFMiiv3jMyAHzv4Tt49MvMvVQsl0nN8DEvumOR+uwiDprzUqVyHzSV0SWq5ZIR
            0lwBuMCVRa0fCjUxHrT/SOQUfFrLw5AP1vgsHctkdiWQ9UnMsjng68YA3QeXtjqu
            QS6pvEbgRkdNO950VPxBEOhbrmmIoM1xuQcwGAujJ/Kn+Qysou6O+A8+kxcrnQ==
            =a1yp
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:YG29/6VMM2zHXAH9,iv:N/XmoaeemO+9pA7YrzwGnwkhXYOiB6GKB0tVCtY2agQ=,tag:3upPLNY54LQEbOnz085bKQ==,type:str]
    password: ENC[AES256_GCM,data:rej7o3S9LDsSx9hk,iv:S4i1X6ZOfUzIFSzZpzOfZ99PaN0FQfDJ5qyK6I/1BhY=,tag:8GxN2MkZ9rcsVnRLWCCdAQ==,type:str]
kind: Secret
metadata:
    name: passbolt
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-02T14:31:01Z'
    mac: ENC[AES256_GCM,data:7eUiVOscdnK39wxwyJ9kW8A6jowshKnqv6IsSxVvnlyrDw/fBcslE94IFmeGoxUpmM/KlIMFg8c6a4aC5+2Ott6KmsGrH5K1QVjBIunj39iN3scpyrMAwrxq9eezoc2wEHrOgp6fZVmekKjr+Oq/6tnFXbw2kjImd55kEMNQJnU=,iv:VOvvXYD/7LXWZHAR8Zk3OCvE8MIlVfItCoWdbzc7LcI=,tag:jCRnzlmygOYohlSnI6PZzw==,type:str]
    pgp:
    -   created_at: '2026-09-02T14:31:00Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAuvnlQtbZs4RKaza+fZDzMPEy2KjuGHm7EanUGKPV2kUw
            zkWFMiiv3jMyAHzv4Tt49MvMvVQsl0nN8DEvumOR+uwiDprzUqVyHzSV0SWq5ZIR
            0lwBuMCVRa0fCjUxHrT/SOQUfFrLw5AP1vgsHctkdiWQ9UnMsjng68YA3QeXtjqu
            QS6pvEbgRkdNO950VPxBEOhbrmmIoM1xuQcwGAujJ/Kn+Qysou6O+A8+kxcrnQ==
            =a1yp
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:3tRREqEmdljSq/nc,iv:nPaHlI6TiMzbAT1Rmxh9H/YttTLYX0hnu7E+sqfwggI=,tag:8ZbO5y6W/P/2mwLmIgBUOQ==,type:str]
    password: ENC[AES256_GCM,data:YeoBEYv29RB0UjvN,iv:A/4+tMYnKQpwkgL6eMdmfcoIwiQK/d//BJnNCqfUWi4=,tag:N5C+6a0MQGPVGaZu6qTLUg==,type:str]
kind: Secret
metadata:
    name: pocket-id
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-02T14:31:01Z'
    mac: ENC[AES256_GCM,data:7eUiVOscdnK39wxwyJ9kW8A6jowshKnqv6IsSxVvnlyrDw/fBcslE94IFmeGoxUpmM/KlIMFg8c6a4aC5+2Ott6KmsGrH5K1QVjBIunj39iN3scpyrMAwrxq9eezoc2wEHrOgp6fZVmekKjr+Oq/6tnFXbw2kjImd55kEMNQJnU=,iv:VOvvXYD/7LXWZHAR8Zk3OCvE8MIlVfItCoWdbzc7LcI=,tag:jCRnzlmygOYohlSnI6PZzw==,type:str]
    pgp:
    -   created_at: '2026-09-02T14:31:00Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAuvnlQtbZs4RKaza+fZDzMPEy2KjuGHm7EanUGKPV2kUw
            zkWFMiiv3jMyAHzv4Tt49MvMvVQsl0nN8DEvumOR+uwiDprzUqVyHzSV0SWq5ZIR
            0lwBuMCVRa0fCjUxHrT/SOQUfFrLw5AP1vgsHctkdiWQ9UnMsjng68YA3QeXtjqu
            QS6pvEbgRkdNO950VPxBEOhbrmmIoM1xuQcwGAujJ/Kn+Qysou6O+A8+kxcrnQ==
            =a1yp
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:nD72fo0WUKVe4x+v,iv:FGMR7X4xTw2XwsHxYJ9RxFyl2YfCXrEnJspiCR4YTw0=,tag:cqAIh2OoDhqLdkXFNsiC8Q==,type:str]
    password: ENC[AES256_GCM,data:vkgGcqZtIv3uITPM,iv:J3y27UJVaIn303bjaqU47YSkmbVCZLATWuUbhG81FTk=,tag:CAHDPQux8NYifGGoJwgUbQ==,type:str]
kind: Secret
metadata:
    name: prowlarr
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-02T14:31:01Z'
    mac: ENC[AES256_GCM,data:7eUiVOscdnK39wxwyJ9kW8A6jowshKnqv6IsSxVvnlyrDw/fBcslE94IFmeGoxUpmM/KlIMFg8c6a4aC5+2Ott6KmsGrH5K1QVjBIunj39iN3scpyrMAwrxq9eezoc2wEHrOgp6fZVmekKjr+Oq/6tnFXbw2kjImd55kEMNQJnU=,iv:VOvvXYD/7LXWZHAR8Zk3OCvE8MIlVfItCoWdbzc7LcI=,tag:jCRnzlmygOYohlSnI6PZzw==,type:str]
    pgp:
    -   created_at: '2026-09-02T14:31:00Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAuvnlQtbZs4RKaza+fZDzMPEy2KjuGHm7EanUGKPV2kUw
            zkWFMiiv3jMyAHzv4Tt49MvMvVQsl0nN8DEvumOR+uwiDprzUqVyHzSV0SWq5ZIR
            0lwBuMCVRa0fCjUxHrT/SOQUfFrLw5AP1vgsHctkdiWQ9UnMsjng68YA3QeXtjqu
            QS6pvEbgRkdNO950VPxBEOhbrmmIoM1xuQcwGAujJ/Kn+Qysou6O+A8+kxcrnQ==
            =a1yp
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:9ai4dzYEdAjX8EU+X8lwNQ==,iv:5GDDCWx7B9W+ye3l1ksKwICIVakXkGgUIiqWPmaZfZw=,tag:Uk8fRxgRzJZQacgdZOUR4Q==,type:str]
    password: ENC[AES256_GCM,data:TlwBO+ogM1lm8cNyf5s9SA==,iv:u/0vHSgDbmEYKJpNssrTwYyHsMfyQpoXAEey2w4onyY=,tag:hBNtpVtSctXzTr916U2FMw==,type:str]
kind: Secret
metadata:
    name: vaultwarden
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-02T14:31:01Z'
    mac: ENC[AES256_GCM,data:7eUiVOscdnK39wxwyJ9kW8A6jowshKnqv6IsSxVvnlyrDw/fBcslE94IFmeGoxUpmM/KlIMFg8c6a4aC5+2Ott6KmsGrH5K1QVjBIunj39iN3scpyrMAwrxq9eezoc2wEHrOgp6fZVmekKjr+Oq/6tnFXbw2kjImd55kEMNQJnU=,iv:VOvvXYD/7LXWZHAR8Zk3OCvE8MIlVfItCoWdbzc7LcI=,tag:jCRnzlmygOYohlSnI6PZzw==,type:str]
    pgp:
    -   created_at: '2026-09-02T14:31:00Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAuvnlQtbZs4RKaza+fZDzMPEy2KjuGHm7EanUGKPV2kUw
            zkWFMiiv3jMyAHzv4Tt49MvMvVQsl0nN8DEvumOR+uwiDprzUqVyHzSV0SWq5ZIR
            0lwBuMCVRa0fCjUxHrT/SOQUfFrLw5AP1vgsHctkdiWQ9UnMsjng68YA3QeXtjqu
            QS6pvEbgRkdNO950VPxBEOhbrmmIoM1xuQcwGAujJ/Kn+Qysou6O+A8+kxcrnQ==
            =a1yp
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
