apiVersion: v1
data:
    username: ENC[AES256_GCM,data:cuM7L3crkstN5eDD,iv:TyvGnigudOwbceCgnL9+WQ6k/7MrcYlpHm6wvfrKhx8=,tag:HvMFaxmhIXt/HBHX5KIwsA==,type:str]
    password: ENC[AES256_GCM,data:x83029NXNIcRuCB/,iv:ob/VMERPtG7sgsoN20ZDiXZU2fx8OODe5eEbeFl+9Iw=,tag:TE9wB1Qs5YB+QsGBiYXc2A==,type:str]
kind: Secret
metadata:
    name: openbao
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-01T21:07:38Z'
    mac: ENC[AES256_GCM,data:d5xSHgkJ4KxHmS9B3Nm3nqXA6Ds81b8wHPJ6n1siCqzMJUmO7jd95NXZYbjHsGaHFsoJ2AXqvYmFMrFhqCULRLbK+6+L/Ij5Hc4IFHnI4LfG8c0C0zt1iG+gt7ViMHWyWaPHR6k6fjC1aNVauzNs91A1dfvm/I0usJJTJZAOMOw=,iv:NkCWF/iaOd+H1gN+1D2e8JCZRnmTi5nkouty9qOYC/k=,tag:Yw1m4oGg18wwv3iqds4ylg==,type:str]
    pgp:
    -   created_at: '2026-09-01T21:07:37Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA+i70tKbI2khrdHCEC/mXhF2iK++cIDHEsP7mD4UdeCow
            QbsVGjHAt3nFK9xLbHX4Lryy1XEVkqgq2mYZWzBhuHZz6O42/iO7/AYT0tH141bg
            0l4B4K7ga4Ja6xakGdVlqqYjpIOqyVDOBNaq0vfkaD2GJ6DtOnfo+4h2lurTFhrE
            QXe2yRme8g0vh0V48tFu2AtqSSX7TFVdbiDDPrF8gnK7csCQucmNSE+yGhO2XJZN
            =XMX8
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:rRnS6ZYuBzwaE9KS,iv:2SyRyCo8z5axqwF+VPgXnxWeBjpHm/GstHkPZ5fz9yc=,tag:5nMiABhB7NUF6Idjg28hyA==,type:str]
    password: ENC[AES256_GCM,data:qDRIw/AW0FWXYa1P,iv:KJRgDfd57m3o5THhY1u1vXLDKfPiG61rX0+/wAVs7bM=,tag:7T+NL7eeVt133HDgYFXX6Q==,type:str]
kind: Secret
metadata:
    name: pocket-id
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-01T21:07:38Z'
    mac: ENC[AES256_GCM,data:d5xSHgkJ4KxHmS9B3Nm3nqXA6Ds81b8wHPJ6n1siCqzMJUmO7jd95NXZYbjHsGaHFsoJ2AXqvYmFMrFhqCULRLbK+6+L/Ij5Hc4IFHnI4LfG8c0C0zt1iG+gt7ViMHWyWaPHR6k6fjC1aNVauzNs91A1dfvm/I0usJJTJZAOMOw=,iv:NkCWF/iaOd+H1gN+1D2e8JCZRnmTi5nkouty9qOYC/k=,tag:Yw1m4oGg18wwv3iqds4ylg==,type:str]
    pgp:
    -   created_at: '2026-09-01T21:07:37Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA+i70tKbI2khrdHCEC/mXhF2iK++cIDHEsP7mD4UdeCow
            QbsVGjHAt3nFK9xLbHX4Lryy1XEVkqgq2mYZWzBhuHZz6O42/iO7/AYT0tH141bg
            0l4B4K7ga4Ja6xakGdVlqqYjpIOqyVDOBNaq0vfkaD2GJ6DtOnfo+4h2lurTFhrE
            QXe2yRme8g0vh0V48tFu2AtqSSX7TFVdbiDDPrF8gnK7csCQucmNSE+yGhO2XJZN
            =XMX8
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
