apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: proxmoxtokens.platform.shokohsc.com
  labels:
    provider: opentofu
spec:
  mode: Pipeline
  compositeTypeRef:
    apiVersion: platform.shokohsc.com/v1alpha1
    kind: ProxmoxToken
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: user-token-workspace
            base:
              apiVersion: opentofu.m.upbound.io/v1beta1
              kind: Workspace
              spec:
                forProvider:
                  enableTofuCLILogging: true
                  source: Inline
                  module: |
                    variable "comment" {
                      type = string
                    }
                    variable "user" {
                      type = string
                    }
                    variable "name" {
                      type    = string
                    }

                    resource "proxmox_user_token" "this" {
                      comment = var.comment
                      user_id  = var.user
                      token_name = var.name
                    }

                    output "user_id" {
                      value = proxmox_user_token.this.token_name
                    }
                  vars:
                    - key: comment
                      value: "Managed by Crossplane"
                    - key: name
                      value: ""
                    - key: user
                      value: ""
                providerConfigRef:
                  name: proxmox
                  kind: ProviderConfig
                writeConnectionSecretToRef:
                  name: opentofu-token-workspace
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.comment
                toFieldPath: spec.forProvider.vars[0].value
                policy:
                  fromFieldPath: Optional
              - type: FromCompositeFieldPath
                fromFieldPath: spec.user
                toFieldPath: spec.forProvider.vars[1].value
              - type: FromCompositeFieldPath
                fromFieldPath: spec.name
                toFieldPath: spec.forProvider.vars[2].value
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: spec.writeConnectionSecretToRef.name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-token-workspace"
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.outputs.user_id
                toFieldPath: status.userId
