---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: configarr
spec:
  schedule: "17 4 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            app: configarr
        spec:
          automountServiceAccountToken: false
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    topologyKey: kubernetes.io/hostname
                    labelSelector:
                      matchLabels:
                        app: configarr
          containers:
            - name: configarr
              image: ghcr.io/raydak-labs/configarr:1.33.0
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                capabilities:
                  drop:
                    - ALL
              env:
                - name: TZ
                  value: ${timezone}
                - name: HOME
                  value: /tmp
                - name: SONARR_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: configarr
                      key: sonarr-api-key
                - name: RADARR_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: configarr
                      key: radarr-api-key
              resources:
                requests:
                  cpu: 100m
                  memory: 64Mi
                limits:
                  memory: 2048Mi
              volumeMounts:
                - name: config
                  mountPath: /app/config/config.yml
                  subPath: config.yml
                - name: repos
                  mountPath: /app/repos
                - name: tmp
                  mountPath: /tmp
          restartPolicy: Never
          volumes:
            - name: config
              configMap:
                name: config
            - name: repos
              emptyDir: {}
            - name: tmp
              emptyDir: {}
