apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: proxmox
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: config
    files:
      - ./config/haproxy.cfg
generatorOptions:
  disableNameSuffixHash: true
