---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openbao
spec:
  interval: ${interval}
  url: https://openbao.github.io/openbao-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openbao
spec:
  interval: ${interval}
  chart:
    spec:
      chart: openbao
      version: 0.29.3
      sourceRef:
        kind: HelmRepository
        name: openbao
      interval: ${interval}
  valuesFrom:
    - kind: Secret
      name: openbao
      valuesKey: config
      targetPath: server.ha.config
  values:
    global:
      enabled: false
    server:
      enabled: true
      # extraEnvironmentVars:
      #   BAO_K8S_NAMESPACE:
      #     valuesFrom:
      #       fieldRef:
      #         fieldPath: metadata.namespace
      #   BAO_K8S_POD_NAME:
      #     valuesFrom:
      #       fieldRef:
      #         fieldPath: metadata.name
      volumeMounts:
        - name: temp
          mountPath: /tmp
      volumes:
        - name: temp
          emptyDir: {}
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 256Mi
          cpu: 250m
      statefulSet:
        securityContext:
          pod:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          container:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
      gateway:
        httpRoute:
          enabled: true
          hosts:
            - openbao.${domain}
          parentRefs:
            - name: cilium
              namespace: cilium
      livenessProbe:
        enabled: true
        execCommand:
          - /bin/sh
          - -c
          - /openbao/userconfig/mylivenessscript/run.sh

      dataStorage:
        enabled: false

      standalone:
        enabled: false
      ha:
        enabled: true
        replicas: 3

        # Set the api_addr configuration for OpenBao HA
        # See https://openbao.org/docs/configuration/#high-availability-parameters
        # If set to null, this will be set to the Pod IP Address
        apiAddr: null

        # Set the cluster_addr configuration for OpenBao HA
        # See https://openbao.org/docs/configuration/#high-availability-parameters
        # If set to null, this will be set to https://$(HOSTNAME).{{ template "openbao.fullname" . }}-internal:8201
        clusterAddr: null

        raft:
          enabled: false

    # OpenBao UI
    ui:
      enabled: true
