apiVersion: v1
stringData:
    config: ENC[AES256_GCM,data:1u/aRihQpZ6rlS8t90VCS01bcMSS2ZhEXlNg8yZ89/c9jIY7As/GyowjpZ70nWcB6yiCU4ZuHiUHipEO8ReeRor3X8lrhfAF8ygUubGnM5bQuCv1eJOS9/vod2B1mHqfacNaWchvLk8S/d66nJtpQECKtJ84KRWN9WksGtK/RQx6Qf2rTpeZfEJba6NGcigfyrDwydDY+Omg9DFJbBEW+SBXLGhKkvSRDd3Z3wpajJfKfYmUdw44PuDGdMpllQgxtxfAVp9ruzJDKvvlpV+vmlcLIjb+rUVvtWa6twzakVrmi8ylftKGeOM=,iv:RI+zzIwjbNFaWeUb4jszD2wrQkZ35Z25iK8+Qyr3jNU=,tag:pv8gN3beQB690HSHy5GjTA==,type:str]
kind: Secret
metadata:
    name: openbao
    namespace: openbao
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-02T09:39:49Z'
    mac: ENC[AES256_GCM,data:8hdFmKoiJzTBocBJSkLsgqaICKJuYs0X52bp7Gdo/cJVXCjdchigRrPwi6Kxd1E3FEUbiZoY9Og48CDF6SXcwxgNk0+69n6d9Ty0Hqmk54K+2NKCjF2ViT/T8UEhSje6GKLRHfpRnuC3bWMRJORvwbxyf28oupW1KRR74BP2Uzg=,iv:8xfgmrCfZttF2jDR8RMw5byZwuf+HytOHeV0CmvBtOU=,tag:ZL7X5mKrFA12HcMOmgrGog==,type:str]
    pgp:
    -   created_at: '2026-09-02T09:39:48Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAhdxAgG691u5w2gXaxBtsmgnTtb+Pfx23zUfzL1A+nh4w
            ku0U5tygpM9nLr7BB7AIKIOipiXiBf7wfkx85LCt9Cr+N8BxAeoBqoqmjRwbBn1I
            0l4BcpWAb36MhL0FmPFapXiZQKFBYJehj/E0R2VGD9m1TuBh1l+xXGZ7Uh06xC+c
            sfZEfeCT9LQHhd/qeZAXcewTgOQGVmKLt/kSD/d768k7szarl2jCTQvarQ6VaZip
            =tVo6
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
