apiVersion: v1
stringData:
    config: ENC[AES256_GCM,data:O21+tGaU3QKyg5jN7CannoZMhSBQuDvHz13iN4EoTgKnPBaKL4vRFHs0vD0XUbP1yJV84HJjI8XkJJiyzpv2puRxDRKWiLReFLx+CrZTfYzAfy5PPgguS3J5esP2dYUtTyMwWfKiE9fsE7H0irxmLkkgkQxraOEiyKUdZUKYCA0JF5K6THxa7Zxn9xvwYfmB4K9TMs0eNkhA1OKnwsKdL1/1Gq/+FVsezQth5ERXiLzTOYv2BDwm1kvxDsfLI4PnPJ5rJBqw7tLsSXE0Ol1gjRiKEoFIsrD1sSl8qSukIw2NBbepr2M9+luhdPzbeuiM4vVenUqY+QjcWiIkOhE1mFReUKewyY8QHkmUxiWJ2mA=,iv:HJFeIXy2G4SYO/E0P9WR0ERljgRMNnaZP4NAGV+KGyE=,tag:ZEMth7iY78MjU7tJcAo3eQ==,type:str]
kind: Secret
metadata:
    name: openbao
    namespace: openbao
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-01T21:51:05Z'
    mac: ENC[AES256_GCM,data:uL/dWzrtJeQ58rweHscLVhl6eSoPXGZSjyR9Jth5oBl6hEuyvvvYWr/zuc7jzmB3skEqhk53LWIoZ8VMbhp7/gca+yDPB9fJykVGjc8zxHw7SY+nvZmqrPVN6vHq46GLUGulLAH0/j3sHIGl82IckHLJggMovoMw52G+48aVdOM=,iv:tOwRkhXY8/WVCAmbiccyrYFXn1iL49twTJKL4VA5G/o=,tag:0hWyfLLxTXs1EvS04qiGBw==,type:str]
    pgp:
    -   created_at: '2026-09-01T21:51:04Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAjlhBskUygPTKgtjKl8OWBJ7yGqVDz1Q6sFGZ6qOLdysw
            LkcbUkAAd2Gi0j0tN6oH9+/Nd/OK/sFl3C+AJN6UM3WvCw2ceN2dpqutBCePOHJG
            0lwBSlMisQXhH4+U+FpGzXfdU6gP9qsr2TfhiRQeOz10gW2/TPU4h0pVQwP6aVL9
            nhwmaPsqeRj/zAvVBuSx3eF+OY1Vov9WsgorKlgIFiAA3Or/n1LAQ82dhcDk0Q==
            =bL23
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
