apiVersion: v1
stringData:
    config: ENC[AES256_GCM,data:JkfgRk5qzj1ClrZ1IwBOZCwDo4ffIcwrETD9N6XXv+dJxan1UXQol7nkMD8uyLFHbQUDCiOfv4jWJoM9VC/QEHAPCixgZcbMnOSrfeSsnP8YscFdYpuYGv2i+xf8RN9BBLUfy15dn1t68qCarfZdCitsytqjXnLHQUpjzr8Hvi0CgTFAAv3QpwNgmVw14zO9wHdaqmbcqqs2L5vjZYP+Bfe6QIzqPORV8RPxZz1KstkNjzYf87pcR54eIIx4Svmc3i+FFsor9yTZBn4KwpOrSJ+wnWTRiU37Dd4hWaLLKxu87XHufxXWGo8pVpYeyz2/pEl3M8EEfU5jhazYaSdU1ErG8TRNIXzJ5JnuXfONY2uto7MlRefsOrT7Fu0nCfzDYyk6rLumLe/5FoH3yjsPZpD9mKI04JMwLQce4kCPA4dOzkTLmqGkG62bptji6uAgVxFgv9jM1IN0zRey9kAVmaOB4EPYsivdCQq+2Lbuz5INF5N+ThtDZE8VtudutqyutxBbC2rJEhtP5fYMVEJMwVgQOh/GbTE36OjvBnG3HzxjPe5m6/RTvK69e7OykfBg7QylQMkW1i3EjR0YNMG4xtyYOV9wtx+Pquu8+w+41ZdF92JW7LH5Ri0v8/VVxQl2Y9PoiAQRP6SnDYk4UUPq2WrYV/U9QfXtDbXkZ10rvX58u7QgZfoRYdi5t/9gXA3593PbWq+S5Pkbieg1q8c1QwtyhoOiYElgQ1LIxapzMSxJv0fF3vk4twVM6Fo03UfGrWruZ9XfMp9z5WtSlbkhp8W2+c1i9KRtQWEsRmFsmCIcBVRIdt1p4GFkq2N84MB2vAc1pR3QpWewJ0gcXnYIkKs0rbsZvD1CoH3Id4Ey6YHPeQ3eB7EeD8zhE1bcwsxgpswYff3YoS9Hqosc8r8HY/xBHmDwkq8sRDR3tvrvDkC8H7MoL9VEs+eXYGdzb+381JJQpC0in+Y6sgbKvv+fM4m6RVFb//f46jjFGHsbUqZT0lcGr5OOuhNiPICAZvP+0RWYq5lrklKAZspE7bGFbyxvvuVylEkgppWDrbHRClI1NiV5+iz3gp8L/gLrMkKg4F67Hfb4jMPFSuySbNScclMZBLE4ATnIHIZqpE9/FesZ02+VNnU8R85GSK0MB0P7+wavD9o8+Brmx2inJAdfsNjjHz/FTACF36vJKz1JiJ9Tq5WSS1B6ij+lR+7B+24Dcm1RAZZKRc1XN1Oe2neRPWFC9n8WLheHRxDeb3QIJGES5Q==,iv:aG3VcEj8pXPV6C6l9KmEnmynY6cXAxZMRMMkhmo6VtQ=,tag:Rfldet4erCgwZbUNc5eKIQ==,type:str]
kind: Secret
metadata:
    name: openbao
    namespace: openbao
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-01T21:40:47Z'
    mac: ENC[AES256_GCM,data:rcXsGq5vsnI09m4f5akgHBF7hlsDbKQpY6Hsbj2WwbvjZJpubY7uutRTmPvjkZPcPjM0HVmBVmV9d/aEt5s6igIesU2cAY+l5kOpds2XIa0EOiZCzrBzdEMyvchbxox1JdEul4dtbj3FLbK45lSRtAsxdxq+TGntKPDltl8/Jwc=,iv:wFENyeuqQV/FjQOcGfefVY8F/k97YVlER0alLi55LQ8=,tag:d//ouWemJi1bK707nHGZgQ==,type:str]
    pgp:
    -   created_at: '2026-09-01T21:40:46Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA9JgPWTCOy7X3lpbQJ+PU/3hke3DbDcjpaeFHnbE9dQww
            vP+W6rHiGJdSbGKNLLgu5zreZ+4si4m+h0VNur3qump1pQD0eUQYoFra8IvYN2QW
            0l4BV9/p5cvJKlUbhdZZCbECaHmrIbeOs/7eyNoUzPvwiB4FnrYEc21YMuMHXRzM
            5lw3o+pHAGQD/aJ1pNU3lfK7x14w70u4Uit7rR/TPVfBfJMciDWJG1DTg0fUDPG4
            =KIWN
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
