apiVersion: v1
data:
    TS_AUTHKEY: ENC[AES256_GCM,data:B2J5sYMkcl94xX+kRQO3Ivj7HuzdRBKuYX4TKqRT+2XHzWU5jKNgY6Y0/RTfTwozBn38SqnAGBSxJooeOgJd7K9LZ/UQLVzw6kKFA843F9uvY6Cs,iv:W4O9Dt37Ppj7gcFlGAla3pQQS28xNRarjAbhqyFDtfU=,tag:6GcH8UcXXMqeAsajNaTiPw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tailscale-auth
    namespace: tailscale
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2025-12-17T13:26:13Z'
    mac: ENC[AES256_GCM,data:jiRCE6m1AUxyglazuWZydIhnsJFo7ZvxyEQhAtIRhDDmofx5Itrj608pniYIvzZPmc5k7TQJ4is8nztSBwG84gNflE6y30+5N2NxfrTppf7NiISWNOwImaXZb694zxKXt/dhD2Ihzgz6nKdYcA1sbcQOge1A/1qDSiy1R6UJENA=,iv:ew8Ue98j3vmwd1/nC3QIwSXelcd/vEaSoHH1iYpO0D8=,tag:1Ejrb0mp3oIY2ll/gdPY4w==,type:str]
    pgp:
    -   created_at: '2025-12-17T13:26:11Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxv5FnUBLaS9AQ//eNawPlRnkoruVN/HO6UXSWhoCJsIDDP3YiyzcmSVMcxr
            cdY58k6RgHYG+S8ItvL7Smxf0xMQSPPopUYZEKfMGKjGMrjI4vb5JHXzMeTJtnfS
            AGUAoAjf64i9bhkJSUBDTGjCXrm1wTRaEibnuPObQUxIY3/wcwJoSzkoGJRH28K8
            g0KEIH30mij2BVdBaFVKWtye1op+Aojz4OtbDHRnv/PHwoSUv276rzzIuzsdCauk
            GdmsHCX8f/zk9u6bYjlSHV1tGhPzdK5psRwiRxO3oohDJveoKDdkQEAUMIjco65M
            AYa5My/YklpViy9d6mObX674yLHJ0QjQEnPohcA72J9w1riUR/undCQu9SByhT0B
            YjSiYwZRLrZY+gqa1WJbGUbmEA9rYeOoh3aqCJLTmFAIkXXpWaaeFcbnv2fwr45p
            YVPU44gQL64WCQRPDG//F6OH31R+Q4/0AaHl+7Sl9UnkhAzeATa4eX9WIrebbT86
            lfOEJRIaKs5TYcFI6RfeP9092IBVbM20Gy6+F5AYdnSdH7CkHz7ael7Z8VC0fN+k
            cDLZqoTM3ieaP5m1RTc+uk5t1IzpMx5WfsxaDiBqQqmPQ/0xhZ7eILD/uDWT7QRX
            dJPvrf/2OCMvmkJBByP7DGqua7DL7+dxzmip8+jAyZY1Uc+y/8ZjhGmwRplfEdHS
            XAGpj9rSmrdvOTYiI5aPki7yRblWEiBOsNYKqW//mcOJ2BjTaPy3ud9NLHjdRFbQ
            xcRDerhSjJ5IQzbWdYqXT2CH9XhVAn49RZKULYtmbLWK5edV1k3EK3LTP6ck
            =pCG4
            -----END PGP MESSAGE-----
        fp: 0BCA2EF044187A707E2507E54C4527913792AFD8
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
