apiVersion: v1
data:
    TS_AUTHKEY: ENC[AES256_GCM,data:jJNHI6gsbI32/dPKb9hGgEBuN50FGjcdCqoepAZMkUs4ESFxAxBXFg8PS1c7hDxhd27Z1vXtwL4BAdgF5J6m5IN41rUkkdCNjcnDouNCFslxgibk,iv:XRA2aVwCMG++m/wPGxOFco6oCpJHcrqN1jAOOBrsApY=,tag:1+QkIKCCx3UZcFTwT/N/tw==,type:str]
kind: Secret
metadata:
    name: tailscale-auth
    namespace: tailscale
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-06-06T22:38:59Z'
    mac: ENC[AES256_GCM,data:7TjS/11dh5DM1zIXbHhcKClV8Y/ZFJbgxLSnTNp3JOiMwVs/DvgTFgwWEtC/MyX3QiCZ6A+47tkzC0bQsiD+qF2AE5wQiznHrFzfTlqa2PxCgNFU3kSg+vFS5QsMp1jFaQwZacLOKFEKswKVGVyA7Qgd+pxQ7vovZNtBlAAOnFE=,iv:y6Lnr1D6c2hDLop7RMArhTHS8Ksyd7bEoIUF5DE5cQY=,tag:w/XrlVCpYt7qGD5S3Nl+aw==,type:str]
    pgp:
    -   created_at: '2026-06-06T22:38:58Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdARsVLuLYqCBfVGX5qb5XKvrPHmKrzgAHcULVe2joChAsw
            m6lMKiOjLBHnuXDKumiyTqh/TNeZ/ZS9OMchmuzIRvFmxR689WfEaNXOOmVy6gj8
            0l4BWWTfQn+RI3JHHa+sfiy/X5ubSN0TiyQQTgGBodjwNgjQr5A7ushhJALQLzzv
            8E+Oo20PKIrZJ7mlOLjAIe3gOgEsD196pF0KCnRz7PnSPQqS4opdYNpdbPwMHfqM
            =Wg6d
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
