apiVersion: v1
data:
    TS_AUTHKEY: ENC[AES256_GCM,data:wM7nYdhcA34mRNsaBYlau0njZAr3xrcpRBJNZGrkWeYXfLV9iUw8mUFgAtBFQdJVnTIskM7nZ7TV7NQfKVxD+93Okg/gEl4/oVxNxP6U7u089+Ot,iv:ihhD5Ora1WMINs8qV3Y7jneHqQIPn3w69rJKy9Ww3jo=,tag:imxdKv593zemDyjHHP6CdQ==,type:str]
kind: Secret
metadata:
    name: tailscale-auth
    namespace: tailscale
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-03T20:31:04Z'
    mac: ENC[AES256_GCM,data:sU1sD0v1bRYO+9F+WbqbnzGCNvUVn24to0j9J9omd+96I5hpksA8ORDGb5d3YyVT7dkf7sOi4A38SqupbhqYX35P5IcHhH5Jqu2m3HJWe7YaC5RVbpJqHoOMUhYRLNncwIyXVd13MX2nxRjWpsmgVDO+UTcXc1ZuuhLj75ZrQS0=,iv:zczdPlz7ZviFUEYaHMFceahcgZzV2GFfZ8rLdOM1OzY=,tag:SMlTyztdizQzPnlT6ANAZw==,type:str]
    pgp:
    -   created_at: '2026-09-03T20:31:03Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAsKRzQuxt/Wh0TevYX4f1B6R9nAJJaCOiTwbZXCpGBxMw
            F3Gka1P3aUDkvqb5hOjpJHdm9vefBEeRpeCEobX716UICiwxL1qbrco/5h8aLx5M
            0lwBDQwpueI/rAWSGI6DHFXfb0yRVy2hBLXKQ5A/yMg6da+QGp2xQFIZwLPKPjH/
            nD07I+xN/HKo63ztk+tDpJI++P+P3ByXQ+6iNze+KeuYmrnQ9ssD2skL8IvRcw==
            =qInZ
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
