---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:v3.5.2
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          env:
            - name: LOG_LEVEL
              value: info
          ports:
            - name: http
              containerPort: 8191
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: http
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 2048Mi
          volumeMounts:
            - mountPath: /app/.local
              name: temp
            - mountPath: /tmp
              name: temp
      volumes:
        - name: temp
          emptyDir: {}
