---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: victoria-metrics
spec:
  interval: ${interval}
  url: https://victoriametrics.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs-collector
spec:
  interval: ${interval}
  chart:
    spec:
      chart: victoria-logs-collector
      version: 0.3.7
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
      interval: ${interval}
  values:
    nameOverride: "vlc"
    remoteWrite:
      - url: http://victoria-logs-vls-server.victoria-logs.svc.cluster.local:9428
    maxDiskUsagePerURL: 1GB
    podLabels:
      policy.gatekeeper.sh/ignore-no-host-paths: "true"
      policy.gatekeeper.sh/ignore-psp-volume-types: "true"
    persistence:
      volume:
        emptyDir:
          medium: Memory
    resources:
      limits:
        cpu: 500m
        memory: 2048Mi
      requests:
        cpu: 500m
        memory: 1024Mi
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      capabilities:
        drop:
          - ALL
