---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pairdrop
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pairdrop
  template:
    metadata:
      labels:
        app: pairdrop
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: pairdrop
          image: lscr.io/linuxserver/pairdrop:1.11.2
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          env:
            - name: WS_FALLBACK
              value: "true"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: http
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 64Mi
