---
apiVersion: v1
kind: Service
metadata:
  name: cmangos
  labels:
    app: cmangos
spec:
  type: ClusterIP
  ports:
    - port: 3030
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: cmangos
