apiVersion: opentofu.m.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: proxmox
spec:
  # Auth is via PROXMOX_VE_USERNAME/PROXMOX_VE_PASSWORD env vars set on the controller
  pluginCache: false
  configuration: |
    terraform {
      required_providers {
        proxmox = {
          source  = "bpg/proxmox"
          version = "~> 0.111"
        }
      }
      backend "kubernetes" {
        secret_suffix     = "providerconfig"
        namespace         = "crossplane-system"
        in_cluster_config = true
      }
    }

    provider "proxmox" {
      endpoint = "https://proxmox.home.arpa/"
      insecure = false
    }