apiVersion: v1
data:
    BW_CLIENTID: ENC[AES256_GCM,data:7vhPLOeSD6d/GXll50hxRRqZydab52kI9xBsrKj7dTr9v94g5FvC9kG1tY7Z2Y/6Fi5pLEBCwok=,iv:Aoc0rXx2PD6cqwo7e7cSjd6qLV6a1R2eDcoksw15Ny4=,tag:K/LtRni/Ro9oAGXV4lmYHA==,type:str]
    BW_CLIENTSECRET: ENC[AES256_GCM,data:DBa9rZI7S3usouazMQeMubUxdtWxeGYD4rIctKMRV5baPU3kZPFJtg==,iv:JgfNtRVv+aBBtKHaCLb8Ejia4t0ZrRxj0ZuERdtyMus=,tag:3EJMNkjhmQvRswIEIP21ew==,type:str]
    VAULTWARDEN__MASTERPASSWORD: ENC[AES256_GCM,data:MJT82MLwBMW9cNU7nimeu4+5AtFEj4qLTpnd/gf2x1s=,iv:vUO58NugtcO0eAk5PaqGiqgkCcjrAOos+uYQkUUKq40=,tag:oCcziqhndGXSiHzePMnD5Q==,type:str]
kind: Secret
metadata:
    name: vaultwarden-kubernetes-secrets
    namespace: vaultwarden-kubernetes-secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-02T22:03:22Z'
    mac: ENC[AES256_GCM,data:DCvJqVoq4WMzBvopjh9N3tq0cCG44Gvws/wFLmz3XftsYQHgL0EC+dc0/B+Ad7/Wq1c+LatD1VGV84Wq8XmkFY7/kslRZ/zwQ5v5eGqggXxL9/sDXr9t8abuCHmVmhCM2B0a3v6URLYlcYzkelp0dBXJ2e0zLyntnZ8juWov/sM=,iv:QHhiUrbEP+mYd2vbwMkym8d1n3oqVtuYEC6h6QfL5nE=,tag:QN3J9o8G/Nr/6crIV6db/Q==,type:str]
    pgp:
    -   created_at: '2026-09-02T22:03:21Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAA7ZxxMIGwjYkLmskBQzRuSwSmsAXO80T0T6E2GVP/1Mw
            vAutGdCt3t9hqAnHpINL7XVxQvvUMZ1yhCMxxCkt3n67UShic+h5ETGITODnWvho
            0l4B+D2q+jogfwEWGSIxNWfyH1CrXHEnGDqIQCB2Lj/5kt5fjmZYmVUrIOWdNm19
            kc6jN3T6Of7TMXF2UfF36QbTw+t08prMbikjX/SAx78SBczvmKPTpMoNQ8xVG2W8
            =fBBU
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
