---
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: s3
      protocol: TCP
      name: s3
  selector:
    app: minio
