apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plex
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - routes.yaml
  - pvc.yaml
  # - secret.yaml
configMapGenerator:
- name: promtail
  files:
  - ./configs/promtail.yaml
- name: s6-plex
  files:
  - ./configs/s6-plex.sh
- name: chromecast
  files:
  - ./configs/Chromecast.xml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
