---
apiVersion: v1
kind: Namespace
metadata:
  name: plex
  labels:
    app: plex
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged