apiVersion: v1
stringData:
    plex-claim: ENC[AES256_GCM,data:rWjS/EMw8Znntf5HMrVaYDes/OZpg6OTav0=,iv:ubQoW+4jD3nejqJb7Y/62vWJDbYE2pg/kyyFCCbb/rE=,tag:wcNsjHkR5j+7F1S+9O2oaQ==,type:str]
kind: Secret
metadata:
    name: plex-claim
    namespace: plex
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-11T14:47:19Z'
    mac: ENC[AES256_GCM,data:dRLMY33GP9B09N8v0BhUBVvln3NUfTlAbnSe0Do3Wu6MSl8qkfnY0RCnV9QpoUDAGYWUVNwYf4x6i9L4gZacgES3OPNW/gauzpYw223QJ8nDTsUl9pwJMYwdl/hFssUmmf2O7fySAWFnZE4EIVGW8k5g1qaDOJBIDJiV1nC5Bfk=,iv:yzhLmZJtUBMkp6vM7FHZ71MpbFtVsdLb7kM+o1u+E0M=,tag:+Z7kbQUGvsueH7cuOdlgBw==,type:str]
    pgp:
    -   created_at: '2026-09-11T14:47:19Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA5mmaZwS2323we2L83A+jwbXG6Hf1CYxDbh97Rmkbnjow
            Vc8Q5Ndp8an8kGUuEXWzfn1/d+kXEuru+rO9AIDPf2RkyJtl1HlLJsVFRpRqTWfP
            0l4B3x2SV44a6U1W8v41Fv4ZiRc6B4vUVhky/SKOCtVbXTU0EuXO1H1rzsGHIvaj
            gIpOgH6JFhKLbF+WPA3uz1SRRlyKNFudYpWoaQSuyJ6D4343TLaZQA3ZTdUYXegm
            =WiiK
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
