apiVersion: v1
stringData:
    plex-claim: ENC[AES256_GCM,data:h9V5vVUigT379Uljl0DiK8cOPixs5HlAZas=,iv:uvgQ8f2hy4uQwinmw0YunJBhgrtqF5vMKXw7/ji4izM=,tag:RVE3UTpLWinOif+lozUtjA==,type:str]
kind: Secret
metadata:
    name: plex-claim
    namespace: plex
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-08T21:48:12Z'
    mac: ENC[AES256_GCM,data:8RbsRwQxdHsyL+lIC/0hM2x3Ddhr7zVluSLsfB1+7Jy9fiJJAiz3JHVST4Us4KG+rl8p8ZrJ234+ns4q0grpuRey9znvVtssZiuDxypM1Mhxh8bJJJEpAva0GX3pdbluVt6DG3KhT35E4hPbOstpvJcYK135jPBdgnLyG0JrnXE=,iv:73swOLytG3sa5OrlKuU6aTlYMDF0l2mhYAoGrooUc9o=,tag:/DxfFmTZHzlbe0iduUezQw==,type:str]
    pgp:
    -   created_at: '2026-09-08T21:48:11Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAOVvuNEYK1SyzpoGGf9nMUAcajma2tK+47xhT1SGcpjow
            1890UJXb5IccSjhAhm7vbKgN7Rc6QDoAk8IG405Xw9c+ZkgnZU0hwA4JmQKDziS3
            0l4BIspClr5ci4T8nndTjdLa8Cf4/SqwQOJf2lA45eTwJDNd6E7r9aigpJ3LUmSC
            q6Ai06CNc8J16hXFduMkSkTy6hPpLpsUkiLfC40GVY9DtMVbaNQNdKtT1Fq453+t
            =gvY5
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
