apiVersion: v1
stringData:
    plex-claim: ENC[AES256_GCM,data:vbIlR3mXzRGwisviuZPJ1464KMhc+ZcJkMI=,iv:Modn5lHbj3LqGUqsyel6QpOPfVi7qP77RRROJzumYug=,tag:GI0mCI5suuAcy6YA6sXWNQ==,type:str]
kind: Secret
metadata:
    name: plex-claim
    namespace: plex
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-11T14:58:20Z'
    mac: ENC[AES256_GCM,data:Q+6a34XLejGH/7VM5yuVDmnOXLQHQFRDJry84sdMy2cuYxBNlzwNT/dBNnTiuxmyJTLuHCIrCcKuXqy1zqQbyFWqSP2MyJm/fbuRyYQyv3bOKye2SMqfpeajkKsqu/9Wk0AHsA6SLcCndg172RNBlIMHUr10L0QpPwNz9E6engE=,iv:AAhhu2z3zA10be+lnAUQffW9itGHPmU38SfAPPB0rWc=,tag:HsrWwOVi5mePueK6hI+E0A==,type:str]
    pgp:
    -   created_at: '2026-09-11T14:58:19Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAi95a3a+HJBP9nChA6XtVuG3gZdsQGl9MgRoDy0tgOlEw
            uBDmaVazMKxVhKz+sJ/UxK9sj6Ao8K3INQnXYIaoQRYkpH1SEVgom1aFDkqsOxXH
            0l4B1oQs1is14WhW5oj+2BpkoYyLC12ynYXZx6zPs1/93OORGKn0/ucyZAOUipmx
            wXOZQztoCstR14RWqHsJOyBypcWYLkB2N/pNkFTwqRy/0mFKRYO79RV5q65Pk6Pn
            =UNjF
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
