---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: city-roads
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: city-roads
  template:
    metadata:
      labels:
        app: city-roads
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: city-roads
          image: shokohsc/city-roads:release-20210531100947-17-g84a77a5
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          env:
            - name: ENV
              value: production
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: http
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - name: cache
              mountPath: /var/cache/nginx
      volumes:
        - name: cache
          emptyDir:
            medium: Memory