# acl localnet src 0.0.0.1-0.255.255.255 # RFC 1122 "this" network (LAN)
# acl localnet src 100.64.0.0/10         # RFC 6598 shared address space (CGN)
# acl localnet src 169.254.0.0/16        # RFC 3927 link-local (directly plugged) machines
# acl localnet src 172.16.0.0/12         # RFC 1918 local private network (LAN)
acl localnet src 10.233.0.0/16         # RFC 1918 local private network (LAN)
acl localnet src 10.42.0.0/16          # RFC 1918 local private network (LAN)
# acl localnet src 192.168.0.0/16        # RFC 1918 local private network (LAN)
# acl localnet src fc00::/7              # RFC 4193 local private network range
# acl localnet src fe80::/10             # RFC 4291 link-local (directly plugged) machines

### ACL for all local sites
#
acl localnetsites       dstdomain "/etc/squid/acl-dstdomain-localnetsites.cfg"

acl SSL_ports port 443
acl Safe_ports port 80		# http
acl Safe_ports port 21		# ftp
acl Safe_ports port 443		# https
acl Safe_ports port 70		# gopher
acl Safe_ports port 210		# wais
acl Safe_ports port 280		# http-mgmt
acl Safe_ports port 488		# gss-http
acl Safe_ports port 591		# filemaker
acl Safe_ports port 777		# multiling http
acl Safe_ports port 1025-65535	# unregistered ports
acl CONNECT method CONNECT

acl hasRequest has request

### Access rule - Never cache local sites
#
cache deny localnetsites

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow localhost manager
http_access deny manager
http_access allow localhost
http_access allow localnet
http_access deny all
http_port 3128
# visible_hostname ${domain}

# Memory Cache Settings
cache_mem 256 MB  # Adjust according to available memory

# Disk Cache Settings
cache_dir ufs /var/spool/squid 5000 16 256  # 5 GB disk cache, adjust as needed

# Cache Management
# cache_mgr postmaster@${publicDomain}
cache_log /var/log/squid/cache.log
access_log /var/log/squid/access.log hasRequest
cache_store_log /var/log/squid/store.log

cache_effective_user ubuntu
cache_effective_group ubuntu

# Logging Options
# access_log stdio:/var/log/squid/access.log squid

# Logfile rotation configuration
logfile_rotate 0

# Performance Tuning
cache_replacement_policy heap LFUDA  # LFU with Dynamic Aging
memory_replacement_policy heap GDSF  # Greedy Dual-Size Frequency

# Connection Handling
client_persistent_connections on
server_persistent_connections on

# Error Page Customization (optional)
# error_directory /usr/share/squid/errors/English

coredump_dir /var/spool/squid

refresh_pattern ^ftp:		1440	20%	10080
refresh_pattern ^gopher:	1440	0%	1440
refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
refresh_pattern \/(Packages|Sources)(|\.bz2|\.gz|\.xz)$ 0 0% 0 refresh-ims
refresh_pattern \/Release(|\.gpg)$ 0 0% 0 refresh-ims
refresh_pattern \/InRelease$ 0 0% 0 refresh-ims
refresh_pattern \/(Translation-.*)(|\.bz2|\.gz|\.xz)$ 0 0% 0 refresh-ims
refresh_pattern .               1440    90%     43200
logfile_rotate 0

# delete x-forwarded-for header in requests (anonymize them)
forwarded_for delete

dns_nameservers 9.9.9.9 149.112.112.112