---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: byparr
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: byparr
  template:
    metadata:
      labels:
        app: byparr
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: byparr
          image: ghcr.io/thephaseless/byparr:3.0.4
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: 8191
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: http
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 1000m
              memory: 2048Mi
          volumeMounts:
            - name: shm
              mountPath: /dev/shm
            - name: cache
              mountPath: /cache
            - mountPath: /tmp
              name: temp
      volumes:
        - name: temp
          emptyDir: {}
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 2G
        - name: cache
          emptyDir: {}
