apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iptvnator
resources:
  - namespace.yaml
  - listener-set.yaml

  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/http-route.yaml

  - backend/deployment.yaml
  - backend/service.yaml
  - backend/http-route.yaml

