apiVersion: v1
data:
    BUILT_WITH_API_KEY: ENC[AES256_GCM,data:2g8VBqqCaF0TMff8e5DvIKrNQh0xMQ/3Xm6uyi3GCRGFSys7sX9VHmb07rq0yS5q,iv:KoNszNBInz95Nbwg4B8f8kes6JJT/uDuprhW7d1hw7I=,tag:1Lv5baYCKvzaMZRBLfjjbg==,type:str]
    CLOUDMERSIVE_API_KEY: ENC[AES256_GCM,data:UCj48JKFd7wQV0qC/1KLfZDP6gquZjOqzp/sJJKGbba7gzVAsla3JmzKcd0pwhC9,iv:tWTRkaPZb5oq2VkiC+TiJ0lpp6BYWsG+ll3/DGFSLI4=,tag:/dlEv/gBl9+rI6ULS9ksGQ==,type:str]
    GOOGLE_CLOUD_API_KEY: ENC[AES256_GCM,data:wLLcET3ytmK01jDSwK6lf2Drt/5UBOJXPfhVdWN00ulZI/NF87i5p65bkAlfodk55Y7JBA==,iv:JsKpOTXDKJWEE0pUQFxHMSKPXqqX6qU7OyqeuLrhTYs=,tag:MAPcWtNVB5yWo2EUwkKikg==,type:str]
    REACT_APP_SHODAN_API_KEY: ENC[AES256_GCM,data:lu3gQykn4dOPHhh/Rakn5kpvx97RbbF5nfQUuHCapMrHe8lZqMy0p85c7ts=,iv:z+sivvfAps3gcRBSNoZP90LJXkjWSax8be2uE9sMOMo=,tag:iPmLdPZf7F/jIx/yrhBTzA==,type:str]
    REACT_APP_WHO_API_KEY: ENC[AES256_GCM,data:2Sf+e/Rs3Xg6mQHTVXZkknDD4gKVn7qwWb8VqyRUNjo=,iv:zMqQ3aCiiZRUUwLCS9gFCaVb7D/Vfq5AWs0YV2Y62Xc=,tag:UNlRCWHZwiM7VRQcW/t7yQ==,type:str]
    SECURITY_TRAILS_API_KEY: ENC[AES256_GCM,data:sS6SPw2sIgX6733jJ3/wVcs8+CLiCzQZU1Vtm1nVx+jzvde+HBEyDx1Mp8M=,iv:oc9lVrfNzFA6zyujFS/2AlmnnXLZmTVJapRvcsfDqMQ=,tag:MijcDS6rX+j7+3uX5J6WPg==,type:str]
    TORRENT_IP_API_KEY: ENC[AES256_GCM,data:t7js+5mkArt0bR+B9Hooj2f14qiLeonEhCNO5kAjz0rMAQS0/qHF9j6b5K4=,iv:BpS8X0XzUeVrqON61ct7CZSI1swgAjZTaxMiRPwJK8Q=,tag:vgiMFQu1Y371z5jpJ4u9Wg==,type:str]
    TRANCO_API_KEY: ENC[AES256_GCM,data:soumR7PRcoK3T2vki4U9OUnI7EnXySHeE+L5v/rVXNw7x9GPiJelSASnZ10=,iv:V66n+aqMaAYmiDw+5VHJi4+GDwtlp3OUgwc5ht8BGkQ=,tag:VVdieY2FP0tIb1THTTYdIw==,type:str]
    TRANCO_USERNAME: ENC[AES256_GCM,data:V8f5C/9GYU3Bb+WyH+sAy+x6eb8MCsLDzuLhOA==,iv:3Mo+gWpkbrAjQXzWuACLxNSffFqdxMPTTouxtkz5lG0=,tag:Ag7D2thI4AAmVxMG+fZJSQ==,type:str]
    URL_SCAN_API_KEY: ENC[AES256_GCM,data:gG9I7FlABmNcLFmDY/l3aW9ODcxhF+XKmfSQvt/bG+eBZRzBHklF39nX4/zM45nu,iv:+UHy25um5UMk9BOEfhPFHmlHPw3DTbxlUHDcfy2JkF0=,tag:2VwmmCWw/mHGovm6uBhhFw==,type:str]
kind: Secret
metadata:
    name: web-check
    namespace: web-check
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-17T13:31:26Z'
    mac: ENC[AES256_GCM,data:F3dsat5Ncmf0cgFR+YHOGEtEXSWwOJHeUtAZIW4D8XzUwksyfRvUd+GNtGSQQGYgKHxAaNXb6bwzpQEjRpQwZ5cHuokM2zKkuCTMlIV0tWZCIbko/vHMhBZaTvqL4Xnp6AQtB4bWh3ldEovRJi7k5VONBQRsICHBAdx463WQvoM=,iv:b1P/Q/1C380R9TBDSj4D3RVyUdTTzgSbfS5Uw7EhXL8=,tag:tjAMba6b+n4pIgf1WbQNvQ==,type:str]
    pgp:
    -   created_at: '2026-09-17T13:31:25Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAUsSTlJ9ggjsU6wpaG1dMFDCIsFZOyB2aMFhQ/7k/VHUw
            W+1JiElAIxigyE34lBAEYeVmc0m530HnLZxvag4Gdk92P8r8wL6Mzt4Y2vJHW33h
            0l4BKpIhP2oY7xcoCdQzWfh7n6q/SzKYTwVATKqAZQwbP4VPcTpUz8y60PiP81u9
            j47KWBEZKtqmO/EEKqOUccDLrZZdKx0n4oxVmW1axKFC33wxp4v1ppgE3o7lhVzL
            =pCwW
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
