apiVersion: v1
data:
    BUILT_WITH_API_KEY: ENC[AES256_GCM,data:6SxyURDZEU9xoF6B2Hn97Y70Rwm34rJBCs548Zxv844mHNxK0X1//GsHeyUfjCJ9,iv:ECH7qqsOkSBPfHNocIaKfPbsOcHFq1hJCY0xbl5muFo=,tag:OVnHiC/u4aUDdkAMmVx7Jw==,type:str]
    CLOUDMERSIVE_API_KEY: ENC[AES256_GCM,data:Fm9pK9uSZLjH/eZZFdaCPrlkzYVrQ1T4gmpLM1oQlBsOIUP4uA7yGauHFa5hVCSI,iv:tYbgWzckT6IvPdeBCUFh9td9l8PA3AENWJqwj7ELECg=,tag:VDTwF7VSANph0kntCnvgGA==,type:str]
    GOOGLE_CLOUD_API_KEY: ENC[AES256_GCM,data:vx2rnShACpR8Qaxz08lVC4FzaYNShfQHMooupIDa/jW5JaypK+lFgzVwlJ2mnfSXTn9V9w==,iv:b8ezd65X+1uEDEoaxppUdvgM/jum2Yi6uaW+7z+jzY8=,tag:cDRF8HHK9azKf2Hgrh7hcA==,type:str]
    REACT_APP_SHODAN_API_KEY: ENC[AES256_GCM,data:rqloLB36F3TrC6w0lczAq9Q11P1ddo5xRzytdnowwSIj6cHpIO86r3F032A=,iv:lYif/PutiNlqQPmXvf1dMScQSwf/QV2d/OLT242Nsb4=,tag:EVOJI+C+XfgELfv7anXC/g==,type:str]
    REACT_APP_WHO_API_KEY: ENC[AES256_GCM,data:M7g1iyXyE8Jnf8aMOjTD4k9oxWqbjlytdMma74dMjoTd3fwp5ZnIIjQ7IwA=,iv:BiS4mkqodMbVIgwLKL367msf1jnw55g/Mb+VAD/uPds=,tag:cx3OP7cLPGSyRrC630HcCw==,type:str]
    SECURITY_TRAILS_API_KEY: ENC[AES256_GCM,data:gMJH+sBgsIuXiKJj2TP0NBZYVgUwFOkgicUtrCRq3U4NGnlAcztgw4K0Fz4=,iv:heiffLInQQDu4scWOl7k98D/JxVa040DuHhxHdP9zAo=,tag:6EIAdsrxSBRdXTbye73yJg==,type:str]
    TORRENT_IP_API_KEY: ENC[AES256_GCM,data:E9TtAnuGP1Jc1SB8MpL2L5z2B80D1sqRZ7o8eEjsEIEiJ35xiPO8QI9veU8=,iv:2O2nnrBHZS/eBMaW14sscqMC/mzD7Ga3gydAuAokwH0=,tag:rGnxiyFTUI04ldOYmgxBCg==,type:str]
    TRANCO_API_KEY: ENC[AES256_GCM,data:zVuXe9hHSKWe34kw1iTLIZept0yeh/ZXHZYT4+JlpZhgvzEbVBVOLTmD1Nc=,iv:uJKUJU9f8bl/MUMV23pHr9fu2N8P/+7jpSqPig97nA8=,tag:I9xH6yXtiJ8nhCMjXDKG4Q==,type:str]
    TRANCO_USERNAME: ENC[AES256_GCM,data:qJP/zw2TDB63ZjKmKzOeu/IE8szz4UiTa1CRzg==,iv:YkDswuY1AgDbc0NYl0t9dVai9J6VNdrr/7ZcCZJ5kQ4=,tag:+ZaMnLKYtn1Iw17dgu7Img==,type:str]
    URL_SCAN_API_KEY: ENC[AES256_GCM,data:RD7K6q7awN/kAtT8VyuyKehrfVU5X2nX1Iyf2kCOIPmE4oWW9+QbgYmvPQtfYGGy,iv:T+/IwYs1IofqiHj30fmXpcxDun/EJ7nJKs9e5z2yieY=,tag:+LwOpm6s6xIsb1BzypJE9g==,type:str]
kind: Secret
metadata:
    name: web-check
    namespace: web-check
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-17T16:11:02Z'
    mac: ENC[AES256_GCM,data:xuRSTF8MBZX2iZHel0sKUUoCTVLifTVhN13pjakfQ2vt/Uqk62HrObaoBIDjRxOBSz1N+M8MPLF/wMnV2rsYrD+wTPHFWWwT/qb0JBnK7tnK+UMn7/rwliudY/86T6ieE1KJhBkJXe+lG5v0TBlYpifpW3iX/egsNXSj+0ZzLX0=,iv:YnpfEAJpicmD9TC4X8148vxQln8v6dU3Dl/xU/6RdAY=,tag:y5YFtrPiy+0LilnuPwY3dg==,type:str]
    pgp:
    -   created_at: '2026-09-17T16:11:01Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdARaOiXVCNbDa3K5p+3Dp3MpVXQhhvqhCs28wUrgq2PGEw
            PY9uyK1HnjHFhjaoyTSzS1/hpLmRu0u4uCT/bMUaxDHgxPivtC20YfU+r2SxvkjZ
            0l4BI4Znppau7C20ZPQjqSw8NGHWNDIrzl5CaB1t9UnrFAgja95sZ2uOsKFIAIXm
            2vNqxUceKP5X1JvoGnv+eKGyti3v3MVCokGLLBz6RClJQ1vySYKJHDQ4fREw3Bbp
            =H7I2
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
