---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: homelab-ca-cm
spec:
  sources:
    - useDefaultCAs: true
    - secret:
        name: ca-key-pair
        key: tls.crt
  target:
    configMap:
      key: "ca-certs.pem"
      metadata:
        labels:
          app.kubernetes.io/component: trust-bundle
    namespaceSelector:
      matchLabels:
        bundle.cert-manager.io/inject-cm: enabled
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: homelab-ca-secret
spec:
  sources:
    - useDefaultCAs: true
    - secret:
        name: ca-key-pair
        key: tls.crt
  target:
    secret:
      key: "ca-certs.pem"
      metadata:
        labels:
          app.kubernetes.io/component: trust-bundle
    namespaceSelector:
      matchLabels:
        bundle.cert-manager.io/inject-secret: enabled