apiVersion: v1
data:
    tls.crt: ENC[AES256_GCM,data:fFFsSR9Whtkps2pUZ+QvyGHJeCh0WfvfnVOFsW2l73fxirxvTbRLHtZq3/kT13oNfRCu6x8UsMo74zWI6hRhsmsGN0m/oz3GgR+NZfqDHhL1nal5oiOnXp7b3zgzBh435muc3PTFOQ4n9AfUSnDv33q5MoRZNVNdhV6PJJpEQobVc0uWdhe1qWkL/IhaqurgOq9XHoYlh8D24uLy80korEMp1eD21rcd6fYbD5VIgIGeQ3rxH7sGy2W9fTsBxbn3+7gMAd4YyiiINbAh1vykTmpIMjQnXo6TzfaqnHMit69l/eVqKGFpwbjPYwOjVzKhTsQZvExAMvGTuY3bw8gT4xEwdfKDG1DOiFchyXbA24PZ3K0htAhsodBB+/MYhOwFOI0XZ2qvCiBrFu+mPZKksdMgtPyF2YH2baOLvvKLdG5eAqAr+gHqE21irgzXmp5xzQUNd/4sX6lssxgcKZJqEobxSv/RddLyLIKmN5vv1ONVYQhVxMtjH6a6c8clllMiW4ZajsY5myz1rPVDsAqfbXD1Afi+iAsxSDCwnDXgX/YrV4OMmJrokXDuR0W84jC+xsK7qB/kLfzbICj0QCX5UFOYDXl5/QnD033ZW7UtoXC9wOBiey8ex9Y3Vh/iK8epniYLmY6+lyI6983QDz/5GYhboEwdqX+y2rQd5UM1YCkSKDaW23BHGG35eHGQiyAzCpdfw+4kX0mQe0fdRLDW+DZ/iTx8Mz2hU3FUlDlGDEMmadh1ZspXPBsinwAByLxYWAtyHSP8VhVTjc6EXZcI5RXkUAzzq6RteO4AvnwmXC6aDS1M1futmaPf+47r67g5pw5vW+DJWk1hQ9wkQjnxlhfgxE1DXSxoqM7eGH2uCq8+ivMy+69r9/UnHMyQhwfaY2UGKdHxJcdEfHm6BpT10rHMefKXZZi1MdGYLMgiA377ib1INpsXzFFo1awO2rTQJt2U8UElBybw0Hrgm2adqdoFHeZZAi1BAAKf9D2Pcp0mI/mlWW66zv/8ighEFnSRWjBo9S8KyKLnYiK933sZN36+08LX9FXj13chTOvUYT5RjvUoNxAhdUqEpK8+xPb4yJBF02PPh0nUl8pu5XaEEoJLzW8+4X9fzIT0+VrSL1/2y+GN9ShNfkdpxr+5gtvVcVbCw0DHmpNgi8Xj5KJ/7DfnHKJWPvByu1RId9fFfLPVz4Pg0zM5JUrQ7JU1FNfhTeaVGdXIzrWVkXDVxz3HOboK3iQhbzu2Q8PJEofOKwWReXTDR1C4rkdE6eywZRxjVHhZdE/oM6mY2Lw2aNeQWI3Q9htdjpnkYL7azHf1PB9YQ8dvhoOhS6T7tv+H9AsJ//mzXRvJcDQygxVBue2CDB1kF6ZI7IxAiUsIn9NQTPsjB0KRXOgzJoY2LDGvcSj8CXHRoxrVmbvAcg4wfN+a/q/tTxD7i0+8Mf/zXSHZ4v2VlUqWNEpJeVey2oGRPhPq42Ds92xk3oStiAScixYTh+eqIXIssJx30nJSb3MwF4YjEhaUvqFFUngnUvzWoA3Ll+9QrbzXjWqcjvfEbnyBp2Rq+xzk8rvpBF6GvT/KPr1nyJDMO+vJwehZLqylXm8TK7+iP96vt5kS9tVyBjv1qQ==,iv:TOgjbYW2C1KiiAMfXPBaLOD3vW8zTubHjNUsyR8kUH0=,tag:G9/Ye6npliqWxwCpaE81oQ==,type:str]
    tls.key: ENC[AES256_GCM,data:8FGZeIUC50LdJP/vpz9VBqvKs3SYd0JlCFGeLdMBYTCvEDJJsFhabFRvklXiUG9QBxfii+5HaDnuG9vtGsmbj1sRCQRdLNN5JGGQAaVtBAd5JLaOyyMwyTLE/RQinxa+jBt3mML/C1KzqCvtdLM3AcstlFjbFnKHa6rAQhoK2vvBKHbYkbIfwzZKAxAHZta80G9mWLbpLetJ4ivXmW8TlOPhKCVsiwRR9v25+booJMDsoLZU15I68+Qct5AMVmqO02NOrioE+9pwzo72aV3AXWCN3j9Z/5ezHP5/Zbd2/91LcOj+DrtqV10UpRg924QGpoZJ6hq4dvc/5qLlQnUJHwDU/kV/Mo3hK51TP9l2Iz2UGl6fEixKkI+V/tiaBLHsX2aNL4tCugktNJsqZG6Gw6lnCI5DhEs8V7VcVecJGjwfMBIreIxeN7Uar+6UW6fqxbV+zILwAxjGEAZYBt6DWvdYduDnWfxNCz0bepSV4rFYcAnrOi9wqtAxrPc8R22bnweTYdslqL8IUQ1mQ/+hPSoY5Gg=,iv:ckPro0i9LWS+blsAGH9NA9L6grqDh9X5VLaAkJC/Sxk=,tag:NPDxxFejrnyklSNbgblRbg==,type:str]
kind: Secret
metadata:
    name: ca-key-pair
    namespace: cert-manager
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-06-01T19:23:25Z'
    mac: ENC[AES256_GCM,data:yW7B9FeJQbpo+cwKj8GLtczv53vFpvYQhfBBdBXGD5i7pJlUR8vCiUIdotDoBccxdmILAzsr1NCDTT2LXvcpH08Mh0Ue1FcgP8MHqHZW/i2aD7eOANvQGpv5IWpq+n1B5lXwhAqnV9A4a1yuEMFI8pu1LB28eUbidosSs7Pou1Y=,iv:DCAHFPxefyaJwrhJG9EdAcOjdDgnuGqHQTCG/vZY2AY=,tag:0Ghs43zoRo4Gl50/T9pSjg==,type:str]
    pgp:
    -   created_at: '2026-06-01T19:23:24Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA+6wyn761jNuDVU3QeZs0UdYfeEITTDhQLiWXYv/p7iYw
            8iCwqbzXT8iAmYGsytO7RuELUEW8reYshSoGrSSNR744tMHgjIB6Jc41u7sbqDId
            0l4BxLW4JbqNIBSSn2g6nZzJCbDmF7S5n7nhLFSK809ITwkkWObUKCwFEAF2GeiY
            8eJeaWxJkoh35apUN2g2Sg+/30U94AvA9+K/gXsCYjjHtEsEno6mLocTlOpWweFt
            =nk4y
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:6UmgXy3BTiUtTQ/0lhD36Z4CDI/EM0l44kBfq6d+/r4XiSpisBkhAN7eJ72P2y0zo+wxHZ/eccc=,iv:hEzD3oythcdJLyIG1rOHwIxsaFrjBqpO5WLyyMQk8ok=,tag:bFQ271PjRJNfYXuVPt3NPQ==,type:str]
kind: Secret
metadata:
    name: cloudflare
    namespace: cert-manager
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-06-01T19:23:25Z'
    mac: ENC[AES256_GCM,data:yW7B9FeJQbpo+cwKj8GLtczv53vFpvYQhfBBdBXGD5i7pJlUR8vCiUIdotDoBccxdmILAzsr1NCDTT2LXvcpH08Mh0Ue1FcgP8MHqHZW/i2aD7eOANvQGpv5IWpq+n1B5lXwhAqnV9A4a1yuEMFI8pu1LB28eUbidosSs7Pou1Y=,iv:DCAHFPxefyaJwrhJG9EdAcOjdDgnuGqHQTCG/vZY2AY=,tag:0Ghs43zoRo4Gl50/T9pSjg==,type:str]
    pgp:
    -   created_at: '2026-06-01T19:23:24Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA+6wyn761jNuDVU3QeZs0UdYfeEITTDhQLiWXYv/p7iYw
            8iCwqbzXT8iAmYGsytO7RuELUEW8reYshSoGrSSNR744tMHgjIB6Jc41u7sbqDId
            0l4BxLW4JbqNIBSSn2g6nZzJCbDmF7S5n7nhLFSK809ITwkkWObUKCwFEAF2GeiY
            8eJeaWxJkoh35apUN2g2Sg+/30U94AvA9+K/gXsCYjjHtEsEno6mLocTlOpWweFt
            =nk4y
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
