apiVersion: v1
data:
    tls.crt: ENC[AES256_GCM,data:gXp7sr/u1CIroyxxj3BxpWqkQufIMwwrvjK0ypma5L8QdWIbVGSi8YEpx187SNnlAPt1WKd5m5V9FbayZV2N7HAIGkobGtU4QKRxX3ZLfXm0cjv6uX6tidWThBKH8J2KJTigKmmQc3xOgoe01uroSh66h9Qb59Rb9F10ylKq89qgQpqRQIWA4K0P7tRI7ioZhXUuPrOHsqNq0M+onZgdcfWgjPRmzPjQXYVjfZoo+ooXhSoQLp18/tD1vaMrtRwiyYsHeieYqMm3kDwSZdCEkxEEF2IfFofw02Trojl1KlZuUfrWwZh/WqWUr3XB2/uHiRgUxd7pcji0EP+gW205lY6BU6k1/ryvcpWLQQO4Faz1Np3X8Ibpj3JUgxcAS0scqbp6LbRk0vK9Wju4ETGewdPuFTUD6W5scsewdEI7uCiKbZJZC5ljPbFBjJ+/mZHuVKJC1h9mKeG8/hUSYd4UX4ccgsdaCSbDqoDIGhQouWhtrlE1fh+TvgO7pD5/e4/3CZSHYk3NgTt31yvk0rwxjaY98/71x1DudjhrAaZdy1JtEEl0l0A+ZEa/kHjX5lilXyOk6RnaLLswFwrB3tasFB1dc4GOhqnU/MIN2kQYEQDaH8Z31IMwKDwIW+MxyPIlxawWxNzPBO/Q8mUEO9lBg8EPYdBFhli1afpxdwLloWOV+kka1SVkrMIXAkvwcvT4e3Q35qboF6h2DvVxzaKOBuq41dNEWP5CMULcW4h6dgI4yhxq0uEVPW/oHWHC+t/GSzgFHk7ByL89vkaHhgMQmroZNtqxXgbGsOu6Zv+xCa5IPSmk2NDyOhmPc6F5ixer58Pcns4/WqaDes0zlFE2dbbDLwczIdqeF5DHmt+FAnTdwLa3UTgPRdYZAJPaoiMu+wPYhNM5Vj83AnZhpLTGJPHG5WHvR4yBijXT826G5HCkVDmz3iciHynjM/wyYSdRc35K+hCIjkx+GCyUbVGZ31LtCscm/ftMdgiSPi1pV/vZn2J1nEDRWvXEx/JPMJ3RD+1+JGP2K9GSkQWLHbghHChOgvAZPEX0p5vXSXUxL20aL6ZAmJB0+MA0uAd593zSauTPM6hVqUhx8FJQkewbbnrIupO/rYgjeQBG9dx0RDZBkD/ZgQd8ONkMaHzC2qh1f4YDOwHFeMihUapExT6/abCmHaZAc2ngOyNh/wOcC+23bNW+zKPkuWX/TER06Iau+ipozLHyy3fa/A8QYEh1dOx1uvZvBTC6Gt0l/6J1/ExEaPSFCJ3rnHmZKyJ79sZTfj/gIqtoBYVMMZdetOLWvd9uJAQ85kbr6KmTxEKlr2emKkRza19KbpFvUrE5keW2iwQPhDnZclGtkcVko725Ev4pFeMmD0BsyTCYWFb2gDEptxW6DFpZCZzywDDfSN1oaJ9JDrjGh1A/4x7LZd84A9McnILS+pz3Nl2tunmTbHrOry1gwBJgewlq9BCrAzROfSkX7tan6F7GpmypFj3fBCQFRuUSQLNe5ERbCzCcltEREgQeHBT5em25xoSgzx8ZgSUvF2RVsGv6YMZkeictZE3UiAnjdFVlXLGRKLBgvagm/cLHKCbZjhTRVcLr3WHs420Kirp639HzlWbTtSkHAukNWA5UIU8J4D9lwecewvgujqXi+kAFtQMfSg80+5SHqLwifsYDvx2Xz3bgh3NSnR4rOhDfgisWtbA/01pX9sTFY2NySSYeaLFuROMqlG+agsiAeOdNpZYiFUeWRW8ju+sPBgRFSFcg9/dNGVoTjZIvqd14yJ7UP1exLAyLDc5ee0LevzUvVKpyJquEB3iw5D/FL5k3NLScz1BCMVjX1ZTaoTP/vcdj2vKWjZRUvsTLHX56UYTFt5I/ivmbJx6NK11hICvB9YKQq0nVh2j9i7Sd6l5e+AM4IXiaNbEr9iMMDIWj0qYlp3EVBC2A7qiaK8X3Chj6C7vV0kmAXoEl//x9DbzdLI2nJBLUB+1NZzy4pzleuQK6ShqHXVuS56tvH8aMFZO0jBNkHSoK2QH4+q/WShXUu1Ke7JabjiC5QO2e4aY97leekmlfNNZLYqtvvy9/cSDlQ+ctFZmz1P1dUEHm9POgb2hixgNHzN7WpnKNg4YEsta5OlkOgJ5v0aw642h5tWAN9/E0I2R8arGJZSosFj6M6431ChPTFSL1o49H39kFOuN3gOao0WdffFZ67+AZL2+xvHPPjyv0+voHWwRX8nlXX4eU58IXkNIt1sY/N+WQBywCgAWLgoXpNcm1JbOmqHzBqrBG4hO9luRBQ5E5xiIqauJoklHYWffiPpMyNnxMdNUlMs1qJ6ptYSXSWxojnwZvXqdoMl9X7n6Ef5rgRqPIOi/LjkF0NEFZq9ahfZDOcRHmzC0iubR0VItgt4P5fEteRbe5ApFArwKfpNdqmaKbwvAL+41l7N3/ipFnVYAl0NuRxLYQZcRXhWH7Tj/xt2wudzcPkX/a5ZIPqjTFPN/ZvbapkZUjcMYLUk3/ERBYbM4kSlZ6wTNOahfPeEn756v9VwMzzZJAXTkiFQo0xuMiac280V45ns0r+mQfuywX1rtciol4oJPBb1AUH0mio5s47OJypZHOU3q5UidyHQ6bQfdZXTkd7sVOHcDfPr6uLsbW4O56FZSN61tt2g2DjoNU5Oti2BmVpM08M1tgu5bBZ/xKIfDMeq3uD4hz3y7AgTtB/xf2/MxKQYoivxvndQLCKLRTeBCUQe4F8KokL9p8nkjH5nYymVH9fBDm98iY89emwuylntQg1XocbAAQXnewE7nzkhzzFC9lxYoiF+sUX8rzFoTVZlIe6RL7JYEb4bRu/pzVixEJOuOMcqFS6Jqc2vevreESkGuV6lCLkzyOgU7bjNjLD7EqXu6Jctk0VhP8DRQT3yDjvOzbIKYxvCe1T+st+Y+PfMFcUhJhbdq+2DQ7CnpVCoNIwQYeJCYrHGlbMySVu9ZYzO5t2XECa4ZIFqtSMTWOSTeeN5L1XnwD/ESLIL3rWkkWCajEZdlPS9n2wXgWir2tK3nSwdoh86I3lk07VddT1gRYnvF8sKuqYecxohM1UG0w7KB4DwuFIlVXUSvjsMrtdyU0NXVNDrzMWonzZ0RsgnCHPiSBifcHLiTECWxM8b88VezBAVPM0b+A4tEnect5a3o5DlNZpSryfSc/iPpqWMOd9UCZJ+xz+Vi5m6Rzgz3NCUt9oeWy4kpkD+2kKngUWdITotm/xK/Mzu9oab2Mk88elo7QBF2yHxNSFJ0HDNkfOjZMgnEIzpYwbatsrou2mA64yV0sAhakghq+iZy2TzN0cKA=,iv:8QilpsPt0KbT5CP8JDovw2dhJPIpC/MnUYqdSXzNL5Q=,tag:QAoJvmQk5bTnQ09IoJCBww==,type:str]
    tls.key: ENC[AES256_GCM,data:jGIaLgv3U2+ZSxbc1UTwvVTDOyCDrY6xO9JippyqrVRi/vLxwDwUIxJnq+AE/43xyIQZW74c0eoVFF/nUrd3L4e+hHVqboMoD2Rgkv2moTpAS4doocbSzAtYKoN5aFkYDQR3YmkRpvn2NFmA2CXdEFoLhr2HCUyMMJvDZTttJX4Luxu8OBJSbItN6HaIdN44jpMHwpqO1gwfB96BBxFZGwiHC6wyzovFnkn1iyZJgM/snr52lbZf/MS2DJeI2YlZrLIHNvGRCdsUhzeJIOVf5r5dtMkCkop4L0cLyrhlw5ew1zDagAPXCHWT3NB+yyYUQitxpcthnNQWIdgXVOmZhnnXtZz/Ubi6c2vXm5oulNuyLWl7vXMUDwVM3lhoclwCyQYSwkVDX4f4Z2XWKwMinw==,iv:GUgOs+K9CpyzmbYQpsKSJmwbEBlpTpIeHEqon+iU1Ak=,tag:j+0k1pmkCExmVzpfmsqRIg==,type:str]
kind: Secret
metadata:
    name: ca-key-pair
    namespace: cert-manager
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-06-02T15:45:31Z'
    mac: ENC[AES256_GCM,data:dW3kIDKM19/6EXuQxlLRYWvxLujATYYp0l2BqNXafou6KFlLe7M3ibeAALaPoRuqFMszVs+nsDMZCoX2fACg4WPNkZ+7p9tqMdMZbEVPpwdfi6zQuIKfpzC1TZcXrcdLMU2mQQjqMNXOP4Z8qeAGAS4dcXXLh4Av3jSBrnKWC/Q=,iv:EO2aMPM+XRIPldL6zHMOZVq1U8IJPPuVm2ulvzSQrEA=,tag:rDjqfWW4MRDWOaUNUwLxbA==,type:str]
    pgp:
    -   created_at: '2026-06-02T15:45:30Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAzgT+SigBfsus0g4Rxi7UN2YKN7X5onCsG+VDtThfpG0w
            4VqCOfhMqqEtqmFjf18evKiMqDkikXRfUEnrvo6e4yeOD9X+N6U6t+n//hL+xrBx
            0lwBWL6bwD9rSKk2oF0MV0VGgOXOiS61XwpSJ6LTkH88EaXB0813DyKfDFQb8suK
            j+dcD8cbjVLjhk4gE2iAIrnA5LY8nhsGRZFBj8d8V/dWXwi/glM7XcUXjW6CYA==
            =rVDD
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:49xTgJ6+PU+C4UXFQnnL7f3+i/8vQen+elEqyHnWw9rZRXMOEygC8n2W/Gvz3HqVie7Zo0WVfC8=,iv:CRW9fM8sdUKLUjWHfE8bsqBDHcDVeVjuWhLwDS6QTcE=,tag:yg3W101sZuREigaJeoa/Uw==,type:str]
kind: Secret
metadata:
    name: cloudflare
    namespace: cert-manager
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-06-02T15:45:31Z'
    mac: ENC[AES256_GCM,data:dW3kIDKM19/6EXuQxlLRYWvxLujATYYp0l2BqNXafou6KFlLe7M3ibeAALaPoRuqFMszVs+nsDMZCoX2fACg4WPNkZ+7p9tqMdMZbEVPpwdfi6zQuIKfpzC1TZcXrcdLMU2mQQjqMNXOP4Z8qeAGAS4dcXXLh4Av3jSBrnKWC/Q=,iv:EO2aMPM+XRIPldL6zHMOZVq1U8IJPPuVm2ulvzSQrEA=,tag:rDjqfWW4MRDWOaUNUwLxbA==,type:str]
    pgp:
    -   created_at: '2026-06-02T15:45:30Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAzgT+SigBfsus0g4Rxi7UN2YKN7X5onCsG+VDtThfpG0w
            4VqCOfhMqqEtqmFjf18evKiMqDkikXRfUEnrvo6e4yeOD9X+N6U6t+n//hL+xrBx
            0lwBWL6bwD9rSKk2oF0MV0VGgOXOiS61XwpSJ6LTkH88EaXB0813DyKfDFQb8suK
            j+dcD8cbjVLjhk4gE2iAIrnA5LY8nhsGRZFBj8d8V/dWXwi/glM7XcUXjW6CYA==
            =rVDD
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
