apiVersion: v1
data:
    tls.crt: ENC[AES256_GCM,data:4TBzC8jeASVoMGA+kD/2twYJiwWxyhIM6SZrMpFyW/0SCYA2LZXOYeU7YrzB8BzEeoevDCWOXRxNgcyYZEp3o6f6tDhs4RRq++7o3VIIhjcZ1CpBcCuz8FVOjJgYfaGFfnaMMF9Ywc27et92L/AcQupNUNSOIGz+wYYdTe8iNdXZB9ROEFWU+PRUk7mPjGo9d8iHJn7Q02k8uleJ1orBV+Ugg8ph90F3HOdyAL8nXHuijxpzQbXxjOEDueDLu1LnF23DkmrRbbJHTnp262gK6PX8k8wSgn6vmkNR3lzuV8VdbvT3RC4UAiswTsIvFS1bQ/4JKjqPAce/kTcF38cP+JKJBxho/Q0RnuLwesRCTSG1P5aQ+MLLcr0ZI52i/xeZrLCDYfwzZWT6T/ETljmDJLr+AvFGw7A/mf54S0NKakZKcnXFKBEBXX7hOAMmYCj7n+5XuSI92Oenaiu2GOL9lw+o0A4KM7qH/lBBHhKNv5j1+y6TEbiKfcKJ2XRhVN8MQWhon2BxVFdsQFJYUbXNMjdOZCv0qxzVS8mfwrfL+4jGx5vu2xGa9fBFLawsKCSdTPvBb0rCONOaGvSWIzs3U3oVgP+JxzOXnQsMDMhtb1s9WoMWCaLJYicsEc4EdrgoUsslBNuPyumSMl9CGlW2UajdP2cgAlClKlCwjtXFFLx64CFbS/62/zR7yv4duwdD1cw6h1UxDbmfMjEXPyHQiZScf35mY+gStXyKwG+ITX2xXWo66V8grgMOLBY4wR4eZPmsl2q31NQ7aahZNiqyGzRmkQO27XFM1u/Ll8bR0L3Wq0wkNuZNMKcdBx8fVy8FkKpYpntHrfnfMsIEHr1636olCsflHzZnaMy7W3KhnBWAxqwxgYrpTH1knF/qc5WNujhtOTNbgbJrUxH1eWVpBXhi5r5GcRQLQL2x2Ml/vB3jxbpkwIFqtYR+/C5OHRTdaTUcq3LVMgqsOV+SKnM0ist8CR2ndQRM9JtnLirqxhTBYVzLnfUQ92w0hujf8lQyHt6U5YoSOxVVS+J+PTjyeTArGsf8H/pu7TlvbJYbeffb5X8H8i+f5ISUNXWuqPFtBORtuIaPF36szy1g3kOZQckHSqsha5ajq+JIK31Eaya74P2daIwRcJ2rkPBuheWGJUpfenexLJD9jcxi1bBqtCHOn3prixEPtiAkYpXYZtSONpmXYuzpL97NdHppAK0/b6Y6qurKQPjL/siPc3TMgrdEAXVHV4BiXG6cd4UUOYCQL91GBRYSx5Q6kFifp20hO2pIPwF9HouakIOa/iH4hinG3NKGYOOX8NtLCuCwuZWpQTQgItifUao0Hu7yeyzUG8GemFf0u7Cdd9L48idycXAFSVDuNk4DcEof0wAVex6SFZKjD+ghZhKJkRmD+J6VEZasKAaYWb0/JDiT3Mwly4HeXh2koGtZN46wUFSv05G6418mxjHFeOzAQ3CIo4GVHaZryAseFQQCOxxoHD36zj49w3VVzXi147CLaB6NcVbOiXNErlqWkxvy0ayDsI0tW0Hag69XzcG0NDbz5o0dqi/TDTUYlfEycUEzb8gJXH8/bH1ijeiT+cAwfWnkkhksN9ohWgWE/Dh4sFKAcZzaFXGiJHZ73dCr2OJ1lEZMT5QYMh535VnWSSFDgD2Iv4qJL8qkyWj6iUCjeRP/QW+Od4zBCpEU+Dy3fincw/gy79QnYE3umd1LbVwVLwKUWesuou9wR1/uN2jKVcqNKJyMuhryiE0JdO6oqZFlksP/KQHu+P28ZFoVrV4DBciuNFxLDZFmqRoNzdUh3dU826s4GwIhPa7djuxpa/xSU1CgN97d8WSm84GWBWrDDSHw5JFfZDhE6tT5k9ZrON3ggSJhVuyQ6zgTN+qB5SWi44gliBQmW/TZ5eLB7QfQY23vApGo60oo0i4VxxgAw40FstU1iv5yDHiydiIHrbzuNQgodxpzoVD/Z+aKo9iw90M4JS4/C8Laa+iEgONdibz/xZHlrtfQulyU6u9dpZzl9fyWYEEI7roihJoIcKPCpta77RN9danJ95zRV0RD7frHaTbAEzrnDGOUXb4Jowaq4rXAYGaL7n70s1xggYVaHE7MhAPzEdDfscrOQOdU52QLNmruFVIUi6gxVisSuR3uyKxRu+SlSjJ3gZAk2mAEbK4CufjUo0Wl4RTCKYgdUu+6qB4g6hKAvSUtVdZafzMUmg7blqMswTVaJpLNzUQfm+8b1qPjH30ixw4cYg0fuYPJw8EB2jdvVdhhfj1u1xbVCiuoF+Bb1O6CDeb5xftbXrkW8YPlyJvyKweoyBnlcCfNi6EUChPAR5GC1fpWc05Z7ZmoefcvvZxi2NKjvYgkKbkpsHQgWCYC3vKjdBNW+CVTDuZPlNiZb4sZCWgvHO09Sv4SEXuFIX/rPomUaFfS1RWECKhTjfEwnjPA+SJeSBVnc7THSqd7ag393IU5JwaAeeup7mlqH0IL5lwiQOfU/bSvrJ9up4vrGqCmxu9k61sQegaPXZf5TbTK08TY9h05/NZeYsNqcSHOYnRvYqlQQyn/Wxg4fPa3MxgIgzO02h4s2nnu371METZ2yPb8ADmCTSenaI9xMH16Sh91a9ULdpp50z57JunoR+JzIkC7vo/xTBQfvn7lMfU1bw/6pGMiK+jIJ2EqrRd2QLrCZx5pQ40XVcyUUBPzdBfNCw4lNs4NC+h+JOuhvPvnrr7XOwYAe1XUiHA+rpxvsNV7UbHOmJmw3lTYm3OsLy9DLbS2BiOKIP5yjWzISYPAaiNsAHSb/gLU3YP/4DHUKjT3EBmz2lmLTNipZnyr399XnEifjDQ9EVNC6csP+BQQBDer8ak1SEIH0nl102f4KEj7EWtCneksSV9ci+IkuJvpKrfS/BVtUuRNUlY0PkDw3cveY0Xvt/xWHYF6QfMP7ZChqQn9XrcOtjIptZ9Bu2WM2PtJzfaE+r1SZ2RPKvvvSqY976oH0RTPKFBRHAuRV+/Y/IvCOL4Ln/l2CBEwb5lZ0UuzZqoonQO9YRhdTGrs+ntFOF6S8NOQX7FLORGBC4yhNE3APBcO2xx7TcXT1GgaU/XpWeYud0SezW1h1QnpqPOyUEHluFv7xsrGz1WWvJSP8OTs9a4p+391/mGx1SAbS9Et2zIVKZFif43REYDS4uTq2gthRFXtv4veHXI5OgHxiGdSF44Odd+FiQhNXvgg+MVKWOS0JprDV7TZv1qmR4NWAqriA4K+OoXwcfUGRU6s89I9tV2hVyfr1kK9w46rMaZheF8uSEFJd7BjJ2ss2fUUUhVfFvm1e+4=,iv:x+1vR25LA2NfiyqIaT4SUfNDKxZFHNh/6uXqfoQH18I=,tag:0FmovmrvCdFPbRlnSaUY3w==,type:str]
    tls.key: ENC[AES256_GCM,data:2knMdBXNXGgf6mQaqIDfaYdtJJ+Nksq32+hUZ3OWllm3iLT948lPI5aNl/XfY7+OAke0G2orIymD0Zz8zH4HwdBtNqzB7MUHaWLDU6RWSjiUL3i9DQ9BUFx04zfdlrrjlCzbZGTOZ2H0kfNEoaP4BAEQyvS2h1b7UKzMOb5wOtFy/o+raEUR2DByBnPdTbF6Z+6ZqFI2nKGzx+2wAajQGB+rKzGv6AVnctH2uwFrb2IUCWakspqrT4yBjv9yjUqAjcsC4eYq2roNxeeDyO+9xqaXVM1wRvrV22gsCc1YocvzsaXCyl5bRefDS7Naj7J4f7irjLzdjlslYyQ6x97ViTXiyh5KfOPfcS8m3O4NyClvMA1GYjD18myEFOvHOYU/bkWqXv5VVrAjsmRpjvajfIU7/NHDCalJQHsH8zJihDeE1CPDBPUR9fqvGFEw4GcuTL1Jeui/WxSbBKV0aNRmfhXaItSewa/9ld19qFbxUfsfRiUdllMr751JGMf8JmtWaQLCAHtALTy9xYIAU1EtXGToU7g=,iv:jTHYxjVWL7sEUC2KXeZQrbqJsRwAk9BUA8PtPP5eD/s=,tag:p5iVy8Cq58nnFxU/YWk4uQ==,type:str]
kind: Secret
metadata:
    name: ca-key-pair
    namespace: cert-manager
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-06-01T21:13:09Z'
    mac: ENC[AES256_GCM,data:4CmIsisyif1K6F7QfqtGT/v4sqN0AUz7UsGx8Za1YAQz6JwfoL0G/FXOxG8fDDLINuh09bNw0Z5JZpJpAP50BJLFYvcyY5UcgGV4uunCv+mQhbXufnH0n8JmDcLiRVuiPOjcUyr5/7hZo12IETZUFA6DwXavJcm0o5oEHoLmFhk=,iv:ZYkLZeJJOn6HmSlywdltHuLdeWIAeFLSI11zv9hqBoA=,tag:JCUqgKrCRr7DYumAjMJzlA==,type:str]
    pgp:
    -   created_at: '2026-06-01T21:13:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAgB0gTNSg/hFlumljHcnwBqXg8bJA17WHXXjS00s8uxow
            4vONpqTpq67Ft4J99iPPTi9qxQjXMLcl8IV4zo+EP1V9XkeC2FmKVkupHFEBfZTS
            0l4BP3+/FRlZt+xlfxU+fc9ktgFMzRD9vQ1TkItjdjGcPfHpNB+51Pdp88SK3oI7
            vhK9U2UCFMzaYa/nzS6MinVyTHXqGYCafEvRMHq7DO56kzRXERNplp7DnYIgI4J5
            =XT2k
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:or0ZAkAkAhb3xtMT6XoXm2Gt033uzyiBga0I3iuVmIaX0JZCJuuhhqUMSPGwBTbWfLROpBdKAVc=,iv:nXS/pT47GqPsMb23qdhrFSf+erKNj6YvfsWpkvgvol0=,tag:5Xy7Vi8wY/iaKfVoc5tyZA==,type:str]
kind: Secret
metadata:
    name: cloudflare
    namespace: cert-manager
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-06-01T21:13:09Z'
    mac: ENC[AES256_GCM,data:4CmIsisyif1K6F7QfqtGT/v4sqN0AUz7UsGx8Za1YAQz6JwfoL0G/FXOxG8fDDLINuh09bNw0Z5JZpJpAP50BJLFYvcyY5UcgGV4uunCv+mQhbXufnH0n8JmDcLiRVuiPOjcUyr5/7hZo12IETZUFA6DwXavJcm0o5oEHoLmFhk=,iv:ZYkLZeJJOn6HmSlywdltHuLdeWIAeFLSI11zv9hqBoA=,tag:JCUqgKrCRr7DYumAjMJzlA==,type:str]
    pgp:
    -   created_at: '2026-06-01T21:13:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAgB0gTNSg/hFlumljHcnwBqXg8bJA17WHXXjS00s8uxow
            4vONpqTpq67Ft4J99iPPTi9qxQjXMLcl8IV4zo+EP1V9XkeC2FmKVkupHFEBfZTS
            0l4BP3+/FRlZt+xlfxU+fc9ktgFMzRD9vQ1TkItjdjGcPfHpNB+51Pdp88SK3oI7
            vhK9U2UCFMzaYa/nzS6MinVyTHXqGYCafEvRMHq7DO56kzRXERNplp7DnYIgI4J5
            =XT2k
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
