apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: maddy
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  # - cronjob.yaml
  - certificate.yaml
  - http-route.yaml
  - rbac.yaml
  - secret.yaml
  # - tekton.yaml
configMapGenerator:
- name: config
  files:
  - ./config/maddy.conf
  - ./config/aliases
  - ./config/ban-list
  - ./config/quarantine-list
  - ./config/spam-domain-list
  - ./config/Caddyfile
- name: scripts
  files:
  - ./config/alias-filter.sh
  - ./config/mailbox.sh
  - ./config/backup.sh
generatorOptions:
  disableNameSuffixHash: true
