---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
  labels:
    app.kubernetes.io/instance: maddy
    app.kubernetes.io/name: maddy
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
