apiVersion: v1
data:
    db-password: ENC[AES256_GCM,data:HbnbHRBhQqk=,iv:FcwhokxH+5Ko3qfQ6i0GU9l+AuvPcSoo2eZ9nhhFOxA=,tag:uCGwuI8ryOlHZS8shHWiKQ==,type:str]
    db-user: ENC[AES256_GCM,data:SP9z13RJCDg=,iv:+HT9JL8hHtUXT/DqIvsoTXQBVSIG9sns6enpWFkq/Xw=,tag:o5Nwa+g6MzIIeTrZx3nItA==,type:str]
    relay-password: ENC[AES256_GCM,data:icqT6ZiDfShqMDoCEPIOnzNsZ2wcCv+1,iv:WLqLc5/eukfCwGKf2UGLP9/hAXa32XpgwSYbLXbBEGM=,tag:0p0c6VpGuZ35tI5eWD9VpA==,type:str]
    relay-username: ENC[AES256_GCM,data:tfwGSlLstaZd0LNxLpCTLiC7dm0O/qnoLIUNmuVew1M=,iv:WdYUGmIGab5yfFlPwhOg9O+vZdlCA3ZRznd5cLV8fVg=,tag:IdGluAc2PGzOKexdgXhdXA==,type:str]
    mattermost-channel: ENC[AES256_GCM,data:GZbIfraIUG7bMHq/dx0ITL8V+sXmKYD6e5egfCqHA3Y8Jpit,iv:R/0zLcB9E1atVcrckw+d8fKkWgJQ4m1wHxlBKtAHvVE=,tag:hSLXMGNp9laI58boKw9wGQ==,type:str]
    mattermost-token: ENC[AES256_GCM,data:yEn2sJM24PK0aBEa2jIZCmUs3/ijXagfadLG5rjcep+8pyU9,iv:p+Lg2bYZC8poYzNrx1fFopvDf00PbixkPjoq5HE0V/s=,tag:hYrEPaDCmoyuohd7/hdd/g==,type:str]
kind: Secret
metadata:
    name: maddy
    namespace: maddy
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-06T14:40:02Z'
    mac: ENC[AES256_GCM,data:z6WKWRNfUZAVK1OoMmRuS5uJh2wF/XGAS0FWrEJ4eOqzqlr5tmhsM313BCJYqtlGj9fQeJZ4Mk0e0ldxZ4D7jjp10rv6z4N1YG4QczVBPl0Tmj5BE7726BzvY0BJ+oW8nMjpY/L1c5/Naz2EUK0m1RENvp6i8zIir9+T+6EsZJM=,iv:KMdpBTLscWJDSwkq+wdfCu7RU2IrXOMoUNIrUNY4Jnk=,tag:vasB/mO8XP1GvYC9zowAzQ==,type:str]
    pgp:
    -   created_at: '2026-09-06T14:40:01Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA6fmG4jQoXALt8ZHy1YFfnN1WRtax/wDlIDYtTkZAf2ow
            jeY7m0ZS739kii1wQz7Ks6Hps3ENAikTCy+UP2l/j0zFBl2lMJkXhDKA2CKsRTf/
            0l4BcIRi1wB6wlvn+YMnJ5K9kJ+LLDt0vvlaiKEp5+13lXIgT9g3xmHUgAKh0dld
            eVX6nudpLyTYzjrTwSSqAdEv9l614Pu3k/KJLxi6NFJTi61xJ5gtl6hW2mfN68/v
            =5fe2
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    dkim_maddy.key: ENC[AES256_GCM,data:CC6MaiUybiuzBhqjKQLrFyltAmgQyREh9iYipgbgxDova5V7kO3OWbpVWRdw80TQJhCN7Rbx/HCg5wLfiofFfqo0le6BbNTNXrIA7e+E0NrvezYoffv0/cUqrEY0GCWpEgIQVIT50Gvk5OXCXKuLMQ54XekjnNf4mgwCmj9WLvKzA+mqhW21i35p3LxNxd3cV+pEPs7g+NagYjd9tRUPHZsZai+eZcuOHAJ8Y5BZeW0R2ibyTlrNzUCRvk+w5e4Hr/mUj1Xwbrdu/l5ikYYcNRMwjE9Vgkq8cCDrBVRFW5VFSKyGgsQHERTF6jkINfBJn2gVu3YxriVllAJhSRlY6tJev2Lc+ZhzPSrQmQQekkeiemKpHhhlNrdMDulkApqSas6LM0TYqrh1GbgxnAEbcz8iC2q+T9aEfPMvfYs3pcHXhHwLBGpqbA4W+MD2UQKPP+p1XqKLJza9gak2tJzGl0nzpSC7zagfRi9PHe4HbUWh5qtzx77rMknOVVwPZpQWUGVDLlIO35NgiLOg5a9JWuidSxqbe0Y7o26NZE0yaw+X224Iv5rJYjfEZaGHOqq9UfJV36LqYx4TtLzuMwdEu2z46bXqVO6yl73gxtFrdixQML3yac9sKaQAWZYusouxX13FFuIIUMOQzo2qoS7WDtKFfDLn8yBBxBUR21H7mIvByAkM92sy3ll8ztH6E4cx8z/OSkgfw6RzfmFzadzO/Wqbgl7HRRealgaeHWsNy4Q1xY4PCVsFTiFlwIRDiE6WL2tVx9ymoIQRvGvJ1RZojGe4JI2X6AlOauH4Bc9vWjC9BG1682R08D3XVaN+O+bivrUDQflbETVHcdnRiKHr/F3hpfozyEYSt1j6cu8zJMtWjJLzHhikv6DA+yJXo1t/lEfnQoMHXQA/2JQVY1lBdw5g/oU/OO61wL+Lt9DuRE2LYXwzydzADPLZGcRFzHkb+t2HxE3pvRIzPvIoY0hl22mmQ3/8bqWnkuz7DQDP+8lE0NgLIJ4xiJr+DJXX8IVKc4JqU2eUg9QOWgSlKJMwgyY7r+zNT+3DjAoxHVQK8XiPuF4meTeoVjehz7CZVCeY0Q3KCA9FzhCYNkciJJ7omwAssTV71P1AFCQeJHkydiJJhnHceU+AulBHiFNdGamIZ14hU7uklX49asvfoOK5CD8i2rBY9uRLCjWMtXDaaTEDIKGOwDMYM3o1W6he0uAGuedZJ4ZCOUXndjwsGrLnTt+d03Hoq9B3jofPaOQCUiSXU072gdUrkExl74LGflXa1hypZ6XHGCKxZHJGsfbnm/gQH+TklgN9KOYrPIwYMNQWsp1q9AjEIVLClLdJWbIOmaQawjoaHiIuoLNG27Pniwbu+G41R0jGJjftENaLNG2exgHZGyqA9QBt6bFKFiShiyYcV6iD69R7YLVjFSeOxZ1fQ7MOlVrWVMLb0Z6cNjpShbJQPc0LLyCWqVjk6GIf3VOV2Oi7ru4wH4MwjCULpFzN4Z73DEUBmWHHX6P+tUNSh1ZnoqOq6Mf+g2b2cpI2YmTbjB7YSw9LqE+b9liyubDOqr2C05xepQqqFCc4wMPN2JihhKC8H895sQ6A0BzEIPLyIQU4UuJ1k7HTphaB9whBVRlaw4YuASXBggduu6xaCzkRr+MjiSrPr8w1CSVZ1IGhC9WZDjc11wkaN+UUuEyg/4b62Mg7Wvr+cvnPJ3W6Yhv/kIml+4NsRIV+md6+q3+n0xFOUVwHOftlXJDKB0UU6Y2mxW/EO/tMJfJtNNxuWe7k1kzdYW2VYwniEBpbel8TpO87LJ6rjFs6yQSxdJqTsjzWKPzMRqad2Q2UydtKsdLNRAy0gDOp26FdYmZiCMjGlNuwm1RcNb2Sxnk/fnnnZqMVrP4DqbSe/OQd2tjLybacKs/HcD6wtvuhXxekCFqEm1m3+36+sXu9YDFJ4keNhb6LA5AsYNWH1L/+n8OXuTHmH+9GxASZWrsVTt43/a9t9HLzbVxYno6bQp1K66Maity1p9+1w3FFd1QXm4jeb7kQa6Wcauq+buFZSOw6iUfNVayFeWgCcqHHQJNKHjY5XWcbft/IdL+ao/FwDWgWOaqvsrY4+6IP9r1fFrYW3op/VG4dwgT754SmXfKlYrGQyih+CoNPBcDli7Xv1CADQtftAx2MtAfH6S35Eo6/veWH1dk/CjT7tfPEAgCw5lOEpgeNfufsvqwLYhipFUyH7CRuJ6ylAlr2crNI9e0ViMNgt8miVlSaFpE36tWwm6LRv5wDqEJJFxNp10Zusra/A0ojTlIFTpHlVcigmG1bvOLeQ4n7c7f8a9SDrP/VbtSM1SVlPskoDTzRFEPoalWcuHV+YVvqngpP6IbXB5zGCuN4gSriuUXJlH7wI72UuLS+dKQRY3RnMYz0ka3HEm11w1IlemyCuwBA4rTB7YOvhbtzFZIeHwfGJdXJxX7Wfzz59C7RGKuQ+O1xj5irV+gl3cRCJ85QtnLUv4uSkClkBlEzIKb57nyGdvbyip2vjX1ajqS5h0/lUC0PYeD9XrDNRPrvlAJhhKJlSfNpIDmKHBH9ZnlKYUWM33wO6tN3c6Q3VEh5ZKJe5mCz3/i3TtH0jzAhn3nI1XVAyJ5CkzJYNQ9XczqKPGsgn7pA0fI8E18TMli9i19wm8+DfITLNQyXfRQn1VIAOwCMmOQ2C7qYt3V6TsQcUL8V2x/KNlDXqz6aM8hxSzb3evtk3e9iCE09Ozb3cNkZzJ4w0ZSEMNedb9xQkeSAWR5aXNT+TnHB0qP/ytQoAjrxkFTxEuZmAeh+ey8XZBtH4dwpFqrxQZ2KAcVsG8pETPxB+IfMYO0pEIhyT+LNHRvH2AxWFjZbWyBcc/5f93XZFijbFGAipiYqaO9KfVO9LztbNN1wcyYCpLdqtOEf5QLw0ZAegy35UqZ1dgHXqANofPh06fWHXJrWjEUYBu2cDBRTxRvBVHSsNq2Cnh9sLIvQ4V44cQ==,iv:K3CsMWmjvGfPwrj1pvz7h8ZRh24E0zdo8aOaIq1qy8U=,tag:C86Kp8XYf0o8qeKFkxsE2A==,type:str]
    dkim_maddy.pem: ENC[AES256_GCM,data:QoIruuA4J3A9v2T/+WhvCJFUXJwbBwitHTTk1JpVLfL0rE5I+4rQVWEHtLaZAxLeEIGpU36l7osXrUA/0b+xHkYQRfZXoM7b4whHsujDfFgXdJEo8RyNJDq3AkIYU/7xpQAgZU8VcClpnAZtX9yfGqP7c/EKXSDgtvR8pjKaem3ZhjdvQmw6HCZo/LNX7eWSjMbvlw5L3V5sofOfMIb3JTLMobJwdYmmCizq5ZkZCzV6oAWdm+FnIhuXFdpYZfMSMjsbMdfgVKJSlAYMBWdehQ8kxfHlXewHngasLUvTkVgSri4jKBIIJc8nd5i3Om26VegGL30Rh7aWCUL35NFRidePSt7JBeACB6JHKv6TE8IVPTwZVW7AxtaPhryoJOiVMITqYWkKeXjPTCrMietHhT1sJ0vdA0Rv35QB17J15ROAcm2iXbNn1PDVqWq2YDOogfZzAdkaN4IxkmhKIDv5vH9MblyxiVLP98D1W1S8V0sGqVjea+gwfnsKaOD59bDGqNfoKv0AKr0kjCxb26W3e4rdX4C7vhbzfhO/IM+3KEKt/LF0VlbwIOcagmqQvStnThgJq7aQkLkqBpKfKn0Itc/oTlwr1+Cga01gf3himIML12GNG7xHG1PBDMC5+vLnnsO7hsroozu1DN90bNd5PLcK8kDObj1dYsEZQ9/kqNzsLifxVsu6C6fJY7QnUOGq429hu4V6SwrCAobZoFNnT/vUdEWo684kL/8So17SsgsHB677o/uAOJuJm0KYTmAfyGZe0pXPdK5Fbh2niBgJz4NhB2tcDR89gAnZ8g==,iv:FQeqwJ7z5qcLMXfz3EVAHsDMMmL1kC6QJmOWZJvy7T0=,tag:8N6KfBWWLhl9kigu2nAI2w==,type:str]
kind: Secret
metadata:
    name: dkim
    namespace: maddy
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-06T14:40:02Z'
    mac: ENC[AES256_GCM,data:z6WKWRNfUZAVK1OoMmRuS5uJh2wF/XGAS0FWrEJ4eOqzqlr5tmhsM313BCJYqtlGj9fQeJZ4Mk0e0ldxZ4D7jjp10rv6z4N1YG4QczVBPl0Tmj5BE7726BzvY0BJ+oW8nMjpY/L1c5/Naz2EUK0m1RENvp6i8zIir9+T+6EsZJM=,iv:KMdpBTLscWJDSwkq+wdfCu7RU2IrXOMoUNIrUNY4Jnk=,tag:vasB/mO8XP1GvYC9zowAzQ==,type:str]
    pgp:
    -   created_at: '2026-09-06T14:40:01Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA6fmG4jQoXALt8ZHy1YFfnN1WRtax/wDlIDYtTkZAf2ow
            jeY7m0ZS739kii1wQz7Ks6Hps3ENAikTCy+UP2l/j0zFBl2lMJkXhDKA2CKsRTf/
            0l4BcIRi1wB6wlvn+YMnJ5K9kJ+LLDt0vvlaiKEp5+13lXIgT9g3xmHUgAKh0dld
            eVX6nudpLyTYzjrTwSSqAdEv9l614Pu3k/KJLxi6NFJTi61xJ5gtl6hW2mfN68/v
            =5fe2
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    catchall-password: ENC[AES256_GCM,data:CjuvSdTWR6OesIK6,iv:LjjsnGtOSBhJwEEIOjy62nuyELZyGdi5lqjf7LyMX/Q=,tag:w+GIVYPeEfiA25MJLm+lfg==,type:str]
    postmaster-password: ENC[AES256_GCM,data:En83UE9x9BN0uI5s,iv:PkinQcvE9/Yz9zmI3RLCp2V+QCT0Y1HNzwV3wQfgwo0=,tag:FCuqaqrxHKdqquF2HfHnRQ==,type:str]
kind: Secret
metadata:
    name: go-imap-backup
    namespace: maddy
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-06T14:40:02Z'
    mac: ENC[AES256_GCM,data:z6WKWRNfUZAVK1OoMmRuS5uJh2wF/XGAS0FWrEJ4eOqzqlr5tmhsM313BCJYqtlGj9fQeJZ4Mk0e0ldxZ4D7jjp10rv6z4N1YG4QczVBPl0Tmj5BE7726BzvY0BJ+oW8nMjpY/L1c5/Naz2EUK0m1RENvp6i8zIir9+T+6EsZJM=,iv:KMdpBTLscWJDSwkq+wdfCu7RU2IrXOMoUNIrUNY4Jnk=,tag:vasB/mO8XP1GvYC9zowAzQ==,type:str]
    pgp:
    -   created_at: '2026-09-06T14:40:01Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA6fmG4jQoXALt8ZHy1YFfnN1WRtax/wDlIDYtTkZAf2ow
            jeY7m0ZS739kii1wQz7Ks6Hps3ENAikTCy+UP2l/j0zFBl2lMJkXhDKA2CKsRTf/
            0l4BcIRi1wB6wlvn+YMnJ5K9kJ+LLDt0vvlaiKEp5+13lXIgT9g3xmHUgAKh0dld
            eVX6nudpLyTYzjrTwSSqAdEv9l614Pu3k/KJLxi6NFJTi61xJ5gtl6hW2mfN68/v
            =5fe2
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
