---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: headlamp
spec:
  interval: ${interval}
  url: https://kubernetes-sigs.github.io/headlamp/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
spec:
  interval: ${interval}
  chart:
    spec:
      chart: headlamp
      version: 0.43.0
      sourceRef:
        kind: HelmRepository
        name: headlamp
      interval: ${interval}
  values:
    config:
      clusterInventory:
        enabled: true
        accessProvidersConfig:
          providers:
            - name: secretreader
              execConfig:
                apiVersion: client.authentication.k8s.io/v1
                command: /access-plugins/secretreader/secretreader-plugin
                provideClusterInfo: true
        plugins:
          - name: secretreader
            image: registry.k8s.io/cluster-inventory-api/secretreader:v0.1.3
            mountPath: /access-plugins/secretreader
      watchPlugins: true
    pluginsManager:
      enabled: false
      configContent: |
        plugins:
          - name: flux
            source: https://artifacthub.io/packages/headlamp/my-repo/my_plugin
            version: 0.6.0
          - name: flux
            source: https://artifacthub.io/packages/headlamp/my-repo/my_plugin
            version: 0.2.0
        installOptions:
          parallel: true
          maxConcurrent: 2
      baseImage: node:lts-alpine
      version: latest
    httpRoute:
      enabled: true
      parentRefs:
        - name: cilium
          namespace: cilium
      hostnames:
        - headlamp.${domain}
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - name: headlamp
              port: 80
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      capabilities:
        drop:
          - ALL
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 64Mi
    tolerations:
      - key: "node.kubernetes.io/nuc"
        operator: "Exists"
        effect: "NoSchedule"
