apiVersion: v1
stringData:
    HEADLAMP_CONFIG_OIDC_CLIENT_ID: ENC[AES256_GCM,data:vz2PMbVx5g8dIehr0JDS+GoUQgrFIDm9+7CReMAjRUjysCTM,iv:KYlLgYJFgKMLcWMKktJO67/Hv7EQR7f8vhL93s3Lxjc=,tag:OU8EFP4UEbVf6GK57y/dnQ==,type:str]
    HEADLAMP_CONFIG_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:ZhBFhauqjp5iBOEm3loj1O5ygniuEgl7ZHvb8wR/nR8=,iv:IaP2WGjoCnN5oj2s1Tl0eSKtrEoq3PtJ/L3jKYUKvBg=,tag:Lfm1I0AwbB912iXhZ+26Gw==,type:str]
    HEADLAMP_CONFIG_OIDC_IDP_ISSUER_URL: ENC[AES256_GCM,data:5O7OH0+XXjjb5pg3uSKN+gYQqbixuN3I9qZ9,iv:3foACzdx1fLs5jhQ2pjIBfrGRsFYkQn4nRseLnGxRXI=,tag:zM7xCPeMtRl/46IKIA4BeA==,type:str]
    HEADLAMP_CONFIG_OIDC_SCOPES: ENC[AES256_GCM,data:YT+AJDInUjyTvUJPJT1/vpEf4zALtjdeuCTr,iv:v1UrNzj91Nldwdq+WpA/7Xiqk6nou+b2/IVlUbUHS9Q=,tag:Jr7Mygt4z+HTLcFLIsnz0g==,type:str]
kind: Secret
metadata:
    name: oidc
    namespace: headlamp
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-10-01T14:30:11Z'
    mac: ENC[AES256_GCM,data:kxIa/0VtKwP0iDm26+lYuQ3jrWNoQ86shZGo6gZf3m9Jiirp8YhD5aHCdV3bsUVC/ieKI9VdhOReSxYWQBF7067dFvS9zo2H+IXOwmhZPiaVWSX3p3iY3bcmdtEbVwwmrZql8cG5Qk4neX11JfNOeNcc4TJdJXvKb1HTlFTsNXI=,iv:zSnlJsnRULk6IPBLPWO+2RdGpwYY58IZXDY+D6tbP6w=,tag:m2bRkgANqtum1mlltlsrlg==,type:str]
    pgp:
    -   created_at: '2026-10-01T14:30:10Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAWsS+LxAwvUTTTycF7bIMawwRlmdAAcDQO7ZE00AUMBsw
            JO6Bcz1rUkL8YzEm3OFU7JQh7nb+maHRxNewN5O0OVoSjXWM78ZuDm6YX7DmD1uH
            0l4BzgeRg2gBkN9/crVpNmsj+ecL5ATZ9haFwG4f3xjVYIUp9IzJQZFEgluUDwuM
            zTT52uq8SDXFMshnpF9kfSCXCg+0n3x9GJxhlIAuqwNK2n/9eLU2c8E06MPBKqv1
            =DiCv
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
