apiVersion: v1
data:
    postgres-url: ENC[AES256_GCM,data:+GMGQaLYSqtxji3Mk8GQH2lN7ThxORyEW8CurlYXKgEmXDRFu9cr5tYO7yOm/X7gKw38dU7pRhf3wBTVqp5JdvcWcDcjBwlxYVKsKkca+RE9ZC16aA35znEzMdDkrVBRMMXmljj9YnYi9+gnA9Wktitnq4O1dOgUa0XswFi31IkdLEkGXQQMPXpv1lMyNIZtwg4/n/yz+mkERW4H,iv:6pHkBlIJ6pDWSFCZAtfZm2bCwNq3WLK+f7nDVywyW7I=,tag:tqQ8Hj4DyuP7sMd8C72Ikw==,type:str]
    access_key: ENC[AES256_GCM,data:hH4gm4DFAQ1eb7+xJxeO3AhicOH1WPL4F/LDNQ==,iv:EzDf2SwY8MsbQ3ua66h9oMT/VD+RISbZ/7FlNoHs5Ls=,tag:nIvY1Vnk4eocoXe/JvDGfw==,type:str]
    secret_key: ENC[AES256_GCM,data:qFgwqHUk1IuEltPEuN1OQYAkMvRiXB1wrlyx+g==,iv:173yl4Qw6WvhbifFhewBwpubaEyfmH3VKD411HGkrBY=,tag:lO0sLlPK+CEs0CXnG/Qa9w==,type:str]
kind: Secret
metadata:
    name: credentials
    namespace: instancez
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-08-30T19:36:26Z'
    mac: ENC[AES256_GCM,data:6Fi/JmxDm25cfL2DaJxSA9Hax/fwIUSeO2xJFEzVLdQE/1i0wM/Y/3hCVZtD0sFiyeEd+QJlAKCRwtX0r/PHLwrLkUh2AxzNx7+lB+/0fJdUxeoTIYjKtKuIhv5pZ1DWYbsKCdO8ZC+kzg+yaUfnHrjYSweIXATwJh43kKpf/EM=,iv:cfhtzRhG8d5aQ3CoUHU2X4csUY5vOu1sYFYp14y9574=,tag:pxN9kiKns0FqaauVpjE11Q==,type:str]
    pgp:
    -   created_at: '2026-08-30T19:36:25Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdASOGyhe9qqNEBU1MGw9Fh8ISXpbwWmIMxcuWHllDVWTgw
            /prcKPKbgld5cMA4zcB7BVBuOYeaO6DK6vofotTPsC3wApc/zFp4SMmn2010CElM
            0lwBwahJA7sOEhrO9A9iPCukmAstyUcg/3nTlBJJTlY8ZTGZ+ORcP5nIBjw4er7D
            GFn+1/TwgEXuFeX0PX3IqZKTNl455o9VA/qeT8VdwiEeyYykfr7gAwKdaRb8iw==
            =jQiH
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
