---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sidekick:api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sidekick:api
subjects:
  - kind: ServiceAccount
    namespace: sidekick
    name: api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sidekick:api
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
