apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shell2http
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - rbac.yaml
  - cronjob.yaml
configMapGenerator:
- name: scripts
  files:
  - ./config/restart-vpn-egress-gateway.sh
  - ./config/get-trackers.sh
  - ./config/add-trackers.sh
  - ./config/get-vpn-egress-gateway-average-download-rate.sh
  - ./config/monitor-vpn-egress-gateway-bandwidth.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
