---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
spec:
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
        nfs-genji: "true"
        nfs-hanzo: "true"
        policy.gatekeeper.sh/ignore-psp-readonlyrootfilesystem: "true"
        policy.gatekeeper.sh/ignore-psp-capabilities-baseline: "true"
        policy.gatekeeper.sh/ignore-psp-pods-allowed-user-ranges: "true"
        policy.gatekeeper.sh/ignore-psp-readonlyrootfilesystem: "true"
    spec:
      automountServiceAccountToken: false
      securityContext:
        # runAsNonRoot: true
        # runAsUser: 1000
        # runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
        supplementalGroups:
        - 101
      containers:
        - name: samba
          image: jamp/samba:2.2.0
          securityContext:
            allowPrivilegeEscalation: false
            # readOnlyRootFilesystem: true
            # runAsNonRoot: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
                - SETUID
                - SETGID
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - SYS_CHROOT
                - NET_RAW
          env:
            - name: USERS
              value: "dummy:dummy"
            - name: ENABLE_PUBLIC
              value: "true"
            - name: ENABLE_TIMEMACHINE
              value: "false"
            - name: WORKGROUP
              value: "homelab"
            - name: NETBIOS_NAME
              value: "samba.home.arpa"
            - name: "TZ"
              value: "UTC"
          ports:
            - name: netbios
              containerPort: 139
              protocol: TCP
            - name: smb
              containerPort: 445
              protocol: TCP
          volumeMounts:
            - name: nfs-genji
              mountPath: /public/nfs/genji
            - name: nfs-hanzo
              mountPath: /public/nfs/hanzo
            - name: temp
              mountPath: /etc/samba
            - name: data
              mountPath: /homes
            - name: logs
              mountPath: /var/log/samba
          startupProbe:
            tcpSocket:
              port: netbios
          livenessProbe:
            tcpSocket:
              port: netbios
          readinessProbe:
            tcpSocket:
              port: netbios
          resources:
            limits:
              cpu: 100m
              memory: 1024M
            requests:
              cpu: 10m
              memory: 64M
      volumes:
        - name: nfs-genji
          nfs:
            path: /
            server: genji.home.arpa
        - name: nfs-hanzo
          nfs:
            path: /
            server: hanzo.home.arpa
        - name: data
          emptyDir: {}
        - name: temp
          emptyDir: {}
        - name: logs
          emptyDir: {}
