---
apiVersion: gateway.networking.k8s.io/v1
kind: TCPRoute
metadata:
  name: netbios
  annotations:
    external-dns.kubernetes.io/hostname: samba.${domain}
spec:
  parentRefs:
    - name: cilium
      namespace: cilium
      sectionName: netbios
  rules:
    - backendRefs:
        - name: samba
          port: 139
---
apiVersion: gateway.networking.k8s.io/v1
kind: TCPRoute
metadata:
  name: smb
spec:
  parentRefs:
    - name: cilium
      namespace: cilium
      sectionName: smb
  rules:
    - backendRefs:
        - name: samba
          port: 445
