---
apiVersion: v1
kind: Service
metadata:
  name: samba
spec:
  type: ClusterIP
  ports:
  - port: 139
    targetPort: netbios
    protocol: TCP
    name: netbios
  - port: 445
    targetPort: smb
    protocol: TCP
    name: smb
  selector:
    app: samba
