apiVersion: v1
data:
    token: ENC[AES256_GCM,data:BAdgPYxDd89y8qDW6mW2E4h9I0fRQtbiXSVVZfaLC2WLCfkuJqThoKUAVoq2hIG9VLCf9PphAxtDpz8ez1WFYww1xm0AAQnFNE+98/sYkxB/jIQ+WAkzUEIgNzTR+cCwRJEzJXvKCoPvUArETJUWpiF98A5i8XqbBDpEzQ==,iv:Nd1seliLXQrMDgYtcn0m2u3Xw7OxJpqIzBsXr+GsuSc=,tag:Nf274ctlwPtnEVdWjTtDnw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: github
    namespace: konflate
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-06-15T21:37:20Z'
    mac: ENC[AES256_GCM,data:zHf0ABHfTi7114smUAcAqUBTNDwx96HZNYfSv7v77zsgb5rkSHs3sfiZTg9WG1ymquHLhYZSZeaVfjLgO/S/alYMRLiLVc7C5rYyhu357nm+1p3Lxp2Wf3Gt74948KADfYXB/HZzJugg+iWz/7qPDJ8LR0p78HTavGna3B2blJ0=,iv:UV2kKJZ3WpIV3nWvWo7hhvwYi+Vkhm072qsjcoaAFP4=,tag:vqQaBY0Ar628Q2L0xKMvig==,type:str]
    pgp:
    -   created_at: '2026-06-15T21:37:19Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAISKiQswET+yqDlgurpmKbEe3ZK/lucgo4vlzqSbtyQow
            TANO9rylWo5GTOlUQL9oOpk2f0VzufSzgd1tf9XHLrtChuCE+C9YXBHOx8pnNX4F
            0l4BHIw9vrfijtwmQq8pL39QqKm3m9WLexwWZaQRbuCLVSr2FpgF96HXdOzkgnz2
            MpLZEQVzl5+Y3pAqOa/TlM8ffX/EESPb78Gtmy5ej55NXwWQDwc7BFYMd7H2IzGu
            =wsMk
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
