apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pod-gateway
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - mutatingwebhook.yaml
  - certificate.yaml
  - issuer.yaml
  - cilium-network-policy.yaml
  # - networkpolicy.yaml
configMapGenerator:
- name: pod-gateway
  files:
  - ./config/settings.sh
  - ./config/nat.conf
  - ./config/gateway_sidecar.sh
- name: openvpn-client
  files:
  - ./config/entry.sh
  - ./config/get_ovpn_profile.sh
# - name: vector
#   files:
#   - ./config/vector.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
