apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: deluge
resources:
  - namespace.yaml
  - deployment.yaml
  - pvc.yaml
  - service.yaml
  - http-route.yaml
  - networkpolicy.yaml
  - secret.yaml
configMapGenerator:
- name: pod-gateway
  files:
  - ./pod-gateway/settings.sh
- name: settings
  files:
  - ./settings/autoadd.conf
  - ./settings/core.conf
  - ./settings/hostlist.conf
  - ./settings/web.conf
generatorOptions:
  disableNameSuffixHash: true
