apiVersion: v1
data:
    auth: ENC[AES256_GCM,data:/eZKa/iwab7cEQFgCRDKmonDjLekbgvk6pnOe51/YbfWlwiYLKFKfrv3QRpD3JWU/eqeE72iO9YIb3PWHhF8JLNJKmfB0EW+H30Q677OclAxSj2ldUSIp7D4JOzMdp9M,iv:SOsx9Bz+80z2pVZmU+HQuLUMG0R4kv14eLaS4YZRhtM=,tag:S6SbzRiwNoj16OXVBMPN6Q==,type:str]
kind: Secret
metadata:
    name: auth
    namespace: deluge
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2024-11-11T20:37:52Z'
    mac: ENC[AES256_GCM,data:vtMCnYnu7vTkoBEYdZWpAjz1nG4ZZZFUOjikLqW+5jjsN/MG82yhOeJd5Wsp7p/wH+XXaiHZu1J/8o6Swl9ZAHzd3LnuP70+ra6HKjYwh1MdR2C2/uXcMcGum+9gpAHbifVVdeD6nq4Kad7PqDGd9bsIHdcEh9ilF2eC0fZEZSA=,iv:SfhmIk4HC7UIEx+QanMFM9X0egqGaae4ANvy84r/k5g=,tag:PPUHgnlSVDOr5C27PL/Rtg==,type:str]
    pgp:
    -   created_at: '2024-11-11T20:37:48Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxv5FnUBLaS9AQ/+Li/qGcYWCx1lSD1la6NXwf9Bw3e5ea1jdSOZUG5x8iL1
            L+kSdoyH+RRvIO0Li8ElP9tGMfVQ9mzZXl1YWaPQlo7e4TB/95gVOrT5v2FMkjqw
            DeRGWJapKChNryzfJDFOjsWzc5iwsbdygSolSWgjYTkQbb1joLNn8zVD0OaFz7cs
            9cBvR4OXFoOoU5iDAcYSRSrDyl/xX0UVBhUfZLwvXxMTX2rOWlc/isuQMCYsyzpz
            n9O+bmCzm2Jzs58cvQzGrbNej/GeNl7Q6Vqf/u2MGwBBhXHL49algEyCmmdNBJKF
            viFCUj3nUW7sfTdkzH7WX4CaZbswn8cp8Ihl8pb53ZfLEMymFHiE/Y+aZImaD1MA
            TXdP7DETCSZW0GSeKVISUe8PUvlIy1qLPvBl/raTEvvKX06TspEU6YEhnUsE/Tq+
            upD7lt5mMFxRlSp3EP7YkYIF0xr0WlqnTy6DwAEP+Wdp9Dc9LhvqGxcuWqK/1psv
            JwSqaA0LONgPFM3qERL00xKaWd7/14HaRK/93RF2tckBl+A6Rb5UgPyjMBiH0D/p
            ZJWCDx1R8eW/HSZiwEqCOaB1IKOvMSAh5TjkEiSECvAM6W6gAftuljM66hLnt4sR
            T9ys3+497mUwlUZ7B8PoIacDp5TWT6WZjsbxpxg0E1+FVxxp81nQ/PDjOetVKdnS
            XAEZaeYNFBi4vD03DupgWaDULrSMHO+LxV3agBTLI83EGwOQs51Vn37AQeUEdgxt
            GHPnm52Z6VKGGwTuUzs6MNY2ZBnT7dZhKuNLqVUhnbkR9Lf80r5VMsms0Gbn
            =X5Ay
            -----END PGP MESSAGE-----
        fp: 0BCA2EF044187A707E2507E54C4527913792AFD8
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
