apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gatekeeper-system
resources:
  # - gatekeeper.yaml
  - https://raw.githubusercontent.com/open-policy-agent/gatekeeper/v3.22.2/deploy/gatekeeper.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            affinity:
              nodeAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 1
                  preference:
                    matchExpressions:
                    - key: topology.kubernetes.io/region
                      operator: In
                      values:
                      - metal
            tolerations:
              - effect: NoSchedule
                key: node.kubernetes.io/nuc
                operator: Exists
    target:
      kind: Deployment
      labelSelector: gatekeeper.sh/system=yes