apiVersion: platform.${publicDomain}/v1alpha1
kind: ProxmoxIdentity
metadata:
  name: csi-proxmox
spec:
  user: csi-proxmox@pve
  passwordSecretRef:
    namespace: crossplane-system
    name: csi-proxmox-credentials
    key: password
  userGroups:
    - csi-proxmox
  aclPath: /
  tokenName: csi-proxmox
  groupName: csi-proxmox
  roleName: csi-proxmox
  privileges:
    - VM.Audit
    - VM.Allocate
    - VM.Clone
    - VM.Config.CPU
    - VM.Config.Disk
    - VM.Config.HWType
    - VM.Config.Memory
    - VM.Config.Options
    - VM.Migrate
    - VM.PowerMgmt
    - Datastore.Allocate
    - Datastore.AllocateSpace
    - Datastore.Audit
  groupRoles:
    - csi-proxmox
