apiVersion: v1
stringData:
    config.yaml: ENC[AES256_GCM,data:2+xBwn7hLfBjpKmESb8aR3lDduTuS/Lzl9Tj4VhGojcDKjMcUquTmu8PhaZnpsPRjXOrfjTjEMBb/NRfvhvpRjlmdKbaK3wQhbOSc3p5BZU/q1MDd2kuCLLdxm7nL7JA8XCNEzMqdE3jMSuMEZxbxWFeb55gez6RnUt9sA11NXx49s/BMQq+MWVQNe8sYi9UIexdDw4ZKJBWsYZHzP1AfDhMPc+EIskvivL3BWTM3q7KR08CO4N82X8n8ARaDOG5+ZXJt13HAP14FCcQcqGnCA==,iv:KTeKlj9WJ9HE9CMcpEGi0EeyfBEmDwh28H2UNq5rozE=,tag:YmgH+LLzzpu8Ga7eqZAJFg==,type:str]
kind: Secret
metadata:
    name: proxmox-csi-plugin
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-27T15:22:47Z'
    mac: ENC[AES256_GCM,data:6/wY3YiBII0rFJ3CqPmCZ2HkDsgcRJLJHGe0Gpb8Dh+6YYUJlP0a3uo3WHhzNBn7/7DZfywmSqRvPxEPPegjOjLk0cW+mxXo3zFGN+tvoTPg1/X681Z6byjoI9Kyg0X8mchr0s65hOukP1kR6EeMm4sAZbr3hhJ4Hj9aGblsbEc=,iv:VH8YFxqlvNFfZEIpWi1oCHlbEH54gxkTDGiOx5s2tpU=,tag:1Gp7qX/+GjTIWu4FamNEww==,type:str]
    pgp:
    -   created_at: '2026-07-27T15:22:46Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAaYIjO5kzN5CUyp/Vh2vQgz2OXkc3gRw04jIOrdpXeCww
            NboXF2nPxZv2rtpZ7Ej6/qQpIOfp1YlaLxh8SOkW06adFMdyN2gegB7pCoLvLDFv
            0lwBV9pzhICuNts8B8wtu5OzSrjnKtwLJr0Om54jX/3QW9lMkGsXjq7Kioln6MKE
            VawGHzLLXSvlPZXiwDhMDKj7RIHPVyFFd6wWWODD4AivQNKECn06Xp3XQRbAFw==
            =DBOC
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:6xMopahJ9r3teW78gxXEDHPUEDY=,iv:gf3vHivsZXiT0IU8+b86NvTmeyNhERcIksdxOSld/bE=,tag:YBxblGH/3qAleQ+i1q0eig==,type:str]
    password: ENC[AES256_GCM,data:65iBrgBSTbqX20+V5D8hKw==,iv:rpzOY9LwxZxdtPttJeyyowsKScHEPONyY+2+xfxuzNM=,tag:FbMR68XVu8SSkdV1O+jn9Q==,type:str]
kind: Secret
metadata:
    name: csi-proxmox-credentials
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-27T15:22:47Z'
    mac: ENC[AES256_GCM,data:6/wY3YiBII0rFJ3CqPmCZ2HkDsgcRJLJHGe0Gpb8Dh+6YYUJlP0a3uo3WHhzNBn7/7DZfywmSqRvPxEPPegjOjLk0cW+mxXo3zFGN+tvoTPg1/X681Z6byjoI9Kyg0X8mchr0s65hOukP1kR6EeMm4sAZbr3hhJ4Hj9aGblsbEc=,iv:VH8YFxqlvNFfZEIpWi1oCHlbEH54gxkTDGiOx5s2tpU=,tag:1Gp7qX/+GjTIWu4FamNEww==,type:str]
    pgp:
    -   created_at: '2026-07-27T15:22:46Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAaYIjO5kzN5CUyp/Vh2vQgz2OXkc3gRw04jIOrdpXeCww
            NboXF2nPxZv2rtpZ7Ej6/qQpIOfp1YlaLxh8SOkW06adFMdyN2gegB7pCoLvLDFv
            0lwBV9pzhICuNts8B8wtu5OzSrjnKtwLJr0Om54jX/3QW9lMkGsXjq7Kioln6MKE
            VawGHzLLXSvlPZXiwDhMDKj7RIHPVyFFd6wWWODD4AivQNKECn06Xp3XQRbAFw==
            =DBOC
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
