apiVersion: v1
data:
    config.yaml: ENC[AES256_GCM,data:NV8kU6UFZo7jLMq16TrM/dY2k/yxkfyhWmtdX6owWAqCT+a0yd63ypuKf6CA7bIvx3cMu9uN0P1zylmcrOD8ADgJ9eFxz9ijSAu0TqLYAsqHXTo9ngBD76tMW21lCIuVJlFlLcJRa9VV1bbS4MOI44wZs1Zt1Qk5bynoUFBRGDwxtMaVLIdxciJrY73eVFpEKRos0yOImD7hklsm94KrB06QYFPYSSkukiTrldf9zAL8muE/kIbZhAWcBnS6hl2r+5u0xHgrBkAQg9mkQd0FKOPbrAOTBzCkJbrPeYlGc9BxTwIL93qlqrlWFhLFXirdcV5oOa/faLV6HcXd2zPc9LYJj8t5W/A+,iv:kPlO1ePNUHJYNqp2c3jwZyL0wd0H47Yos2QRQXqDDzI=,tag:PfYKuO8h5DdKBkBKgHCnLw==,type:str]
kind: Secret
metadata:
    name: proxmox-csi-plugin
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-12T17:32:15Z'
    mac: ENC[AES256_GCM,data:aLI2ltA8kh2TxYMW7Ygul2bximXyKUyLa/qekIaksC4c1WCO2kLxYNDZrFxD0ZqVnl5YN0cixiVxN8fCZNuhMsmljK6GmT8L5kI375vuZ5YvHYjvHH9n8Fj9ZNahMd90ojAb+CHtFJJZn2n5qkiJrr0ajpeRmjdWaMq+f5TBpfU=,iv:7Ny1Q4b1pAQ5/4VMXsMhSfWiu/OYokmRFBOdBdUs4AM=,tag:CKzT9tl2uhRwuxplIBqVig==,type:str]
    pgp:
    -   created_at: '2026-07-12T17:32:14Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAX032KuRodhGVgafjEEfs1H/mr32Q2bcbXNNGu3MO7Dkw
            3bHr2bR0DObuNuPdvLuF8aqvFv8bmjHHaQ3UJrxCsLF/h+igTIV2NnlMY/BCR1BE
            0lwBuK83lQhsNlvLClTaiL+Ns4FaI1OGleImcwp/jHXdG7LbY5OCa/RGlSZjkzGz
            k3T3CdqRMo3w9KWx/7ubLlfZuPVJS9prvNd8r9Gr3s/o/qBrij/E0vg3RwGviw==
            =Fa+K
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:pdKmJ772KxQODN85p5Sj1YSiABA=,iv:hq3MK6InaHxGXRN8oO7MeIGaDMk/isNTIGh5U7opfkM=,tag:o9ZOmduHneU9Yld1fyFk1w==,type:str]
    password: ENC[AES256_GCM,data:gwu8QpHPoNVK0HG+NYUF1w==,iv:7d0OVXz1pL7o+OrPF0rRigJQUJ/eKZYLNn62mkFs9cc=,tag:n3SeOTyg1iBvNM56PldA9A==,type:str]
kind: Secret
metadata:
    name: csi-proxmox-credentials
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-12T17:32:15Z'
    mac: ENC[AES256_GCM,data:aLI2ltA8kh2TxYMW7Ygul2bximXyKUyLa/qekIaksC4c1WCO2kLxYNDZrFxD0ZqVnl5YN0cixiVxN8fCZNuhMsmljK6GmT8L5kI375vuZ5YvHYjvHH9n8Fj9ZNahMd90ojAb+CHtFJJZn2n5qkiJrr0ajpeRmjdWaMq+f5TBpfU=,iv:7Ny1Q4b1pAQ5/4VMXsMhSfWiu/OYokmRFBOdBdUs4AM=,tag:CKzT9tl2uhRwuxplIBqVig==,type:str]
    pgp:
    -   created_at: '2026-07-12T17:32:14Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAX032KuRodhGVgafjEEfs1H/mr32Q2bcbXNNGu3MO7Dkw
            3bHr2bR0DObuNuPdvLuF8aqvFv8bmjHHaQ3UJrxCsLF/h+igTIV2NnlMY/BCR1BE
            0lwBuK83lQhsNlvLClTaiL+Ns4FaI1OGleImcwp/jHXdG7LbY5OCa/RGlSZjkzGz
            k3T3CdqRMo3w9KWx/7ubLlfZuPVJS9prvNd8r9Gr3s/o/qBrij/E0vg3RwGviw==
            =Fa+K
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
