apiVersion: v1
stringData:
    config.yaml: ENC[AES256_GCM,data:CbXk5mTXRILG5lwfngnvEZOOzXNiWsymC0nCwIbDI7iiRA62qMdosVk/7t/18EhcHgrvGptnr4STAX1EPadUnRRlzsqKoXflfrYdJL2pxjd+Jnkbfkvg7ApYWgLMlaPBBoN5RFVPtPhIqoQzmTq6VXZjxFWnaYTwXH9/Hm1RKH8T/EAgnvVBfBG6izbfIgqglH+TbkhYWGxeW1M=,iv:Pfal0BfvsRGOh7pyYGvNXkCbInljjA/tc7EgVKSwivo=,tag:Ob3PtVklLqLBIpbPrkFlvw==,type:str]
kind: Secret
metadata:
    name: proxmox-csi-plugin
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-27T13:14:50Z'
    mac: ENC[AES256_GCM,data:5w5B6P9INyfqZxrvVoaEZKp/gCz2Zhpue8uKDWcIoED486qUkbuRyAzmcWciicAIMa5hERuZvtPXDOUlPjTb8hBU/fff17NytqduXjoRdWGr9pyzNkyW+ijKfLqkz0rDI0nXYzfWdhXfMny593C/VbdpqfAajcWOkTSR41wNhDg=,iv:Qv7+yiaTnXL8Mb9g+ZOU7ri8n0R2ndx+IVqxm+T7mCE=,tag:qs5qPd6B2DWPc2idhJ8E8w==,type:str]
    pgp:
    -   created_at: '2026-07-27T13:14:49Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA8/fXdGvL+ivSqdUu/oA4inhsSbmANExoyTr1T2HPjX8w
            k42ORsivi73ycL9xoBYa5DzcAJa3Gi6r0+Dzo0ISt2sEEO8mca1z3ae9E4oNzA8q
            0lwBm+pTtDxFbaD3HLQJuqnkPNWCRwc2ZY2R7RwDYI7eHellwSAxkbFAUXSxMFhw
            CWYLDoCiOU33WnywvzGPGXNjIASUgxPBwsUtNMbgSewx+IyasxJfiULdmKoMBQ==
            =103b
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:t/33y9VDZklmmxGwGG7o0TQHuTs=,iv:aiEXlR8TVk46lkeWoFK9kCyDvlyD2X/H5+YMYZNvlrY=,tag:ruFZW/Hmse3D8tA4jWU5Xw==,type:str]
    password: ENC[AES256_GCM,data:tteXkT/tzACWIndk2wz6FA==,iv:sdeYs0+dF0dfVli+cDhziuY5UnXw8kW50z6nb9ni6k4=,tag:P7PnRktvui/8g86LAdR1Bw==,type:str]
kind: Secret
metadata:
    name: csi-proxmox-credentials
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-27T13:14:50Z'
    mac: ENC[AES256_GCM,data:5w5B6P9INyfqZxrvVoaEZKp/gCz2Zhpue8uKDWcIoED486qUkbuRyAzmcWciicAIMa5hERuZvtPXDOUlPjTb8hBU/fff17NytqduXjoRdWGr9pyzNkyW+ijKfLqkz0rDI0nXYzfWdhXfMny593C/VbdpqfAajcWOkTSR41wNhDg=,iv:Qv7+yiaTnXL8Mb9g+ZOU7ri8n0R2ndx+IVqxm+T7mCE=,tag:qs5qPd6B2DWPc2idhJ8E8w==,type:str]
    pgp:
    -   created_at: '2026-07-27T13:14:49Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA8/fXdGvL+ivSqdUu/oA4inhsSbmANExoyTr1T2HPjX8w
            k42ORsivi73ycL9xoBYa5DzcAJa3Gi6r0+Dzo0ISt2sEEO8mca1z3ae9E4oNzA8q
            0lwBm+pTtDxFbaD3HLQJuqnkPNWCRwc2ZY2R7RwDYI7eHellwSAxkbFAUXSxMFhw
            CWYLDoCiOU33WnywvzGPGXNjIASUgxPBwsUtNMbgSewx+IyasxJfiULdmKoMBQ==
            =103b
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
