resource "openwrt_configfile" "wireless" {
    name    = "wireless"
    content = <<-EOT
config wifi-device 'radio0'
    option type 'mac80211'
    option path 'platform/ahb/18100000.wmac'
    option channel '1'
    option band '2g'
    option htmode 'HT20'
    option country 'FR'
    option cell_density '0'

config wifi-iface 'mgmt_2g'
    option device 'radio0'
    option mode 'ap'
    option ifname 'wlan0-mgmt'
    option ssid 'OpenWrt-Management'
    option network 'lan_mgmt'
    option encryption 'psk2'
    option key '${var.wifi_password_ssid_mgmt}'
    option hidden 1

config wifi-iface 'guest_2g'
    option device 'radio0'
    option mode 'ap'
    option ifname 'wlan0-guest'
    option ssid 'OpenWrt-Guest'
    option network 'lan_guest'
    option encryption 'psk2'
    option key '${var.wifi_password_ssid_guest}'
    option isolate '1'

config wifi-iface 'iot_2g'
    option device 'radio0'
    option mode 'ap'
    option ifname 'wlan0-iot'
    option ssid 'OpenWrt-IoT'
    option network 'lan_iot'
    option encryption 'psk2'
    option key '${var.wifi_password_ssid_iot}'

config wifi-device 'radio1'
    option type 'mac80211'
    option path 'pci0000:00/0000:00:00.0'
    option channel '36'
    option band '5g'
    option htmode 'VHT80'
    option country 'FR'
    option cell_density '0'

config wifi-iface 'mgmt_5g'
    option device 'radio1'
    option mode 'ap'
    option ifname 'wlan1-mgmt'
    option ssid 'OpenWrt-Management-5G'
    option network 'lan_mgmt'
    option encryption 'psk2'
    option key '${var.wifi_password_ssid_mgmt}'
    option hidden 1

config wifi-iface 'guest_5g'
    option device 'radio1'
    option mode 'ap'
    option ifname 'wlan1-guest'
    option ssid 'OpenWrt-Guest-5G'
    option network 'lan_guest'
    option encryption 'psk2'
    option key '${var.wifi_password_ssid_guest}'
    option isolate '1'

config wifi-iface 'iot_5g'
    option device 'radio1'
    option mode 'ap'
    option ifname 'wlan1-iot'
    option ssid 'OpenWrt-IoT-5G'
    option network 'lan_iot'
    option encryption 'psk2'
    option key '${var.wifi_password_ssid_iot}'
EOT
    depends_on = [openwrt_configfile.network]
}
