apiVersion: v1
data:
    access_key: ENC[AES256_GCM,data:+TJ1L920pr1T0mLAKe3l+S+VPmYApJ7Px/gPdA==,iv:Jabo70xyz+KOzTKn/WUdRIG8Xjy8hyIahyGtcFlU1Hw=,tag:Lmt1ZBsoffIUhqleKn5jAA==,type:str]
    secret_key: ENC[AES256_GCM,data:80aRs45BhY0/RuHuBuzY9yR6cnaHOn1pzDzWsA==,iv:TwtdKrC1B55lpRpSYohJLx8lFL1LAB741RgpDJxW9+c=,tag:tuWjrZeYeF/8iYguEH8hDw==,type:str]
kind: Secret
metadata:
    name: credentials
    namespace: rustfs
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-08-30T13:32:08Z'
    mac: ENC[AES256_GCM,data:eYvudYpJ+uOCHsX/QZgtloLMcbBcyUD4CdUUoI5/C0gp4lj4/DGBRqFi/OBZC9T9eGinQVtwkDt1w4N9RzKN7zpKQlA4R7s0Ab2u7WEtjbltap8AdPNiWJULcxbq48LhtXiP5AuqqvxG2d6A8FATKpnRJdqMOEE5OVIlbcreiRc=,iv:QBqrj6ZUGXdbUPLW1OHN7lV/PH2Vg43ZInN3V/bDxps=,tag:QlXtEHqXWkUmURYs2WfW4A==,type:str]
    pgp:
    -   created_at: '2026-08-30T13:32:07Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdArEhWHDK9AjLXUXeGZ4XP917pz5qJq5iJ6GVpoTBZ5HUw
            rTDE6bEKYZmU/SrqXRUhDGmsEdMjdMRNpa252koqVhitORunVyX+L3sNhKjF2Kyq
            0l4Bfm94v4DxHjlv15SdgW9s944bLNaG+wkq7iYhuna6lSLHa2R3aF7f21pn7dhu
            qw0AVzSftf84TnCXrR8Xq/Cx2MrDnwHNUpQ67NJ09DVsgC4qFXjmkIV2Rl4Y+rP9
            =80mJ
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
