apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: proxmoxgroups.platform.${publicDomain}
  labels:
    provider: opentofu
spec:
  mode: Pipeline
  compositeTypeRef:
    apiVersion: platform.${publicDomain}/v1alpha1
    kind: ProxmoxGroup
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: group-workspace
            base:
              apiVersion: opentofu.m.upbound.io/v1beta1
              kind: Workspace
              spec:
                forProvider:
                  enableTofuCLILogging: true
                  source: Inline
                  module: |
                    variable "comment" {
                      type = string
                    }
                    variable "group" {
                      type = string
                    }
                    variable "propagate" {
                      type = bool
                      default = true
                    }
                    variable "roles" {
                      type = string
                    }

                    resource "proxmox_virtual_environment_group" "this" {
                      comment = var.comment
                      group_id = var.group
                    }

                    resource "proxmox_acl" "this" {
                      for_each  = toset(split(",", var.roles))
                      path      = "/"
                      group_id  = proxmox_virtual_environment_group.this.group_id
                      propagate = var.propagate
                      role_id   = each.key
                    }

                    output "group_id" {
                      value = proxmox_virtual_environment_group.this.group_id
                    }
                  vars:
                    - key: comment
                      value: "Managed by Crossplane"
                    - key: group
                      value: ""
                    - key: propagate
                      value: "true"
                    - key: roles
                      value: ""
                providerConfigRef:
                  name: proxmox
                  kind: ProviderConfig
                writeConnectionSecretToRef:
                  name: opentofu-group-workspace
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.comment
                toFieldPath: spec.forProvider.vars[0].value
                policy:
                  fromFieldPath: Optional
              - type: FromCompositeFieldPath
                fromFieldPath: spec.group
                toFieldPath: spec.forProvider.vars[1].value
              - type: FromCompositeFieldPath
                fromFieldPath: spec.propagate
                toFieldPath: spec.forProvider.vars[2].value
                policy:
                  fromFieldPath: Optional
              - type: FromCompositeFieldPath
                fromFieldPath: spec.roles
                toFieldPath: spec.forProvider.vars[3].value
                policy:
                  fromFieldPath: Optional
                transforms:
                  - type: string
                    string:
                      type: Join
                      join:
                        separator: ","
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: spec.writeConnectionSecretToRef.name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-group-workspace"
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.outputs.group_id
                toFieldPath: status.groupId
