apiVersion: v1
data:
    api-key: ENC[AES256_GCM,data:HoPlEUo4lnVfqmYz4RlGglLdZ+lQoNOLq7x8PDqvlrJ6UzCH++5JjeZ1Kmo=,iv:68n0xw5AKgyIlvRB6HzjfhcZoTtnfn/SEPq4DB8v6c8=,tag:t7CJh1QL5Nxfff7JYRhDbA==,type:str]
    database-password: ENC[AES256_GCM,data:gpZ7KNgnnPk=,iv:IOTxfFsrEJXNrHngQI+M7kv/BUNF02fdOQY6wRxulxc=,tag:XnkWfEM+wNMAYGUIIOxHUQ==,type:str]
    database-user: ENC[AES256_GCM,data:4iA5H7Dtqb8=,iv:hlt+1z8kUN9f0ywJDvMimXM0F/RGA1Sk0nzRLMj/13A=,tag:SuTFiFgwleYFOi/PYv1MRQ==,type:str]
kind: Secret
metadata:
    name: radarr
    namespace: radarr
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-13T23:32:19Z'
    mac: ENC[AES256_GCM,data:MeQSpHYKhWdUiqLLDb28kHfdVgykdOj9eEPGn7tDyFf3NKFyuEzvQWwpfKEldkmAvYGwh7+aiskf0WB7iwH8C2kygvLDK0JX2tEPFUDWpYiWmDHphQoUo1AN6+/dd7VMUc5O6w/HjRrgXEa2bzmMiXVSyYxEOTO568+1uHqBjNE=,iv:bk2dhSMcGojx8DABXCZibl2GWlB36ZfYPlZu5zm263k=,tag:QavGtW4drPL8w0rF5puwZw==,type:str]
    pgp:
    -   created_at: '2026-09-13T23:32:18Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdACIWdrEStdCVZ5/LxDV/MvgTfTvqvxODSXMW/Gai1Lmcw
            kwtkRKkujPcGWLqJZECw6m0jGUbH6IuRmDTEoout0PvUtsd7TAyPOukMkysQ24a6
            0l4BkAZKLerakXY9ANxXj2atRyNhpy7ShsQbfEfQcfUQ2G5gVpgrAguPp8+84xl4
            c07rRjjrr3yjRVNr0MwNlpsyaiD0/Wmhein5l99U7FZa196isk73zVmEFgYtv806
            =tcw/
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
