apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      group: kubeopencode.io
      version: v1alpha1
      kind: AgentTemplate
      name: opencode
    patch: |-
      - op: replace
        path: /metadata/name
        value: kubeshark
      - op: add
        path: /spec/contexts/-
        value:
          name: kubeshark-repo
          type: Git
          git:
            repository: https://github.com/shokohsc/kubeshark.git
            ref: main
          mountPath: kubeshark/