---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: renovate
              image: ghcr.io/renovatebot/renovate:43.251.0
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                capabilities:
                  drop:
                    - ALL
              env:
                - name: LOG_LEVEL
                  value: debug
                - name: RENOVATE_BASE_DIR
                  value: '/tmp/renovate/'
                - name: RENOVATE_CONFIG_FILE
                  value: '/opt/renovate/config.js'
                - name: RENOVATE_GIT_AUTHOR
                  value: 'Renovate Bot <bot@renovateapp.com>'
              envFrom:
                - secretRef:
                    name: renovate-env
              resources:
                requests:
                  cpu: 100m
                  memory: 64Mi
                limits:
                  cpu: 1000m
                  memory: 2048Mi
              volumeMounts:
                - name: config
                  mountPath: /opt/renovate/config.js
                  subPath: config.js
                - name: work
                  mountPath: /tmp/renovate/
          restartPolicy: OnFailure
          volumes:
            - name: config
              configMap:
                name: config
                defaultMode: 0644
            - name: work
              emptyDir: {}

          tolerations:
            - key: "node.kubernetes.io/nuc"
              operator: "Exists"
              effect: "NoSchedule"
