apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
type: Opaque
stringData:
    RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:503RTiW8EKjmRNJgzmEAmRzl80ReXpiFQeWDgbIMdbpu/SuT1za4SA==,iv:8lvXwHLf4jLa/vmhrAy/253s4E3Rl7UMNIkeBL3+xCw=,tag:oMxUorSDyjK7J/K8+e/r0g==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:Dk4ncAxmfvBY593onMhVJgPP+Ch/XqKnF+bPBe8E4fQRfceDvMf8Eg==,iv:E87LTlDHCtqLGeIi1hACd0w2KitkqX9XakjTOUaoUPQ=,tag:4tGeejT0plnhE2jRSNO9oA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-06-04T10:16:11Z'
    mac: ENC[AES256_GCM,data:wW6ekZveXMDhWH4uuu+QR1sgKHPV9xh26rSbfZu+1yi22KVE1qaBxAqo2u4TWwzRLtjvCfL69wVOsY+0VzoWpAI+IqL7Ps/tKxavUQBt/goXYp2TlWQRl7xcSASBg9f6YT4PfKLeDzF+yx3uJBnqJsHxAsBn87ODnGmtOSLW1aA=,iv:seKCU1sg5m5If4h55QDvthGUhC7hwDWYTCpvz/d+zjQ=,tag:K7+02tfetL9O4RXcv4URsg==,type:str]
    pgp:
    -   created_at: '2026-06-04T10:16:10Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAW7ZjCrl6J5oGY7c+jphiaqCfSaEQ/HOBwfEBBpmAfj4w
            K87izY22mY5UsajVWoIUHiGWOrZGaQANHlxNJe/9zhctwAsQ0rl8rL76c6IbYWyF
            0l4BwcVY2yIOJ1YKpGgz6U7kmpClTZv4IE2/yRMb23CjLm4DzGAXnTqvol1H+JQQ
            ZZz32BCxkDJKGNB/vRmaISQQmuPp/mvaWUDs/wRND6+4l7EgrwGPUaIXZcs3+zke
            =paRF
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
