apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
type: Opaque
stringData:
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:6OwHvtdHQnluwbpISNa+XDoZV35V/vcMGHfqsHyo5WznPxLCKZzqxQ==,iv:KXMH7JjDWfAiaBJjUd2jrII+DEjlK3c/cbRpxE3OhYs=,tag:kKhXTACQ+j4WFtI/bEhBig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-06-04T09:55:19Z'
    mac: ENC[AES256_GCM,data:Be96bAFb7XW7sGkA1gV/5HyY5p5slPOZZemdLAaFmDcUP32fNIIff/YZwRNEfRcNKWLLJLaLNyWtwXN9pbnV1hJ7dzd5J3PcmdsWc0WbOXWybXQIKInyCchLivPdF0rQ8/kvsFz2gQp3Mlc7E76bNLFQN8WuqN9DX2ifR6jJ9d0=,iv:AQNNxuWvrSkUK588yJvz4YjLaH6D46DD40a/42moGI4=,tag:maVTA6EbxgDFRSFoywvjEA==,type:str]
    pgp:
    -   created_at: '2026-06-04T09:55:18Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAjKBeCynaR4B4stfmea0sa+WdFz7D6Pb3y9B39B32N2Aw
            +7kHy1Vm5Za6jdzUfcArb0D8oFt3+UKMhItbWTofuKZ5AogamHHOLmVixXjm0JOi
            0l4B/2yRs2uMSS3y0vCFvbJR50PhicPGLSQa0altb6PsRxsWzVdL30f+OmfV8sjb
            enTHN+CYgDKIyT7gc29hUOm6B26Lylf9uWUHApLTQs5qcKq+47piaSvDSF5TaXKK
            =cHbe
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
