apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
type: Opaque
stringData:
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:vP6nJ8Y=,iv:oen4UIYRfRN5D9EXUOC6vZPY560RIb5rzutm/hBrZQs=,tag:iKvVzH0g7AWfGrlVLNmBuQ==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:ayoZRM9kctaMmTyPEt05/bMTxrCAUtn/2V5xcBBZc+1ZSw==,iv:rFRqgPtLhGmZJ2I8HmFho1Y2i8YuiMZWxoc0zMtIdKY=,tag:gyb+f7iwlYvdT+we1M9ESw==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:H4K4tqsE,iv:FFuXo5OrGwwM6ne6rfiPPZIjvJFZdNhSzWaxAUN+Lfo=,tag:Y1waR3uiNi8Mn34sSyAtag==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:rG+gYve1vIh88q5CDiA2RjTxAwb6OBP2+p7di2wVfDOcIy2d6iOtkw==,iv:K5Hp00hgB5V1ln44YVjT6cefSa+oGn2H3Zg+6l086qU=,tag:/m4zvlAcOc4gwP7cJGmt5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-06-03T16:15:27Z'
    mac: ENC[AES256_GCM,data:zVq2sEfmmONbMdTu9hQqB0uNqWZFuKOxRynr44xGlW/8496seQN9vlnwW8/aXfrLGDmMfAGpAfyAHDdwU0DVCFmVEIIBnTPsLI0qEwPscQMJeAFtTuwj7S+0yZ/bzJTOWeg+0lsbfLYs72+Srj0USSAEOpECWL8SEgxbSjL92A0=,iv:bHdQ7+jEPCTFVb9HYcpCf8zFD7dsRB7IY53ojwBpsNo=,tag:7wWLMBemJjObf3WhDXKxsw==,type:str]
    pgp:
    -   created_at: '2026-06-03T16:15:26Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAFy1KT1Qzszu0VnBvINw0FdsrmAMPcHAnVrbLJvNK5l8w
            eG4lRWEuTK1Nq+EBygn8ACFL+z7+A2sxtkIW6B8QxNBv2HeFwmwgpc0In0gIcg7G
            0l4BskQanIfni0aE3HhUsSq7r29rh/6dqJT/cAsCvLrKvld0AnyzGbzA6UVieU+H
            QbkXO710843iq+o+n+ANr1UoPYdoKCjCIRBFIMGQtgf6CILIVza7bd5OpXdwtohr
            =I5QF
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
