apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: proxmoxroles.platform.${publicDomain}
spec:
  scope: Namespaced
  group: platform.${publicDomain}
  names:
    kind: ProxmoxRole
    plural: proxmoxroles
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                role:
                  type: string
                  description: Proxmox role name
                privileges:
                  type: array
                  items:
                    type: string
                  description: List of Proxmox privileges
              required:
                - role
                - privileges
            status:
              type: object
              properties:
                roleId:
                  type: string
                  description: The Proxmox role ID
