---
kind: "DeschedulerPolicy"
profiles:
  - name: TooManyRestarts
    pluginConfig:
    - name: "RemovePodsHavingTooManyRestarts"
      args:
        podRestartThreshold: 10
        includingInitContainers: true
        states:
        - CrashLoopBackOff
    plugins:
      deschedule:
        enabled:
          - "RemovePodsHavingTooManyRestarts"