---
apiVersion: "descheduler/v1alpha2"
kind: "DeschedulerPolicy"
profiles:
  - name: TooManyRestarts
    pluginConfig:
    - name: "DefaultEvictor"
    - name: "RemovePodsViolatingInterPodAntiAffinity"
    - name: "RemoveDuplicates"
    - name: "LowNodeUtilization"
      args:
        thresholds:
          "cpu" : 20
          "memory": 20
          "pods": 20
        targetThresholds:
          "cpu" : 50
          "memory": 50
          "pods": 50
    - name: "RemovePodsHavingTooManyRestarts"
      args:
        podRestartThreshold: 10
        includingInitContainers: true
        states:
        - CrashLoopBackOff
    plugins:
      balance:
        enabled:
          - "LowNodeUtilization"
          - "RemoveDuplicates"
      deschedule:
        enabled:
          - "RemovePodsViolatingInterPodAntiAffinity"
          - "RemovePodsHavingTooManyRestarts"