apiVersion: v1
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:Tlay25R/Wxg7jGhwBWAxhOGX7b1yzsb36KIPF03R8MRJNIt/PcichIwLfKNs+Ze2Gx0BMKlODc/DxgboZQxItA==,iv:jb8MuPf3h4pPw74EJ00jO/nZWqkGs33RmaOAzsrWBwI=,tag:OnmMYBmHVwAD8ebiByZONQ==,type:str]
kind: Secret
metadata:
    name: variables
    namespace: freellmapi
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-14T21:22:36Z'
    mac: ENC[AES256_GCM,data:NifXL6G2G4r2jkC2B6qeSmdlWGYyMJTdkfRV90G1UD7PCq52yvKE+voqtMv+Tv1Ls6qBmw0pzbv0yxALjm7Wth+VbP/lhDS0QVskb/NzZgMW8m0SN6AquIwKhZySJkzV7g6YFpJsh59dcbvAbcDIH4473a3hhVX3THXIUOlXpzQ=,iv:uVYgmNTLkDB0+MAZlgorPL3ZQo4QT1xRhJjHiWSLfEg=,tag:PyujPuEMGQhMMIXpg9e7WA==,type:str]
    pgp:
    -   created_at: '2026-09-14T21:22:35Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA2oOIGsPF7Jw/RuDyydGWWhSpzs4W+b+PrlRYmXN+vFcw
            g7pL5W0jXMY4nKvWSXlkwvAXWq9WuMS9GrdBa20yjvhOA9sSSTpkz69evnLqR9Cs
            0l4BAj9QQpADSW6gBTFyTVrRmQ8zz1h+Mx1UcK9ZDd5YqG4sh8UhEhcSotFfSOdO
            JVemNyUY14FeoA76taJBpsqz0NjdbsZYIDl3kwyKuCjOO9rlLRj07Rzhug9uy5mz
            =GiJ0
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
