apiVersion: v1
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:pTy4dvWZc4FeNvoG51fSL3v2WWT2Cd4IABrli/hDYhxLj/Qvq2p4uCQEEBb9CCy/zAf1fCCCYHYlF6WBvCd2/g==,iv:dJ2EJIb3Q3xboPn6/cbLLlw7fFsOGKIOok54VUOhjQg=,tag:+tXF9RZegONj9G5xqqmFJg==,type:str]
kind: Secret
metadata:
    name: variables
    namespace: freellmapi
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-14T21:45:26Z'
    mac: ENC[AES256_GCM,data:XDq/eF5sTELbR6IKVpmXObN6JF8I+0v+B9A5Jfv3sRokmIp9+dW0Cd/5erKac8eMKFOPYo5B4v4BvpH2g8brkz2eT0cr1kH+F4Z7vi/ThLW7gm6m+gBYzr18Yx1+fBv/ijUZmWGOYfxZ/Aq0c9mqUpfisIsjkfPck7BqjRz8vpw=,iv:umKJh/FhtaL2kmRhRQR/QpuMqUf0qJhDBqqHkuZU2Gw=,tag:7MmGj/KByUAINgR6YccAfw==,type:str]
    pgp:
    -   created_at: '2026-09-14T21:45:25Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA5rhLTQqzGMX7La2fKn81lJlj6g5gN/OtKEIEOKJEvkAw
            9gxBZJ2EoikiJ08495vl9S2lFBVwKzdeUm4KOMmUyYhz295qY6aoTNisD7NfRWs4
            0l4BeJWZNCnTgN2n6a+GEze7pz8C7Uksrhx1/CNzSRRFLer0ggVkMHDw3S03mKKg
            aRb4EVPksODCntXwOsQyftPyq6i7zS7Y1t5PFAoA/QcXXd3cypwonJJL5/7N3x21
            =tD++
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
