apiVersion: v1
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:q/S7DKMn7zJXCN/BHn6fQKZYoaL5CM/JnUJpPXDWRdtE9odDsqF6gtP2+A5vLevle/v00jeVHncwmhJ6aBFyIQ==,iv:ZlR4Qv3yXwE+/QjmvmbzA97pdgELLmBWJaFmT3Ohfy8=,tag:2EefS/UOCm7WYa33gPGE5Q==,type:str]
kind: Secret
metadata:
    name: variables
    namespace: freellmapi
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-15T15:38:34Z'
    mac: ENC[AES256_GCM,data:E3jGOTLoDD8ZaFG5WOzYHh6gK0/pDsWtQWWYTK0np/tjpf6pbPmlHpxT2utEepFdGWE//6M07G7j80e49lupy6OXx5U+F1j0fHfyvXebk7alKSkUXzJpZVvnLgJ31qf3voaa/pzZSIsI+hE426XiHDWec/wV/vX6T2nNBaIh6/I=,iv:7Uywyp3jtEBoJeJI9oj1I9jDdeqevGkf4yEy2s0MNvw=,tag:ITfc4MhsmNpYEG7IEM1a6w==,type:str]
    pgp:
    -   created_at: '2026-09-15T15:38:31Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAZ0Ud0gsdb8PaLzzsSkYQmTs5VmPYHczye8uQ23uYDkcw
            6J30zMRp/V6E0i1u0f2vyUS3j78OFMiM/oZn0Ef4NmAnQ6QGp1W1hJeADZrInAxI
            0l4BFZQ3x6De95eoZ+vNzvs4bo8bG0wCjvuFxVKfxyObwg3YlBbq1JvemZmkczNN
            +99hQjZbzTQELQJRjsqnfzNSB+yuTcQqt2QWiU4FydTEhIpD7AyeBGViVH/SvOhK
            =H0/j
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
