---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: curator
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: OnFailure
          automountServiceAccountToken: false
          containers:
            - name: curator
              image: busybox:1.38.0
              command:
                - /bin/sh
              args:
                - -c
                - /usr/bin/curator.sh
              env:
                - name: SPACEMONITORING_FOLDER
                  value: /data/loki/chunks
                - name: SPACEMONITORING_MAXUSEDPERCENTE
                  value: '60'
              volumeMounts:
                - name: storage
                  mountPath: /data
                - name: scripts
                  mountPath: /usr/bin/curator.sh
                  subPath: curator.sh
          volumes:
            - name: storage
              persistentVolumeClaim:
                claimName: storage-loki-0
            - name: scripts
              configMap:
                name: scripts
                defaultMode: 0755
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - loki
                topologyKey: kubernetes.io/hostname
