apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pyload
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - http-route.yaml
configMapGenerator:
- name: pyload
  files:
  - ./config/pyload.cfg
