apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sidekick
resources:
  - namespace.yaml
  # - tekton.yaml

  - api/
  - vpn/
  # - changedetection/
  # - kubernetesevents/
  # # - cmangos/
  # - email/
  # # - cloudflare/
  # - search/

images:
  - name: shokohsc/moleculer-sidekick
    newTag: "fb8c753"

configMapGenerator:
  - name: common-env
    envs:
      - ./config/common-env
  - name: config
    files:
      - ./config/nats.conf
generatorOptions:
  disableNameSuffixHash: true
