---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ceph-csi
spec:
  interval: ${interval}
  url: https://ceph.github.io/csi-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi
spec:
  interval: ${interval}
  chart:
    spec:
      chart: ceph-csi-rbd
      version: 3.17.0
      sourceRef:
        kind: HelmRepository
        name: ceph-csi
      interval: ${interval}
  values:
    csiConfig:
      - clusterID: b6e1f4cf-3e62-40f2-95aa-b403d469a097
        monitors:
          - 10.42.30.10:6789
          - 10.42.30.20:6789
          - 10.42.30.30:6789
    storageClass:
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
      create: true
      name: ceph-rbd
      clusterID: b6e1f4cf-3e62-40f2-95aa-b403d469a097
      pool: ceph-rbd
      volumeBindingMode: WaitForFirstConsumer
      provisionerSecret: ceph-secret
      controllerExpandSecret: ceph-secret
      controllerPublishSecret: ceph-secret
      nodeStageSecret: ceph-secret
    secret:
      create: false
    provisioner:
      replicaCount: 1
    logLevel: 2