apiVersion: v1
kind: ConfigMap
data:
  ceph.conf: |
    [global]
      auth_client_required = cephx
      auth_cluster_required = cephx
      auth_service_required = cephx
      cluster_network = 10.42.30.0/24
      fsid = b6e1f4cf-3e62-40f2-95aa-b403d469a097
      mon_allow_pool_delete = true
      mon_host = 10.42.30.10 10.42.30.20 10.42.30.30
      ms_bind_ipv4 = true
      ms_bind_ipv6 = false
      osd_pool_default_min_size = 2
      osd_pool_default_size = 3
      public_network = 10.42.30.0/24

  # keyring is a required key and its value should be empty
  keyring: |
metadata:
  name: ceph-config