apiVersion: v1
stringData:
    userID: ENC[AES256_GCM,data:N/HYzcM=,iv:BUbkhzDFyt8dLNNUryguqEIrY8fq8ROb10p+yB6ckzY=,tag:T5LVSz4aLqELSMv0rgyW3A==,type:str]
    userKey: ENC[AES256_GCM,data:I1LWNdvQyxlUwyEg29fM6Sog4h2z6ulVYmc2AA/i5NdbF7q/VTBFKA==,iv:mIA4BiD+3H6bPJZZSntMYmLN6NLuo8VrlOlTQtQ6cXI=,tag:h+n5ROT8dW5MVmVtpAjmRg==,type:str]
kind: Secret
metadata:
    name: ceph-secret
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-27T22:35:52Z'
    mac: ENC[AES256_GCM,data:1eqmYdbXWnxKnwP6ru/Y8cDTG+KbNg0krIXzkMfZSSf9zHw/YR+k9EwKaawMDNHHk5SxzccS/0lqkpK0Xh8Aegs/fzI8H7NtPvqV/uSIPg6E02MoAZHkV40DNfcDMO5MVrJvYIp4AtlnthrcpeDHihGyMFfGPkXbEJX/Dfj1ya0=,iv:YQIFIizQSkYPmkQwpEGCxcGMqA0mpJQc5tLPgTS0A0E=,tag:Ds3/niq+pD4kb+kZ3b9QDw==,type:str]
    pgp:
    -   created_at: '2026-07-27T22:35:51Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA2d6vLKfsIZsDHbijjN3TRtz6pm1aDN+GVLLadUNvBWEw
            h19E+EpwA4qUZr+VXLIZnOesjN4pP4fpTWv66lfi04t5nK4ai/m/PDycA23JFLh0
            0lwBbR3Ef3j3nqbkjx1PaJCwx8hYLjv4jrSBLeIluk7uim4FXfv+Zfs0YC6la6Tf
            tAVxxB2a5fKePnek3vl7s3WXI9sb/tbJcSaolhuWIvTFTnKi4q7RZRJCByuWnQ==
            =/R/9
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
