apiVersion: v1
data:
    api-key: ENC[AES256_GCM,data:+/JKQQPHvUG/hHr9x+/JixscRHnTjtt/CxbPMP7qmPTOnd/mtnHYEw2Yw4moKDi4zw8xTQ==,iv:vIZCWTydnfXIDfYf668v11VgFMiM7UgOyJTyvei06kc=,tag:su1uLT41WWKztpHFiYcBxg==,type:str]
    project-id: ENC[AES256_GCM,data:YyFd+HxxdosjJQsFL6vbInIrEek=,iv:KDxICVN6YlK3Ar3QUJUo/EfzglRQkehTkkOZU4Qx4gY=,tag:gwcxpbfc9tiq9s2EM7PFEQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: firebase
    namespace: sidekick
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2022-02-06T20:57:37Z'
    mac: ENC[AES256_GCM,data:4pMu85ukxJxq7I6Ymhc9u3mtpiH3CMEW3UedJJ3UAUQGmhWDo1CY0AF3ak7hJj/dY7Qs3/gSOaNIshQqqlbDPwrLnpFH+0Nex+29aJuTjkkaMpcWWqC027qI9iH9MikeWqMp0+cYNTrNRhxYiUTRnK2yCcBna81BVFYHylffd5Y=,iv:CT+R+/4BYbEb/GUhGC0CsA55pNUlV4KJlWrrcAQubhc=,tag:HdWsKyPYzU6/oGIBjaGEuA==,type:str]
    pgp:
    -   created_at: '2022-02-06T20:57:36Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxv5FnUBLaS9ARAAsabUE5oy4+r2LYegAbeeL0kbsn6OTuVJlzMwsOn/bxz3
            az1n7B/g4l7V7KKDj+6j3RZKjj/aI3WW8nqqCgDZmttvQ87QWmpTBQBq5qYDvfIj
            U4UdPiWrtyOOPydhi2whf3L+StxYoyykCl51nmyD5ybwNPMtrfS5nPl09A57mtTc
            uzbmp91HgAFs0dBzcZZrHo0ERFZQOn8e+t3mB5cEc5kydLck4HT5wG3aMInZdAJg
            PcSkVFc/9hgn3hTqsOXW/lXiwnF6UM8jy8nbnyEYhHTVn64MqrQsOwFDY2COOHt1
            DxeAqf1/9w0/5J40+tf/s/j2TD24BD50DVRPL4yR3NrT3+pLhJrc9rjF1npAjoNh
            2EYAmxZ1UfHTby9KgR7AzPnebS+mMALvcskFy8RbsQ3rgDCKo50RnAtVN2ObbMdi
            6tIHKOEt4FBTqmCu+g9Txd1OmACtKXlCYOIO1NOVPWai5piTx/xX/dfB4n1+GMe/
            3drSo2N1fJpfDusqxGtCxXFigMZDBjU73rwGWeZ0Pz/UHf1VYuLk3dtA5YoMjukh
            NCY6UOErVrEuAAwwOZ0jdk/8Oem+q9Cj2NOclOudSip19yQmb50GPjweSBQsA9/Q
            R1PeZu62VWQ2sTX//0gUlKGhL85QeHMwedNmram//DoI59q1CT/y65gV9EbAtdXS
            XAHCBy9h5MuGKNEkGLpoHrSjjiwoDSo5TJgzVTRlXVoRc2oVIPaJH5Q2qdqZfwZd
            ZvyA6Aq8Bx4CiPmE//cH20Kzr9JDdYIP9il8UrZee0IVva3juwxa2lp4V3QT
            =6d9v
            -----END PGP MESSAGE-----
        fp: 0BCA2EF044187A707E2507E54C4527913792AFD8
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
