---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: browserless
  labels:
    app: browserless
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: browserless
  template:
    metadata:
      labels:
        app: browserless
        policy.gatekeeper.sh/ignore-container-must-have-limits: "true"
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: browserless
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: browserless
      containers:
        - name: browserless
          image: ghcr.io/browserless/chromium:v2.56.7@sha256:b1ba7b054af2891a8199f884d4bd249cf8c3bd2fa8a97b339077e40f92803ba8
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          env:
            - name: TOKEN
              value: EeJ4Ou3waagh7goMohsah6sooTeehoom
            - name: CONCURRENT
              value: "6"
            - name: TIMEOUT
              value: "15000"
            - name: HEALTH
              value: "true"
            - name: MAX_MEMORY_PERCENT
              value: "80"
            - name: XDG_CONFIG_HOME
              value: /tmp/.chromium
            - name: XDG_CACHE_HOME
              value: /tmp/.chromium
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: http
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              path: /docs
              port: http
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 4096Mi
          volumeMounts:
            - mountPath: /tmp
              name: data
      volumes:
        - name: data
          emptyDir:
            medium: Memory