---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: browserless
  labels:
    app: browserless
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: browserless
  template:
    metadata:
      labels:
        app: browserless
        policy.gatekeeper.sh/ignore: "true"
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: browserless
          image: ghcr.io/browserless/chromium:v2.52.1
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          env:
            - name: TOKEN
              value: EeJ4Ou3waagh7goMohsah6sooTeehoom
            - name: CONCURRENT
              value: "6"
            - name: TIMEOUT
              value: "15000"
            - name: HEALTH
              value: "true"
            - name: MAX_MEMORY_PERCENT
              value: "80"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: http
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              path: /docs
              port: http
          resources:
            requests:
              cpu: 100m
              memory: 128M
            limits:
              cpu: 3
              memory: 4096M
      tolerations:
        - key: "node.kubernetes.io/nuc"
          operator: "Exists"
          effect: "NoSchedule"
