---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: fan-control
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: fan-control
              image: node:26.8.1-alpine3.23
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                capabilities:
                  drop:
                    - ALL
              envFrom:
                - secretRef:
                    name: ipmi-credentials
              resources:
                requests:
                  cpu: 100m
                  memory: 64Mi
                limits:
                  cpu: 100m
                  memory: 64Mi
              volumeMounts:
                - name: config
                  mountPath: /home/node/fan-control.sh
                  subPath: fan-control.sh
          restartPolicy: OnFailure
          volumes:
            - name: config
              configMap:
                name: config
                defaultMode: 0755
