apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fan-control
resources:
  - namespace.yaml
  - cronjob.yaml
  - secret.yaml
configMapGenerator:
- name: config
  files:
  - ./config/fan-control.sh
generatorOptions:
  disableNameSuffixHash: true