apiVersion: v1
kind: Secret
metadata:
    name: ipmi-credentials
type: Opaque
stringData:
    IPMIHOST: ENC[AES256_GCM,data:b/nY8OLkMywOYPU=,iv:r7SefJGE6IE5/+B3UTJTfWE4HoxZeP7G3XQTr2QT2BA=,tag:5u0bKjKEttQAT54WaHtiyQ==,type:str]
    IPMIUSER: ENC[AES256_GCM,data:6fncLA==,iv:8sIAwaFNbxoVQWjsCpWjie1G9aQyxhIo+KeAxJ8jsyQ=,tag:kIyQUCgSk6AsDtW81Ezrfw==,type:str]
    IPMIPW: ENC[AES256_GCM,data:b8dQEeg4,iv:ByaAAOwtEcLFPC2krk4hAk5adCabzQa/iXeOYKQXopE=,tag:C+rtY/+ro1tqhAXBZIrn1w==,type:str]
    IPMIEK: ENC[AES256_GCM,data:+SvgJAf/u4PQjCy2IN0+QpMG+hNwU9reyBB9Drz9Li2LQ7Acpq+kOw==,iv:76gix76Zj969hQBgpscUJ9RLn5YtHv+c6XePakkX1nQ=,tag:Hx0wPQESLfdQPdNTUr9RTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-08-28T04:47:05Z'
    mac: ENC[AES256_GCM,data:3sJyk0ErSIccT5SKQgJFuXY03Nfc3sYTLM34lVKfnsFFIZugDlGUzQFuUC04Oojeyws+pWF5yPK17I7CGYhNzhy028lWohdBLQDQBket/k3WgOURLkWxFjpsEliTxidXDuQWPlm+Dg21VryCvZKulZXk5QWZkbkUZkb61BEB2/E=,iv:QtT9S0g+NMgxPLvqBNAtVSuNmnPevT8ALLC2Gx4YG4E=,tag:FD1x+prcvNVahL4RFBSbkw==,type:str]
    pgp:
    -   created_at: '2026-08-28T04:47:04Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdARcJ15DUVLQ9XiAuIphMBHTDfq3HfH9Konfk5irDOd20w
            BUHo8eHQ7yn30HXWGIX3YfXRcLY3ICvxjhZcZg8baDAuLfDJa07xuaeFOZhruOMW
            0l4BRDi8rSdODMWkr9XBbpU3qwWDoiuubcn7EQXVW9Uvbb3plHvW7ZT4JqxdHNkH
            bsyFtX3BU1vrSUfadAIDDOTYB0u7YcD44QoVNpEHTtsxl1VwDr7wlMLzKJu4ffxd
            =ryLH
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
