---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-downloads
spec:
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-downloads
  template:
    metadata:
      labels:
        app: nfs-downloads
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: nfs
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          image: izdock/nfs-ganesha:3.4
          env:
            - name: PSEUDO_PATH
              value: /
            - name: EXPORT_PATH
              value: /downloads
            - name: TRANSPORTS
              value: TCP
            - name: GRACELESS
              value: "true"
            - name: CLIENT_LIST
              value: "${cidr}, ${kubeServicesCidr}"
            - name: DISABLE_ACL
              value: "true"
          ports:
            - name: nfs
              containerPort: 2049
              protocol: TCP
            - name: rpc-tcp
              containerPort: 111
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: nfs
          readinessProbe:
            tcpSocket:
              port: nfs
          volumeMounts:
            - name: downloads
              mountPath: /downloads
          resources:
            requests:
              cpu: 100m
              memory: 512M
            limits:
              cpu: 1000m
              memory: 1024M
      volumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads
