---
apiVersion: kubeopencode.io/v1alpha1
kind: Agent
metadata:
  name: main
spec:
  templateRef:
    name: main
  profile: "Homelab Devops specialist"
  share:
    enabled: true
    allowedIPs:
      - 10.42.10.0/24
      - 10.244.0.0/16
# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: main
#   annotations:
#     dashboard.${domain}/icon: robot
#     dashboard.${domain}/name: main-agent
#     dashboard.${domain}/url: https://main-agent.${domain}
# spec:
#   hostnames:
#   - main-agent.${domain}
#   parentRefs:
#   - name: cilium
#     namespace: cilium
#   rules:
#   - backendRefs:
#     - name: main
#       port: 4096
#     matches:
#     - path:
#         type: PathPrefix
#         value: /
---
apiVersion: kubeopencode.io/v1alpha1
kind: Agent
metadata:
  name: nostr-gateway
spec:
  templateRef:
    name: main
  profile: "Homelab Devops specialist"
  share:
    allowedIPs:
      - 10.244.0.0/16
  command: ["opencode", "acp"]