---
apiVersion: kubeopencode.io/v1alpha1
kind: Agent
metadata:
  name: main
spec:
  templateRef:
    name: main
  profile: "Homelab Devops specialist"
  plugins:
    - name: "superpowers@git+https://github.com/obra/superpowers.git"
      target: tui
  share:
    enabled: true
    allowedIPs:
      - 10.42.10.0/24
      - 10.244.0.0/16