apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: workspace
resources:
  - namespace.yaml
  - secret.yaml
  - agent-template.yaml
  - cilium-network-policy
configMapGenerator:
- name: skills
  files:
  - ./skills/golang/SKILL.md
  - ./skills/javascript/SKILL.md
  - ./skills/self-improving/SKILL.md
  - ./skills/self-improving/learned-rules.md
  - ./skills/self-improving/CHANGELOG.md
generatorOptions:
  disableNameSuffixHash: true
