apiVersion: v1
stringData:
    token: ENC[AES256_GCM,data:PYzVs9d4ITyYdSWBH1KYKlFT+0VPIF5MNiddjnCX1Bai398stnZ/qRpiUf75bY5lMyIUFfvmAFHByarL1PUo1ZbIUci4lCchwS2xMtRO25KzQPYs/YLkW1bI7JVm,iv:RPMCu7HTm14343BTRWqaUnOrvRvRe6YMbi8BCZDnFIY=,tag:LVsaUSHAIf00Bm6pzlKcgg==,type:str]
    postgres-url: ENC[AES256_GCM,data:1x32389kWW0C/dVTaWrRHM5mn278YbLJ+0P/fFgvP5mko7pNy14ID5Nqb+TYoVMC+u7GWMSM90wVxAzMxXAo/y1UZv9Sd7lbhXT0veDHCWqPcTncaA432YZEUtY=,iv:7/E0dRyBuFDlzONOtKBbKrdku0B6DUxceFy1cIzFzS4=,tag:jVMfHj07jNKC5chmfRLx4g==,type:str]
kind: Secret
metadata:
    name: credentials
    namespace: workspace
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-22T20:48:05Z'
    mac: ENC[AES256_GCM,data:OEikTJW6nLK1sj9eeZ57/pQMJSvJN/OgczJc77AIhpXfFJTvNRRtt1iSYFKMHrNeB7ehDb9vcczWsXbKuti0T4aEG2SYTdML09K5+Cjdd5KULu2Uge46FhUYUi2t4s4V+N0adO3uWEeTH6vXLoo6Eks3LIRTFMQJG3dD1RDY6t0=,iv:FclPs1WNki65Eb5TOo7+o6t/VChBL6IK31UcdbByvLY=,tag:ymxkuI+WiAtwQXMLewGPqw==,type:str]
    pgp:
    -   created_at: '2026-09-22T20:48:04Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAoyLpJ25sVxI5EuQVxs4vhVAUMT8eJxlMla2vBP5WlzEw
            NdxGOgz3iwxQW4VrmOPw6qfApkwvbuGJzzZzgIeyf9omZL3qWRUuThE2SfUKrj4I
            0lwBtCHWql6/jK0A9DLST6Fz0jLSlSSf+nFyrgWrcIv/xcU39RbDO4TeumVOgA3t
            cNDxYnYa+vXGSgamxZ0EVDElSVhz/FjNo2cFGY82AzszOPIFIcWS6WO3cMBYuw==
            =Tp0y
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
