apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  annotations:
    secret.reloader.stakater.com/reload: prowlarr
    configmap.reloader.stakater.com/reload: config
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: prowlarr
          image: ghcr.io/home-operations/prowlarr:2.6.4
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          env:
            - name: TZ
              value: ${timezone}
            - name: PROWLARR__AUTH__APIKEY
              valueFrom:
                secretKeyRef:
                  key: api-key
                  name: prowlarr
            - name: PROWLARR__POSTGRES__USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: prowlarr
            - name: PROWLARR__POSTGRES__PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: prowlarr
          ports:
            - name: http
              containerPort: 9696
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: http
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 1000m
              memory: 256M
            requests:
              cpu: 100m
              memory: 128M
          volumeMounts:
            - name: tmp
              mountPath: /config
      volumes:
        - name: tmp
          emptyDir: {}
