apiVersion: v1
stringData:
    config.xml: ENC[AES256_GCM,data:tXgLGoKxJ5w2CspTIToukb2BPxVcjE8mUjcohxwVWecRLE/rhBgXLaCh/mn9oqR7CLkUE86kNzxzd0pqg3OhnJf6kvN+b7HAWnpGHJmaOxCGruEyXnvb5JBgx1q1DtuSjdwCgai/GZ4PdGuLHM62YQwPIqwghpNVhBWOlwVGjWrXECqUAhwHlxIik8OY27ndJpwhQvp8G+s1UpCPM8bHUzKcFz9Ttj4JrzIsEPW/aM0b+9WRDwVrtU5IAK1GYPCbOeWNQh2gYmC8FWkNsZ3WwA/7I2ZAYdDMvLrfeDjlYi/WloNrmRVmJN2THYTPyx/MK2wk2H62Cn4Uxsyz2C+d2J85KFDTidSJq+n01vP0Ry4osAnFrLrFOaUJXmxI7CF4iUrNK2ugt42hK3F/8FIHKu2bE6gAK5XB7luK7Jv5GuOakoyj4KryvZt6I7DgVaWrf/lpyyyC61NDPzXNxWG5ZsIOd+xdrDg3r7k75arJhk9AVEcNcB8GgJbTBu3Mq1g20rRJbXxhBUNqzWloKnEOCLRFRAzwvxaEtaIMYu8xI9jU6zFzOw1lkThA/17b1rJ0ejE3BWZGtaxj1KIymYtQj2aCHMY8RwwIMAdIwYjU6cLA/my2jotOBr7obRyJJHkEpfQ84MLuR4IpFs+ndQp28MopfIvpXi/KUKXRrS+308zgokCHxsFinwccdavM+IFR/EczuPKE+DQeF5G9r8STeOMLrX3riST9+AdGFV9JoUpCHjgeGnHpcn0vZcnPRiDDkDS1n2bUuxsoSsCT3kpzOlX7OdtXoYUjqqYRku1I1uJYxBi5q4jJFRkA8MjwItGLN2z8Khe1UqoKtzXi0pdAOdWsCSyuyMwrlJqv/2HDtsh1D1W4CYsfH4f+axCNAQstRCqFxMo7ZrDmNbRaBxqN4jYkSh9MRUsqxOXwBUuV5+w2RKFYqIv71T7ZeRy5qYLh3swwzb677da2ApKupK20I3r9ctJnXMZ78sHENb2vmOHtjgdfDZBNydKEAE6ZIdKR5WR2cJ9GZXUSdcgZ446oeYY0wntDgtIy4xykXi3UY2mB9iu7vvLwoQqtUjRTkY0+CDUEp2SaSw6Vl1Ec5YwgQJtUc9JV9hwptErGuPEqDC+EE33Dyrtr3arRmxe/9NZedkaq3i6wfOXD+etImT4samDpOwfW2CmpitKSZ/S3boOlqdpl1yKGzKmm,iv:Ts4UKTzrXCll1UCxF66b1TtYvIc37n6WUa/qAAzdVnE=,tag:xGjUGY3Cux48GnxPcoDnRw==,type:str]
kind: Secret
metadata:
    name: prowlarr
    namespace: prowlarr
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-14T00:12:41Z'
    mac: ENC[AES256_GCM,data:QRCl73RsiR684kiQLWrLHI6YGQcw0HNbWufbkkdXYYslzqzhik1siHqy1d146/RH8a+J19E5ty5TTzb22/CrOT2AsCeSNmki0haQDTTKCaRqL7UhgHreU0VTvyBowXKVfznkdihAuzzcANoRIf9WNDocl+LSqcNPF5IGAu0PwlA=,iv:Bi98l/iALQJsHwn7GLQpI8rNdqCcszLE8Ua7bnL6HtU=,tag:dAtaMRLYrmv3hoKrQPpMDQ==,type:str]
    pgp:
    -   created_at: '2026-09-14T00:12:41Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdArrCRYJDbsjP1KZH8xNWJz41IaP36AduamNICSAB5GzYw
            wLZkzHrlfXO38e8l1VcJdUPB1bUgvrIZMqKlaZwVocNqJbz+KotCDwwdJrDGxPzU
            0l4BA8ZOoQCWCar0P+C6sHudw/KkhEOInlqKKfdcbkFtzoD8GB1JnNXnKsSWtxyx
            dMWbNONxvOldCJEVza3k1slzbFEMRe6LB9NjsWG9twm18kETZCkOtVoYAAsyI2PW
            =MScm
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
