apiVersion: v1
data:
    api-key: ENC[AES256_GCM,data:s9A1++jjIuh6K7t4sQzC4bNpb8VI9ClUTevIiU/EZ5wgpUH0CGWp81+zH/Q=,iv:nU1lgziuYZy3n4Wob31p41ZN34UPSc/9vEQfTgJuX9k=,tag:uJPyCxVGDwgpbDS2BIOG8A==,type:str]
    database-password: ENC[AES256_GCM,data:F8m8ag/rQHBcmkhS,iv:tsqpv2m+/uopCD0sBZLF0XJWQEB8Mnlh50xsuOfu4EQ=,tag:g/59Zzf1ygS0KtJJ9MWfFw==,type:str]
    database-user: ENC[AES256_GCM,data:jfC0ufWJVjU3RTG3,iv:32B36G2HNwU8+CDTcXeWEZu6I9bmtuXIru0cGGQqES0=,tag:ZgOOcU7NxT+w0/V1IeL49Q==,type:str]
kind: Secret
metadata:
    name: prowlarr
    namespace: prowlarr
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-14T00:27:09Z'
    mac: ENC[AES256_GCM,data:02o8Bc8tj93ym/wV5Q0GaHG+HoJw2B+n0QdjTX7zAj4WjUGWGpdmytXfFcUoFMDOABDXiPvqwSmniCFfHG6TdvsPDGcmGQmao7Txdg6jbqhGQ0CCu8sTHzHnX8mBJtI00AqNBVjnS585HgRkjbU3ii3si9nUXKV/GgUk0j+mGnM=,iv:gA1vonKVVkZTHa1ywStJZ8KMyqeR4QwH1WTa/8mBZTU=,tag:TcCJq1xtFOqOpnz51xVAJQ==,type:str]
    pgp:
    -   created_at: '2026-09-14T00:27:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA4zQgkiIt6vCTGiNpph7IoUOMEI9h/lWRXZ0Z508UlVIw
            y+iNC8+BuofyUuPer0TLSAMi/PFZTKaUPO1aoqTxn55qF8NPVZ4b1zIHhIG87qpt
            0lwBZ8XggS6rlsiU2mNclVQU2/qAWCyXoWpbngVw6W/T8Ye4zENMv2G2h24lwI/g
            4n7dxzI5b9Ax2dfcL5Rl5om7YnevxScOtgGBSQujUIKTQOhCgRAX5ewjTfPwRg==
            =IGb4
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
