apiVersion: v1
stringData:
    config.xml: ENC[AES256_GCM,data:yGbNAgMzC1hLMqDNijlSH3gPKUQh8aoPTx+SlTCJR/qJRCpSWmvwQZt0jaBF9RUi/QMj39/t5Eor+vos44Ngj0T/8EPNiIzdsN5uuuWPS7Bs+qkjpJt5+n3YEnAuKyEOrtuwdkxfKKb3hPqKHaCCLM4qS4My9beAxfkhNjW3NDAkBOmcWGdVsBx6GSKg+Lt3WoMIHR2uZc4sg3a7Y4zT46T9wMnq9/kXglUAuMlMayCytvIKaX11EqF6A894jGKySdwxRCI7K+h5ODP6APWq5LbX2qwUCbePfxxG9wzQq3u04nBTNR0zqTLUqQmXXdE+TSyHzONzjxLgees4q7y8y3W4ow8yylvmJ3BcGJVswSswPQSFu8oSo6AAX27YkXLR/l22pFwYtWxGKG5jwb3GJrhTRKwEnalLTvfjFbVUEhdOMgPq5YtY4wLKfa+4/iLDBCHD4eG9Co4z277vChyslmJspCDL55Q1wZvyqjgo3Syl6tWdzVKTE3Xo096EYoPneiOtrs0X6+tE+UPdTZabGRZ9dgUz3qSle+0dHeG+afyX9Z7QMkb6I8wrswsEeEgefGOYPD0pVY+uKgCfCiZ8RsvhT/x4vSUjb5GiT/cZFF6CszfxviIbYrKQjWPWhb5+JWaMI39VQbHLCE9SXHoChSld2hiDiIXNjQV7ggKB638m2KGWCLC+vZ03mgSAaLITbHnZxM7+f4giAtJB3OPmBMHMbmMk26feyP5N1pqGZaPqM9AIHCymJXcyI2OoktDpS3lsqo2U9gyKd6NObMLjRwdGwhRgDCn/dMpITLubcmw0amER4EcvQO4RgZnvCosMFe/rjrxgPSLSNvJv2QjF4VCRJT0CSPLI3RY8EYQQfGuy1u2K1WuBjPnag1m3/OlAgRJXtUlyHU9h1ttqeCti50ixDqU+B6HWrR2svt4K0xPW1FVVa+v6d+9QqU69kE1j6lh+OLYrVnSSxeqgtsD01aJuIjAioDmK0yfqNdB98C95N/JkQB9ZuZRTzouTqFzWSzjyqlY05jdvX+IouPQoV5V8++JRt/IInoFXZN0Qd6BWBwvhD+a13bpJ4em7MP4Nd8UzXlVmkRwEI1WnfDnyGt/r02QnRqqWsGoeqMIegFI6RAP3ORs4C6ysEh7puaFuzyIfB3Htl6+11EfLThTYbJbghEbw54g=,iv:rYvZhATJFe4QFFEBxrT90axrZnm8FT5aS8gGeNPRXFM=,tag:eUv7DAQqtzArx6fDIujUAQ==,type:str]
kind: Secret
metadata:
    name: prowlarr
    namespace: prowlarr
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-13T23:45:56Z'
    mac: ENC[AES256_GCM,data:c5gieviaUYLNpO1nA/UWoa7NEevWkvvhvmQ8PYz9Ks+MhkrcpUWoBwggptXP134aKzdSKVSARKoX6/z7DeCLRVpJ10sjpCWSNLNBtbmRlegixTFCQKzTBIuKr9sXczsbaTwEoK0Ct+Z6JolVKZnnTEU++NiyhiYvXS5reaKfkik=,iv:xrXpnKwTdYDtA1pMbLw+T+mf46L2otTqZ78np5/2k+c=,tag:IdvSFNmj70Ge5mTLoHunsg==,type:str]
    pgp:
    -   created_at: '2026-09-13T23:45:55Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAxXwDfa0N01gSb8bvlKtAVtqSEe0DyMHxrill530cWxQw
            ZG7IpJlBGgRs4dVSOYNRy2tNkfQSQJelNDALXTLV2+GKhKJ+c7NJzXDOEQKDMlu/
            0l4ByQJhL8L2ScjhOpGn+ikbDXCBB9ptI9Tsx5bPvqzb3LoUAn05Gs1U91eM5mJB
            9m+ZQK/C6+5bAHbCVbSmaK/I4BV0ol+nJQ64qyx5HnrzRcVRQkNy6N9NfMxehI/2
            =kDbE
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
