apiVersion: v1
kind: Secret
metadata:
    name: mikrotik-credentials
stringData:
    MIKROTIK_BASEURL: ENC[AES256_GCM,data:9+hHbkBvC3SeMeP0Hx41fqGUADH/TcBX+PY=,iv:/+e5uogfjppCQ6ofofiQAqWpIz/weyOkkRAzlxlqNBE=,tag:ChkZ1uYJed91ADWhhsbYPg==,type:str]
    MIKROTIK_USERNAME: ENC[AES256_GCM,data:rn6IXdGy+Rc=,iv:llNRYttXO95a38TI59FRBF72JO2w9NidFZyB7i1JxKc=,tag:wzOLavazn1AYhJAHve2MnA==,type:str]
    MIKROTIK_PASSWORD: ENC[AES256_GCM,data:8JZk7rQK7wU=,iv:s3U6XD15zgqW0DtMxCCU0rOhOLxz1onBIcQgGbHMhkc=,tag:V6mT0QzlwIXJLKR27rFzFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-06-01T16:32:48Z'
    mac: ENC[AES256_GCM,data:yzA2pgxr5ryjYf+997m7eHCLvqSbwaaP/SIu+fTQ7+pDaqWY6Tdf9Wdd36+ePdtw1pn/BAlnpCUGFtowlEKyizqytATa9PIneF/TjMxiCSbdouEh27u9UsckPxN6IOSvRxmPtSLo/Z67a41QzkAP8MX8HFCyaI/5Zx4O/gkHbNc=,iv:CXA0SJ/wzhM/4SG8mlXrm0Ef+dS0ulH++t61kqjuayI=,tag:sNwCH4PSXOmk/Nv7rtniUQ==,type:str]
    pgp:
    -   created_at: '2026-06-01T16:32:47Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DTe0P/qWvzAMSAQdAFyrgdOxlxC/g3+T9oE4ZXLuNi+kajYlBKJoknKfgwyEw
            e8XJ80G383AAAK9LjbS/grM3GjVRGQSP3884ovOth1mNDGpti7Y5QTaM9Ahwap/T
            1GgBCQIQb53oSJ9t3/k/p0sSrmsY8tLwQzb/RfZmEIeFhw5308WfvtusRtSQfi/J
            9xRBJJN4Bw8IINUI05auAL0IKK3T5SIsCJvPBkHODmgJjERoUGhqFsIr0lZxs/hL
            ohxiuzdJ2dd8Vw==
            =ThoM
            -----END PGP MESSAGE-----
        fp: DCCB612CCF10CFA0670BD8E74DED0FFEA5AFCC03
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
