apiVersion: v1
kind: Secret
metadata:
    name: mikrotik-credentials
stringData:
    MIKROTIK_BASEURL: ENC[AES256_GCM,data:rEFhDr0SiAugdthQY0c3jDqw7JUXsXsuGko=,iv:gUnOFlG7rMqT6jEHlSLSR8UPYuCkvaRsQiNp4l8MjjU=,tag:ORf6igbhCIRkWf/Iu5v6ow==,type:str]
    MIKROTIK_USERNAME: ENC[AES256_GCM,data:PIUdroIhaSg=,iv:P1SZtQ/aqcyMIFJZCcaUlV7cN3CyKPjlJFZFbIUKpLM=,tag:odlMz9iVep/RoIhmAzonXA==,type:str]
    MIKROTIK_PASSWORD: ENC[AES256_GCM,data:PuaK7bYUII4=,iv:UMBpNqx0OxM5u+iSuiig9CDthxETg36KwIl9DxKxbek=,tag:Ae8GxTkeQVsM+TAPGxRJVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-06-01T18:38:37Z'
    mac: ENC[AES256_GCM,data:6jgPpYFJPYS/CUkEP6I0UtjK6l4BdJyD36B8rWVMgIPaa3BfWy/RDKa3dkotLlY40mR4PDFyYP2pMVzDWGrGahUJzHCH3JOgJVcYnJSn/yHZfHmK9eSVWVTW6AwiE0igEn+pknXe55q/Ar4xUu/7MgjdKkOLGTCr4csM0RqEkHM=,iv:bBU2yXnYz7SLUiBRqZGDiHKfqrmKQm3GT0JqkCztN4E=,tag:+cYnXwa7LFDWv7JGLDVxUQ==,type:str]
    pgp:
    -   created_at: '2026-06-01T18:38:36Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAxOCS5f/QjlqcFS2FqVvsiavmEm30ErhnsqF/7I692icw
            7docNOgFkc0jbfhCVRMXRKZ0QlGifTNpPEKMpkVEk6PjrQRlveeimjOx+NUSUs0Z
            0lwBa88L7tNUpl+6ok06HxyvX/NSVjxMF6f5FE8wLb0rT25YDbQ9o5t/TE8v47o4
            Jr7G0GJblEgLacB7DyAvV8h6wAlrSnryHKndL4UoWe4Z/cA1bDGPAiXC010WCA==
            =Mlik
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
