---
logLevel: debug
logFormat: text

interval: 5s
sources: ["gateway-httproute"]
registry: txt
txtOwnerId: default
txtPrefix: k8s.
domainFilters: ["home.arpa"]
excludeDomains: []
policy: sync

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

provider:
  name: webhook
  webhook:
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop:
          - ALL
    image:
      repository: ghcr.io/mirceanton/external-dns-provider-mikrotik
      tag: v1.6.0
      pullPolicy: IfNotPresent
    env:
      - name: LOG_FORMAT
        value: json
      - name: LOG_LEVEL
        value: debug

      - name: MIKROTIK_DEFAULT_TTL
        value: "1800"
      - name: MIKROTIK_DEFAULT_COMMENT
        value: Managed by ExternalDNS

      - name: MIKROTIK_BASEURL
        valueFrom:
          secretKeyRef:
            name: mikrotik-credentials
            key: MIKROTIK_BASEURL
      - name: MIKROTIK_USERNAME
        valueFrom:
          secretKeyRef:
            name: mikrotik-credentials
            key: MIKROTIK_USERNAME
      - name: MIKROTIK_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mikrotik-credentials
            key: MIKROTIK_PASSWORD
    livenessProbe:
      httpGet:
        path: /healthz
        port: http-webhook
      initialDelaySeconds: 10
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /readyz
        port: http-webhook
      initialDelaySeconds: 10
      timeoutSeconds: 5

extraArgs:
  - --ignore-ingress-tls-spec
  - --managed-record-types=A
  - --managed-record-types=CNAME

tolerations:
  - key: "node.kubernetes.io/nuc"
    operator: "Exists"
    effect: "NoSchedule"
