# helm upgrade -i cilium cilium/cilium \
# --version 1.19.6 \
# --namespace cilium \
# --values cilium.values.yaml
#
# Do NOT enable bpf.masquerade with KubeSpan
operator:
  replicas: 1
  resources:
    requests:
      cpu: 10m
      memory: 64Mi

envoy:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi

resources:
  requests:
    cpu: 10m
    memory: 64Mi

ipam:
  mode: kubernetes

kubeProxyReplacement: true
k8sServiceHost: localhost
k8sServicePort: 7445

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_BIND_SERVICE
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

gatewayAPI:
  enabled: true
  externalTrafficPolicy: Local
  enableAlpn: true
  enableAppProtocol: true

hubble:
  enabled: true
  relay:
    enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
              - mercy
        - weight: 1
          preference:
            matchExpressions:
            - key: topology.kubernetes.io/region
              operator: In
              values:
              - metal
    tolerations:
      - key: "node.kubernetes.io/nuc"
        operator: "Exists"
        effect: "NoSchedule"
  ui:
    enabled: true
    backend:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 64Mi
    frontend:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 64Mi
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
              - mercy
        - weight: 1
          preference:
            matchExpressions:
            - key: topology.kubernetes.io/region
              operator: In
              values:
              - metal
    tolerations:
      - key: "node.kubernetes.io/nuc"
        operator: "Exists"
        effect: "NoSchedule"

bgpControlPlane:
  enabled: true

loadBalancer:
  l7:
    backend: envoy
routingMode: native
autoDirectNodeRoutes: true
ipv4NativeRoutingCIDR: 10.244.0.0/16
enableIPv4Masquerade: true

bpf:
  masquerade:  true
  lbModeAnnotation: true
  hostLegacyRouting: true
  disableExternalIPMitigation: true
  tproxy: true
  lbExternalClusterIP: true
bandwidthManager:
  enabled: true
  bbr: true
  bbrHostNamespaceOnly: true
