---
clusterName: talos
talosVersion: v1.13.6
kubernetesVersion: v1.36.2
endpoint: https://talos.${TALOS_DOMAIN}:6443
additionalApiServerCertSans:
  - talos.local
  - talos.${TALOS_DOMAIN}
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12
cniConfig:
  name: none
inlineManifests:
  - name: rps-ds-tuning
    contents: "@./patches/rps-ds-tuning.yaml"
    skipEnvsubst: true
patches:
  # - |-
  #   apiVersion: v1alpha1
  #   kind: TrustedRootsConfig
  #   name: custom-ca
  #   certificates: |
  #       -----BEGIN CERTIFICATE-----
  #       ${CA_CERT}
  #       -----END CERTIFICATE-----
  - "@./patches/cluster.yaml"
  - "@./patches/machine.yaml"
  - "@./patches/network.yaml"
  - "@./patches/firewall.yaml"
nodes:
  - controlPlane: true
    hostname: sombra
    installDisk: /dev/nvme0n1
    ipAddress: ${TALOS_SUBNET}.10
  - controlPlane: true
    hostname: lucio
    installDisk: /dev/nvme0n1
    ipAddress: ${TALOS_SUBNET}.20
  - controlPlane: true
    hostname: zarya
    installDisk: /dev/sda
    ipAddress: ${TALOS_SUBNET}.30

  - controlPlane: false
    hostname: mercy
    installDisk: /dev/sda
    ipAddress: ${TALOS_SUBNET}.40
    networkInterfaces:
      - interface: eno1
        dhcp: true
    nodeLabels:
      topology.kubernetes.io/region: "homelab"
      topology.kubernetes.io/zone: "metal"
    patches:
      - |-
          machine:
            kubelet:
              extraConfig:
                registerWithTaints:
                    - effect: NoSchedule
                      key: node.kubernetes.io/nuc
                      value: mercy
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
            - siderolabs/i915
            - siderolabs/gvisor
            - siderolabs/nfs-utils
            - siderolabs/nfsd
            - siderolabs/stargz-snapshotter

  - controlPlane: false
    hostname: winston
    installDiskSelector:
      wwid: naa.5f8db4c152400459
    ipAddress: ${TALOS_SUBNET}.50
    networkInterfaces:
      - interface: bond0
        dhcp: true
    nodeLabels:
      topology.kubernetes.io/region: "homelab"
      topology.kubernetes.io/zone: "metal"
    patches:
      - |-
          machine:
            kubelet:
              nodeIP:
                validSubnets:
                  - ${TALOS_SUBNET}.0/24
      - |-
          apiVersion: v1alpha1
          kind: BondConfig
          name: bond0
          links:
              - eth0
              - eth1
          bondMode: 802.3ad
          # Time in milliseconds between link checks
          miimon: 100
          # Time to wait before enabling a link after it comes up
          updelay: 200
          # Time to wait before disabling a link after it goes down
          downdelay: 200
          # addresses:
          #   - address: ${TALOS_SUBNET}.50/24
          # routes:
          #   - destination: "0.0.0.0/0"
          #     gateway: ${TALOS_SUBNET}.1
          xmitHashPolicy: "layer2+3"
    schematic:
      customization:
        extraKernelArgs:
          - net.ifnames=0
        systemExtensions:
          officialExtensions:
            - siderolabs/amd-ucode
            - siderolabs/gvisor
            - siderolabs/nfs-utils
            - siderolabs/nfsd
            - siderolabs/stargz-snapshotter

  - controlPlane: false
    hostname: worker-vm
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        dhcp: true
    ignoreHostname: true
    ipAddress: ${TALOS_SUBNET}.255
    machineSpec:
      mode: nocloud
      bootMethod: pxe
    nodeLabels:
      topology.kubernetes.io/region: "homelab"
      topology.kubernetes.io/zone: "vm"
    schematic:
      customization:
        extraKernelArgs:
          - net.ifnames=0
          - talos.config=http://tracer.home.arpa:8080/metadata?p=worker-vm
          - vlan=eth0.20:eth0
        systemExtensions:
          officialExtensions:
            - siderolabs/amd-ucode
            - siderolabs/gvisor
            - siderolabs/nfs-utils
            - siderolabs/nfsd
            - siderolabs/qemu-guest-agent
            - siderolabs/stargz-snapshotter
            - siderolabs/uhid
            - siderolabs/uinput
  - controlPlane: false
    hostname: worker-vm-gpu
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        dhcp: true
    ignoreHostname: true
    ipAddress: ${TALOS_SUBNET}.255
    machineSpec:
      mode: nocloud
      bootMethod: pxe
    nodeLabels:
      topology.kubernetes.io/region: "homelab"
      topology.kubernetes.io/zone: "vm"
      node.kubernetes.io/gpu: "nvidia"
    schematic:
      customization:
        extraKernelArgs:
          - net.ifnames=0
          - talos.config=http://tracer.home.arpa:8080/metadata?p=worker-vm-gpu
          - vlan=eth0.20:eth0
        systemExtensions:
          officialExtensions:
            - siderolabs/nvidia-container-toolkit-lts
            - siderolabs/nvidia-open-gpu-kernel-modules-lts
            - siderolabs/nonfree-kmod-nvidia-lts
            # - siderolabs/nvidia-container-toolkit-production
            # - siderolabs/nvidia-open-gpu-kernel-modules-production
            # - siderolabs/nonfree-kmod-nvidia-production
            - siderolabs/gvisor
            - siderolabs/nfs-utils
            - siderolabs/nfsd
            - siderolabs/qemu-guest-agent
            - siderolabs/stargz-snapshotter
            - siderolabs/uhid
            - siderolabs/uinput

controlPlane:
  kernelModules:
    - name: br_netfilter
      parameters:
        - nf_conntrack_max=131072
  networkInterfaces:
    - interface: eno1
      dhcp: true
  nodeLabels:
    node.kubernetes.io/exclude-from-external-load-balancers: ""
  patches:
    - |-
        cluster:
          etcd:
            extraArgs:
              listen-metrics-urls: http://0.0.0.0:2381
  schematic:
    customization:
      extraKernelArgs:
        - net.ifnames=0
        - talos.config=http://tracer.home.arpa:8080/metadata?h=$${hostname}&m=$${mac}&s=$${serial}&u=$${uuid}
      systemExtensions:
        officialExtensions:
          - siderolabs/intel-ucode
          - siderolabs/gvisor
          - siderolabs/stargz-snapshotter

worker:
  kernelModules:
    - name: br_netfilter
      parameters:
        - nf_conntrack_max=131072
  patches:
    - |-
      machine:
        nodeLabels:
          bgp-policy: active
  schematic:
    customization:
      extraKernelArgs:
        - net.ifnames=0
        - talos.config=http://tracer.home.arpa:8080/metadata?h=$${hostname}&m=$${mac}&s=$${serial}&u=$${uuid}
