---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-secrets
spec:
  schedule: "0 5 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          serviceAccountName: backup
          containers:
            - name: backup-secrets
              image: public.ecr.aws/bitnami/kubectl:1.36.1
              command:
              - /usr/bin/backup.sh
              resources:
                requests:
                  cpu: 10m
                  memory: 64Mi
                limits:
                  cpu: 1000m
                  memory: 256Mi
              volumeMounts:
                - name: tmp
                  mountPath: /tmp
                - name: scripts
                  mountPath: /usr/bin/backup.sh
                  subPath: backup.sh
                - name: shared
                  mountPath: /backup
          volumes:
            - name: tmp
              emptyDir: {}
            - name: scripts
              configMap:
                  name: scripts
                  defaultMode: 0755
            - name: shared
              nfs:
                server: genji.home.arpa
                path: /shared
