machine:
  install:
    disk: /dev/sda
  nodeLabels:
    topology.kubernetes.io/region: "homelab"
    topology.kubernetes.io/zone: "vm"
    node.kubernetes.io/gpu: "nvidia"
---
apiVersion: v1alpha1
kind: DHCPv4Config
name: eth0
