---
- name: Harden Raspberry Pi for PXE Boot Server
  hosts: tracer
  become: yes
  pre_tasks:
    - name: Update packages
      apt:
        autoclean: yes
        autoremove: yes
        update_cache: yes
        upgrade: yes
      become: yes
      tags:
        - packages
        - pre
  roles:
    - role: raspi-hardening
      become: yes
      tags:
        - ram
    - role: containerd-setup
      tags:
        - containerd
    - role: talos-pxe
      tags:
        - containerd
        - talos

  handlers:
    - name: Restart systemd-journald
      systemd:
        name: systemd-journald
        state: restarted
        daemon-reload: yes