---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacebar
spec:
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: spacebar
  template:
    metadata:
      labels:
        app: spacebar
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: spacebar
          image: ghcr.io/spacebarchat/server:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          env:
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: spacebar
                  key: postgres-url
            - name: CONFIG_PATH
              value: /config/config.json
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: http
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 10m
              memory: 10Mi
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
              # mountPath: /config/config.json
              # subPath: config.json
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: config
          emptyDir: {}
          # configMap:
          #   name: config
