apiVersion: v1
stringData:
    postgres-url: ENC[AES256_GCM,data:KEx2VR+Ar4Pbjw8A43zoo30aQmghL7NYmH/8ipQDu00FObFZmWvX7oZhiberXpNOuhR17YsdOtoJLr80P97Bon1zHJmniBJ3UKRvY2Tgzkg=,iv:rn3OIke6+lAEpJtCrHJ/vD0AnvOsxWhiQaC9lEVoWzE=,tag:UvNTvjA8zCtywQ5HQdGMQA==,type:str]
kind: Secret
metadata:
    name: spacebar
    namespace: spacebar
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-23T17:25:50Z'
    mac: ENC[AES256_GCM,data:A5TV4f/V1oWPdf9LYS/Ld17nduAqlhrEkpA2wRylutETUjYa9+0Clb7UVi+Wm5RSTS50i8LnPBY473pRtB8eJNRL8TOkWBhvyZAmxNF8Z6M5AKmwt0L415mpz9KrITtJrcidwnaJ6gobtirQ6YeAunImAjLUGout+daM3dEqG7U=,iv:UdRFL+f9A5YBwrMlTJbN+zSh/czap7sGRO+nWWMx/4c=,tag:SvR5NckhYtoZCNDpnTb0Zw==,type:str]
    pgp:
    -   created_at: '2026-09-23T17:25:49Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAesM0CEoSXGQX72XMByY62gVxc4IhviX27ueiKdFjdS0w
            tbGDr1nNUzzeK4G0VqhSPVF+Cm++1BFN/eF5GMEXy2AUkgXFwIwLHcUpSKQ8uKxY
            0l4BtGlWoykBxEouXoV9lv0UY53fXU8xvRARhgRWKEFoYbxm1wnU7O1PEw9PhHwL
            aOUYbh/5eBSQBilAsKTTU39arBRGgyoqFVLsEwHyW3xrdKifIaFhOOf4/od8NAX8
            =4s71
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
