apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: enable-psa
spec:
  deploymentTemplate:
    spec:
      revisionHistoryLimit: 0
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                capabilities:
                  drop:
                    - ALL
              env:
                - name: PROXMOX_VE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: crossplane-credentials
                      key: username
                - name: PROXMOX_VE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: crossplane-credentials
                      key: password
              resources:
                requests:
                  cpu: 10m
                  memory: 64Mi
                limits:
                  cpu: 1000m
                  memory: 512Mi
              volumeMounts:
                - mountPath: /etc/ssl/certs/ca-certs.pem
                  subPath: ca-certs.pem
                  name: tls
                - mountPath: /tmp
                  name: temp
                - mountPath: /tofu
                  name: work
          volumes:
            - name: tls
              configMap:
                name: homelab-ca
                defaultMode: 0644
            - name: temp
              emptyDir:
                medium: Memory
            - name: work
              emptyDir:
                medium: Memory
          tolerations:
            - effect: NoSchedule
              key: node.kubernetes.io/nuc
              operator: Exists
