apiVersion: v1
data:
    username: cm9vdEBwYW0=
    password: c2hva29uZXI=
kind: Secret
metadata:
    name: root-credentials
type: Opaque
---
apiVersion: v1
data:
    username: Y3Jvc3NwbGFuZUBwdmU=
    password: Y3Jvc3NwbGFuZQ==
kind: Secret
metadata:
    name: crossplane-credentials
type: Opaque
---
apiVersion: v1
data:
    username: Y3NpLXByb3htb3hAcHZl
    password: Y3NpLXByb3htb3g=
kind: Secret
metadata:
    name: csi-proxmox-credentials
type: Opaque
---
apiVersion: v1
data:
    username: a2FycGVudGVyLXByb3htb3hAcHZl
    password: a2FycGVudGVyLXByb3htb3g=
kind: Secret
metadata:
    name: karpenter-proxmox-credentials
type: Opaque
