apiVersion: v1
data:
    username: ENC[AES256_GCM,data:qaCvUWRTBFgsoAXK,iv:/R8xqRIxopojH8VkstecmZlxLLp3SEC4QymU2OmAzVk=,tag:xBlA9elYXAUJRhpdX4xEOw==,type:str]
    password: ENC[AES256_GCM,data:HDqivyNNPr0ImYlh,iv:16guVWes8LbNkhXHEdL3EwaYDsuC6kgg3ouE5Vbk+/4=,tag:GaNX47Z676CB7NkPOIfKAg==,type:str]
kind: Secret
metadata:
    name: root-credentials
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-12T17:32:41Z'
    mac: ENC[AES256_GCM,data:A6KlBkekz1zQjgnbxZe4Pv0goe3hs1+8bu0zQ0/gWbAcG+ENmBBtsWySo2icmiIIp6Ta4/vGILiFW0bSdyJH9pZADwyhSdXEEFRnWbZ0mBHnoV7paQ/kVjYQ6tXvJfmRC2tK8TuEHYy+S4VGU5UPsBl/eQs+7O+MNaRjrYp+E8I=,iv:Lwi0CGcq20e4WYB76hQKi2gOaRLvAYHs9HPz0O9S9Xc=,tag:U350mlBHcL8+Qnzw2V1xnw==,type:str]
    pgp:
    -   created_at: '2026-07-12T17:32:40Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA5P8gEFquVASDJEJrxpyEXD5L23AXIUNPlK9rG/ENsQUw
            O6JMvV6XGMT3+e/9mRWZoICypzCrpFQ38UV//ALeUh+Fs2QSiWFfQHPncOit7AuW
            0l4B6bV9grZWB3IfYn13iGIQvfeJpC+BKrjvX+HMvymUNcjLVLHp+yLaOL5VBMJd
            dxb0B6D/FYSV80/4i5O+FwYk07FrZ9wGyDc1aoVxhEO165Rx4yBB7YcLns9eP8da
            =lo01
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:ISMGMUfNl1X41b9jZXdewj39APQ=,iv:zTAsxAmQUkOh6/5D31eFbwv0uB2JZAeEV85lcxMVM8Q=,tag:dPlF6PcY2k0/4XeKWp4lmQ==,type:str]
    password: ENC[AES256_GCM,data:4IlWjz/V79kaWqnmmO8KhQ==,iv:kevIgW+sTx8ofX3mtU5fWy9iFijTj0mwWQn8Oz3cbck=,tag:CFekSUThRAlXQ+w3HgdIkQ==,type:str]
kind: Secret
metadata:
    name: crossplane-credentials
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-12T17:32:41Z'
    mac: ENC[AES256_GCM,data:A6KlBkekz1zQjgnbxZe4Pv0goe3hs1+8bu0zQ0/gWbAcG+ENmBBtsWySo2icmiIIp6Ta4/vGILiFW0bSdyJH9pZADwyhSdXEEFRnWbZ0mBHnoV7paQ/kVjYQ6tXvJfmRC2tK8TuEHYy+S4VGU5UPsBl/eQs+7O+MNaRjrYp+E8I=,iv:Lwi0CGcq20e4WYB76hQKi2gOaRLvAYHs9HPz0O9S9Xc=,tag:U350mlBHcL8+Qnzw2V1xnw==,type:str]
    pgp:
    -   created_at: '2026-07-12T17:32:40Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA5P8gEFquVASDJEJrxpyEXD5L23AXIUNPlK9rG/ENsQUw
            O6JMvV6XGMT3+e/9mRWZoICypzCrpFQ38UV//ALeUh+Fs2QSiWFfQHPncOit7AuW
            0l4B6bV9grZWB3IfYn13iGIQvfeJpC+BKrjvX+HMvymUNcjLVLHp+yLaOL5VBMJd
            dxb0B6D/FYSV80/4i5O+FwYk07FrZ9wGyDc1aoVxhEO165Rx4yBB7YcLns9eP8da
            =lo01
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
