---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syslog
  annotations:
    configmap.reloader.stakater.com/reload: "config"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: syslog
  template:
    metadata:
      labels:
        app.kubernetes.io/name: syslog
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: syslog
          image: balabit/syslog-ng:4.11.0
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          args:
            - --no-caps
          ports:
            - name: syslog
              containerPort: 8601
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/syslog-ng/syslog-ng.conf
              subPath: syslog-ng.conf
          startupProbe:
            tcpSocket:
              port: syslog
          livenessProbe:
            tcpSocket:
              port: syslog
          readinessProbe:
            tcpSocket:
              port: syslog
          resources:
            limits:
              cpu: 100m
              memory: 64M
            requests:
              cpu: 10m
              memory: 64M
      volumes:
        - name: config
          configMap:
            name: config
            defaultMode: 0644
      tolerations:
        - key: "node.kubernetes.io/nuc"
          operator: "Exists"
          effect: "NoSchedule"
