---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
spec:
  interval: ${interval}
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  interval: ${interval}
  chart:
    spec:
      chart: alloy
      version: 1.12.1
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    controller:
      type: daemonset
      volumes:
        extra:
          - name: temp
            emptyDir: {}
      tolerations:
        - key: "node.kubernetes.io/nuc"
          operator: "Exists"
          effect: "NoSchedule"
    mounts:
      varlog: true
      dockercontainers: false
    global:
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
    alloy:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
      configMap:
        content: |
          discovery.kubernetes "kubernetes_pods" {
            role = "pod"

            selectors {
              role  = "pod"
              field = "spec.nodeName=" + coalesce(sys.env("HOSTNAME"), constants.hostname)
            }
          }

          loki.process "kubernetes_pods" {
            forward_to = [loki.write.default.receiver]

            stage.cri { }

            stage.docker { }

            # stage.match {
            #   selector = "{app=\"eventrouter\"}"

            #   stage.json {
            #     expressions = {
            #       event_kind             = "event.involvedObject.kind",
            #       event_name             = "event.metadata.name",
            #       event_namespace        = "event.involvedObject.namespace",
            #       event_reason           = "event.reason",
            #       event_source_component = "event.source.component",
            #       event_source_host      = "event.source.host",
            #       event_type             = "event.type",
            #       event_verb             = "verb",
            #     }
            #   }

            #   stage.labels {
            #     values = {
            #       event_kind             = null,
            #       event_name             = null,
            #       event_namespace        = null,
            #       event_reason           = null,
            #       event_source_component = null,
            #       event_source_host      = null,
            #       event_type             = null,
            #       event_verb             = null,
            #     }
            #   }
            # }
          }

          discovery.relabel "kubernetes_pods" {
            targets = discovery.kubernetes.kubernetes_pods.targets

            rule {
              source_labels = ["__meta_kubernetes_pod_controller_name"]
              regex         = "([0-9a-z-.]+?)(-[0-9a-f]{8,10})?"
              target_label  = "__tmp_controller_name"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name", "__meta_kubernetes_pod_label_app", "__tmp_controller_name", "__meta_kubernetes_pod_name"]
              regex         = "^;*([^;]+)(;.*)?$"
              target_label  = "app"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_instance", "__meta_kubernetes_pod_label_instance"]
              regex         = "^;*([^;]+)(;.*)?$"
              target_label  = "instance"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_component", "__meta_kubernetes_pod_label_component"]
              regex         = "^;*([^;]+)(;.*)?$"
              target_label  = "component"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_node_name"]
              target_label  = "node_name"
            }

            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              target_label  = "namespace"
            }

            rule {
              source_labels = ["namespace", "app"]
              separator     = "/"
              target_label  = "job"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_name"]
              target_label  = "pod"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_container_name"]
              target_label  = "container"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
              separator     = "/"
              target_label  = "__path__"
              replacement   = "/var/log/pods/*$1/*.log"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash", "__meta_kubernetes_pod_annotation_kubernetes_io_config_hash", "__meta_kubernetes_pod_container_name"]
              separator     = "/"
              regex         = "true/(.*)"
              target_label  = "__path__"
              replacement   = "/var/log/pods/*$1/*.log"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_container_image"]
              target_label  = "image"
            }
          }

          loki.source.file "kubernetes_pods" {
            targets    = discovery.relabel.kubernetes_pods.output
            forward_to = [loki.process.kubernetes_pods.receiver]

            file_match {
              enabled = true
            }
            legacy_positions_file = "/run/promtail/positions.yaml"
          }

          loki.write "default" {
            endpoint {
              url = "http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push"
            }
            external_labels = {}
          }

      mounts:
        extra:
          - name: temp
            mountPath: /tmp
      resources:
        requests:
          cpu: 100m
          memory: 64M
        limits:
          cpu: 1000m
          memory: 128M
    configReloader:
      resources:
        requests:
          cpu: 10m
          memory: 64M
        limits:
          cpu: 100m
          memory: 64M
