---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux
spec:
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: miniflux
  template:
    metadata:
      labels:
        app: miniflux
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: miniflux
          image: miniflux/miniflux:2.3.3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          env:
            - name: RUN_MIGRATIONS
              value: "1"
            - name: CREATE_ADMIN
              value: "1"
            - name: ADMIN_USERNAME
              value: miniflux
            - name: ADMIN_PASSWORD
              value: miniflux
            - name: "DATABASE_URL"
              valueFrom:
                secretKeyRef:
                    name: miniflux
                    key: postgresql-database-url
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          startupProbe:
            initialDelaySeconds: 180
            tcpSocket:
              port: http
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              memory: 2048Mi
            requests:
              cpu: 100m
