apiVersion: v1
data:
    postgresql-database-url: ENC[AES256_GCM,data:mcAZj1KVIZgYqEaskFjCYgvTwKyuaDlHcaTf6QZQaPGuJzd7XLHz48zEFmqeMNhSdf2omwmOPaWIFhdEWSEMZyy8yGu0v100Ohngn6OY8MqBkLoDZIpgfLjjhjncpjXwc+UZm/Z8bU7yMvhZ,iv:02T/Qq9zrp+uITbm84/JqsX++/CwhqyqSzrWSxGlr+s=,tag:zJBOaNBcRyePueLYJJ/YRw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: miniflux
    namespace: miniflux
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-14T08:49:43Z'
    mac: ENC[AES256_GCM,data:3cZb+xphD0xqDmBR/R0ww6sdkPKYZjoJ3Gb7/T18e0Qj9ObmBfTnsiGHO1zwSw7ZOmeMm4s9vL0r9DXhF3sbYTP0xUEHbtyDUhnIYMBl+FxC61GCy54eMOW0sfkpT8+Jf584+x9SfT2Fxr6sKn47AUtlBIDerXlpVyD7Vag6Tq0=,iv:6QjE8mTciw2OupM9zKJ2Ff6MZMx11a4qaS4QsSJa3x8=,tag:aCG+1+GoVUq6jqmurSuW+w==,type:str]
    pgp:
    -   created_at: '2026-09-14T08:49:43Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAXk+fhVpWiyVhzdJFFxNWrw3RAkmuqHoCpu423Z6I928w
            l8U4LKW5rRf1K8bY55PM1IbDteNwQxy0RNRmYkxWnbvxHVVFx122JTxrL4UBZpFp
            0l4BVoCxvzm0oBSvIdhNbaE1zCTvyGVASfdozvGadd8b3ousS5veTF2XprE2HMiC
            sqJKA6P+Zr52dWdPNwjEqYaq5Pao1ojRckv+F38634HdloMUI4r3H+OReGhXKzdT
            =Ka+T
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
