---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftpgo
spec:
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sftpgo
  template:
    metadata:
      labels:
        app: sftpgo
        nfs-genji: "true"
        nfs-hanzo: "true"
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: sftpgo
          image: ghcr.io/drakkan/sftpgo:v2.7.5-distroless-slim
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          envFrom:
            - secretRef:
                name: variables
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: ssh
              containerPort: 2022
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/sftpgo/host-keys
              name: temp
            # - mountPath: /etc/sftpgo/host-keys/ssh_host_ed25519_key
            #   name: config
            #   subPath: ssh_host_ed25519_key
            - mountPath: /var/lib/sftpgo/nfs/nfs-genji
              name: nfs-genji
            - mountPath: /var/lib/sftpgo/nfs/nfs-hanzo
              name: nfs-hanzo
            - mountPath: /var/lib/sftpgo/nfs/downloads
              name: nfs-downloads
          startupProbe:
            tcpSocket:
              port: ssh
          livenessProbe:
            tcpSocket:
              port: ssh
          readinessProbe:
            tcpSocket:
              port: ssh
          resources:
            limits:
              cpu: 1000m
              memory: 1024M
            requests:
              cpu: 100m
              memory: 64M
      volumes:
        - name: temp
          emptyDir:
            medium: Memory
        - name: config
          secret:
            secretName: config
        - name: nfs-genji
          nfs:
            path: /
            server: genji.home.arpa
        - name: nfs-hanzo
          nfs:
            path: /
            server: hanzo.home.arpa
        - name: nfs-downloads
          nfs:
            path: /
            server: nfs-downloads.nfs-downloads.svc.cluster.local
