apiVersion: v1
stringData:
    ssh_host_ed25519_key: ENC[AES256_GCM,data:ZhMyJ0/R+O1zHGAivOf6U28FKz+RJJX7lsy5mgsP3rNdf9P+LsH2AEOZBZjELTUKOEoEcX2SEymvepPYIR542fgrFduI/j076L24vJ8I5rktJYf8paDYHv2Sx4qYWRL05Q0A6urUmEDBSLfgmL1pL2y6A02w4ye7WbEOF2OOI2tYB5fJ6WbnQzNqfXtbQveCQ9hcWFc7hn6tiohwZIldp1JwGzNhpKUxIjI3nHsvYcEMT1lqUVAlDMaflBEpz3LYVj/ILBr9buLOV+k2j/XY6TWhnQCsSdRParv5O4GOzxi2TohMvH8Q4x68qj5pNLGPb/8MnxGoo74uqPjMBQ9yltMn9bta0GG61w0gZJpPPmEWj3zw4rfe4V/zVR4BWNXC7TT1Y35Sme5kxUzRZZM9krm+N4cbLK0cFYyGzLTNN6RSwmCGIAnI3+mH54hwAxgtkE8/XgksQAMkudZx2Wtd+KCdUTVL7p+EwiP0EwvoeF9GBFJN0vYkHzwBq2fDfIE7wZjtKhtpIM+jT79SBob7l04s+zamZ51hCJy46cJWOndzDVM=,iv:49UnHj1RangfdhSO3MY6Cna5nQ+oijTvdsDy8VxuSHw=,tag:jQxiyPoHHi/Ss+i961FsEw==,type:str]
kind: Secret
metadata:
    name: config
    namespace: sftpgo
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-06T22:32:46Z'
    mac: ENC[AES256_GCM,data:4QzU0H70YnNq+jzCt+e54XgSa/us7d3F/y0qFXzw0+sKG6vvUvztLFXD4+VJeJp6CoJn0lfbm1KdK36MdV9YeFo6kZiyFp/tQ+n0Uzzv3/BK7tSK3F/3xzrnKeL1P4ulth4AsjIm7urFnV3yCga0mVx9WeH5SVsQ7NrSYGFy2Pc=,iv:5QP7jjtzef0MMkaIjDJzg/CmSWndNxpeESFztYGbZow=,tag:2eUin+hEfX9NrOeJrgyV8Q==,type:str]
    pgp:
    -   created_at: '2026-09-06T22:32:46Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdApQ3i95FNHEW83OMfbFv0PUp8cz8LvSP8UtUGX751g2ww
            v5QnJ6A2rFYkxumDCwc5cI7/GpFQEb1RvGApIBjfIo0yEw28yXt5FTqwLo1yetn2
            0l4BrTgN9ZSLSgjEeFCEVgTr8WJZY2ZVkoNKRpEzXZcobfJlLWS0DpVAM8OKDyPE
            WoELUfmpJky4EAFxRwo2mOt4x0FY96qTpf170qJxoJ1SYfVnToScUNCJXm+WPIly
            =2tei
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
stringData:
    SFTPGO_DATA_PROVIDER__DRIVER: ENC[AES256_GCM,data:QTlMST+2tl106A==,iv:F6TTsdCSgYFTzTu7x0vGScuo8XTbS74exJLG6B7SD2s=,tag:3Ct489GtWhxeFtN6W/TeQQ==,type:str]
    SFTPGO_DATA_PROVIDER__NAME: ENC[AES256_GCM,data:X4Ma3dg5,iv:JLd90ra57nS05qgPKAk4BPbD82iwmhcXsRqyGVKkYW0=,tag:Z9UDk3Qn3iRzKMHmMMd81w==,type:str]
    SFTPGO_DATA_PROVIDER__HOST: ENC[AES256_GCM,data:YoMnIE5Ltn+EFk1CCKt9sfab9Q==,iv:GztJ15tQFyB+jXyS8hox3LxSYEOhRQqWuvx0aC2p7W4=,tag:iAmt1xy6KbtO+fwmNH9dag==,type:str]
    SFTPGO_DATA_PROVIDER__PORT: ENC[AES256_GCM,data:uysd6g==,iv:hA7gmUFhSuCMrFQJeic64TZMzSB4Rew/wLLwhBohY+I=,tag:3r76MbYS3jOFprIT9u5+vA==,type:str]
kind: Secret
metadata:
    name: variables
    namespace: sftpgo
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-06T22:32:46Z'
    mac: ENC[AES256_GCM,data:4QzU0H70YnNq+jzCt+e54XgSa/us7d3F/y0qFXzw0+sKG6vvUvztLFXD4+VJeJp6CoJn0lfbm1KdK36MdV9YeFo6kZiyFp/tQ+n0Uzzv3/BK7tSK3F/3xzrnKeL1P4ulth4AsjIm7urFnV3yCga0mVx9WeH5SVsQ7NrSYGFy2Pc=,iv:5QP7jjtzef0MMkaIjDJzg/CmSWndNxpeESFztYGbZow=,tag:2eUin+hEfX9NrOeJrgyV8Q==,type:str]
    pgp:
    -   created_at: '2026-09-06T22:32:46Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdApQ3i95FNHEW83OMfbFv0PUp8cz8LvSP8UtUGX751g2ww
            v5QnJ6A2rFYkxumDCwc5cI7/GpFQEb1RvGApIBjfIo0yEw28yXt5FTqwLo1yetn2
            0l4BrTgN9ZSLSgjEeFCEVgTr8WJZY2ZVkoNKRpEzXZcobfJlLWS0DpVAM8OKDyPE
            WoELUfmpJky4EAFxRwo2mOt4x0FY96qTpf170qJxoJ1SYfVnToScUNCJXm+WPIly
            =2tei
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
