apiVersion: v1
stringData:
    ssh_host_ed25519_key: ENC[AES256_GCM,data:rV0hJGymQ7qKo//lUSp97r8Di93k6bft0aN8k5kjDOieeBm1LqbtSqomGUOAzWGpo5Y3HsjXSsxXRl5BMwvO35NqRTrCMEv9GufJdtfIT1uL4kWJPZkiLh0Y5sSsiiVCjvkR//cNpE8lygTkNOkrf77/F9UMgP3NmL7s2P5C0YcNhOPmZYnyY05hGf9ZhbGlD36fFY9zlptmq0rlFhXJOlw7F52LxEoePBDcWq2pKiw+PzA0XoE5b2HdHcuC5Ro+K8kD4QIkf3m6zHjS2q5+SeInrgNeRDVit7ZmXtEtAnwTjyk/AgcREF6UsR6DNV/Hu7xsb4gzDKhWkIIU/S6hB+8vEqjx5m5+aUfcNV6morSHFYq41Gj0pg+3C8rPUPmSOGehSWS7/0iFb1bmVntBP1znQexnxaOEncU/8YMQ3K2hq+rxKwSFSL3/I4bHnlUonagRXl28Pd+00F6QDi9npWLFLaNQ0fhY8MATCjwBR5pffruJVNAe1q4K/zew6bm1KhQXzGk3KWogxZ52Ttuq/oeTB2oRpuLm9JHlG6MOLIJU5eg=,iv:0bK4ua919QBUqzrrYTaE7ZLV5F5/Hn7ZYOssT9EH5sE=,tag:6QOk9BaCvuNmsz0xHjqv5A==,type:str]
kind: Secret
metadata:
    name: config
    namespace: sftpgo
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-06T22:46:28Z'
    mac: ENC[AES256_GCM,data:jGWRg59yF4LU1RpEP7t6jWt/8lOOulhOJDo1xwTIZDr69i12ZGzWHYzXmBOno4PljHKG3N7ka6VjodckgabHfpo6Dd/nOTk/kGnC0Fhl0wzb6NjQub3vpFBdgxis0h3l12AnYawBbdbGBzSDb/vPJRNBqI0IwZe05bWUeQjpYJk=,iv:nRWk0sX0vIL35MacGki9pfSyoG73LbdwwoXppifaito=,tag:BxKR5b00UUSOaIAGyLqR1g==,type:str]
    pgp:
    -   created_at: '2026-09-06T22:46:27Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAYpGQCnOmxfvzQ58XFu5rgJuuaZobt6BhiZxgNfS8VzUw
            BhuftfY4Nq4rRSjQ6SNmmXx/dDmmW4lF4XLnmnA+gDIgU1/vd0OdF0ihQ7O9t4Gl
            0l4B1e33bEgK7rr3dwiYq4IVR1CrdrvsKWegPR/jAoxe26mAnPl9/orHjipOGy1K
            ctER1hn02ft0o9f+3aeiN53+magRF4MWIDDQ047Aed58alW0rVtv/erDWJr/4o9+
            =F0ib
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
stringData:
    SFTPGO_DATA_PROVIDER__DRIVER: ENC[AES256_GCM,data:nKbfTUdtyfNliw==,iv:ZjV8TGSgEYqfWB43hOeEx401zy4CKTVvIuqYNkUE2yA=,tag:ui/Ey7xr8JlAw1Rda6Ihvg==,type:str]
    SFTPGO_DATA_PROVIDER__NAME: ENC[AES256_GCM,data:Pr9zpwvA,iv:lKsVrA9+sMIicLGMl7cn5AIvcpL52jOMnLAGiYsldsQ=,tag:OGYDB3ZFV9NSf2sy/Z3b7w==,type:str]
    SFTPGO_DATA_PROVIDER__HOST: ENC[AES256_GCM,data:BudsbiJyUc1HkvJ+tM2ZnyDowA==,iv:pUJFbM7hSaEmvj6gaSxQ1eJXVTR1iPQuhNAYVeQmAqk=,tag:YQr6hX1xmEzc4JSkN81RUg==,type:str]
    SFTPGO_DATA_PROVIDER__PORT: ENC[AES256_GCM,data:Ao1yKA==,iv:yON59otVtWwzD4M/vdtd74altFZ7eQ60T2SWaHE4ZyI=,tag:HANQP8SnVrO5znkH9PvZaw==,type:str]
    SFTPGO_DATA_PROVIDER__USERNAME: ENC[AES256_GCM,data:J6NzWsqm,iv:kfsRVhZ6nv24P0/mZlqNOauAyIss+VI0B/728j1S248=,tag:XyG5Q/S0IQCaCT1775hEKA==,type:str]
    SFTPGO_DATA_PROVIDER__PASSWORD: ENC[AES256_GCM,data:/Sp7BR0I,iv:K+UVKCr7R5/d0gGU4wkrSqN8UdLj2JWmy/duCguY+ro=,tag:B6a98ur/onn3fDgsbp4sXw==,type:str]
kind: Secret
metadata:
    name: variables
    namespace: sftpgo
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-06T22:46:28Z'
    mac: ENC[AES256_GCM,data:jGWRg59yF4LU1RpEP7t6jWt/8lOOulhOJDo1xwTIZDr69i12ZGzWHYzXmBOno4PljHKG3N7ka6VjodckgabHfpo6Dd/nOTk/kGnC0Fhl0wzb6NjQub3vpFBdgxis0h3l12AnYawBbdbGBzSDb/vPJRNBqI0IwZe05bWUeQjpYJk=,iv:nRWk0sX0vIL35MacGki9pfSyoG73LbdwwoXppifaito=,tag:BxKR5b00UUSOaIAGyLqR1g==,type:str]
    pgp:
    -   created_at: '2026-09-06T22:46:27Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAYpGQCnOmxfvzQ58XFu5rgJuuaZobt6BhiZxgNfS8VzUw
            BhuftfY4Nq4rRSjQ6SNmmXx/dDmmW4lF4XLnmnA+gDIgU1/vd0OdF0ihQ7O9t4Gl
            0l4B1e33bEgK7rr3dwiYq4IVR1CrdrvsKWegPR/jAoxe26mAnPl9/orHjipOGy1K
            ctER1hn02ft0o9f+3aeiN53+magRF4MWIDDQ047Aed58alW0rVtv/erDWJr/4o9+
            =F0ib
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
