apiVersion: platform.shokohsc.com/v1alpha1
kind: ProxmoxRole
metadata:
  name: csi-proxmox
spec:
  role: csi-proxmox
  privileges:
    - VM.Audit
    - VM.Allocate
    - VM.Clone
    - VM.Config.CPU
    - VM.Config.Disk
    - VM.Config.HWType
    - VM.Config.Memory
    - VM.Config.Options
    - VM.Migrate
    - VM.PowerMgmt
    - Datastore.Allocate
    - Datastore.AllocateSpace
    - Datastore.Audit
---
apiVersion: platform.shokohsc.com/v1alpha1
kind: ProxmoxGroup
metadata:
  name: csi-proxmox
spec:
  group: csi-proxmox
  roles:
    - csi-proxmox
---
apiVersion: platform.shokohsc.com/v1alpha1
kind: ProxmoxUser
metadata:
  name: csi-proxmox
spec:
  user: csi-proxmox@pve
  passwordSecretRef:
    namespace: crossplane-system
    name: csi-proxmox-credentials
    key: password
  groups:
    - csi-proxmox
  aclPath: /
