---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: vpn
  annotations:
    configmap.reloader.stakater.com/reload: common-env,config
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: vpn
  template:
    metadata:
      labels:
        app: vpn
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "3030"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: vpn
          image: shokohsc/moleculer-sidekick
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          envFrom:
            - configMapRef:
                name: common-env
          env:
            - name: SERVICES
              value: vpn
            - name: ADAPTER_URL
              valueFrom:
                secretKeyRef:
                  name: sidekick
                  key: adapter-url
            - name: IPINFO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vpn
                  key: ipinfo-token
            # - name: VPN_PROVIDER_MODE
            #   value: 'fallback'
            - name: BROWSERLESS_TOKEN
              value: EeJ4Ou3waagh7goMohsah6sooTeehoom
            - name: BROWSERLESS_HOST
              value: browserless.browserless
            - name: BROWSERLESS_PORT
              value: "80"
          ports:
            - name: metrics
              containerPort: 3030
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: metrics
          livenessProbe:
            tcpSocket:
              port: metrics
          readinessProbe:
            httpGet:
              port: metrics
              path: /metrics
          resources:
            requests:
              cpu: 10m
              memory: 64M
            limits:
              cpu: 1000m
              memory: 128M
      tolerations:
        - key: "node.kubernetes.io/nuc"
          operator: "Exists"
          effect: "NoSchedule"
