apiVersion: v1
kind: Secret
metadata:
  name: vpn
  namespace: sidekick
data:
  ipinfo-token: ENC[AES256_GCM,data:HPZFlVcLm94GlcPbAc+feeAGOvQ=,iv:jUJrLwZoTjv5NwYS+MjZEWywNI+pxCzFHiYSIl80DVU=,tag:kItRBPbXq+rCsSpvm9kfww==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  lastmodified: "2026-06-08T16:17:00Z"
  mac: ENC[AES256_GCM,data:pEBEwVVjc6XWh2s29C4tA1SW/jYKoUaokF7xxr0z+fT1ukxoZ4lpVYl21epDmEnIr+dnnAMEaW/FobvPgCs4b5vXYVwSp7TBvNLViwzsghWpKD+0jSrp/Aikud7LLScdgT4Z70lWCveY3okaCqHzaES0ag5vfFYMRf3K2Mv1i1I=,iv:5a+X+ykqw633QbKk9emnCDM7z51GCfdK9n8CAoNr/hQ=,tag:9zslxidehR7Y7ybyPrl7MA==,type:str]
  pgp:
    - created_at: "2026-06-08T16:16:59Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hF4DFjJ7f9c9iWkSAQdAhZ4WXSfAWA9zp8pWb6WR8OQwzSuFdVZDAqgbgyEu+Bww
        7OEos42dG6AW6cnV+Q9YvO6I0NjRX3nDRR46tX6YT0Ijdip0jV/VHXoO7ZFK8vj+
        0l4BQ3MO2JHWdtJBL1hUEa/eIHPCubNZvmwRIf7V27AwsuVEuJ216T7y+O3a3Bk6
        8Dm9QD3f6eaSI8e8GrqpsLIPpqxDtUylaxIEVmz32VUjROptWr1mr1WBipCOQU0d
        =Eftv
        -----END PGP MESSAGE-----
      fp: CA2DD399363326254636047B16327B7FD73D8969
  encrypted_regex: ^(data|stringData)$
  version: 3.5.0
