apiVersion: v1
data:
    ipinfo-token: ENC[AES256_GCM,data:kXBMU3E6/Qp+JM/PtPGg/MX35bU=,iv:9TFAtSKCi8t3/wkJTl9WnfnGJaACAJujrZsPDgDAzO8=,tag:2akTzG6GUAi5A3WuTxfBTQ==,type:str]
    postgresql-url: ENC[AES256_GCM,data:ZV4gg7T0G9Z2ZdV1e+mIYtQBsWZ+qdf31msKAniGPsvQA4ZWh93fSJfq2ORUbBsN361d5Z5cLtmW0CMS/SReI6Wo+9XXKXIPKxpZYnylU0Tu9gxd,iv:isGMiLKHfzYv+Y2VPlrjOqE5F6R85r2sfP7sweB2R8M=,tag:ksUztM5tYgElM8H64+DPPg==,type:str]
kind: Secret
metadata:
    name: vpn
    namespace: sidekick
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-14T08:54:28Z'
    mac: ENC[AES256_GCM,data:RBmG8FRoAIOH6GitfOKvTu+N4eQAxEz8XMjle8lBMPK69zUpwsMvq5BYfn78P6yzeK4Z9R7v6iDJBFbNXm8M3lc8TbUF3ktyKOHHY5NaPibwuJ0Sp6mWKE9kXzE4Rs4HvvWIXTISaWVhgq/+n6xoO1GVCRC3+dnFehQsjFN8w3k=,iv:F5Fv9ggLGKB6eMndjWnRQMf74SUkGmEq6fEde9tyu4E=,tag:B+eelD7qokqGvlpy4YxRrw==,type:str]
    pgp:
    -   created_at: '2026-09-14T08:54:27Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA+WnLjkmmXypJp1X/NRq1SnWp64TyZPMZDRvVDAcASg4w
            5eUCueTz3K/LyfdzUMpc1uzOKYSFLWSI9+6BnxxS9eHZWiwZBsusSCSmBmWGMkae
            0l4BYHPI/N8CMyoahSMbu2VVBhOEEv4gTfa1spP2CnlyCi/4pxsuXeC8lqKAXNyI
            gu2bYOpjf4fcmyxYl6wQTcm56DBc3UeCLZDS31h1eb0BzLgcwzfyPbU0t1Zcsjfl
            =Clal
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
