apiVersion: v1
data:
    ipinfo-token: ENC[AES256_GCM,data:sUwssEyYFzlCNdC0hbLvNJayMuo=,iv:KLwN+T6AAwhX99UgQmZPs+rEmmvJR1K/HBXe6KVUEnk=,tag:dsHUy4NC78TYtKD0xLPmdA==,type:str]
kind: Secret
metadata:
    name: vpn
    namespace: sidekick
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2025-02-14T00:45:24Z'
    mac: ENC[AES256_GCM,data:0uGk6ud9ut/jglEjsU4saxRy6rYYuWtn9bSIMsdkeQUfFpj3c312n6lDwAA7h5NGe/XM73oOO/a+eJjW9w0jx8y/S+SLHhHsoFEU2q7tB1e3R7bY1ItgzHrntDOtuXYzzI+L1/UbPLkDZMsJ565GINx6/vb7fFelPZwSBhp2vLs=,iv:UX8b+RPo/T30eozii5Ku6bBZUWKB16esP10EmVp2zE4=,tag:70UE+65rJu4IealhupDDXQ==,type:str]
    pgp:
    -   created_at: '2025-02-14T00:45:23Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxv5FnUBLaS9AQ/+KORTEaxwR9pmIiNTVfNn2jiizOy956M2iLbq38ImokQe
            2gUGo43kXEEXztCxDJjg5G8uJbRZ/RcIMVjCvOXvdc5iO4Y1epHtoGwRRtHyabWV
            Xp+VQwr+u58xTa4Pi8ANiFImVMVxEMqNkGhFmEVOwWpk5JJKOzkwLSnehDt87oSS
            5orenBegz8LO343kDtCP7Ni6b6NfXlWMp4f2smDzWAkhLleDKSXNmysE6xCQfL3N
            SqwOI1PAY4m/0MeSklOfJO+aWb6PLsttKqMJG1yCLZWLdEWHtwUCHDULgFlMZggj
            SdzCjrtEjxziPJ2S1IAErhC8BJQwAFKt4PAKqdivGN/7WMr2qUSTUFe97/Kq6zyu
            ZtO1/gccDkXUIDkdFVyp2XPG5jGaRcvl4DUXNNtlSb6GyTf79xiQRxoCwxnCpR1B
            yyrCAB3wbDoMvGcFTEd9/YvxlzNqnxiT2ajLYhatGGN74AXQplqRkln+3zMc0mOC
            QG3jQX1aAlvtHoR9mFMcgTceQTEV6+Q4+HaleCTNcgl2oeX3nAWbitMS52uxN8vq
            Fyp6iW3vl+EHawKL2do1z8oHJlA2dyCIZTLDJtVejY9EDJ3i7W5o3GiUkAQuOak0
            OcbTjJMg/PWffyq0bvSM/i3MMVfSt1qPLpuo3pT3d8Dp3JlLmAp1joP9agydWYjS
            XgH7GBBaJUx8QNVwc7GXEksrd0aiyG7Qqf4HwIHehhuQ0xaxUe3I+emwuBi8QzlE
            fs62t603r/sPu3RATtHyTdmLw2uwFDX7AyAhPDK3k93oBn3as4WiYmlJzbuWGKs=
            =tAcm
            -----END PGP MESSAGE-----
        fp: 0BCA2EF044187A707E2507E54C4527913792AFD8
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
