apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kaniko
resources:
  - namespace.yaml
  - secret.yaml

#   - kaniko/tekton.yaml
#   - kaniko/pvc.yaml
#   - kaniko/rbac.yaml

#   - https://raw.githubusercontent.com/tektoncd/catalog/main/task/curl/0.1/curl.yaml
#   - https://raw.githubusercontent.com/tektoncd/catalog/main/task/kaniko/0.5/kaniko.yaml

# patches:
# - target:
#     kind: Task
#     name: kaniko
#   patch: |-
#     - op: add
#       path: "/spec/params/-"
#       value:
#         name: CLONE_PATH
#         description: The path where the repo has been cloned into
#     - op: add
#       path: "/spec/params/-"
#       value:
#         name: TAG
#         default: latest
#         description: Tag (reference) of the image to build.
#     - op: replace
#       path: "/spec/steps/0/args"
#       value:
#         # - $(params.EXTRA_ARGS[*])
#         - --dockerfile=$(params.DOCKERFILE)
#         - --context=/kaniko-build/$(params.CLONE_PATH)/$(params.CONTEXT)
#         - --destination=$(params.IMAGE):$(params.TAG)
#         # - --customPlatform=linux/arm64
#         - --use-new-run
#         - --cleanup
#         # - --compressed-caching=true
#         - --cache=true
#         - --cache-ttl=6h
#         - --cache-copy-layers
#         - --cache-repo
#         - $(params.IMAGE)
#     - op: replace
#       path: "/spec/steps/0/workingDir"
#       value: /kaniko-build
#     - op: add
#       path: "/spec/steps/0/volumeMounts"
#       value:
#         - name: workspace
#           mountPath: /kaniko-build
#         - name: regcred
#           mountPath: /kaniko/.docker/config.json
#           subPath: config.json
#           readOnly: true
#         # - name: shm
#         #   mountPath: /dev/shm
#     - op: add
#       path: "/spec/steps/0/resources"
#       value:
#         requests:
#           cpu: 1
#           memory: 4Gi
#         limits:
#           cpu: 3
#           memory: 6Gi
#     - op: remove
#       path: "/spec/workspaces"
#     - op: remove
#       path: "/spec/results"
#     - op: add
#       path: "/spec/volumes"
#       value:
#         - name: workspace
#           persistentVolumeClaim:
#             claimName: kaniko
#         - name: regcred
#           secret:
#             secretName: kaniko-secret
#         # - name: shm
#         #   emptyDir:
#         #     medium: Memory
#         #     sizeLimit: 128M
# - target:
#     kind: Task
#     name: curl
#   patch: |-
#     - op: add
#       path: "/spec/steps/0/resources"
#       value:
#         requests:
#           cpu: 10m
#           memory: 64Mi
#         limits:
#           cpu: 100m
#           memory: 64Mi
