---
apiVersion: v1
data:
    config.json: ENC[AES256_GCM,data:Anr1eT2CDp6JVt6J7oRkXzvs4tXUGHAOAP9/uxNcBCYoFRORI806ZxC3+mjMx/JCmQa9UfW8H5+MJusCN0k4Ta6KZ36nq8auwzkUMwZDnW2NpT/yATZsQLvpJQoFejESoZ6ScucL6p277bNlASkP+AT/WFM320VihOwBZ3p+73jNURyoz7Xm496NeNe0zf2T913SqEJg1+je8bQBFGb2H3nCVH0PFHYycGkMlDNXyv2Xx2HMcRPTF2YJZkAudfGUn1YzvpZsF3ZFmpua6xTLhNvoyziESRD3cTmR+eJ905cMnwOeyPnQ47zD69nUSCHz5j9DWjftsWg=,iv:Xc8rJ5NEbbEtU8eefAdTm/ezC2vw1ZkCajCqbCVm9iI=,tag:B5sxj7Q7Kx/37O5XeHEPCg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: kaniko-secret
    namespace: kaniko
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-02T21:17:49Z"
    mac: ENC[AES256_GCM,data:7y3yRYv2AsJqVrGjI/N7ThyQe/botg/ZjkrlHOyiBeo2cn+0S0cFrov7ROGno/aO3C2WF9KUWfdFmshKUsjwRn+QOVRE3SrJs3tuldW7HJbyiHQZfFe3H7+qF74tB1ptRcSFyeCt4NzcdCdA09mN03BXPeHz2s7KChq6UMPAOkI=,iv:n4O75/A7PP33FBOx2RW2W2Q1KXeBLZzttVPnhoaBmDA=,tag:r5YhnNznJVLJ6MPvI65TZA==,type:str]
    pgp:
        - created_at: "2021-07-02T21:17:49Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxv5FnUBLaS9AQ/9Hi7mJ76/ZIpYzw3m2DXrRE5NKipHwFmLOI5dASwYi/aD
            aLgJa1wphASf5srBHFWbVuhHwI2UVINJt53pBKO5a0PkPgKOY9J79xexLyc5cl1c
            Nv+Y243CaAmW1J+IilM2AvUVQsuKasCw2pEhe0Cmydve6gTk/m45WKepplQA7Xuh
            TQLNWeT8Zm0IhDK0Nrkpimq5vVOx8/2sSX23T0sAc8wD4G66B0ghelrRsx90sAYI
            cfEU7cvWqftlOaA/gvJqmluvC+XCqSNJUlHbgJgGYzbkGHtP07P3UTTpR3Ept13a
            NLvR+n/7+fMECVjZ0KBxrXMgn6/sxDTwvpj2Q7EN5Sd8G6EqRa6/neJcGwi3tSdW
            1r3u6P7Axy6nHnWaD3QR/r755fB7FTPExiMRtw5BQNhFDc/6LmTbfulh2E1Bu8oT
            chEEw+HX2Xm5YToaMaBtnJKgQtoqq7OWAomhOOWVbCy2jSJMA6NnFITM0/lhMBOx
            2qYv+hN56UDlhGyLUDj3+eW2bZuQur1F7I0wUJ+g7R1SfmvRaRuBvO28dx65Egz+
            PEmGISps8t5Jtn6DqMu071SnxUC72T3xYFY5k5G6MeE8yB2OXyzvlaFxP8ABP4Ja
            SUF3/10UfIeNpQT+Xs4dVFi7WwsRkTb6j+6uhKgJaCrIga3DzPrKIsKU4IrZd2DS
            XgGTL63efJi+aDv03YgKjzuV6VBcahdCsgod2j4nWBbQ5t5m0PuZ6BJLxEF4zutE
            ShjxOZvQpMHoNysitzEsKdxx35T7E1LUktzZmsG2l8jwOCHX1FTZ0pNQNu1c4vs=
            =7do+
            -----END PGP MESSAGE-----
          fp: 0BCA2EF044187A707E2507E54C4527913792AFD8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
