apiVersion: v1
stringData:
    config.json: ENC[AES256_GCM,data:MAONoVut75lcyUmWh/qEkwKXRniVU11j/3HtqDh51IOC4PF6gvb+yNTKcW1EDK6eJpLq2nQ0Ofi/GcKWC23i7cDT8x2+p0UsujIKCsjHy2AlT/8rd7/ST8H+L/Cxhnq3Jj/IwHF686bCMiEuMAsDUMRoF7iXSToTL44dqeuN94mMRUJaKI7jQBFQ3UNDdLvKnma3LhErxPTEMjjHGLhnzJcamuJTWzk6k7hGdkTxzfeJik7uyfPY8NDGje/HSSzAolyd7+TuVds/qQyDYq6xz/9hxua3v6Syjl0S7AwfHs+DyG89G2g/FAe1V4sHAXL4CvY6bgCF4wYeyMdQGKtqlRhgTQ==,iv:9AFAkbjV7TnZLhFW/Y/p2ud2pv8y6xEtnngZCDYsR2c=,tag:MNqB1fu/zjiXz21zFY2Log==,type:str]
kind: Secret
metadata:
    name: kaniko-secret
    namespace: kaniko
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-09T06:49:39Z'
    mac: ENC[AES256_GCM,data:YKOcfFCPBp/uxVFk9kh1G2kOFu1uLjVyUG01ZC2HlOpMHzt2Kj6lfKUecji8d/b438HOd5BCwT6bT46f2qg+P++vs8D2VahQoVNn4Ho36wAxQ8d6vxmFasqYad6ExdrYmmWxJyKC5i3oso6UPt5Mqd0yFQcfbk6koJ5nJnrV+ys=,iv:V+Iu2Kmfbvd5NUhyKHNRcUHSTerT3daLu9wUFbrLmLE=,tag:VDcMGYWX5IY1JcnBX37ZEg==,type:str]
    pgp:
    -   created_at: '2026-09-09T06:49:38Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAzS3cyqJu6r0zmztdOghTHdKehpfFdt8RM3nHwyjNcWYw
            gwgDPadCK/Yc8dO0DxCsgSiHW6LNmAWCeQWxpoFGGbn0wYcnadB5HSgY8u5CXjNV
            0l4BmPfELdWSpohg++8BrHzlpAJ74RcmnGvUDS4C6kF1nPa/ggV/cmqlZ3N2yJSH
            lePOQP8q/oSDD9I940u9Y3tkQL3K3+p10IaYL+gHYUkvzvl+kA3HtoZCf8cntDQe
            =3rFT
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
