---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-egress-gateway
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: vpn-egress-gateway
  template:
    metadata:
      labels:
        app: vpn-egress-gateway
        policy.gatekeeper.sh/ignore: "true"
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      initContainers:
        - name: fetchconfig
          image: ghcr.io/shokohsc/gateway:ed9ce66
          command: ["/usr/local/bin/fetchconfig.sh"]
          env:
            - name: CONFIG_URL
              value: http://api.sidekick.svc.cluster.local:3000/vpn/profile/ovpn
          volumeMounts:
            - name: openvpn
              mountPath: /etc/openvpn
      containers:
        - name: gateway
          image: ghcr.io/shokohsc/gateway:ed9ce66
          securityContext:
            privileged: true
          env:
            - name: CLUSTER_CIDR
              value: 10.244.0.0/16
            - name: GATEWAY_CIDR
              value: 172.16.0.0/24
            - name: VPN_SERVER_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: TUN_IF
              value: tunl0"
          volumeMounts:
            - name: openvpn
              mountPath: /etc/openvpn
            - name: tun-device
              mountPath: /dev/net
      volumes:
        - name: openvpn
          emptyDir: {}
        - name: tun-device
          hostPath:
            path: /dev/net
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-egress-webhook
spec:
  selector:
    matchLabels:
      app: vpn-egress-webhook
  template:
    metadata:
      labels:
        app: vpn-egress-webhook
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: webhook
          image: ghcr.io/shokohsc/vpn-egress-gateway:ed9ce66
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          env:
            - name: TLS_CERT_FILE
              value: /etc/webhook/tls/tls.crt
            - name: TLS_KEY_FILE
              value: /etc/webhook/tls/tls.key
            - name: LISTEN_ADDR
              value: ":8443"
            - name: GATEWAY_IP
              value: vpn-egress-gateway.vpn-egress-gateway.svc.cluster.local
            - name: CLUSTER_CIDR
              value: 10.244.0.0/16
            - name: GATEWAY_CIDR
              value: 172.16.0.0/24
            - name: VPN_SERVER_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ROUTING_INIT_IMAGE
              value: ghcr.io/shokohsc/routing-init:ed9ce66
          ports:
            - containerPort: 8443
              name: https
          startupProbe:
            tcpSocket:
              port: http
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 1000m
              memory: 1024M
            requests:
              cpu: 10m
              memory: 64M
          volumeMounts:
            - name: webhook-tls
              mountPath: /etc/webhook/tls
              readOnly: true
      volumes:
        - name: webhook-tls
          secret:
            secretName: vpn-egress-gateway-webhook-tls
