---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vpn-egress-gateway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: vpn-egress-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vpn-egress-webhook
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: vpn-egress-webhook
