---
apiVersion: v1
kind: Service
metadata:
  name: vpn-egress-gateway
  labels:
    app: vpn-egress-gateway
spec:
  type: ClusterIP
  selector:
    app: vpn-egress-gateway
  ports:
    # - port: 8472
    #   targetPort: vxlan
    #   protocol: UDP
    #   name: vxlan
    - port: 4789
      targetPort: cilium
      protocol: UDP
      name: cilium
---
apiVersion: v1
kind: Service
metadata:
  name: vpn-egress-webhook
  labels:
    app: vpn-egress-webhook
spec:
  type: ClusterIP
  selector:
    app: vpn-egress-webhook
  ports:
    - port: 443
      targetPort: https
      name: https
