apiVersion: v1
data:
    token: ENC[AES256_GCM,data:DcPbXYL7bxwI0vSjnJ4SXUY4JoyR3wF2cKfkYEUVyTO3/QD3KLdmC0TAXgTGN+FDt2ZnMkDU9pLVC6OdjRzq4eunZ+/RtzyEwf/2yMP0QeeXFredc4XgKkuCcspXr+HHuVkBWuOwn+6RO/ZAa5ZjzIAPFciYl5YUBsp1Flj1Yse8A6/4KhuheYcAgm9HUlGGcR36Q2iHimrn95mUMQTYh4wLwDv4JyGMyZORJZMRzChBeYtcV9qF+ZeMUjFG8Q4RAr70xngXYTtXW/FD4sbY9ZWoEUr4Q5Jh3uNnybZ75ojzVIra9j/aowWZcVj/joafrYsd3ecY8NM=,iv:CBfTA5zR8veNga4ZxJXQGjwmSeFDe6FZGQPVZpx7Bio=,tag:bhsm6sBS1WbSHkHnGiJLOQ==,type:str]
kind: Secret
metadata:
    name: cloudflare
    namespace: cloudflared
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-06-03T22:28:45Z'
    mac: ENC[AES256_GCM,data:YWkOuHgAflD7nPehguMCddfxeuFsmr9s0KfqHV1YZsqolt3wfX6y58oT5tAhZh6XVU0s6aeYSp7pabUj1XdOzRzS33dfEm53OSyArsqOcy54nbRWK0qwlQfypFKzhQ8BYtRGlngyY1wBMCEg2r+uE1K6DUEmb/dSloNqMAUkKIA=,iv:+Vpv5+Gsjr/5XuhHVuWkFTf/y8OHBMFwYsGGEyyqCkU=,tag:/uY2SgppKkpUHO8OzKKu8A==,type:str]
    pgp:
    -   created_at: '2026-06-03T22:28:45Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA61vFf3pop5XXifzF1IIiR/R0SSSkr+m79FabgB105X8w
            UhHh8sBMPO6UNHoej97LRJPeZ3sjZ2yMlW46m5ErivoKcsvjVYExBUb5XvNB1Vrn
            0l4BLqsRmAUNsTnxWVE0hRwtm50r+pi1lFDXgvPeUWr3UhTt1Yy6u9LY1G8RJNPs
            t+XzK99ZokA9PLNb6fQS89AXEaCIMQRS2bDn8yj1R2GTP0Mpu8is0WkGVO0OUPbZ
            =p2qy
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
