---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kubeshark-config-map
data:
    POD_REGEX: '.*'
    NAMESPACES: ''
    EXCLUDED_NAMESPACES: 'kube-system,cilium,kubeshark'
    BPF_OVERRIDE: ''
    DISSECTION_ENABLED: 'true'
    CAPTURE_SELF: 'false'
    SCRIPTING_SCRIPTS: '{}'
    SCRIPTING_ACTIVE_SCRIPTS: ''
    INGRESS_ENABLED: 'false'
    INGRESS_HOST: 'kubeshark.kubeshark.svc.cluster.local'
    PROXY_FRONT_PORT: '8899'
    AUTH_ENABLED: 'false'
    AUTH_TYPE: 'saml'
    AUTH_SAML_IDP_METADATA_URL: ''
    AUTH_CLI_SERVICE_ACCOUNTS: ''
    AUTH_ROLES_CLAIM: 'groups'
    AUTH_DEFAULT_ROLE: 'kubeshark-admin'
    AUTH_GROUP_MAPPING: '{}'
    AUTH_ROLES: '{}'
    AUTH_OIDC_ISSUER: 'not set'
    AUTH_OIDC_REFRESH_TOKEN_LIFETIME: '3960h'
    AUTH_OIDC_STATE_PARAM_EXPIRY: '10m'
    AUTH_OIDC_BYPASS_SSL_CA_CHECK: 'false'
    TELEMETRY_DISABLED: 'true'
    SCRIPTING_DISABLED: 'true'
    NETWORK_POLICIES_DISABLED: 'true'
    GLOBAL_FILTER: ""
    DEFAULT_FILTER: ""
    TRAFFIC_SAMPLE_RATE: '100'
    JSON_TTL: '5m'
    PCAP_TTL: '0'
    PCAP_ERROR_TTL: '0'
    TIMEZONE: ' '
    CLOUD_LICENSE_ENABLED: 'true'
    DUPLICATE_TIMEFRAME: '200ms'
    ENABLED_DISSECTORS: 'amqp,dns,http,icmp,kafka,mongodb,mysql,postgresql,redis,ws,tlsx,ldap,radius,diameter,udp-flow,tcp-flow,udp-conn,tcp-conn'
    CUSTOM_MACROS: '{"https":"tls and (http or http2)"}'
    DETECT_DUPLICATES: 'false'
    PCAP_DUMP_ENABLE: 'false'
    PCAP_TIME_INTERVAL: '1m'
    PCAP_MAX_TIME: '1h'
    PCAP_MAX_SIZE: '500MB'
    PORT_MAPPING: '{"http":[80,443,8080],"mongodb":[27017],"postgresql":[5432],"redis":[6379]}'
    RAW_CAPTURE_ENABLED: 'true'
    RAW_CAPTURE_STORAGE_SIZE: '1Gi'
