apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeshark
resources:
  - namespace.yaml
  - http-route.yaml
  - configmap.yaml
  - daemonset.yaml
  - deployment.yaml
  - rbac.yaml
  - secret.yaml
  - service.yaml