---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeshark-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeshark-cluster-role-default
rules:
  - apiGroups:
      - ""
      - extensions
      - apps
    resources:
      - nodes
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - networking.k8s.io
    resources:
    - networkpolicies
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
  - apiGroups:
    - authentication.k8s.io
    resources:
    - tokenreviews
    verbs:
    - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeshark-cluster-role-binding-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeshark-cluster-role-default
subjects:
  - kind: ServiceAccount
    name: kubeshark-service-account
    namespace: kubeshark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubeshark-self-config-role
rules:
  - apiGroups:
      - ""
      - v1
    resourceNames:
      - kubeshark-secret
      - kubeshark-config-map
      - kubeshark-secret-default
      - kubeshark-config-map-default
    resources:
      - secrets
      - configmaps
    verbs:
      - create
      - get
      - watch
      - list
      - update
      - patch
      - delete
  - apiGroups:
      - ""
      - v1
    resources:
      - secrets
      - configmaps
      - pods/log
    verbs:
      - create
      - get
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - create
      - get
      - list
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubeshark-self-config-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubeshark-self-config-role
subjects:
  - kind: ServiceAccount
    name: kubeshark-service-account
    namespace: kubeshark
