---
kind: Secret
apiVersion: v1
metadata:
  name: kubeshark-secret
stringData:
    LICENSE: ''
    SCRIPTING_ENV: '{}'
    OIDC_CLIENT_ID: ''
    OIDC_CLIENT_SECRET: ''
---
kind: Secret
apiVersion: v1
metadata:
  name: kubeshark-saml-x509-crt-secret
stringData:
  AUTH_SAML_X509_CRT: |
---
kind: Secret
apiVersion: v1
metadata:
  name: kubeshark-saml-x509-key-secret
stringData:
  AUTH_SAML_X509_KEY: |
