{
 "title": "External disks",
 "description": "External drives capacity & network traffic",
 "tags": [ "system" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "External disks storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "wd-sombra External drive usage %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/mnt/wd2to\",instance=\"10.0.42.60:9100\"} - node_filesystem_avail_bytes{mountpoint=\"/mnt/wd2to\",instance=\"10.0.42.60:9100\"}) / node_filesystem_size_bytes{mountpoint=\"/mnt/wd2to\",instance=\"10.0.42.60:9100\"}  * 100"
    }
   ]
  },
  {
   "title": "4to-sombra External drive usage %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/mnt/4to\",instance=\"10.0.42.60:9100\"} - node_filesystem_avail_bytes{mountpoint=\"/mnt/4to\",instance=\"10.0.42.60:9100\"}) / node_filesystem_size_bytes{mountpoint=\"/mnt/4to\",instance=\"10.0.42.60:9100\"}  * 100"
    }
   ]
  },
  {
   "title": "wd-lucio External drive usage %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/mnt/wd1to\",instance=\"10.0.42.70:9100\"} - node_filesystem_avail_bytes{mountpoint=\"/mnt/wd1to\",instance=\"10.0.42.70:9100\"}) / node_filesystem_size_bytes{mountpoint=\"/mnt/wd1to\",instance=\"10.0.42.70:9100\"}  * 100"
    }
   ]
  },
  {
   "title": "4to-lucio External drive usage %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/mnt/4to\",instance=\"10.0.42.70:9100\"} - node_filesystem_avail_bytes{mountpoint=\"/mnt/4to\",instance=\"10.0.42.70:9100\"}) / node_filesystem_size_bytes{mountpoint=\"/mnt/4to\",instance=\"10.0.42.70:9100\"}  * 100"
    }
   ]
  },
  {
   "title": "wd-zarya External drive usage %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/mnt/wd2to\",instance=\"10.0.42.80:9100\"} - node_filesystem_avail_bytes{mountpoint=\"/mnt/wd2to\",instance=\"10.0.42.80:9100\"}) / node_filesystem_size_bytes{mountpoint=\"/mnt/wd2to\",instance=\"10.0.42.80:9100\"}  * 100"
    }
   ]
  },
  {
   "title": "4to-zarya External drive usage %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/mnt/4to\",instance=\"10.0.42.80:9100\"} - node_filesystem_avail_bytes{mountpoint=\"/mnt/4to\",instance=\"10.0.42.80:9100\"}) / node_filesystem_size_bytes{mountpoint=\"/mnt/4to\",instance=\"10.0.42.80:9100\"}  * 100"
    }
   ]
  },
  {
   "title": "wd-sombra Used Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/mnt/wd2to\",instance=\"10.0.42.60:9100\"} - node_filesystem_free_bytes{mountpoint=\"/mnt/wd2to\",instance=\"10.0.42.60:9100\"}"
    }
   ]
  },
  {
   "title": "4to-sombra Used Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/mnt/4to\",instance=\"10.0.42.60:9100\"} - node_filesystem_free_bytes{mountpoint=\"/mnt/4to\",instance=\"10.0.42.60:9100\"}"
    }
   ]
  },
  {
   "title": "wd-lucio Used Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/mnt/wd1to\",instance=\"10.0.42.70:9100\"} - node_filesystem_free_bytes{mountpoint=\"/mnt/wd1to\",instance=\"10.0.42.70:9100\"}"
    }
   ]
  },
  {
   "title": "4to-lucio Used Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/mnt/4to\",instance=\"10.0.42.70:9100\"} - node_filesystem_free_bytes{mountpoint=\"/mnt/4to\",instance=\"10.0.42.70:9100\"}"
    }
   ]
  },
  {
   "title": "wd-zarya Used Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/mnt/wd2to\",instance=\"10.0.42.80:9100\"} - node_filesystem_free_bytes{mountpoint=\"/mnt/wd2to\",instance=\"10.0.42.80:9100\"}"
    }
   ]
  },
  {
   "title": "4to-zarya Used Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/mnt/4to\",instance=\"10.0.42.80:9100\"} - node_filesystem_free_bytes{mountpoint=\"/mnt/4to\",instance=\"10.0.42.80:9100\"}"
    }
   ]
  },
  {
   "title": "wd-sombra External drive free space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/mnt/wd2to\",instance=\"10.0.42.60:9100\"}"
    }
   ]
  },
  {
   "title": "4to-sombra External drive free space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/mnt/4to\",instance=\"10.0.42.60:9100\"}"
    }
   ]
  },
  {
   "title": "wd-lucio External drive free space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/mnt/wd1to\",instance=\"10.0.42.70:9100\"}"
    }
   ]
  },
  {
   "title": "4to-lucio External drive free space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/mnt/4to\",instance=\"10.0.42.70:9100\"}"
    }
   ]
  },
  {
   "title": "wd-zarya External drive free space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/mnt/wd2to\",instance=\"10.0.42.80:9100\"}"
    }
   ]
  },
  {
   "title": "4to-zarya External drive free space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/mnt/4to\",instance=\"10.0.42.80:9100\"}"
    }
   ]
  },
  {
   "title": "Available space",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/mnt/wd2to\",instance=\"10.0.42.60:9100\"}",
     "legendFormat": "Wx: wd-{{ node }}/{{ device }}"
    }
   ]
  },
  {
   "title": "Available space",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/mnt/4to\",instance=\"10.0.42.60:9100\"}",
     "legendFormat": "Wx: wd-{{ node }}/{{ device }}"
    }
   ]
  },
  {
   "title": "Available space",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/mnt/wd1to\",instance=\"10.0.42.70:9100\"}",
     "legendFormat": "Wx: wd-{{ node }}/{{ device }}"
    }
   ]
  },
  {
   "title": "Available space",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/mnt/4to\",instance=\"10.0.42.70:9100\"}",
     "legendFormat": "Wx: wd-{{ node }}/{{ device }}"
    }
   ]
  },
  {
   "title": "Available space",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/mnt/wd2to\",instance=\"10.0.42.80:9100\"}",
     "legendFormat": "Wx: wd-{{ node }}/{{ device }}"
    }
   ]
  },
  {
   "title": "Available space",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/mnt/4to\",instance=\"10.0.42.80:9100\"}",
     "legendFormat": "Wx: wd-{{ node }}/{{ device }}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{device=~\"sda|sdb|sdc\",node=\"sombra\"}[5m])",
     "legendFormat": "Wx: wd-{{ node }}/{{ device }}"
    },
    {
     "expr": "rate(node_disk_read_bytes_total{device=~\"sda|sdb|sdc\",node=\"sombra\"}[5m]) * -1",
     "legendFormat": "Rx: wd-{{ node }}/{{ device }}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{device=~\"sda|sdb|sdc\",node=\"lucio\"}[5m])",
     "legendFormat": "Wx: wd-{{ node }}/{{ device }}"
    },
    {
     "expr": "rate(node_disk_read_bytes_total{device=~\"sda|sdb|sdc\",node=\"lucio\"}[5m]) * -1",
     "legendFormat": "Rx: wd-{{ node }}/{{ device }}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{device=~\"sda|sdb|sdc\",node=\"zarya\"}[5m])",
     "legendFormat": "Wx: wd-{{ node }}/{{ device }}"
    },
    {
     "expr": "rate(node_disk_read_bytes_total{device=~\"sda|sdb|sdc\",node=\"zarya\"}[5m]) * -1",
     "legendFormat": "Rx: wd-{{ node }}/{{ device }}"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total{interface!~\"br.*|lo\", device=\"eno1\"}[5m])) by (device, instance) * on(instance) group_left(nodename) (node_uname_info)",
       "legendFormat": "In: {{nodename}}/{{device}}"
      },
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{interface!~\"br.*|lo\", device=\"eno1\"}[5m])) by (device, instance) * on(instance) group_left(nodename) (node_uname_info) * -1",
       "legendFormat": "Out: {{nodename}}/{{device}}"
      }
     ]
    },
    {
     "title": "Connection refused",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(vector_ingress_nginx_connection_refused[30s])) by (host)",
       "legendFormat": "{{ host }}"
      }
     ]
    }
   ]
  }
 ]
}