{
 "title": "Global Cluster View",
 "tags": [ "metron" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_status_ready{namespace=~\"$namespace\", condition!=\"false\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(container_memory_rss{namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Spread",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Sombra %Limit",
     "type": "grafana-polystat-panel",
     "description": "$namespace/$pod:$container",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "round(\n  100 *\n    sum(\n      rate(container_cpu_usage_seconds_total{instance=\"sombra\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"\"}[5m])\n    ) by (namespace, pod)\n      /\n    sum(\n      kube_pod_container_resource_limits{node=\"sombra\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"\", resource=\"cpu\"}\n    ) by (namespace, pod)\n)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "CPU Lucio %Limit",
     "type": "grafana-polystat-panel",
     "description": "$namespace/$pod:$container",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "targets": [
      {
       "expr": "round(\n  100 *\n    sum(\n      rate(container_cpu_usage_seconds_total{instance=\"lucio\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"\"}[5m])\n    ) by (namespace, pod)\n      /\n    sum(\n      kube_pod_container_resource_limits{node=\"lucio\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"\", resource=\"cpu\"}\n    ) by (namespace, pod)\n)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "CPU Zarya %Limit",
     "type": "grafana-polystat-panel",
     "description": "$namespace/$pod:$container",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "targets": [
      {
       "expr": "round(\n  100 *\n    sum(\n      rate(container_cpu_usage_seconds_total{instance=\"zarya\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"\"}[5m])\n    ) by (namespace, pod)\n      /\n    sum(\n      kube_pod_container_resource_limits{node=\"zarya\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"\", resource=\"cpu\"}\n    ) by (namespace, pod)\n)",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "description": "$namespace/$pod:$container",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(1000 * rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"\"}[5m])) by (namespace, pod, container)",
       "legendFormat": "{{ namespace }}/{{ pod }}:{{ container }}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "description": "$namespace/$pod:$container",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"\"}) by (namespace, pod, container)",
       "legendFormat": "{{ namespace }}/{{ pod }}:{{ container }}"
      }
     ]
    },
    {
     "title": "Network",
     "type": "timeseries",
     "description": "$namespace/$pod",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "avg(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\", pod!=\"\"}[5m])) by (namespace, pod)",
       "legendFormat": "{{ namespace }}/{{ pod }} Tx"
      },
      {
       "expr": "avg(rate(container_network_receive_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\", pod!=\"\"}[5m])) by (namespace, pod)",
       "legendFormat": "{{ namespace }}/{{ pod }} Rx"
      }
     ]
    },
    {
     "title": "Filesystem",
     "type": "timeseries",
     "description": "$namespace/$pod:$container",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"\"}[5m])) by (namespace, pod, container)",
       "legendFormat": "{{ namespace }}/{{ pod }}:{{ container }} Rx"
      },
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"\"}[5m])) by (namespace, pod, container)",
       "legendFormat": "{{ namespace }}/{{ pod }}:{{ container }} Wx"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs & Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"\"}"
      }
     ]
    },
    {
     "title": "warning events",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__time(\"createdAt\"),\n  \"involvedObjectName\",\n  \"message\"\nFROM\n  events\nWHERE\n  $__timeFilter(\"createdAt\")\nAND \"involvedObjectName\" = ANY(ARRAY[$pod]::varchar[])\nAND \"involvedObjectNamespace\" = ANY(ARRAY[$namespace]::varchar[])\nORDER BY time DESC\n"
      }
     ]
    }
   ]
  }
 ]
}