{
 "title": "Kubernetes events",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "reason",
    "label": "Reason",
    "query": "select reason from events WHERE $__timeFilter(\"createdAt\")"
   },
   {
    "name": "involvedObjectApiVersion",
    "label": "apiVersion",
    "query": "select \"involvedObjectApiVersion\" from events WHERE $__timeFilter(\"createdAt\")"
   },
   {
    "name": "involvedObjectKind",
    "label": "kind",
    "query": "select \"involvedObjectKind\" from events WHERE $__timeFilter(\"createdAt\")"
   },
   {
    "name": "involvedObjectName",
    "label": "name",
    "query": "select \"involvedObjectName\" from events WHERE $__timeFilter(\"createdAt\")"
   },
   {
    "name": "involvedObjectNamespace",
    "label": "namespace",
    "query": "select \"involvedObjectNamespace\" from events WHERE $__timeFilter(\"createdAt\")"
   },
   {
    "name": "sourceComponent",
    "label": "component",
    "query": "select \"sourceComponent\" from events WHERE $__timeFilter(\"createdAt\")"
   },
   {
    "name": "sourceHost",
    "label": "host",
    "query": "select \"sourceHost\" from events WHERE $__timeFilter(\"createdAt\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Kubernetes warning events times",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  reason,\n  count AS \"eventCount\",\n  \"involvedObjectApiVersion\",\n  \"involvedObjectKind\",\n  \"involvedObjectName\",\n  \"involvedObjectNamespace\",\n  \"sourceComponent\",\n  \"sourceHost\"\nFROM\n  events\nWHERE\n  $__timeFilter(\"createdAt\")\nAND reason = ANY(ARRAY[$reason]::varchar[])\nAND \"involvedObjectApiVersion\" = ANY(ARRAY[$involvedObjectApiVersion]::varchar[])\nAND \"involvedObjectKind\" = ANY(ARRAY[$involvedObjectKind]::varchar[])\nAND \"involvedObjectName\" = ANY(ARRAY[$involvedObjectName]::varchar[])\nAND \"involvedObjectNamespace\" = ANY(ARRAY[$involvedObjectNamespace]::varchar[])\nAND \"sourceComponent\" = ANY(ARRAY[$sourceComponent]::varchar[])\nAND \"sourceHost\" = ANY(ARRAY[$sourceHost]::varchar[])\nORDER BY \"createdAt\" DESC"
    }
   ]
  },
  {
   "title": "Kubernetes warning events",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(\"createdAt\"),\n  message\nFROM\n  events\nWHERE\n  $__timeFilter(\"createdAt\")\nAND reason = ANY(ARRAY[$reason]::varchar[])\nAND \"involvedObjectApiVersion\" = ANY(ARRAY[$involvedObjectApiVersion]::varchar[])\nAND \"involvedObjectKind\" = ANY(ARRAY[$involvedObjectKind]::varchar[])\nAND \"involvedObjectName\" = ANY(ARRAY[$involvedObjectName]::varchar[])\nAND \"involvedObjectNamespace\" = ANY(ARRAY[$involvedObjectNamespace]::varchar[])\nAND \"sourceComponent\" = ANY(ARRAY[$sourceComponent]::varchar[])\nAND \"sourceHost\" = ANY(ARRAY[$sourceHost]::varchar[])\nORDER BY time DESC\n"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{namespace=~\"$involvedObjectNamespace\"}"
    }
   ]
  }
 ]
}