{
 "title": "Pod Spread",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sombra",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 23, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_info{node=\"sombra\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Lucio",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 23, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_info{node=\"lucio\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Zarya",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 23, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_info{node=\"zarya\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  }
 ]
}