{
 "title": "Squid Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Bytes Hit Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "squid_client_http_hit_kbytes_out_bytes_total / squid_client_http_kbytes_out_kbytes_total"
    }
   ]
  },
  {
   "title": "Catch Hit Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "squid_client_http_hits_total / squid_client_http_requests_total",
     "legendFormat": "Hit rate"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "squid_client_http_errors_total / squid_client_http_requests_total"
    }
   ]
  },
  {
   "title": "Client Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(squid_client_http_requests_total[5m])",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "rate(squid_client_http_hits_total[5m])",
     "legendFormat": "Total HTTP hits"
    },
    {
     "expr": "rate(squid_client_http_errors_total[5m])",
     "legendFormat": "Total Errors"
    }
   ]
  },
  {
   "title": "Client Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "rate(squid_client_http_kbytes_in_kbytes_total[5m]) * -1",
     "legendFormat": "HTTP Traffic in"
    },
    {
     "expr": "rate(squid_client_http_kbytes_out_kbytes_total[5m])",
     "legendFormat": "HTTP Traffic Out"
    },
    {
     "expr": "rate(squid_client_http_hit_kbytes_out_bytes_total[5m])",
     "legendFormat": "HTTP Traffic Out Hits"
    }
   ]
  }
 ]
}