apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vuio
resources:
  - namespace.yaml
  - vuio.yaml
  - http-route.yaml
configMapGenerator:
- name: config
  files:
  - ./config/entrypoint.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled