---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
spec:
  schedule: "0 5 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            fsGroup: 1000
          automountServiceAccountToken: false
          containers:
          - name: backup
            image: offen/docker-volume-backup:v2.49.1@sha256:e1da571e739d73f633f19e7a9f324007907089ffd80b3b7a1d71de5b87f80d77
            command:
              - backup
            env:
              - name: BACKUP_RETENTION_DAYS
                value: '1'
            volumeMounts:
              - name: data
                mountPath: /backup
              - name: shared
                mountPath: /archive
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: thelounge-config
            - name: shared
              nfs:
                server: nfs-shared.nfs-shared.svc.cluster.local
                path: /backups/thelounge
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - thelounge
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                    - thelounge
                topologyKey: kubernetes.io/hostname
