apiVersion: v1
data:
    adapter-url: ENC[AES256_GCM,data:si1XT0QnY3SkXfopl4m/OyVOTXy925BYk8NHhcgkmpwlEUoT1AWbWSGe6qJwANot1Qd4+5oYAfXP1a+2b58Jkt0gGp9Zvju45wEihAzSPmycc5NcaI2QCA==,iv:JXnMQIerSWM8jbWd+EdUsodtw/U4GxKlbIMpZp8QTRI=,tag:ah4AWDNWLbci3VVnEZFirQ==,type:str]
    postgresql-database-password: ENC[AES256_GCM,data:GmoSppQu+5KoaWRg,iv:2gW5KO6S97WFS6bxMy1sPA6t0JEnQrZK5khqq1WkFeI=,tag:mN8hZ6fjTpFcxg6laJYGiA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sidekick
    namespace: sidekick
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2022-02-27T10:15:07Z'
    mac: ENC[AES256_GCM,data:ie1phHAJZQNyTPV5sK6O94i6CQxXvxNEYE/lNxEzR4DvuCefUpXX5dKL3P1pg9n/I5GmCBh0sKWGCJSsZcx1T6WWyeaUmPeyO2aHlx7PG/sqMYmydX+x1WvLgdwjRy8Ar/WHw8P1YviQ6VmTT6sr+znbUerUh1agpoSIiNqYFMQ=,iv:RA/vJKO0DhFX5MkcG2uueYENg97Lg5EX/kjskQX2UY8=,tag:Z7RK6l7SUXntK8sSi9KJdQ==,type:str]
    pgp:
    -   created_at: '2022-02-27T10:15:07Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxv5FnUBLaS9AQ//bYfrMrRtDPtFZg4rM/QquBjqto8K+EfOiod+l0jtMUew
            L4iexOncE1qqHtDYJDm89D0BGLnuheaa6TQdYAd08I6vPQTGcuyJkEXria2/DitW
            0Q1vJz8BjlpvFfvHvLRduIaVJ63QSE3lQNTCessH2bQR1YczbbjP6aQcEipV31cy
            6CVlYCbikcIPc+4b/gU+SWO2ABRUWp4XGjGAkPehP3tmNfpVCZqTr8Qi+67F+jax
            9AN0qunqYNZ2cvKKrg5mxU3bG4eQqmxSHIhaGTr9hfKgKDocyOFErjGgpAXT+W/S
            BH0Ve4cPMTfDExXL3KqDRlXAVe6fGEPenIw3YPQ4ZBh7dSWFKjIL80pS5jK7p3XP
            4KScPotkEnvbW+PiOb884eCzqmjdiQbKp+tBQZ04OWNvX5tmsKFnTB4myoQWvi5i
            tqI4p3IbIs1JFpZHSV3EpwhRyiYPieX9+x6ucwuF7e97+Jm79oVgnGwpCyK5+520
            wKIc4qInIbP2Wz3zk8Rr45q1sNJk6zIl+oY3UI5R25iIl7IgtBXgIEzBgT7paFE5
            NgcyuXyC9CQdn8ogFZjrZjEMnCB0BYZPHv+MEQSc0zMEpwTh/1RYVPD+dY4uRerY
            QjjRvFJDZUK9j7Dz7pWIZoClWSrkfgp6vH3oaGlaKr+uACM/8a3NZaNhQ+PefWnS
            XAFnOzSeMWJM05/vANTPANSykwru4G2MNB9Yf3MBzGACmiGkWmKPWjg/oMw+1Hsx
            4c7PRy5YtqSY4ysmT33/sZTW+V/Jp/jjz6weH1dw3dTQ777YdjJIwRSn7Sfm
            =I+8R
            -----END PGP MESSAGE-----
        fp: 0BCA2EF044187A707E2507E54C4527913792AFD8
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
