---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-proxmox-backups
  labels:
    app: nfs-proxmox-backups
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nfs-proxmox-backups
  template:
    metadata:
      labels:
        app: nfs-proxmox-backups
        policy.gatekeeper.sh/ignore: "true"
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: nfs-server-alpine
          image: itsthenetwork/nfs-server-alpine:latest # Find an alpine image that has nfsdcld
          securityContext:
            privileged: true
          env:
            - name: SHARED_DIRECTORY
              value: /exports
          ports:
            - name: nfs
              containerPort: 2049
              protocol: TCP
            - name: rpc
              containerPort: 111
              protocol: TCP
          volumeMounts:
            - name: backups
              mountPath: /exports
            # - name: nfsdcld
            #   mountPath: /var/lib/nfs/nfsdcld
          lifecycle:
            postStart:
              exec:
                # command: ["/bin/sh", "-c", "chmod 777 /exports && nfsdcld"]
                command: ["/bin/sh", "-c", "chmod 777 /exports"]
          startupProbe:
            tcpSocket:
              port: nfs
          livenessProbe:
            tcpSocket:
              port: nfs
          readinessProbe:
            tcpSocket:
              port: nfs
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 512Mi
      volumes:
        - name: backups
          hostPath:
            path: /var/mnt/nfs-proxmox-backups
        # - name: nfsdcld
        #   emptyDir:
        #     medium: Memory
      nodeSelector:
        kubernetes.io/hostname: winston
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-proxmox-content
  labels:
    app: nfs-proxmox-content
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nfs-proxmox-content
  template:
    metadata:
      labels:
        app: nfs-proxmox-content
        policy.gatekeeper.sh/ignore: "true"
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: nfs-server-alpine
          image: itsthenetwork/nfs-server-alpine:latest
          securityContext:
            privileged: true
          env:
            - name: SHARED_DIRECTORY
              value: /exports
          ports:
            - name: nfs
              containerPort: 2049
              protocol: TCP
            - name: rpc
              containerPort: 111
              protocol: TCP
          volumeMounts:
            - name: content
              mountPath: /exports
            # - name: nfsdcld
            #   mountPath: /var/lib/nfs/nfsdcld
          lifecycle:
            postStart:
              exec:
                # command: ["/bin/sh", "-c", "chmod 777 /exports && nfsdcld"]
                command: ["/bin/sh", "-c", "chmod 777 /exports"]
          startupProbe:
            tcpSocket:
              port: nfs
          livenessProbe:
            tcpSocket:
              port: nfs
          readinessProbe:
            tcpSocket:
              port: nfs
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 512Mi
      volumes:
        - name: content
          hostPath:
            path: /var/mnt/nfs-proxmox-content
        # - name: nfsdcld
        #   emptyDir:
        #     medium: Memory
      nodeSelector:
        kubernetes.io/hostname: winston
