---
apiVersion: v1
kind: Service
metadata:
  name: nfs-proxmox
  labels:
    vlan: lb
  annotations:
    lbipam.cilium.io/ips: 10.42.60.50
spec:
  type: LoadBalancer
  ports:
    - port: 2049
      targetPort: nfs
      protocol: TCP
      name: nfs
  selector:
    app: nfs-proxmox
