---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  annotations:
    configmap.reloader.stakater.com/reload: config
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9411"
      prometheus.io/path: /prometheus
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: zipkin
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: zipkin
      containers:
        - name: vector
          image: timberio/vector:0.59.0-alpine
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          args:
            - --config
            - /etc/vector/vector.yaml
          ports:
            - name: vector
              containerPort: 9412
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: vector
          livenessProbe:
            tcpSocket:
              port: vector
          readinessProbe:
            tcpSocket:
              port: vector
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 128Mi
          volumeMounts:
            - name: config
              mountPath: /etc/vector/vector.yaml
              subPath: vector.yaml
      volumes:
        - name: config
          configMap:
            name: config
            defaultMode: 0644
