---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden-secrets-sync
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: vaultwarden-secrets-sync
  template:
    metadata:
      labels:
        app: vaultwarden-secrets-sync
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: vaultwarden-secrets-sync
      containers:
        - name: vaultwarden-secrets-sync
          image: ghcr.io/shokohsc/vaultwarden-secrets-sync:51299d4
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          env:
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SYNC_INTERVAL
              value: "5"
            - name: DRY_RUN
              value: "true"
            - name: DELETE_ORPHANS
              value: "true"
            - name: VAULTWARDEN_SERVER_URL
              value: "https://vaultwarden.${domain}"
          envFrom:
            - secretRef:
                name: vaultwarden-secrets-sync
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          volumeMounts:
            - name: temp
              mountPath: /.config
            - name: tls
              mountPath: /etc/ssl/certs
      volumes:
        - name: temp
          emptyDir:
            medium: Memory
        - name: tls
          configMap:
            name: homelab-ca-cm
            defaultMode: 0600