apiVersion: v1
kind: ServiceAccount
metadata:
  name: vaultwarden-secrets-sync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultwarden-secrets-sync
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vaultwarden-secrets-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vaultwarden-secrets-sync
subjects:
  - kind: ServiceAccount
    name: vaultwarden-secrets-sync
    namespace: vaultwarden-secrets-sync