apiVersion: v1
stringData:
    VAULTWARDEN_SERVER_URL: ENC[AES256_GCM,data:6MhNXwzD6SY+mP2mWjsdd4uQu9/5+6zvW/SeHj7nmN/fO+v7uo8KJdexp9fprR+A,iv:rmrSrJXLlMPbDRuX9lDYYoNKRDaiZ18Q0QGz4RQH79E=,tag:tI4zDBo4PrtYFROyw3Wkcw==,type:str]
    VAULTWARDEN_CLIENT_ID: ENC[AES256_GCM,data:Q+ey8HQbzr8b0T8ukYiy9K8Akp2/igWeznC5ZyFsV8b5hHB0etuifA4=,iv:kraXG51qfeqFBSVvGN1JyQLBTxknAQBkhqyxsqHsvM0=,tag:Y0egfWzwuqjDrKsyhv6SRg==,type:str]
    VAULTWARDEN_CLIENT_SECRET: ENC[AES256_GCM,data:TDv7bL0UVITdzw+ufnomvaFiG+cTkUfkxzHBU5U0,iv:vtfHKULdzJm0c42metXgUIJPU3tR300lzlB07rU4kac=,tag:dYsE9Eoc/PatEsaMT2lKxg==,type:str]
    VAULTWARDEN_ORG_ID: ENC[AES256_GCM,data:uizEMmTPKJqYTw==,iv:9cFjgschAZlTqgYHzKK6bhX5jhZ1Us9WCQEzR5GAYKw=,tag:Kc8vbdnLbaIuWcia7j58LQ==,type:str]
    VAULTWARDEN_FOLDER_ID: ENC[AES256_GCM,data:17PSug0rpPvUviVAgU2cBdddHJKPVBgAVfTpWWprcW8/OJ8f,iv:nuLPUq/gLILhgO9Qmm6btFTn8CDNHlgF/Vd0k4Ka+ik=,tag:Vn3O7zpu9Iirw0EJrruIIw==,type:str]
kind: Secret
metadata:
    name: vaultwarden-secrets-sync
    namespace: vaultwarden-secrets-sync
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-03T17:00:26Z'
    mac: ENC[AES256_GCM,data:+9hOv8Jfvq51iXVqYsZYyEhGaLlVP2Z1si4nQEt2LFoCnPd/eHmgi4NApAL+brMnMJYhJO+71PgZOckIDNmr7ykYlVpIPCnf+hcQIjWBXifesYBEsgD72cfkwZ/gSq4fXUY6dakOawbcpfKCUNWfpkq8mXdfEE0iy8F+mjT0Jjo=,iv:OM3ooq/8vI9y/NxWYUMI8jdGrAaTUejko4iVfuWBPX4=,tag:Fx9aPRralgZT6ff8vOKc3g==,type:str]
    pgp:
    -   created_at: '2026-09-03T17:00:26Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAaTldg3eYcJC6B4pB6LR+9V2vKwgtVG1axPzHWcp05nQw
            otKyg8BdNueBDcl+7ih5iz/Njdv02F/CsmrL8W52PEfjOXfE56cro/aSC8w8lsHG
            0l4B/ZtwX55GcTYcLDe4nwqs8euXtk5UJdv2HMMSuqkr/JR9mWDzt3Sqgh04+oGn
            L2+va0pY/Angbh0awg7dke/npVKbagqQ+Etw6JGhYZMfjnmXw8op/RBuHtQeVFMI
            =bfUv
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
