apiVersion: v1
stringData:
    VAULTWARDEN_CLIENT_ID: ENC[AES256_GCM,data:l0vqyTfFNsGF6DjzbIWRMjq+8CBVy8xtMLrPG1pPU7ipxz7DHfm2T70=,iv:XtrfUlyb4id6TuLRqyVcjnJaB142iKz6o2RKVQ7bhsY=,tag:fVvhnDWzldkIa33qIQhW1w==,type:str]
    VAULTWARDEN_CLIENT_SECRET: ENC[AES256_GCM,data:tq2loPTUWCHNtNJxqDLp/2d187ewB+HNcbxX/ZbT,iv:bnxRcbBeQi4dXJlSYaWjCn6fEHW9/5pLm1CSrYf1fr0=,tag:S2zyu+mK3AASF99ksNBuKg==,type:str]
    VAULTWARDEN_ORG_ID: ENC[AES256_GCM,data:bp9B2ZDXXDDppQ==,iv:xKsyySrqJ7tcTAajglvDkLpAdNcqTB5reZ0rJ+iPshs=,tag:WdpgflobrVLJWsTvs+VAOQ==,type:str]
    VAULTWARDEN_FOLDER_ID: ENC[AES256_GCM,data:ls9ctBb4yJtvEmZTnRP1I/kCHymlQMGHeSLik2oTVVgVaXuc,iv:5VW56PAav+yJ6YJR2K5UU8UwR84VM7VEr+PL6rvXgQI=,tag:zLdNzKW02zth2onUvcvr8w==,type:str]
kind: Secret
metadata:
    name: vaultwarden-secrets-sync
    namespace: vaultwarden-secrets-sync
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-03T18:32:14Z'
    mac: ENC[AES256_GCM,data:J/pt0J7EbUjd89hRIxPdf1weP5tDnPQ9VzbMLhGt6AvaG1A2wqmVKg7RVZSJNQtqxZA9FEw3Qodunude+uD3n2t48i8XWdEVbGXmposNRwbolnmEwiU4Y60Wze873tU4KwUCqTrDK3IXZXX5Pxbic1WUqtY3lwlXyxEyuGJqnrc=,iv:xJJ8ZdNCjjh/qwxifA3/JeFfzWWhewJC/0A532MunpQ=,tag:+HaSghVJnMo9B4497/YYYw==,type:str]
    pgp:
    -   created_at: '2026-09-03T18:32:14Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAUr3BlMoJ7iMOsFnUI4dqDpWsEfld9GDZWBO0Lt2jeFEw
            eox6a75ZeEessxUHWVRyMAdrbX7Z5xQKKqV+1zNbhtqc98UAJq9HyK++8nk+hbOt
            0l4BqGy92AYva1FrCJqIihv9b7Z2JlUCFcSrqRquzWcSaUNXTlkGFP9CYaSUZK9b
            X/+FLw58u4cNnTw5H1O+F59BN7ehoyAD7hRDPr974oG0mdFkAbCHKNoqWCA8Pejl
            =yiC/
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
