apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nostr-gateway
resources:
  - namespace.yaml
  - deployment.yaml
  - poddisruptionbudget.yaml
  - service.yaml
  - secret.yaml
