apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nostr-gateway
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - secret.yaml
configMapGenerator:
- name: config
  files:
  - ./config/agents.json
generatorOptions:
  disableNameSuffixHash: true