apiVersion: v1
kind: Secret
metadata:
    name: nostr-gateway
    namespace: nostr-gateway
type: Opaque
stringData:
    MAIN_NSEC: ENC[AES256_GCM,data:AdGTGQ9GkBx72iOxdd3pePth/0gP6FlSWpQ47hO57QX6HxKu/yrZKYwS3XSPIZmkIROEwBcYp37ypE6hZ6qN4Q==,iv:m3CdLLHt+ZSVNuLc/V+4ze+uAfCT3p3WWYBmAaY76OI=,tag:MIFLUVQwHMts1Y//V5nasA==,type:str]
    GATEWAY_TOKEN: ENC[AES256_GCM,data:APGnwGXxKVkHVBjrkw+kVlLMaZJlP78JNFyNTVXtBcpKJDwi59WBAAgJf41IJMF40th1M/0R9bszm6NMAcSpPA==,iv:/TEaQTCodyx5NXTx4H+RUfJofpA4rbTNLRcKWBxojuQ=,tag:8vJNYLqYIHIWkBsVAhLrtw==,type:str]
    agents.json: ENC[AES256_GCM,data:8iroWgVgao2pzgOewORljlPZRdiYBDWeC5ybYCPsO9xMzuxH7e9Zj3+luWsvGkVgYODhpzTKMwJVTBSe+dYHQQjxg5u/fe0kt2WQTQGfxCpNdumgLi2+d0xU4ypbg7OOx368kxFTNUFL/IwAUQmnlCOwNbbH8ZnrFklFy7QIYPVMiH+KCoWjg1h1wNiWJkiPJ0ndU15YifJKzqH90evvj5MDM710wS06PRPijLLvnE6cYGphTDNSfwpH1UE3VeIwI4A2Rrp3y1lAkhm1OdkCcPmCnro5xAyFfa5gyzTx4+MgcDFcBDc0RLqRMlzPpqsdQu7//Sk1IawmwSNMN5fjVVaHTSdzzdxsmfPTPDU9aaYOsHbpI/f/yJ8BMz9ADQIH+VucCtkkga5qO61OAYT2yXPimoC6JXNz678Rce+8Zcu0NJIqwKERlozk62q96PZfDCRKxQV+AW3zaGZt66k70nNA9Ujqee8=,iv:vS24jgRRxNIsBbGCjMsr8iAG0CiIrFPAwsV4AwJB90U=,tag:OWaU2Qvio+Sh9Nue4Jz0OA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-29T10:01:26Z'
    mac: ENC[AES256_GCM,data:scCLMmtyGEalTKDgJxnksn/i33nsefin6TIMzWOlOUTIb0JvZHx8/t1nKRPuSbDj2kqkz2V/j3oUR+KdbmEh1XtRLJ+kMPJ1I/cDGh/ZdgBPP81YiR8gdPPf1/5Y9QlQBkKbEP35KLFhiDzvR1RUmhTXTquZ4ENkOPdEALu3pbA=,iv:18inPCbWYDf9elTIBPtg8ecMwRKHVs8w/A280vI5GdE=,tag:YZxNQUJAwK56Gc/ESmRvvg==,type:str]
    pgp:
    -   created_at: '2026-09-29T10:01:25Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAbbdXn9VRokpj6pXX+Xkfd+TKQ55OwfVMLf+wZ/Qk1AIw
            JqWcuOxSfD1cfgtf+CHyh4siGuuy2mWKRAuSWZr++AYI6v4het/DrX5OTgtTDNya
            0l4BB20E1DWm3NFOGbJJMl3Q98vJfmG8gTQUkdv23Zkuy/JDeUryo2AMp/gTFpFx
            YYlUOLEDSAOsyxxUfijmSR5Djy7Q7QOYzZjq8czyc7J3gKSap3Jtao9bV1IAhjYK
            =hMIF
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
