apiVersion: v1
kind: Secret
metadata:
    name: nostr-gateway
    namespace: nostr-gateway
type: Opaque
stringData:
    AGENT_NSEC: ENC[AES256_GCM,data:ODk1ELgie+7RLurA7OpG2iL3A6M2WO1OX8C1XdGmxh82H6orQImLdbA59AbjZqLpxPOtpgZN7lu1qYyyhykz1Q==,iv:dQ/v4rUYt69/3QgcgZuPOzHTtxke85MI7p6suPRTupE=,tag:g5yUw4IHftK/fXXPN5B15Q==,type:str]
    GATEWAY_TOKEN: ENC[AES256_GCM,data:W8chBEMfUxzoDXB6OUpZ8c1PATjl1G97OQYo87M7Cb0/DuFnK5cBrAROvjYNgYo4SYkhNkKGUDKHxFjWrEO0Ng==,iv:71b9QWXAsGEirfrCMyh1lJEoN7+rhiY5uZsDOEFCTW4=,tag:a9Lw8O+bFDCLQ4WvcnR4UQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-30T11:59:29Z'
    mac: ENC[AES256_GCM,data:KvK+BugHgDVdDdozyqNQac9X4l/hxZOSRAVzahW4nWXG1mzqpytt+9Ke1lfEzCElW14q2DhVtw6CiOrkEdWwdoTbu+crHnQCMMxKVvwNAT0wPcQETLakBjLQ+uxXvxyfg78vFYHGOmv/wG60kApc58437XXSvud1W9cS5qBUv6Y=,iv:IS2Y15ShOZJbHhPQAkUumhbfjjWxdc2Z9XIN3g66Ibk=,tag:mL/WKscN5Y29St/V8/9Fnw==,type:str]
    pgp:
    -   created_at: '2026-09-30T11:59:28Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAy6OezkX7OaTKhyFWNPD1jrnOlIhdTdio/9mTlQZCVk8w
            wtMREKeXCdDta2OXYkQJULNs2d2/uWIRXqkuWjMUq2wjMAi9lJtOisUJ29JkLStP
            0l4Bjvgx9v+fGNC/2m93K/9DVZ7096FGjytGa7bhV5nunMck4tHjH1du4BVXIJBK
            +b/TEF8T9oq6uzYVb0wPx46GeBTDtu5VoXa1wrJGga0Dcw2ZFmtg0tjkRzTvnFYG
            =dLxL
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
