apiVersion: v1
kind: Secret
metadata:
    name: nostr-gateway
    namespace: nostr-gateway
type: Opaque
stringData:
    MAIN_NSEC: ENC[AES256_GCM,data:2vMhyT3j3IQnraNuppoqc/fnodPylR6sHJkQ1Soos8IH9lTeDrovcQujL7PjzsSC9PQ1AS+sxO0fKttDR+RtHg==,iv:GM6/zEqWyRKbuSmA68BLZzJJlBfEAsZw+HhhlnXjEHE=,tag:aR3bhN+cItsKv8EuKKb6kQ==,type:str]
    GATEWAY_TOKEN: ENC[AES256_GCM,data:JJpxRipZVjju82imcqU3mso4BUbKxBORa3Rlv2yhKQoxfzwxC4Euo0Fp4lMm/+PDadDgR4pLYzEd8GtqnW9+dQ==,iv:bQ4/5tA7oEeXe7r2C/mD7iRLKD6drUwU//fiYlI17rY=,tag:rwtkz4rvGRj4mKDLTi0mjA==,type:str]
    agents.json: ENC[AES256_GCM,data:fiXPiYMcrxYxsdUbySY5JgIBZq0RQELYxW1P1b8d2z6cXMN5bC9TpgXVL6SUA0FF+lTBi0SW2ETlcbh13WvKILl8yAIQ/oDExVQBz+wKlCKt4ik1O02zxo3zpo9tP/WzxztfOcHAQXeH2s+4k53kKjepkF07V/vM2pzMkv43AEbaiLNmDsSrH8YtWa6dPDOH3y9g/5G4hLOiv614bsyzzVLgrulobfzihCx8iU0g0bY/6JjghWpDbhmYGnD9fbqGwCf2XUVUM28XrgU1rvf4G1e/nbJBO8Sk2lPS1rdpycNZ/FJfztO0s2QhAfX87Q/h89B8Q5XzgN7Khc2CacExIfsEG7Vxk90iiIbLplZy5TZXkwbHKE6trtH4qMvKJOZnXe9uKhlSPPi93h8yEvGTBJPXiuB7IKVCI/RfqHBhbDYN1ANeeZxpR1ep3fCBGKlqhW8JAUYq2ZiHzG7YkMbF,iv:Tz9A9kw+DjEjwT4VDzmg3LP296Ee2HIhBjHWBl8kQy0=,tag:i2WwiAk6kuWycgaIdwyllg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-29T08:35:09Z'
    mac: ENC[AES256_GCM,data:7rEE2RxtLIxNG899RLP/MkaK3Ilxs4eiG8agJ4Rt1GOvvO9KimlexLaT9YsL7psgK0pWcRhWpzLa8346yjb4lCIKtUvQJFXFAi0i/7gHqyLbLz//AxbpS2VWy6PsFrWLIi9UVx5p5Sg063VaTqGKrlW7lFGPYpzGdKVUklWrMvs=,iv:746zet0RGNVn1Ty/4qm29xQaduLJ3jm8z4H3bxws9Sw=,tag:xG8NdNHau2YIV9CtL6QifQ==,type:str]
    pgp:
    -   created_at: '2026-09-29T08:35:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAcnkUsTlGW/8nM6qyFLGYihsyVMIFnhFGCHnK5WRrvQ0w
            FLYN2JVOe5W96UQhLx6AfUi9k7rip19g2pgMpNWzusomhEyFFRHhMLcmuVBi+JNX
            0l4BQprI6oWZsRodwttiGOoAmEk6oo0igIUWihKrS0eZ/LglAlcTNrHHVvY7/8fZ
            mXUTjViI6gS5ORRRcKMNY6LcMhv+u8BXvxA3ssiO7Tw8ysvd6tQx0sKI9kzExJph
            =/upm
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
