---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: radio
  annotations:
    cert-manager.io/cluster-issuer: ca-cluster-issuer
spec:
  parentRef:
    namespace: cilium
    name: cilium
    kind: Gateway
    group: gateway.networking.k8s.io
  listeners:
  - name: radio
    hostname: radio.${domain}
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        group: ""
        name: radio-cert
  - name: api
    hostname: api.radio.${domain}
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        group: ""
        name: api-radio-cert