apiVersion: v1
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:Bv4mYwGszTR0ZRvztaQwnjFxXIaJqnD4cbS5QY36yvPRKaQ9yfjupoRXf8R/JFjWaUPSeY1A3vJUx945LYuN8Q==,iv:opWmww2h92R23jCJkrby/VubeJXqqMWsJx1bc6cJMwg=,tag:YgUQ46jYAnCncGQeKXFPjQ==,type:str]
    API_KEY_SECRET: ENC[AES256_GCM,data:Sc2Phd1KRTMMyqTHY5dJHzp1ZjdTqyxzHAEG+8bHZ5Yw,iv:rjl+q64A8Q4zVZo2Qne7e1Ww6GTVKiw33CkQlse1xpw=,tag:JG99Ea6f7B6zGkbnYKqGwA==,type:str]
    INITIAL_PASSWORD: ENC[AES256_GCM,data:OYuNlg6JoyOz,iv:NJyX1GlFlIEp1Pqqu+hWp7c/EO1KjolM3+KZufCVvgM=,tag:DAae8lvnnaPnPC+9XUihLQ==,type:str]
kind: Secret
metadata:
    name: variables
    namespace: omniroute
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-14T21:22:25Z'
    mac: ENC[AES256_GCM,data:T9MRYWyZJI3qy79cO9Ak1dAh7vuBMCd3cd3WZFkNqp5DWIdPDXS2vGE1Vb99B5p70VIiVmrDpwzSxv10hJ8GrLMtcmO5bAW8JnGkMXRuE/ZDnqeOG5JqYz5CZNSdTr1Wb12zTFXvPlHvbedPdTWVhfwvTGhJAg9qPYNQkhyeaoY=,iv:0zbnrFdW6JVPp601mdKH47rce+8/dEYuQO3zXkyNnas=,tag:nEyoLlWmALNi0KADKN+LSw==,type:str]
    pgp:
    -   created_at: '2026-09-14T21:22:24Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA+UzRowyULjlS17jnbshNcjK8c3JGUVAtzNtVx7tgGHkw
            S+msoZjXeNl9jUQqT00YnBo5kJrb2eggebLeYHRGYs4PVOcjOpzatuX8iyr66uJz
            0l4BRmbcS81G8OupA/hT6Bnpey6nXiIvrekIMYon4q4VW9ygon75rVKTNXZdVuTn
            AceIL9IdVGKcTmQdG+gSwDl1q2NjnPcAdlOj3mRi94iNWpiXn2vvNrTbEpYU0fP/
            =6NYo
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
