apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whoogle
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
configMapGenerator:
- name: scripts
  files:
  - ./scripts/start-tor.sh
- name: css
  files:
  - ./css/style.css
generatorOptions:
  disableNameSuffixHash: true
