apiVersion: v1
data:
    api-key: ENC[AES256_GCM,data:ZouoCSzhfAmxJfYP/DZNI7Vkp3Bc0VDD239t7M6A9MFzxmkM4qipGVEyTfA=,iv:wclZSJwhYPDDCk5K0/LCgbL/l5t3Lhc4TWO8O9Ja8Sg=,tag:8w08XXZxrTZkpD/dIC3T2g==,type:str]
    database-password: ENC[AES256_GCM,data:a83QmZInJzY=,iv:05TQyv8Xr21G7xQhSyJPHxV+WddeBUqgdyoeAiDXnD4=,tag:puup7Eti1n60tE8YdJHiaQ==,type:str]
    database-user: ENC[AES256_GCM,data:KsoAzYQHb2I=,iv:Uv6aKIPhMmZk/YYKW7/a4sjoudAoNclVdYoXrEfv/Cs=,tag:FO/S8p1HDH370/g/DS6eqA==,type:str]
kind: Secret
metadata:
    name: sonarr
    namespace: sonarr
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-13T23:32:28Z'
    mac: ENC[AES256_GCM,data:oXFc2LIPXdjQC4AvRrPmUe26X/latQEqZiAIXUNCptpFXCg7vhx0Dmv+T2fUMGQ9+7UCbEJSF0fHR/07wRwiSV7d6bpDIPiTglKNQcp5wUH6xzefr7ZL2FSs1yEeE6MuBMWp8ja/vxw9hdP62tyJHgYgRGOBlex9yqiD/sD9hDo=,iv:yH2P9w55hfP+/T8assEq7u68khfnPaoSTt+jP8LaLkk=,tag:HTYmTk3idugivt+xlHOrDQ==,type:str]
    pgp:
    -   created_at: '2026-09-13T23:32:27Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA9ft72IsqhoB8P/cMzM2IGBMWfnpqxa58mjy3InDj5Ecw
            Y+D6YkBj9cUs4qU9GL3Q1PEdf67IvVBECV9A9JET1qKmUsd2IxoDmKKxbrFH+xWU
            0l4BtHGm1Kzs8eORWgfB6rcxiRRW7oH4MD+2JrGGOjVdtPDLB+Mr44T21HaWKV67
            L3uKY+e9xm0TofWtqr5J51/NckzXIO69si/fC616MzyVpAgRIPwIBAIchSOhqiEP
            =Zn3A
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
