apiVersion: v1
data:
    token: ENC[AES256_GCM,data:bVNWVXwXmi90dfeT4z/U6d1vN0ZlENyNTBTtLcf1tX7LBRWKhGVCkshCUKzJAPPokScXWmYncJo=,iv:M7mQ7PT9KMIhcqGJWqXMvYAZRgwVR8M/frr+hrfIPBc=,tag:7P1YCeKNENYUSBU6GtKfYA==,type:str]
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-06-04T23:04:48Z'
    mac: ENC[AES256_GCM,data:iOeE2rr+gtb/AifdyPy1Tqorcu2UHbBmt2JR0DcDCDHeeJKW0w+/qxWfv93JnZyow35UDYXE/W/ilNW+GyCwlZGLrMxyElEciEQdwiesitZR844IOuLhm/nQydOkjwiVAGpP4qB95LmJAL7Qlk7fgzVwrZFLpwT1xoANDGYmQMU=,iv:Kvxr83gapAQa6dN6DAIpvmqMALY14s3cKRzvGFDQ7eM=,tag:HACnvkguY8pQLbBjuNfouA==,type:str]
    pgp:
    -   created_at: '2026-06-04T23:04:48Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAFsjEbE5b4B9G9FQ/nUMq8GpyITT++tGzSz8hrx4U2zww
            X8iJgp+GJo/En6NLpB/YOCGPJQVrxDlL4kBwHCKuKHjpOccbgk61/vcNP3QuD+kB
            0l4BVdIh0jkkV9ere6zIn1FbYMaScIy90NBDNesNDsUCdV0gkL4BY8/K2DLCgX/2
            MHu+J2AlzKcMObrWLNA0goWXC7SBBBYcqgZjToh6w5goMXoJNn+UT2YC7rvxPBs+
            =n6+i
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
