apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: atuin
spec:
  name: atuin
  owner: atuin
  cluster:
    name: main
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: atuin
spec:
  cluster:
    name: main
  name: atuin
  login: true
  superuser: false
  createdb: false
  createrole: false
  passwordSecret:
    name: atuin
