apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: buzz
spec:
  name: buzz
  owner: buzz
  cluster:
    name: main
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: buzz
spec:
  cluster:
    name: main
  name: buzz
  login: true
  superuser: false
  createdb: false
  createrole: false
  passwordSecret:
    name: buzz
