apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: ferretdb
spec:
  name: ferretdb
  owner: ferretdb
  cluster:
    name: main
  # extensions:
  #   - name: pg_cron
  #     version: "<VERSION>"
  #   - name: pg_documentdb_core
  #     version: "<VERSION>"
  #   - name: pg_documentdb
  #     version: "<VERSION>"
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: ferretdb
spec:
  cluster:
    name: main
  name: ferretdb
  login: true
  superuser: false
  createdb: false
  createrole: false
  passwordSecret:
    name: ferretdb
