apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: ferretdb
spec:
  name: ferretdb
  owner: ferretdb
  cluster:
    name: main
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: ferretdb
spec:
  cluster:
    name: main
  name: ferretdb
  login: true
  superuser: false
  createdb: false
  createrole: false
  passwordSecret:
    name: ferretdb
