apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: maddy
spec:
  name: maddy
  owner: maddy
  cluster:
    name: main
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: maddy
spec:
  cluster:
    name: main
  name: maddy
  login: true
  superuser: false
  createdb: false
  createrole: false
  passwordSecret:
    name: maddy
