apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: matrix
spec:
  name: matrix
  owner: matrix
  cluster:
    name: main
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: matrix
spec:
  cluster:
    name: main
  name: matrix
  login: true
  superuser: false
  createdb: false
  createrole: false
  passwordSecret:
    name: matrix
