apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: miniflux
spec:
  name: miniflux
  owner: miniflux
  cluster:
    name: main
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: miniflux
spec:
  cluster:
    name: main
  name: miniflux
  login: true
  superuser: false
  createdb: false
  createrole: false
  passwordSecret:
    name: miniflux
