apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: openbao
spec:
  name: openbao
  owner: openbao
  cluster:
    name: main
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: openbao
spec:
  cluster:
    name: main
  name: openbao
  login: true
  superuser: false
  createdb: false
  createrole: false
  passwordSecret:
    name: openbao
