apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: passbolt
spec:
  name: passbolt
  owner: passbolt
  cluster:
    name: main
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: passbolt
spec:
  cluster:
    name: main
  name: passbolt
  login: true
  superuser: false
  createdb: false
  createrole: false
  passwordSecret:
    name: passbolt
