apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: prowlarr-main
spec:
  name: prowlarr-main
  owner: prowlarr
  cluster:
    name: main
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: prowlarr-logs
spec:
  name: prowlarr-logs
  owner: prowlarr
  cluster:
    name: main
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: prowlarr
spec:
  cluster:
    name: main
  name: prowlarr
  login: true
  superuser: false
  createdb: false
  createrole: false
  passwordSecret:
    name: prowlarr
