apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: radarr-main
spec:
  name: radarr-main
  owner: radarr
  cluster:
    name: main
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: radarr-logs
spec:
  name: radarr-logs
  owner: radarr
  cluster:
    name: main
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: radarr
spec:
  cluster:
    name: main
  name: radarr
  login: true
  superuser: false
  createdb: false
  createrole: false
  passwordSecret:
    name: radarr
