apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: sftpgo
spec:
  name: sftpgo
  owner: sftpgo
  cluster:
    name: main
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: sftpgo
spec:
  cluster:
    name: main
  name: sftpgo
  login: true
  superuser: false
  createdb: false
  createrole: false
  passwordSecret:
    name: sftpgo
