apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: sidekick
spec:
  name: sidekick
  owner: sidekick
  cluster:
    name: main
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: sidekick
spec:
  cluster:
    name: main
  name: sidekick
  login: true
  superuser: false
  createdb: false
  createrole: false
  passwordSecret:
    name: sidekick
