apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: spacebar
spec:
  name: spacebar
  owner: spacebar
  cluster:
    name: main
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: spacebar
spec:
  cluster:
    name: main
  name: spacebar
  login: true
  superuser: false
  createdb: false
  createrole: false
  passwordSecret:
    name: spacebar
