apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: vaultwarden
spec:
  name: vaultwarden
  owner: vaultwarden
  cluster:
    name: main
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: vaultwarden
spec:
  cluster:
    name: main
  name: vaultwarden
  login: true
  superuser: false
  createdb: false
  createrole: false
  passwordSecret:
    name: vaultwarden
