---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: adminer
          image: adminer:6.0.1-standalone
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: ADMINER_PLUGINS
              value:
            - name: ADMINER_DESIGN
              value: dracula
            - name: ADMINER_DEFAULT_SERVER
              value: postgresql.postgresql
          startupProbe:
            tcpSocket:
              port: http
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 100m
              memory: 64M
            requests:
              cpu: 10m
              memory: 64M
