machine:
  nodeLabels:
    topology.kubernetes.io/region: homelab
    topology.kubernetes.io/zone: metal
  kubelet:
    nodeIP:
      validSubnets:
        - ${TALOS_SUBNET}.0/24
  install:
    diskSelector:
      wwid: naa.5f8db4c152400459
  udev:
    rules:
      - KERNEL=="sd[a-z]", MODE="0666"
      - KERNEL=="nvme0n1", MODE="0666"
---
apiVersion: v1alpha1
kind: DHCPv4Config
name: bond0
---
apiVersion: v1alpha1
kind: BondConfig
name: bond0
links:
  - eth0
  - eth1
bondMode: 802.3ad
# Time in milliseconds between link checks
miimon: 100
# Time to wait before enabling a link after it comes up
updelay: 200
# Time to wait before disabling a link after it goes down
downdelay: 200
xmitHashPolicy: "layer2+3"
---
apiVersion: v1alpha1
kind: EnvironmentConfig
variables:
  CONFIG_NFSD_LEGACY_CLIENT_TRACKING: true
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: nfs-proxmox-backups
volumeType: disk
provisioning:
  diskSelector:
    match: disk.wwid == "naa.5000cca270def81c"
filesystem:
  type: xfs
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: nfs-proxmox-content
volumeType: disk
provisioning:
  diskSelector:
    match: disk.wwid == "eui.6479a798ea3027ce"
filesystem:
  type: xfs
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: nfs
portSelector:
  ports:
    - 2049
  protocol: tcp
ingress:
  - subnet: 10.42.0.0/16
  - subnet: 10.244.0.0/16
