---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  labels:
    app.kubernetes.io/name: vaultwarden
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: vaultwarden
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vaultwarden
    spec:
      automountServiceAccountToken: false
      containers:
        - name: vaultwarden
          image: vaultwarden/server:1.37.2
          imagePullPolicy: IfNotPresent
          env:
            - name: DATA_FOLDER
              value: config
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: vaultwarden
                  key: postgresql-url
            - name: DOMAIN
              value: https://vaultwarden.${domain}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: websocket
              containerPort: 3012
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
          livenessProbe:
            tcpSocket:
              port: 80
          readinessProbe:
            tcpSocket:
              port: 80
          startupProbe:
            tcpSocket:
              port: 80
          resources:
            limits:
              cpu: 100m
              memory: 512M
            requests:
              cpu: 10m
              memory: 64M
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: vaultwarden-config
