---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  labels:
    app: vaultwarden
spec:
  revisionHistoryLimit: 0
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: vaultwarden
          image: ghcr.io/dani-garcia/vaultwarden:1.37.2
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          env:
            - name: DATA_FOLDER
              value: config
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: vaultwarden
                  key: postgresql-url
            - name: DOMAIN
              value: https://vaultwarden.${domain}
            - name: ROCKET_PORT
              value: "8080"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: websocket
              containerPort: 3012
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          startupProbe:
            tcpSocket:
              port: http
          resources:
            limits:
              cpu: 100m
              memory: 512M
            requests:
              cpu: 10m
              memory: 64M
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
