---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vaultwarden-config
  labels:
    app.kubernetes.io/name: vaultwarden
  annotations:
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Mi"
