apiVersion: v1
data:
    postgresql-url: ENC[AES256_GCM,data:Zz+Qf4itw9Wp6riXoU82zZhcJ/2dfPPI8TP/XcOjLAIxVZmksKH8hMDkX1Ni3St1NayH22l7+uAM3k9762JZfPT0uDzbtoOcPFflgUdFZVzhEb5pXgl/ixo7m4U2LKnW0NzC+Q==,iv:IC+obN6Aik8K0D09OdXBv3eIsbxPwus+xOLucuztzAo=,tag:WVz0FIogdkH1LNYKHPQQnQ==,type:str]
    client-id: ENC[AES256_GCM,data:t6N12nN3/5l+A0Of0ivCvhdmTK1Yol7xMxakdpxBe4hed+8L55Q5ocTXPxQOXLdRfwW/Uspawy4=,iv:yxXeMoaW+yh8X5Vebq0CYcnvAFYll/lcNgzUAjTNyqE=,tag:44OqJUvbYhufd6PNI9r0pw==,type:str]
    client-secret: ENC[AES256_GCM,data:/G4c6SQxO6ITQX2Hop6DbWGwjUKifuumq6pd55I3cfjWVE0jTEc7Hw==,iv:3D1aTjVo0WHyfyH8QkA8c/bSZK3vGeZRIcfNANndFZg=,tag:gJI7x7opiwr4hL7tqjY6/Q==,type:str]
    master-password: ENC[AES256_GCM,data:zgO8QWk0+tIK5vvacUwHrw+4qroxZDGiG8DSvo5eryk=,iv:E6tPBz2pMyWDag6FCammATpWaBLUiAEhvw6nqujcIlI=,tag:WCOxA6SsLW6BS77oTQg1rQ==,type:str]
kind: Secret
metadata:
    name: vaultwarden
    namespace: vaultwarden
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-02T15:47:32Z'
    mac: ENC[AES256_GCM,data:DbSXyGhZ0/M3fEpDF/a1LqKA3bSTBBsDr6sOTKZkOvvHbHIOnAd9Xa2v9OuBMe95VD06B/YOpxzFpAOw1kYDgucL1ksBnFIYs5uYOBYAfAPlUIuSnmoRvFwRZmGXwjzCW0t2X2BFvMu28b8jmJjJFup1/1zCeT/ZbmWPs3Y3Opo=,iv:gjYU50bMhCB/vz5te98pJyhVFkVSAN3HOvLWXb4EI9s=,tag:K650y20fJY00k/UcKbthpg==,type:str]
    pgp:
    -   created_at: '2026-09-02T15:47:31Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA9edxiTm6m20cRcX39js8Ttz5M+VkG2n7QeiombPxywkw
            +ZmvHZlWscXj3dsUZluWDIxy895jK0EvVTvHBFIG8xJgPot99AH1t/oO1n4Z4OgH
            0lwBUyfT8VI4DtP2rMSl3KGfuBwzduC7sOem6pTGnobaiqwHyp8b4mvnkpOrcrB1
            EjEdws9zhzjSxsBgn4DDUpIkk9z7/B/ipF1uSYJN43dt3nEZdecJFo6KS68kPQ==
            =6JBO
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    ca.crt: ENC[AES256_GCM,data:aMNalwGbIjE1WmILzOU6L9duPJQBs44+WsrW8bnIQenKoEMfsPgePxWZwyKhWq4mY3g2Ou0pH3+sOG4+iwyrdkHLbFGWgU0kZ/UZs8jsfUTzJbreyMCK18DpbbOizKQ0XBkMOI21G6flUhFIBryZVzbD0cCnTPV57Po62q21xmfUcZbyEbJb02rbPtLQyleZPrSElARA9E/C3AxyjqAaPGmJHzw1meYX6UaJaLJKqETxe/BVluwC9EG6eSnK2IXNA5Gl0aXd3p1nbtZEixorkhLZFr3YdWTNKkVPA6IJgo7evwik5pml2bOZJMxLDUJJdVj6dopkUWyu4e0PBqVPG/c+5un6N3vnUR1L9XoSE+RvcgW5fovZVfeagPiHjpyu65Zi0PYmKuOSsGn6YFu08sWrJqmuzcCgfbnaSyVN+XNy8HM/7hh3QStofNrdziLprsm8oJX4w2u9xy/yRKDZYSei2XZZRx/EkBzc2M72tBQ50vZX1uHTwo77vgipKJgDxikGedimtAHnAxTWOSpCLZphWKyrgOlj6JgSkw414Fi2+aPYoDDZEwKCW7k2UgOsamVXOS9/AhVpjPk70X2f5cL9T52kaVfYxsGP8rW+b7jZ0Y/Xvwgw+LkId1I5q3DxXXRXZws19Z5aNX2ktWTv5ortENfsXeyDlyBsG+WDGG8IkHowHfTCSwF8J0geAnj9upz9KQG5UHhv15rX7dFfzhohsNOuklE/ZN9UZcNKj74ei0hvi9Qn75nE4klTLoAL6Od8bHzVi/1ElP5d/vzRdONlCXdvDOV3R8bEiuitX5n+ZMAxb4Gyg8LTxJuK4WwvspLiLmtAA3wZcSgRialukR7xuk2tZbnq5hPltGB39TWqZo2TQuxQHni/QhxP6wH8cIYdz2S5kvoZCSpjgwKKOcv5jBkafSjXELkOKQVqTym615HfXvWxkJqTmQp7e6ejpG69B9JXSy7k5mqblD5asojdyevIxjqbTj5tJgwafktoMhMxaHIHxsAsVWcyTl5rIAFIayvsKIcovZtfFpZjFQMsTk/b8zdecZ2t5PR7Qp5sSF95qYpPR4LpvvD9jBAFsJNdBU9CpLKtnL3l3gYxvOXH6wuGe6KBllphlY/d8+ysVpPfMVHFKsv3x+/y71QYe8XwAHfdseuQVbDvtbKON9P/cAkrvJ/+wfDRaN+5YPkrJe4DCV8Xx0jJ9/uols5u54KvwVoqn3YG5heM7Y8tZMFE5zp5KgNidzGleV2v0ZQ/vTs/HjPFK5ZPkh9NFPDQ30k5yC2GvxJbvPfJRVRmlbw/ULldj1uvXwMglfwOjT+KRPRZsTcTSjbrbKkUdfO1SaLyXQfKP4nkQGQY9X0URtWyCbJkOJ3mIRGXJ2XZk2pMPkFGfF1Vf55WZYBAMtE4APJE2mCX7iqkxkOvjwS7B+twXU/xM60sRYKUdejBpQx/x1kYcl7mlPk9KHKR6blUv/qC1fOy4saWh9yaSpcHiiNGzBNipQPMuWK6Q6Dx4tsxP62rKyujwfqzx5gbvswXbivwILYFgwehv0og9sKjn/saiSR4QE2hfKkvn3460KIZFJl12p81lx4WiMaDxbv4aY/47ZHuNDy+pxyKB7reOtuEPNcKtuJPKtv5YLGNRJHM1TsegLSsEQbJhEDwf4oQYDkSpm55NOVJiq5REn+8nxk1BzWg4ioNdf4OXnNfYimJR3NnMlvUFyIxGOWFUdZhYvClB3ENCVRqMXfv/DmEkIQ6xdTCG883CYBHufj7grNE4RPhL6vktRwreOJg3I1CxuCS0QkTcQBmK9q5uPGSX98INPATXNMb4bFSsw6FV5lY3o6j+GA1AKIruHaZaZy1rqNLBRUrWntIz0RDn2/Uj28It1WBNKcr0pAqq/n1i3mxyqjrbGqOVOvmDnkmKHwkFHeKTAm8k4fjOAo5UU1sBtPvZxG4BAe6sk2yBzcP6Z71CXgD22Y21t/omEPy20vYomFRhsXnUeA4+Bqx1/EC3g7oOMYAdJONwcnM1p8pnUkdsH0sXHSKiMmPtaPEK6jccSYeiIY9usH97es9B6mUYy1Dv3fHUduCyDA6jgYU5Z0aQYoUlz3SCzyV7oAFv+y3e0WvvWpFInvaqIUrQobqQV/0PFskObck4psxS5jm0S2SKYdQPZ4NNHekKLxW756dvDpkkDnCxhvGRqvbmcGHBol4VxLoHCC+tscGmCAbDKopd5YtsUbKS8BQAifu3xviEkrS4cWlrrqCVRQZbBJiS5eGh99MZtJk5nMZIliXfg7JHM4KpBS5xaMeALNdREH5R1MmGkgLnYMu5Pf352t85Q84h+AS1y9PTAFpBn5GzBqFilPyG8EsjYfCCBVdm8uNVIApOKjdBCPdLgiiad5DjZoYglQV5347uwjWM5TYqgyIfMdXigjgrCyFCIrY5p//1MMb5Q41WP0S4mNdP4iuAeb77cGCP7/lgLx/KXgxl4F/m3VWtITxFLgUaN/rXga12u2eXDwNqFMAxO6rzjfJhrFf9e3kPzWDck6nBU5LkBo5qBCnAyvt3tFKyhygj6qRb0EGC++mm30WI2WMShP0lu2wy7EZT09Y8mF3wZK8YofJ4MHlUZ0qMah9O7sXk7TS6UpTgkJ+bHVIw7zXMhk42If+XE5IpZ18G1H2+Zsv2OnY9TGOoKFg8zLlytCYp/dUpWORtNeJjz+UQJWkRBGRyOdLwD9qe5YExbBN8zhyr1a8HMQBq3wpKfSh3OGiH/vp+IkcFwF8aBnUqc0hs7D5Pm0tk9xfxf9quLvy2+FgjMe12/e1PkgOiAESbD7W0TBz8EH09Mzd5r1ALNcoG4gdMF1Vw4OpqQhoVOCB/3/p7OA/HfZTTHsGfHvzpMSaX8sJxA38mXTousLbmphTz6PpGaM/5+c9OkCapkeYjQ==,iv:mXhuz7jYDBaw1G3jWjbWXPuAlfFjtOWDC7gzgh+RMVQ=,tag:kf/IMGlQfysvqDq/OtaKhg==,type:str]
kind: Secret
metadata:
    name: ca-cert
    namespace: vaultwarden
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-02T15:47:32Z'
    mac: ENC[AES256_GCM,data:DbSXyGhZ0/M3fEpDF/a1LqKA3bSTBBsDr6sOTKZkOvvHbHIOnAd9Xa2v9OuBMe95VD06B/YOpxzFpAOw1kYDgucL1ksBnFIYs5uYOBYAfAPlUIuSnmoRvFwRZmGXwjzCW0t2X2BFvMu28b8jmJjJFup1/1zCeT/ZbmWPs3Y3Opo=,iv:gjYU50bMhCB/vz5te98pJyhVFkVSAN3HOvLWXb4EI9s=,tag:K650y20fJY00k/UcKbthpg==,type:str]
    pgp:
    -   created_at: '2026-09-02T15:47:31Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA9edxiTm6m20cRcX39js8Ttz5M+VkG2n7QeiombPxywkw
            +ZmvHZlWscXj3dsUZluWDIxy895jK0EvVTvHBFIG8xJgPot99AH1t/oO1n4Z4OgH
            0lwBUyfT8VI4DtP2rMSl3KGfuBwzduC7sOem6pTGnobaiqwHyp8b4mvnkpOrcrB1
            EjEdws9zhzjSxsBgn4DDUpIkk9z7/B/ipF1uSYJN43dt3nEZdecJFo6KS68kPQ==
            =6JBO
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
