apiVersion: v1
data:
    username: ENC[AES256_GCM,data:5cVMLjxOMyeLzJAZ7buwDQYi5lTrNRz/fbQbLlulgx1leWsHpTiDQA==,iv:Y0W9Hxwdk0X7y0TfozqhZiuhtQdPZnIChA6IhbmbwvU=,tag:dBQ5EFkUO0jbmsmmWNdiCQ==,type:str]
    password: ENC[AES256_GCM,data:1FKYYTV0X2+we2c9ZWsK2GjLBvo2l0siHxpIji6goWY=,iv:vf1/WsYrF1Vpyy1i1Y6jPYN7/TEbW475naeu1jEZNN0=,tag:JAS3lKWum/ioAt15YmSyyw==,type:str]
kind: Secret
metadata:
    name: talos-proxmox-autoscaler-credentials
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-26T20:51:19Z'
    mac: ENC[AES256_GCM,data:hIlQwcvQUK8o1H9JN47BR4cXmDMrknuMDuTmXSF9rop53+AWhN633FEkclumXtlz2CKkhm96nq3++Yy80fDPOCNfcI5/k1oqu1qwFXb60iI1MAtmCVQHvJiLHfkHKjd2ftqY2zVdz6IzLRiGi8hTpVSkpQ935nVNDI8uWRnzZHM=,iv:D4sSbalXFLiJ0zgfCHjv8KfcrUBF9h7/bOZOPZ88Pp8=,tag:pCK22/l5J0XidVzv1vujqA==,type:str]
    pgp:
    -   created_at: '2026-07-26T20:51:18Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA+tiYap44P6NrE6qeVu/+mT4qxfKCXcA75KhEe/PpV2kw
            jVD+YPz6NxqHd8GxS/5oaMGMu5tsrYPfyqD4y69NcgHk6HB41UCnqZIuGlJdx3ey
            0lwB42T7Vctu73ZTSeCNptuV4yvbp7LkoHIqYGw+kNCHmHZeuTyIoFEMXRjx0D7Y
            tNDIZ04AR9STzeeOpvoZgFDmyWu4TWguohF9PwNj+SO+TiHtGlznlqAYjh04yg==
            =kVkh
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
