apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:d4jfLWp/aqWHsYr6/QIZAerrFcclxj7h,iv:GKjx09RnhB+gN/4rJhPV7g3kzIKbAa3v7sGfcP9Dbtw=,tag:t01ZKrTtvrtALBekZPDoVw==,type:str]
    password: ENC[AES256_GCM,data:vV9TnAAUZdJOhe/3abZAxPzHgVFdGS762VBaWQ==,iv:2lqapYZPZlsQcVKpAcuRukz8dSO9K7LvN+i3Un9+4dE=,tag:Dl/4v1YIvA7GH2nc2lezbg==,type:str]
kind: Secret
metadata:
    name: talos-proxmox-autoscaler-credentials
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-27T19:17:02Z'
    mac: ENC[AES256_GCM,data:UAHCm/b8V2vlA/HXVLaOdxunYJ8roWl6YB6nvtXU/CYjBQ4s0nLxuKoYes9wxDVbTKsAKr/GXPfn3PRE9fmekoeDnaTM3HzftWRaIPu3Ig+6GIUlU7lKI034ckJhR4PaR6Swyil27CAN/BiyjZWpJF+ZaVRtilz6PFTRq510AmQ=,iv:stKE5T22RdHrZakVN+gdnnLdXL8eb53ReMNN6W+f6Fc=,tag:SumwFcVZ+qO5xZ7GVVdDpg==,type:str]
    pgp:
    -   created_at: '2026-07-27T19:17:01Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAIu+j5t7EKFXaGaxknYOxL0es7NgMZGJF4nmulM8B43gw
            RlzqhUpaW7twD7kwWIbUfcO5MunUfY7OcO7FZF4xkGsJFdPghu1U3ZFDzbp/hT2l
            0l4B2B1wQ7EeRgxuYsuS0fJj1oENfZ6I7asAhR+9XtV7idADBVugkjZEGOGm/YGg
            zL3/YlMu3OoahRhS53f006UHfjRRm2tGDYdHhMV3fwFvh6e+PU4H3SWlHud3lsT7
            =6tMx
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
