apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:VE5ua+qTkYZUb78RGAveUJyS051MuwV1haUpfw==,iv:lL06bgUUa+Lrx/DlGLd4ikFtzK18otgPK2LeS/z7QV4=,tag:n1bOCBq7MlFTT4GIeuyyKA==,type:str]
    password: ENC[AES256_GCM,data:Ob64uVBp+DMc8QcA3ASKxdCAn6YYoZK1,iv:1ivMxb77q/frd9LjH1lCsa/lxSipdJXcDE0n5wn4UH4=,tag:Ioc+RxFBi7vyW6qt4OZ9fQ==,type:str]
kind: Secret
metadata:
    name: talos-proxmox-autoscaler-credentials
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-28T18:39:55Z'
    mac: ENC[AES256_GCM,data:Orrw5qojgR+DZUPEHoE4F/TqI3Gcd9UyY/jHaLdkNbzYRNvtbxyFLm/Vbg2rQ+Y+G02G9Gb1dBB6fr5UKpSWWfN9lXBMBzw+WmoF0zxsS/LR+jDCm1QXEluAIvy2q/s2Hy0oP9DYjKyVnILhzYtravTA8Aw7rH3PSQ+zlaAkzpo=,iv:lITN+kliDrS8jlyQOaEoJS5EAuPoOT2drZLAKgntEHs=,tag:oVHlWwbhoLCFFFKvqFRZvQ==,type:str]
    pgp:
    -   created_at: '2026-07-28T18:39:54Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAtM99buTKV8uJtLm70bEOT5nLiuRnq7HuHgjN5abUHHww
            AgSzpJCUjluJdK3/QzaIZ6WgKG6Bi3wES4NObPeQv+YuzMFYUVkxu5nAQqnPjHAw
            0l4BxXfKJLXOPfIHRhK9Q5ug7TjKQx0mEMM4w+Hi63j/zofw3pAHuJ2mM2jdTGBz
            WhQeL/BT3yne0/LViWF3j20bDM1Z4wJWPoKqzpG5KKzKao32/7eI7wAP7T2tlVA6
            =IANx
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
