---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ferretdb
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ferretdb
  template:
    metadata:
      labels:
        app: ferretdb
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: ferretdb
          image: ghcr.io/ferretdb/ferretdb:2.7.0
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          envFrom:
            - secretRef:
                name: ferretdb
          ports:
            - name: ferretdb
              containerPort: 27017
          startupProbe:
            tcpSocket:
              port: ferretdb
          livenessProbe:
            tcpSocket:
              port: ferretdb
          readinessProbe:
            tcpSocket:
              port: ferretdb
          resources:
            limits:
              cpu: 100m
              memory: 64M
            requests:
              cpu: 10m
              memory: 64M
