apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: vm-genji
spec:
  limits:
    cpu: "64"
    memory: 512Gi
  template:
    spec:
      nodeClassRef:
        group: karpenter.proxmox.sinextra.dev
        kind: ProxmoxNodeClass
        name: vm-genji
      requirements:
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        # - key: "topology.kubernetes.io/region"
        #   operator: In
        #   values: ["homelab/genji/100"]