apiVersion: platform.${publicDomain}/v1alpha1
kind: ProxmoxVmTemplate
metadata:
  name: vm-genji
spec:
  nodeName: genji
  name: vm-genji
  description: Managed by Crossplane
  template: true
  tags:
    - talos
    - karpenter
  # started: true
  # onBoot: true
  bios: seabios
  # machine: q35
  scsiHardware: virtio-scsi-pci
  cpu:
    cores: 2
    type: host
    # architecture: x86_64
  memory:
    dedicated: 4096
    # floating: 0
    # shared: 0
  disk:
    - interface: scsi0
      datastoreId: local-lvm
      size: 50
      # ssd: false
      replicate: false
      backup: false
  networkDevice:
    - bridge: vmbr1
      model: virtio
      firewall: false
      vlanId: 20
      macAddress: "00:00:00:01"
  # operatingSystem:
  #   type: l26
  # agent:
  #   enabled: true
  #   trim: true
  #   type: virtio
  #   timeout: ""
  #   waitForIp:
  #     disabled: false
  #     ipv4: true
  #     ipv6: false
  # vga:
  #   memory: 16
  #   type: std
  #   clipboard: vnc
  # hostpci: []

  # smbios:
  #   serial: "worker-vm"
