apiVersion: karpenter.proxmox.sinextra.dev/v1alpha1
kind: ProxmoxNodeClass
metadata:
  name: vm-genji
spec:
  # # Region where this NodeClass is applied
  # # Optional: if not set, all regions will be used
  # region: cluster-1

  # # PlacementStrategy defines how VM should be placed across zones.
  # # Optional: if not set, Balanced strategy will be used
  # placementStrategy:
  #   zoneBalance: Balanced|AvailabilityFirst

  # InstanceTemplateRef is a reference to a Kubernetes Custom Resource
  # that defines the virtual machine template used for creating instances.
  # Required
  instanceTemplateRef:
    # Kind specifies the type of the instance template resource.
    # Valid values: ProxmoxTemplate, ProxmoxUnmanagedTemplate
    kind: ProxmoxUnmanagedTemplate
    # Name of resource
    name: vm-genji

  # # BootDevice defines the root device for the VM
  # # Optional: If not specified, the system will use the storage device on which the template is stored.
  # bootDevice:
  #   # Size of the boot device
  #   # Valid formats: 50G, 50Gi
  #   size: 50G

  # Tags to apply to the VMs after creation
  # Optional, in place update supported
  tags:
    - talos
    - karpenter

  # # MetadataOptions contains parameters for specifying the cloud-init metadata
  # # Optional, defaults type is `none`
  # metadataOptions:
  #   # Type of the metadata to expose to the VMs
  #   # Valid values: none, cdrom
  #   type: cdrom

  #   # SecretRef is used if the type is `cdrom`. It references a secret that contains cloud-init metadata.
  #   # It can include the following keys, all of which are optional:
  #   # - `user-data` - Userdata for cloud-init
  #   # - `meta-data` - Metadata for cloud-init
  #   # - `network-config` - Network configuration for cloud-init
  #   templatesRef:
  #     name: karpenter-template
  #     namespace: karpenter-proxmox

  #   # valuesRef is a reference to user-defined values.
  #   # All keys from this reference can be accessed in templates as .Values.<key>
  #   # Optional
  #   valuesRef:
  #     name: karpenter-template-values
  #     namespace: karpenter-proxmox

  # # SecurityGroups to apply to the VMs
  # # Optional, in place update supported
  # securityGroups:
  #   - name: kubernetes
  #     # Interface to apply the security group
  #     interface: net0

  # # ResourcePool is the Proxmox resource pool name where VMs will be placed.
  # # Optional
  # resourcePool: k8s-pool