apiVersion: karpenter.proxmox.sinextra.dev/v1alpha1
kind: ProxmoxTemplate
metadata:
  name: vm
spec:
  sourceImage:
    url: https://factory.talos.dev/image/3ace32a67f3d1aa0303abb3f05db1715da1129b400e99aaadb8c32f87130e97b/v1.13.6/nocloud-amd64.iso
    imageName: nocloud-amd64.iso
  storageIDs:
    - local
    - system
  # # Type of virtual machine (Optional)
  # # Can be one of pc, q35
  machine: q35

  # agent:
  #   # Enable/disable QEMU Guest Agent (Optional)
  #   enabled: true
  #   # Type of the guest agent (Optional)
  #   # Can be one of virtio, isa
  #   type: virtio
  #   # Enable/disable freeze the filesystem on backup (Optional)
  #   fsFreezeOnBackup: true
  #   # Enable/disable fstrim for cloned disks (Optional)
  #   fsTrimClonedDisks: false

  # CPU configuration.
  cpu:
    # CPU type (Optional)
    # Can be one of host kvm64, x86-64-v2, x86-64-v2-AES, x86-64-v3, x86-64-v4
    # Default value is x86-64-v2-AES
    type: host
    # # CPU flags (Optional)
    # # See official documentation https://pve.proxmox.com/wiki/Manual:_qm.conf
    # flags: +pdpe1gb

  # VGA configuration.
  vga:
    # Type of the VGA device (Optional)
    # Can be one of none, serial0, std, vmware
    type: none
    # # Memory of the device (Optional)
    # memory: 16

  # List of network interfaces (Required)
  # At least one network interface must be defined.
  network:
    - # Name of Proxmox interface netX, e.g. net0 (Optional)
      name: eth0
      # # Model of network hardware (Optional)
      # # Can be e1000, e1000e, rtl8139, virtio, vmxnet3
      # # Default is virtio
      # model: virtio
      # Bridge to attach the network device to (Required)
      bridge: vmbr1
      # # MTU of the interface (Optional)
      # mtu: 1500
      # VLAN tag to apply to packets on this interface (Optional)
      vlan: 20
      # Interface should be protected by the firewall (Optional)
      firewall: false

      # # IP configuration for this interface (Optional)
      # # If not specified, DHCP for IPv4 and Auto for IPv6 will be used.
      # # Address4 and Address6 must include the prefix length.
      # address4: 192.168.0.0/24
      # address6: fd00::/64
      # # Default gateway for IPv4 and IPv6 (Optional)
      # gateway4: 192.168.0.1
      # gateway6: fd00::1
      # # DNS servers for this interface (Optional)
      # dnsServers:
      #   - 1.1.1.1
      #   - 2001:4860:4860::8888

  # # List of PCI devices to attach to the VM template
  # # Supported Resource Mapping devices only.
  # pciDevices:
  #   - # Mapping is the group
  #     mapping: nvidia
  #     # MDev Type (Optional)
  #     mdev: nvidia-660
  #     # Enable/disable PCIe (Optional)
  #     pcie: true
  #     # Use as default VGA (Optional)
  #     xvga: false

  # Tags to apply to the template (Optional)
  tags:
    - talos
    - karpenter