apiVersion: v1
stringData:
    config.yaml: ENC[AES256_GCM,data:hgi2qJJmqrOMBorYh7uZs4QB57jtMhvIL1+g4CiLlHCXZqlYlShrms/VDhL5m20NYS+paOTYkww2Jy59n2ug8MfrYg17eHqS0aJu2Oc89UYhflGUxMrKDTWONqXKoEJXGb89ahI42BN+RmbVyJPcDAIxfe9akx5hJYLJhIb96/qlQSDY2p+g8wIR3BNg0dE3dS3IDcXa4VzHnEVIQ8RM4pjLj4g4PwkYPItOkPNXzwWQm/8tKmrwsZBPeZQBW6yqGutR4bGXNqfVqsb68GrRrA==,iv:lRnWIVG9jDaVRzqSwoCXGKXz87moZxKkVmMUMqgTyEM=,tag:Op7RKWe4CfohpNdMTnboKw==,type:str]
kind: Secret
metadata:
    name: karpenter-provider-proxmox
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-12T13:18:07Z'
    mac: ENC[AES256_GCM,data:jDQC+cDGOX0YQE1XnS9pyD1nmM1iLm3LV4kKu0MUEPJLc8oxCuJuGXUqVItPjLNxO7wIphaSgVZDUJvuh+cVdTDwVsPGibunesok4yNC7GmMAdnBi1jDLAbbHv8NQy8Cj3JXzUHb2vmlPcr//1d7JVGyGIVeBYG862luwdEzU/Q=,iv:GB+gz8TAmHRuMd6AqD81ZzkmQLzog0F9PR06kdnRWUg=,tag:m0a2zFwSesZwWqPJB7u4UA==,type:str]
    pgp:
    -   created_at: '2026-07-12T13:18:06Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdA3d63oFWXC0ad5IB4kqi18AiMm1FAAD7GFjqxDK87Ohcw
            dKL1LdNovFU1GaKBo9mFa6ljsbbd0MpDL9Irr50iTJSxgBiLPYOcZKJyXcHNeDh5
            0l4B7lmdJeQk5rg/wiSx2StDaqUX56Dh9SJGW22GFh1xQtGwjvDN7cjO4Pyfc9R4
            RPXSg3FpW3tdacT6PxW5wuvOa/R6wlxi2wFQEZAupPPmZlEDPtmVn1M5eYKKLc3U
            =klbO
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
