---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: infisical
spec:
  interval: ${interval}
  url: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infisical
spec:
  interval: ${interval}
  chart:
    spec:
      chart: infisical-standalone
      version: 1.10.0
      sourceRef:
        kind: HelmRepository
        name: infisical
      interval: ${interval}
  values:
    infisical:
      enabled: true
      autoBootstrap:
        enabled: true
        organization: "homelab"
      resources:
        limits:
          memory: 1000Mi
        requests:
          cpu: 350m
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containerSecurityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
    kubeSecretRef: infisical-secrets
    ingress:
      enabled: false
      nginx:
        enabled: false
    postgresql:
      enabled: false
    redis:
      enabled: false
