apiVersion: v1
data:
    AUTH_SECRET: ENC[AES256_GCM,data:BcFbI84le1Or4Wb0RJSpMSi/PY0w2myO9/KY8dIrqCZwf7uvBchGGuyaJvPUOqexAn7GduFwWzs5mMA8,iv:MVOW9uwH6xxHL/N8svUWYtSy5melafjYVCGiSVgwI2A=,tag:kntNB/5YNnfrYH9oJR3Dwg==,type:str]
    DB_CONNECTION_URI: ENC[AES256_GCM,data:w+cz7sAg1VZ2+KlR3fwDVZGpC/CNJI2f/ykROgcvbUjUAiLTXCM4dKf8YlvhZVNp2qjz86Em0H7IHmvycRJE1i5QmODjZlW51u4JPv8HsxEVqa3lvds2+in6Ip0=,iv:g/JzF76O/0L5alylxhxSNM17OiTZL0qnONAaneQmt2M=,tag:92cIu112WcMKuK0VofVL7g==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:QVO4czAO80VnaDtHjXRMMaJVceoCYIOwuTUfj0PNVA+t1LsFEqM15y7IlD0=,iv:VkyXz43xT4AHw0U4hU2qwSBiPeAdsq4ARXgfLZFQm4o=,tag:2j97PLSmTfO9qkizg++LCw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:ZNZDq5xr3DNeIyge6vO2wtvBycTb4HRH/5oKXSxLKuOlTJZI,iv:4WH5tDiOCG8EuMrIk3x8uaWE3Df0vJU3Wu2tOgIiShk=,tag:XZCbtKCUtaen+lqrajSqZg==,type:str]
    SITE_URL: ENC[AES256_GCM,data:Jfzgls7XK7omlSx5Cs8/oGD6SKieWu1XgOvoJyBjHLTX/iWT,iv:nPu41oODGjp3mYmLsKt0FaHymbfHdk+m9E9Cgd1MD40=,tag:Tx6P4dPVHMxv+KGaiN8OJw==,type:str]
kind: Secret
metadata:
    name: infisical-secrets
    namespace: infisical
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-01T14:04:05Z'
    mac: ENC[AES256_GCM,data:vhhpCEWPo1AOcAh8WGpNi3tBO7N694oyr4WmqjVgDnn28xR5VRsXkDzlR59pSYxNTmdCgKIM5Qf5hSPJZ44jfQg/BO89NchKoXDrSW5fRwekLnfhQC/4oYgcc7m6bdSJ5zxcZGBPSHFSkAfmjgblKPqhk0NnN7vspZrtv4fmN/Q=,iv:O9umV6pzcID/zaEFMKwlmp+tsxhggM0OCSwTPAqVZ+k=,tag:fN17/XvI0g4xS+R96yfMPg==,type:str]
    pgp:
    -   created_at: '2026-09-01T14:04:04Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAMKDSRG9/nBQ1xWIs86DzvEfsWLhKbcmOnWWP20n+gVgw
            aIclKmFPITC0jY6hLy6uj1dWsDImzwWkAU8dzwqoEfkgkcUcmhFtAP1LaBAQxJ4X
            0l4BPkCZefcQcMbWFwDnqHO8DVkMkxxmqaJ1lrKmqRhMCVruAFlMROPf7+Ti9yQf
            txhoS5YCGMzUS/mk07XvajaYM3ALFXUAcbCXz0q/7iCecvo8nvHkjYpyMYvDEUHM
            =0aw0
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:ayjSRQQ+bZbU4aSDX99KUw==,iv:tWNyo2p4Pv5MfNaxZwjnAkOBBz9VPCjhURwBl7yPVOk=,tag:OF2+mUmOqnMmBoA5IVGBgw==,type:str]
kind: Secret
metadata:
    name: credentials
    namespace: infisical
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-01T14:04:05Z'
    mac: ENC[AES256_GCM,data:vhhpCEWPo1AOcAh8WGpNi3tBO7N694oyr4WmqjVgDnn28xR5VRsXkDzlR59pSYxNTmdCgKIM5Qf5hSPJZ44jfQg/BO89NchKoXDrSW5fRwekLnfhQC/4oYgcc7m6bdSJ5zxcZGBPSHFSkAfmjgblKPqhk0NnN7vspZrtv4fmN/Q=,iv:O9umV6pzcID/zaEFMKwlmp+tsxhggM0OCSwTPAqVZ+k=,tag:fN17/XvI0g4xS+R96yfMPg==,type:str]
    pgp:
    -   created_at: '2026-09-01T14:04:04Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAMKDSRG9/nBQ1xWIs86DzvEfsWLhKbcmOnWWP20n+gVgw
            aIclKmFPITC0jY6hLy6uj1dWsDImzwWkAU8dzwqoEfkgkcUcmhFtAP1LaBAQxJ4X
            0l4BPkCZefcQcMbWFwDnqHO8DVkMkxxmqaJ1lrKmqRhMCVruAFlMROPf7+Ti9yQf
            txhoS5YCGMzUS/mk07XvajaYM3ALFXUAcbCXz0q/7iCecvo8nvHkjYpyMYvDEUHM
            =0aw0
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
