apiVersion: v1
data:
    AUTH_SECRET: ENC[AES256_GCM,data:Bg5fChmlNMLxHC3wzMreW9DRBolS/wqHUNf0iIvMqkwA+tGSasgpafdAixkIj+iCK2D3DJo+YwNoVzi9,iv:Kcz5ie3Jkh+GRyK+s2pdyFimx4OVBgj0n+nms4x+g9o=,tag:F56FJVXyB4c/Lgne2cdjFA==,type:str]
    DB_CONNECTION_URI: ENC[AES256_GCM,data:pqhIGkCKWa5i0NYld5STYmh+f4vwjRNvEUOHqHqR7Kol0TqiJVmDPqC1uk8AVmKaYwHGbK7C9/+rt3KRtfc85Q9Ss396ngoYWczva/q3e/G+2aWaiJwi6Tm2KFI=,iv:KCUHtcSqJzY7pE1KJKmLFm/vcyA1NLkpIabgjR35x2w=,tag:mpP+bPS0gh5dWzQVJom9fw==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:18QfjWMZ1g5bQKgqHrHgT7iibPuKvIJxL0f2xvDmHO8t8YtjsnPcltpD30g=,iv:mLA5q9lMkyfTNxs6kXtQHymUa7JGhoySDOZt3SZGiEE=,tag:ucnGa04JFUHsz586icjmhA==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:gXEY9nNEDfCJuK5H9iNnn/Kh0XGPFZVOP7WRNoDiRIgDJXhm,iv:exrQYRNZTfbRVPJwoB+ye9QfrFYpfkTts6GdD2lb/CY=,tag:FlpDvb7ZnyjEuwtVctcEeQ==,type:str]
    SITE_URL: ENC[AES256_GCM,data:T4kDC03u9bHzcgZyypTO34N96GM9rw/6+G8xzLuU4aBUsMqn,iv:fVeBPrZwyIO6zSGwf/tyv2sEF0JLED564LCDfl8vhNA=,tag:p8GOVLxxbV9bliwC8yr8ag==,type:str]
kind: Secret
metadata:
    name: infisical-secrets
    namespace: infisical
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-01T20:51:24Z'
    mac: ENC[AES256_GCM,data:Q2S9XgxElPQokygFoz8T+tRCLlipvdzxOPC4Nblo0LIMDVDpWEXw308NGcpkBNbfAvVkQ/YUHjQzDvt/+MaB+3YF0/jg08kdr3TrACVamaEIDT/C3XYILV2DlpqT3HXEGlygmQv5wBAx1LufAdybLYIpnzta0D2InSGwhiSX50I=,iv:nElxQQWk/pRY9vnjlKmdqiBh/nO4lhqA3hN/BB8UEq8=,tag:LQrbbsEVLiciX2nw46YuFw==,type:str]
    pgp:
    -   created_at: '2026-09-01T20:51:23Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAJTDS+BXhrJjKHQZR52FP/XhCGNTBBku2tQNjPbpAUAQw
            NKTB5f8abncNtfcbB3jYfUiV28nZmXfKgSC8+WlGMgHxjl00AE9yGimC1ykQF9Ns
            0l4BCgHx/E/iv2hVYKf0sJ5qkO11g6uG7a/FJYQKAe7xhogdP5fz3gDgYzi9GZ/C
            PGTXapFPpFV+AxHIE15DYOFRo1tREWziVgfWMWcEQ26xVqSF3KXJhQBS1uEs+w45
            =SekG
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:PJpVcHGgpFmqLexOh+QwqARpCkqnF0uLTNZQXE5VYA8=,iv:cEJPagJGmwgGuHcBUArJ0AcmuYasYk7ftNR56gJRreM=,tag:BUd2kcCSjPA3anOcmmPqLw==,type:str]
kind: Secret
metadata:
    name: credentials
    namespace: infisical
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-01T20:51:24Z'
    mac: ENC[AES256_GCM,data:Q2S9XgxElPQokygFoz8T+tRCLlipvdzxOPC4Nblo0LIMDVDpWEXw308NGcpkBNbfAvVkQ/YUHjQzDvt/+MaB+3YF0/jg08kdr3TrACVamaEIDT/C3XYILV2DlpqT3HXEGlygmQv5wBAx1LufAdybLYIpnzta0D2InSGwhiSX50I=,iv:nElxQQWk/pRY9vnjlKmdqiBh/nO4lhqA3hN/BB8UEq8=,tag:LQrbbsEVLiciX2nw46YuFw==,type:str]
    pgp:
    -   created_at: '2026-09-01T20:51:23Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAJTDS+BXhrJjKHQZR52FP/XhCGNTBBku2tQNjPbpAUAQw
            NKTB5f8abncNtfcbB3jYfUiV28nZmXfKgSC8+WlGMgHxjl00AE9yGimC1ykQF9Ns
            0l4BCgHx/E/iv2hVYKf0sJ5qkO11g6uG7a/FJYQKAe7xhogdP5fz3gDgYzi9GZ/C
            PGTXapFPpFV+AxHIE15DYOFRo1tREWziVgfWMWcEQ26xVqSF3KXJhQBS1uEs+w45
            =SekG
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    identityId: ENC[AES256_GCM,data:H3TnepxOB4bhd9AMJmo7Gm9oQZgphw4SIfbOAeMIUAI5TjigGCCh7evU2WOWz/PQ,iv:V4prMfXm71mowK1eqTx/iXNFI9pKboFZ18oaTCgM5Bg=,tag:aqLLGBkdx7pHx9AnJI9TNA==,type:str]
kind: Secret
metadata:
    name: kubernetes-credentials
    namespace: infisical
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-01T20:51:24Z'
    mac: ENC[AES256_GCM,data:Q2S9XgxElPQokygFoz8T+tRCLlipvdzxOPC4Nblo0LIMDVDpWEXw308NGcpkBNbfAvVkQ/YUHjQzDvt/+MaB+3YF0/jg08kdr3TrACVamaEIDT/C3XYILV2DlpqT3HXEGlygmQv5wBAx1LufAdybLYIpnzta0D2InSGwhiSX50I=,iv:nElxQQWk/pRY9vnjlKmdqiBh/nO4lhqA3hN/BB8UEq8=,tag:LQrbbsEVLiciX2nw46YuFw==,type:str]
    pgp:
    -   created_at: '2026-09-01T20:51:23Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAJTDS+BXhrJjKHQZR52FP/XhCGNTBBku2tQNjPbpAUAQw
            NKTB5f8abncNtfcbB3jYfUiV28nZmXfKgSC8+WlGMgHxjl00AE9yGimC1ykQF9Ns
            0l4BCgHx/E/iv2hVYKf0sJ5qkO11g6uG7a/FJYQKAe7xhogdP5fz3gDgYzi9GZ/C
            PGTXapFPpFV+AxHIE15DYOFRo1tREWziVgfWMWcEQ26xVqSF3KXJhQBS1uEs+w45
            =SekG
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
kind: Secret
metadata:
    name: infisical-token-reviewer-token
    namespace: infisical
    annotations:
        kubernetes.io/service-account.name: infisical-token-reviewer
type: kubernetes.io/service-account-token
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-01T20:51:24Z'
    mac: ENC[AES256_GCM,data:Q2S9XgxElPQokygFoz8T+tRCLlipvdzxOPC4Nblo0LIMDVDpWEXw308NGcpkBNbfAvVkQ/YUHjQzDvt/+MaB+3YF0/jg08kdr3TrACVamaEIDT/C3XYILV2DlpqT3HXEGlygmQv5wBAx1LufAdybLYIpnzta0D2InSGwhiSX50I=,iv:nElxQQWk/pRY9vnjlKmdqiBh/nO4lhqA3hN/BB8UEq8=,tag:LQrbbsEVLiciX2nw46YuFw==,type:str]
    pgp:
    -   created_at: '2026-09-01T20:51:23Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAJTDS+BXhrJjKHQZR52FP/XhCGNTBBku2tQNjPbpAUAQw
            NKTB5f8abncNtfcbB3jYfUiV28nZmXfKgSC8+WlGMgHxjl00AE9yGimC1ykQF9Ns
            0l4BCgHx/E/iv2hVYKf0sJ5qkO11g6uG7a/FJYQKAe7xhogdP5fz3gDgYzi9GZ/C
            PGTXapFPpFV+AxHIE15DYOFRo1tREWziVgfWMWcEQ26xVqSF3KXJhQBS1uEs+w45
            =SekG
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
kind: Secret
metadata:
    name: infisical-infisical-token
    namespace: infisical
    annotations:
        kubernetes.io/service-account.name: infisical-infisical
type: kubernetes.io/service-account-token
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-01T20:51:24Z'
    mac: ENC[AES256_GCM,data:Q2S9XgxElPQokygFoz8T+tRCLlipvdzxOPC4Nblo0LIMDVDpWEXw308NGcpkBNbfAvVkQ/YUHjQzDvt/+MaB+3YF0/jg08kdr3TrACVamaEIDT/C3XYILV2DlpqT3HXEGlygmQv5wBAx1LufAdybLYIpnzta0D2InSGwhiSX50I=,iv:nElxQQWk/pRY9vnjlKmdqiBh/nO4lhqA3hN/BB8UEq8=,tag:LQrbbsEVLiciX2nw46YuFw==,type:str]
    pgp:
    -   created_at: '2026-09-01T20:51:23Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAJTDS+BXhrJjKHQZR52FP/XhCGNTBBku2tQNjPbpAUAQw
            NKTB5f8abncNtfcbB3jYfUiV28nZmXfKgSC8+WlGMgHxjl00AE9yGimC1ykQF9Ns
            0l4BCgHx/E/iv2hVYKf0sJ5qkO11g6uG7a/FJYQKAe7xhogdP5fz3gDgYzi9GZ/C
            PGTXapFPpFV+AxHIE15DYOFRo1tREWziVgfWMWcEQ26xVqSF3KXJhQBS1uEs+w45
            =SekG
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
