apiVersion: v1
data:
    AUTH_SECRET: ENC[AES256_GCM,data:1Dy/FmikUflrpAm+pwOoRTcETeOBiHXA9NnJN+emOKSn6E5jm6psfvU1zFQOvIQh6DKghDcyWpayzzdC,iv:VRQ/GW65R0ONZb4Y/S9mEDjfqvb+NwIJF5Kz9jN7RBc=,tag:FLh3Z5m8PppwCrKq/PHsNQ==,type:str]
    DB_CONNECTION_URI: ENC[AES256_GCM,data:NdMt8cHWjD/dfKZRSnVALOBafr4oFVg1Fs7A0k1A7epOpFPPjx5VRWiwZxA9iG0C1TY+GMDk8gLkmMEtZ8CnCSG2EcmgOTeuh6bLV6qHQXW/Nw9+gEXDVowP454=,iv:CrJtNPGPStJF71n7l9xEEwJ7WnaJF8zkz92KiYVifBY=,tag:BpklFlBoiPZF7YAbTgkPCw==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:5tmVVkGQp8S19Bv2WGuq1Yu7ucSwguLT4G/6hLYljSA1Co2SIANPJ7HqVNc=,iv:eOvUQ+kH/BuLg1aRDSftaTxcyqL6Iv9jBEdUaN2HZPg=,tag:AsY+CoDolNcoCoOvV1pkTQ==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:5IfsFC2V5CATSPKuQfvXf+nu7XmGP87jSMDSlaELBfnv/5mb,iv:k3eFjLpUpDSRlaCQasS2du2jt/DyvjJWnT0bzZAytYg=,tag:l766ZC1ElAUQz7kA9JvKLg==,type:str]
    SITE_URL: ENC[AES256_GCM,data:S+Rr80+mn9qEPdu9wduaXJ9mtJgIFBGutR7osF5/he866qGB,iv:kURZxYRQVZ+PZpSxkWk7xF2OzjEC7GZxkGy16pgZ9vI=,tag:SdPuszn3XUlk9LO98/YIsQ==,type:str]
kind: Secret
metadata:
    name: infisical-secrets
    namespace: infisical
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-01T16:05:16Z'
    mac: ENC[AES256_GCM,data:e8r4I4qFaYgMUL0L6CVCxYqd6oI6CgS7eehNHiP/lZmf7zwlYZW+6NBSfviViDJ7gZ//h3trcyBVsZMrqJgDZICueXcNrzVFPbDGNfx13Y37ECcnvRLBrCwsYDaAwhXSS0Alsx8eD88k3yPULhG1pGNiq0PGw4VJLvcNzOjOuQU=,iv:2SIvmJmwAvlqRStKCgy8OQ87zEM3XMxPf72R6UuaAnA=,tag:J7oyBCikQpuag+drqd9NQw==,type:str]
    pgp:
    -   created_at: '2026-09-01T16:05:15Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAYG72T0EegoMh8hpDIo5aA5wGN/BtVh5AayGGd+ibzkYw
            dO3jQldo7obFXAEKb8fu4WpOFRG0wZ8T4lv82YRUTibe7khozZx4vKSX7EkSSp1K
            0l4BCArYyR0D8fIKImNXPlOzy6Drmox7vYAzjm4umt9ebTIzLCaO4jmDFdKCrViP
            UBp2Z+lxlMQiO9cgc978lDz6/nbitobOJvTIW+t1lvYuK8Wf8jbGZ1Q9QUVMPXBA
            =WMFO
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:b0w8QWabamdrh9gjYwNhaXn0QebzFVf1EYhllxd9ncI=,iv:RXsTR1ZoVqXSjka9dsko8rq+/0JHCg0ZTqiKo0YU9mY=,tag:TBTpsHmQXKEAv033+Z9QNg==,type:str]
kind: Secret
metadata:
    name: credentials
    namespace: infisical
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-01T16:05:16Z'
    mac: ENC[AES256_GCM,data:e8r4I4qFaYgMUL0L6CVCxYqd6oI6CgS7eehNHiP/lZmf7zwlYZW+6NBSfviViDJ7gZ//h3trcyBVsZMrqJgDZICueXcNrzVFPbDGNfx13Y37ECcnvRLBrCwsYDaAwhXSS0Alsx8eD88k3yPULhG1pGNiq0PGw4VJLvcNzOjOuQU=,iv:2SIvmJmwAvlqRStKCgy8OQ87zEM3XMxPf72R6UuaAnA=,tag:J7oyBCikQpuag+drqd9NQw==,type:str]
    pgp:
    -   created_at: '2026-09-01T16:05:15Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAYG72T0EegoMh8hpDIo5aA5wGN/BtVh5AayGGd+ibzkYw
            dO3jQldo7obFXAEKb8fu4WpOFRG0wZ8T4lv82YRUTibe7khozZx4vKSX7EkSSp1K
            0l4BCArYyR0D8fIKImNXPlOzy6Drmox7vYAzjm4umt9ebTIzLCaO4jmDFdKCrViP
            UBp2Z+lxlMQiO9cgc978lDz6/nbitobOJvTIW+t1lvYuK8Wf8jbGZ1Q9QUVMPXBA
            =WMFO
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    identityId: ENC[AES256_GCM,data:wjDyJA0qXBJiK+STcbKuZf19ws/4oWU5PAVZqmEj43ZB/qe39jMmAtKmu44h8b0a,iv:CPTt4qtL5aEQVlRXjFoTS4S1bT3rTb9ICi3EuMvWL8Y=,tag:d+bNNe7mDpUVNd7Wy0aBzA==,type:str]
kind: Secret
metadata:
    name: kubernetes-credentials
    namespace: infisical
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-01T16:05:16Z'
    mac: ENC[AES256_GCM,data:e8r4I4qFaYgMUL0L6CVCxYqd6oI6CgS7eehNHiP/lZmf7zwlYZW+6NBSfviViDJ7gZ//h3trcyBVsZMrqJgDZICueXcNrzVFPbDGNfx13Y37ECcnvRLBrCwsYDaAwhXSS0Alsx8eD88k3yPULhG1pGNiq0PGw4VJLvcNzOjOuQU=,iv:2SIvmJmwAvlqRStKCgy8OQ87zEM3XMxPf72R6UuaAnA=,tag:J7oyBCikQpuag+drqd9NQw==,type:str]
    pgp:
    -   created_at: '2026-09-01T16:05:15Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAYG72T0EegoMh8hpDIo5aA5wGN/BtVh5AayGGd+ibzkYw
            dO3jQldo7obFXAEKb8fu4WpOFRG0wZ8T4lv82YRUTibe7khozZx4vKSX7EkSSp1K
            0l4BCArYyR0D8fIKImNXPlOzy6Drmox7vYAzjm4umt9ebTIzLCaO4jmDFdKCrViP
            UBp2Z+lxlMQiO9cgc978lDz6/nbitobOJvTIW+t1lvYuK8Wf8jbGZ1Q9QUVMPXBA
            =WMFO
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
