---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoppscotch
  annotations:
    configmap.reloader.stakater.com/reload: config
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hoppscotch
  template:
    metadata:
      labels:
        app: hoppscotch
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      initContainers:
        - name: 00-migrate
          image: hoppscotch/hoppscotch-backend:2026.8.1
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: database-url
                  name: hoppscotch
          envFrom:
            - configMapRef:
                name: config
          command:
            - /bin/sh
            - -c
            - |
              pnpx prisma migrate deploy
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 64Mi
      containers:
        - name: frontend
          image: hoppscotch/hoppscotch-frontend:2026.8.0
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 3000
              name: frontend
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: database-url
                  name: hoppscotch
          envFrom:
            - configMapRef:
                name: config
          startupProbe:
            tcpSocket:
              port: frontend
          livenessProbe:
            tcpSocket:
              port: frontend
          readinessProbe:
            httpGet:
              path: /
              port: frontend
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 64Mi
        - name: backend
          image: hoppscotch/hoppscotch-backend:2026.8.1
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 3170
              name: backend
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: database-url
                  name: hoppscotch
          envFrom:
            - configMapRef:
                name: config
          startupProbe:
            tcpSocket:
              port: backend
          livenessProbe:
            tcpSocket:
              port: backend
          readinessProbe:
            httpGet:
              path: /health
              port: backend
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 64Mi
        - name: admin
          image: hoppscotch/hoppscotch-admin:2026.8.1
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 3100
              name: admin
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: database-url
                  name: hoppscotch
          envFrom:
            - configMapRef:
                name: config
          startupProbe:
            tcpSocket:
              port: admin
          livenessProbe:
            tcpSocket:
              port: admin
          readinessProbe:
            httpGet:
              path: /
              port: admin
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 64Mi
