apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hoppscotch
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - listener-set.yaml
  - secret.yaml
configMapGenerator:
- name: config
  env: ./config/aio.env
generatorOptions:
  disableNameSuffixHash: true