---
apiVersion: v1
kind: Service
metadata:
  name: hoppscotch
  labels:
    app: hoppscotch
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: frontend
    protocol: TCP
    name: frontend
  - port: 3100
    targetPort: admin
    protocol: TCP
    name: admin
  - port: 3170
    targetPort: backend
    protocol: TCP
    name: backend
  selector:
    app: hoppscotch
