apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sign-pdf
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml

configMapGenerator:
- name: scripts
  files:
  - ./scripts/entrypoint.sh
- name: config
  files:
  - ./config/signaturepdf.conf
generatorOptions:
  disableNameSuffixHash: true
