---
apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
spec:
  match:
    - excludedNamespaces:
        - ceph-csi
        - cilium
        - cnpg-system
        - flux-system
        - gatekeeper-system
        - kube-node-lease
        - kube-public
        - kube-state-metrics
        - kube-system
        - nfs-proxmox
      processes: ["*"]
