---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: atuin
  labels:
    app.kubernetes.io/name: atuin
    app.kubernetes.io/instance: atuin
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: atuin
      app.kubernetes.io/instance: atuin
