apiVersion: v1
stringData:
    ATUIN_DB_URI: ENC[AES256_GCM,data:dixB6rCTBPPAL9qEoE+/1tKN+oUVDg6geHeZQf3Bmx+b6nZFKGB5JRmy9y5ZdI+rOMK/Rg3hTA==,iv:uHg6POmENHaprzJd8WYh9WaCS37Vl1wNmbI3cXZXJos=,tag:HRzEFLSYsbTl1eL45tuxUA==,type:str]
kind: Secret
metadata:
    name: credentials
    namespace: atuin
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-06T20:43:43Z'
    mac: ENC[AES256_GCM,data:gQWCp5ItR1QMflZaco2YCLrvrUKJtFmHrOPe82bmidoyjlubLRhxtnZsNS9Bmnn33clQwHisutaQK5bJywi/eQmoloQuXcuxFwoNz34b+nF5Y+HO9FcW+9awc/4nVtrudaSyrKIgjwSqS2LZtO+5C9pDjAs7AP7sO75tYCslk0o=,iv:Yaj4koZa34tGabDX88IvemfT0sHRbdXNt2+ForBG3FI=,tag:89UXY9lefg7fDMbo5gsjIw==,type:str]
    pgp:
    -   created_at: '2026-09-06T20:43:43Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAz1BjwP9GALoerEe4R1JT9MEIWNGdUbdNC5uCinuEWjEw
            Lw/bvllrsTIYOVwIzVPrp7ccSvJh9j+goKltvSg17qndW1RMb1WKzWyDw78o+yNh
            0l4BQtNZ1RYSmjhXzxpbyYGl85YEfWmRGs1A0f3cwYKAye/TcG+yWzJNvDC0L+Fw
            iNFcLwLfyCiLAVw83FC7SJAruOgojSDwagzo1bJVgvVrgflBhppeQN6AClXzKr7B
            =4S1H
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
