apiVersion: v1
stringData:
    database-url: ENC[AES256_GCM,data:YjO0GB66829bNqzctB3t9EEOQueMS/ha+i9txINBpA+Xi+Xsu2YWNlu/io/4167Yo5BAP2kMQ4xKpCa3vlKfz/8=,iv:fp5xButeVyhz4ubdPUEvkpjeZsc1eqL2UtmEubpl42c=,tag:HMM69sciOQ4vL4du9QSjUQ==,type:str]
    maxmind-license: ENC[AES256_GCM,data:N5mZQdhPbu/Rlg5WPi61qbuJmHlsrVgNn139o6vuEhkgUgvIBWM9mg==,iv:JvM9RfPAZuI5YMslDOn2LWhw96ItOs7cK8OgmwLQ1Ds=,tag:ammsdq313/CXJguXveXqZw==,type:str]
    encryption-key: ENC[AES256_GCM,data:WEwh4mU6fdoC8dLdyiWwe2xrio7vU5hJMKHFxEt/zuAXjRZ92K0XXbdb8Q==,iv:nDUErn68mNCy8L99pO+O0fBcd3dhQI+SmF2OxvPmH2g=,tag:dtXtCg+SOu9z55iVgEm0CQ==,type:str]
kind: Secret
metadata:
    name: pocket-id
    namespace: pocket-id
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-06T14:40:10Z'
    mac: ENC[AES256_GCM,data:q38qn+tb7IrRc7Jyc+rS/pvlV38sZYSUncVHVJ/OasxeY4T1skwNnzmJJJeN4AQ+JNFXA5ei9hNbB1Hk96YZpmDwiO0gYP23/L7boo56bsEyNcbSPqOfZjxShOjwJXdB8nQEbgRIAivn/Nk/AQxK2aBB/iAHm/rN1ZnbqPisddk=,iv:Xjhavb62NXc5PWgDl6cAxN3UHw5+sYaey8PWPTqpnP0=,tag:DSN/378p6GBQmbdD+cXtpA==,type:str]
    pgp:
    -   created_at: '2026-09-06T14:40:10Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAeiGGxoNC9zjn7MHMIjzdfY4qN2EIsr/4BUnXL/NaNRQw
            i1rAv+riMQRg3qIYiP3NvZHy1oa4TtaAmApDc1kltYBs4wlQzj99vkFiTchRl2yq
            0lwBhk0SjiBcrzww5WYt2ZjExupIHptT6480XSV3XoD0cs/xCccfevQ9PiNsP4xb
            I7Ld3c2nz6KqNtwbNK6/BXs2Nd+Cpiigw1y83OaYmCthDYwYqKOJ7/s28Z6NFA==
            =TSAQ
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
