---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: rebuild
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9000"
spec:
  serviceAccountName: kaniko
  triggers:
    - name: rebuild
      triggerRef: rebuild
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            containers:
              - resources:
                  requests:
                    cpu: 10m
                    memory: 64M
                  limits:
                    cpu: 100m
                    memory: 64M
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: rebuild
spec:
  bindings:
    - ref: rebuild
  template:
    ref: rebuild
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: rebuild
spec:
  params:
  - name: IMAGE
    value: $(body.IMAGE)
  - name: TAG
    value: $(body.TAG)
  - name: GIT_URL
    value: $(body.GIT_URL)
  - name: DOCKERFILE
    value: $(body.DOCKERFILE)
  - name: DOCKERFILE_CONTENT
    value: $(body.DOCKERFILE_CONTENT)
  - name: EDIT_MODE
    value: $(body.EDIT_MODE)
  # - name: EXTRA_ARGS
  #   value: $(body.EXTRA_ARGS)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: rebuild
  annotations:
    triggers.tekton.dev/old-escape-quotes: "true"
spec:
  params:
  - name: IMAGE
    description: Name (reference) of the image to build.
  - name: TAG
    default: latest
    description: Tag (reference) of the image to build.
  - name: GIT_URL
    description: Git url to clone the repo from.
  - name: DOCKERFILE
    default: ./Dockerfile
    description: Path to Dockerfile.
  - name: DOCKERFILE_CONTENT
    default: ""
    description: Additional Dockerfile content.
  - name: EDIT_MODE
    default: append
    description: Dockerfile content edit mode, append or replace.
  # - name: EXTRA_ARGS
  #   default: ""
  #   description: Extra kaniko arguments
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: rebuild-
    spec:
      pipelineRef:
        name: rebuild
      params:
      - name: IMAGE
        value: $(tt.params.IMAGE)
      - name: TAG
        value: $(tt.params.TAG)
      - name: GIT_URL
        value: $(tt.params.GIT_URL)
      - name: DOCKERFILE
        value: $(tt.params.DOCKERFILE)
      - name: DOCKERFILE_CONTENT
        value: $(tt.params.DOCKERFILE_CONTENT)
      - name: EDIT_MODE
        value: $(tt.params.EDIT_MODE)
      # - name: EXTRA_ARGS
      #   value: $(tt.params.EXTRA_ARGS)
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rebuild
  labels:
    app.kubernetes.io/version: '0.5'
  annotations:
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/categories: Image Build
    tekton.dev/tags: image-build
    tekton.dev/displayName: "Build and upload container image using Kaniko"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This Task builds source into a container image using Google's kaniko tool.

    Kaniko doesn't depend on a Docker daemon and executes each
    command within a Dockerfile completely in userspace. This enables
    building container images in environments that can't easily or
    securely run a Docker daemon, such as a standard Kubernetes cluster.
  params:
    - name: IMAGE
      description: Name (reference) of the image to build.
    - name: TAG
      default: latest
      description: Tag (reference) of the image to build.
    - name: GIT_URL
      description: Git url to clone the repo from.
    - name: DOCKERFILE
      default: ./Dockerfile
      description: Path to Dockerfile.
    - name: DOCKERFILE_CONTENT
      default: ""
      description: New Dockerfile content.
    - name: EDIT_MODE
      default: append
      description: Dockerfile content edit mode, append or replace.
    # - name: EXTRA_ARGS
    #   type: array
    #   default: []
    #   description: Extra kaniko arguments
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: GIT_URL
          value: '$(params.GIT_URL)'
    - name: edit
      taskRef:
        name: edit-dockerfile
      runAfter:
        - clone
      params:
        - name: DOCKERFILE
          value: '$(params.DOCKERFILE)'
        - name: DOCKERFILE_CONTENT
          value: '$(params.DOCKERFILE_CONTENT)'
        - name: EDIT_MODE
          value: '$(params.EDIT_MODE)'
        - name: CLONE_PATH
          value: "$(tasks.clone.results.clone-path)"
    - name: build
      taskRef:
        name: kaniko
      runAfter:
        - edit
      params:
        - name: DOCKERFILE
          value: '$(params.DOCKERFILE)'
        - name: IMAGE
          value: '$(params.IMAGE)'
        - name: TAG
          value: '$(params.TAG)'
        - name: CLONE_PATH
          value: "$(tasks.clone.results.clone-path)"
        # - name: EXTRA_ARGS
        #   value: ["$(params.EXTRA_ARGS[*])"]
    - name: confirm
      taskRef:
        name: curl
      runAfter:
        - build
      params:
        - name: url
          value: http://api.sidekick:3000/changedetection/confirm
        - name: options
          value:
            - -X
            - POST
            - -H
            - 'Content-Type: application/json'
            - -d
            - '{"git_url": "$(params.GIT_URL)"}'
    - name: notify
      taskRef:
        name: curl
      runAfter:
        - build
      params:
        - name: url
          value: http://mattermost.mattermost:8065/api/v4/posts
        - name: options
          value:
            - -X
            - POST
            - -H
            - 'Content-Type: application/json'
            - -H
            - 'Authorization: Bearer 758nmqwjj78kdmagqw7uahq1yo'
            - -d
            - '{"channel_id": "wwiubazw1bfffk3pj1zd8efdmr", "message": "Rebuilt https://hub.docker.com/r/$(params.IMAGE) with tag $(params.TAG) from $(params.GIT_URL)"}'
  finally:
    - name: rmdir
      taskRef:
        name: remove-directory
      params:
        - name: CLONE_PATH
          value: "$(tasks.clone.results.clone-path)"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  description: >-
    Clones a git repository to '/kaniko-build' path (ends on pvc volume to be shared accross other tasks in a pipeline).
  params:
  - name: GIT_URL
    description: Git url to clone the repo from.
  results:
  - name: clone-path
    description: The path where the repo has been cloned into.
  steps:
  - name: clone
    image: alpine/git:v2.54.0
    env:
      - name: GIT_URL
        value: "$(params.GIT_URL)"
      - name: WORKSPACE_SOURCE_PATH
        value: /kaniko-build
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
    volumeMounts:
      - name: workspace
        mountPath: /kaniko-build
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 256Mi
    script: |
      #!/usr/bin/env sh
      set -eu
      # MD5=$(echo $RANDOM | md5sum | head -c 10; echo;)
      LATEST_COMMIT=$(git ls-remote ${GIT_URL} HEAD | awk '{ printf $1}' | head -c 7)
      REPOSITORY_NAME=$(basename ${GIT_URL} | cut -d "." -f1)
      CLONE_PATH="${REPOSITORY_NAME}-${LATEST_COMMIT}-${POD_NAME}"
      git clone "${GIT_URL}" "${WORKSPACE_SOURCE_PATH}/${CLONE_PATH}"
      echo -n "${CLONE_PATH}" | tee $(results.clone-path.path)
  volumes:
    - name: workspace
      persistentVolumeClaim:
        claimName: kaniko
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: edit-dockerfile
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  description: >-
    This task adds content to a Dockerfile.
  params:
  - name: DOCKERFILE
    default: ./Dockerfile
    description: Path to Dockerfile.
  - name: DOCKERFILE_CONTENT
    default: ""
    description: New Dockerfile content.
  - name: EDIT_MODE
    default: append
    description: Dockerfile content edit mode, append or replace.
  - name: CLONE_PATH
    description: The path where the repo has been cloned into
  steps:
  - name: echo
    image: busybox:1.38.0
    env:
      - name: DOCKERFILE
        value: "$(params.DOCKERFILE)"
      - name: DOCKERFILE_CONTENT
        value: "$(params.DOCKERFILE_CONTENT)"
      - name: EDIT_MODE
        value: "$(params.EDIT_MODE)"
      - name: CLONE_PATH
        value: "$(params.CLONE_PATH)"
      - name: WORKSPACE_SOURCE_PATH
        value: /kaniko-build
    volumeMounts:
      - name: workspace
        mountPath: /kaniko-build
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 64Mi
    script: |
      #!/bin/sh
      set -eu
      ls -alh "${WORKSPACE_SOURCE_PATH}/${CLONE_PATH}"
      if [[ ! -z "${DOCKERFILE_CONTENT}" && 'append' == "${EDIT_MODE}" ]]; then
        echo "${DOCKERFILE_CONTENT}" >> "${WORKSPACE_SOURCE_PATH}/${CLONE_PATH}/${DOCKERFILE}"
      fi
      if [[ ! -z "${DOCKERFILE_CONTENT}" && 'replace' == "${EDIT_MODE}" ]]; then
        echo "${DOCKERFILE_CONTENT}" > "${WORKSPACE_SOURCE_PATH}/${CLONE_PATH}/${DOCKERFILE}"
      fi

      cat "${WORKSPACE_SOURCE_PATH}/${CLONE_PATH}/${DOCKERFILE}" | sed -r 's/(--mount[^\ ]+)\ //g' || true
      sed -i -r 's/(--mount[^\ ]+)\ //g' "${WORKSPACE_SOURCE_PATH}/${CLONE_PATH}/${DOCKERFILE}"
  volumes:
    - name: workspace
      persistentVolumeClaim:
        claimName: kaniko
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: remove-directory
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  description: >-
    This task removes the working path.
  params:
  - name: CLONE_PATH
    description: The path where the repo has been cloned into
  steps:
  - name: rmdir
    image: busybox:1.38.0
    env:
      - name: CLONE_PATH
        value: "$(params.CLONE_PATH)"
      - name: WORKSPACE_SOURCE_PATH
        value: /kaniko-build
    volumeMounts:
      - name: workspace
        mountPath: /kaniko-build
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 64Mi
    script: |
      #!/bin/sh
      set -eu
      rm -rf "${WORKSPACE_SOURCE_PATH}/${CLONE_PATH}"
  volumes:
    - name: workspace
      persistentVolumeClaim:
        claimName: kaniko
