---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: passbolt
  labels:
    app: passbolt
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: passbolt
  template:
    metadata:
      labels:
        app: passbolt
    spec:
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: passbolt
          image: passbolt/passbolt:5.15.0-1-ce-non-root
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          env:
            - name: APP_FULL_BASE_URL
              value: https://passbolt.${domain}
            - name: DATASOURCES_DEFAULT_DRIVER
              value: Cake\Database\Driver\Postgres
            - name: DATASOURCES_DEFAULT_ENCODING
              value: "utf8"
            - name: EMAIL_TRANSPORT_DEFAULT_HOST
              value: "smtp.domain.tld"
            - name: EMAIL_TRANSPORT_DEFAULT_PORT
              value: "587"
            - name: DATASOURCES_DEFAULT_URL
              valueFrom:
                secretKeyRef:
                  name: passbolt
                  key: database-url
          ports:
            - containerPort: 8080
              name: http
          startupProbe:
            tcpSocket:
              port: http
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 1000m
              memory: 256Mi
          volumeMounts:
            - mountPath: /var/lib/passbolt
              name: work
      volumes:
        - name: work
          emptyDir:
            medium: Memory
