apiVersion: v1
data:
    database-url: ENC[AES256_GCM,data:XhAXUkBo8r1DleAO9AGBXe2HWHU/l2ZradZhj5uwHvxSgJkRWSyL8bquUkRvYfdPQRZlVcmPrlETlqCbmySVkl4VbzJ5BTK90QxqMdsUHN+sRJMh1THPhRBcg9CnI/JYVmQOdjEXsu8=,iv:aP+jvC5MLWyfkKRSZNOa0eYGGwyCmdeODU7rP7BxMQw=,tag:BECW+JYiSx6XgGhvt8UWgw==,type:str]
kind: Secret
metadata:
    name: passbolt
    namespace: passbolt
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-02T15:13:00Z'
    mac: ENC[AES256_GCM,data:3piUAByZqRQsfTkk+yaeiheNiDdOEUjECO/GySo2o1g9GTN/7kcs5tAclEA42j/PdA2vR/oNeYNxv3uOer1Rpr4jfuNzhxQapBiOCuGKN7j1suQb9eJnAvn3MxyV7iGvXHOtjGcPtwipiCSlNR5cFGe6ee0US+DkWrSvLEsCcME=,iv:JrWuEho6pCngRr0YmPE/ILDE1VAeNlPV0vFy2S7PaA0=,tag:LNRTGe9WMOGD2hFS0yW5Ww==,type:str]
    pgp:
    -   created_at: '2026-09-02T15:12:59Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdApRipanoZtcT+1alqxwpdZKqfv1XIVLUXB66zuiqc73Ew
            8eD/IvIEFgrQB19dCxLLOoNHBvXcWmo8Tl6WajN2RhbCfliPAXN3CcPDg+XiOQCz
            0l4BYdeyYcVU5J50btXWwUWaHPH6v0q2uyMcIPwCjMBP8a4+ZOC9TjUyR/+S9kR+
            qxw+S/CjoHjlbEfX/0+i98TJNlCVuEArBi98WPmOgbupq1ozdgD9F9DClt7VubVr
            =+NsW
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
