apiVersion: v1
kind: Secret
metadata:
    name: mikrotik-credentials
stringData:
    MIKROTIK_BASEURL: ENC[AES256_GCM,data:jEk+X1a8q6DnkrTSjJezGOw52jM=,iv:9AMr3b+RVcBj/K//Ss47Wyq145lrj8Y35xpMP2SvHRM=,tag:vRv5Kl9lhbxSrkk403JbYw==,type:str]
    MIKROTIK_USERNAME: ENC[AES256_GCM,data:y5PVW4+gPOU=,iv:FOJikiU4KyeHP17vxl1bkVHscdEKOSzk/xK0mmwfLCs=,tag:l1GBqV3qlG+gTTCxKsT2aA==,type:str]
    MIKROTIK_PASSWORD: ENC[AES256_GCM,data:qv/VQ8WNQzk=,iv:prUbYf0FBymmsvJWr+PCz7peEKQWj7d3IulzleJvHeg=,tag:jHZll9EZZh6zzLS8kwZbsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-05-29T21:20:48Z'
    mac: ENC[AES256_GCM,data:sNjDp+GpTaUvKtg9N5+TgXVhxSOQDAAy2C1bgoKEn2j/Ky5aiVM+jyranv1o6mMrNElgRr3woaNQKOnXKnfPZKlJjCREY9Ih1TUSr29qSpnj7V0U9gIQTc3/MDfaR/V5bLpxpDBZKUwNhBK9uOya+STiftfnbHFFsisif9Cr4hI=,iv:Uhx3GW3Awxps95EpX0ePgYjNpXM1IGf1QeITw0Igo/E=,tag:GPngxsGm0fKxVFLB9g4Rcg==,type:str]
    pgp:
    -   created_at: '2026-05-29T21:20:47Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DTe0P/qWvzAMSAQdAaBZ79adBMrpNddIhpZBh2MqHus+uYSwPDMrGgey9y28w
            JeFpg1uYxDhPxXhTuSkcIaPyjiHYIYZfZsaMlIW6FbPgzCcuzCJRvxQsXDcsjxIL
            1GYBCQIQCfM04T5NU9JZdBxzyhWUAIfKBd3OfD/KuSOrQYOcp8yaT9SasBWRoFkb
            ocSTi5kfrOz78Awb9WhXO42fgD5O88h7AKcJz57IzIP+tNJuNeAB7BUIZykw47lG
            iNb/wmn7ccU=
            =C/b4
            -----END PGP MESSAGE-----
        fp: 3AFE004C7B67F70DCEA1B33187F191C9C8B81E94
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
