apiVersion: v1
kind: Secret
metadata:
    name: mikrotik-credentials
stringData:
    MIKROTIK_BASEURL: ENC[AES256_GCM,data:JuEeFNnB5ZT3LF2qLg22vTQXAfA=,iv:ZPjuMWTiYLGFIHqnqcSRhiiuOhRKRDB/i/DLF3tzdPs=,tag:8ROrrKfZ9R83zxMNk/OmWg==,type:str]
    MIKROTIK_USERNAME: ENC[AES256_GCM,data:LnqogLgXkA8=,iv:x/CVHGc6Hpb7hGP3kEcjvmuPsM1PaHwJhlB9u/xePg4=,tag:ZaYcg2C19AT0eVfDwJiGRw==,type:str]
    MIKROTIK_PASSWORD: ENC[AES256_GCM,data:wtRlqbhmCu0=,iv:37zsD07u117nwl+p/XUtMiw9mgCWZGmLd63WQ4WoLdc=,tag:zcD1ocl882Of//FdUxzW7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-05-30T16:11:42Z'
    mac: ENC[AES256_GCM,data:YXNP1VoVOMA+kVUhe//wixElpmGavWqQ+NMH5KE02fjlzeZme8WeAyD8n++E+lLhmS/J3QMNFE9CqR6xCNU7b0VLc0EsFjUqKMy9yNMc1Nxc+PhxYFOdYcpDA6+HxvGJVwNeQ8Eull8nTPDjUg67IMckws8Jp/Mvm9w5/QaA+Co=,iv:SeqnmroBuDvrPnFanZMCGuVdLbEfTYpSs+BR6oZbOAg=,tag:sBy8RgypRj8r/Q9849sskA==,type:str]
    pgp:
    -   created_at: '2026-05-30T16:11:41Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxv5FnUBLaS9AQ/9EDlmWYeH6rHLKUF6VkufxDBBqp5XfiXRhDOOvqE3bBjq
            25kbCOdEsg4dPXuYrMqVcncaiw8t2wNyRzgmEOIiTh2kp2WtNxr4U5xyvbKGWLNh
            2QupRD8fGGws25B3Jufzg3iLIJxDEQZBdpBlZt21OgDjPdP9U8rS/8XGa81h8BPm
            HVGqWO/zN3CX4KOB5Fjt1h/v3FYHTfAW3/aKTFOq67MsuXiTQiK8PmX/v1G3vADT
            HZNbHeC2UWf1lSyHBZQYE3m8GerKQHuglX+9BDupMOdbLZTUKLsIeWVRNQj8PeF+
            7+/EPncvRlrzrSKR+6tQT5vAYHLkiDHiaLv2gTfAo2Vd6JgkYYRX1ZVSQL1zdT1r
            vVfX6mIj7PuUrdGD1u3w2F7Os+NDQEuFPYm+bVYRxYyJD4Tr6FtHNjfSnVzUpVdt
            9HZoUIe4eeBe/cIVoQoGdaYYY5S9v1F6gCcLCXXDJC/zNPA3MeWUU4UvtQ7BqjzE
            Of7Nq3Qdw6+Z1cS4RLFDClQ3KZkZ6FZ75SSNif5oFdrMKRYSibknXx7iIgmXFjsS
            Q8kZLln/WxTP2tXmhg8YO8+ZZFbwHzwd3FTHr1dRM1wQCoFza09uQxC51nPytpNk
            Q8p1ZoureboJPuN0B+vS9iCJiTQjjlOLRsxMX/uvGsM14uI9Yv0dba/F48dZAgPS
            XAHCi4HQdNiGVt5HPu0n9Qc9hfYeBodVeFIkdRuv74k2XVLhcEfIVBa+uzg7elHV
            2joXccNcmM5g38qZFgoPwWt8FARKXPI+Krn5Z75Ie1DlTLg+diId2R/NwTHG
            =qYLE
            -----END PGP MESSAGE-----
        fp: 0BCA2EF044187A707E2507E54C4527913792AFD8
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
