---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium
  namespace: cilium
  annotations:
    cert-manager.io/cluster-issuer: ca-cluster-issuer
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      lbipam.cilium.io/sharing-key: vip
    labels:
      vlan: lb
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      hostname: "*.${domain}"
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      port: 443
      protocol: HTTPS
      hostname: "*.${domain}"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: gateway-tls
