apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metrics-server
resources:
  - namespace.yaml
  - rbac.yaml
  - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            tolerations:
              - effect: NoSchedule
                key: node.kubernetes.io/nuc
                operator: Exists
    target:
      kind: Deployment
      labelSelector: k8s-app=metrics-server
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            cpu: 200m
            memory: 128M
      - op: add
        path: /spec/template/spec/hostNetwork
        value: true
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
        - --cert-dir=/tmp
        - --secure-port=4443
        - --kubelet-insecure-tls
        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
        - --kubelet-use-node-status-port
        - --metric-resolution=15s
      - op: replace
        path: /spec/template/spec/containers/0/ports/0/containerPort
        value: 4443
    target:
      kind: Deployment
      labelSelector: k8s-app=metrics-server
