apiVersion: v1
stringData:
    ssh_host_ed25519_key: ENC[AES256_GCM,data:I6A9HUqa9osUTBXIomc6behmM7qpASFEZ7c7+s6AEleC9+KUW78p+WJ1FIg3x/jOrIa3H3muAtDPQ3xxO8ZhMKM5uvh9xfQRC9BIlHkkJv78IQ9/ngxK+Nq/Ixlv3EAiGypQP6+W5DhlxHNpOHtFyDZ6B6BaFfNK6U25bIgcQvymqIJ1aSpjxEaaNcMgNZKQffkJJSGCRh54hDFTOABuPE40nSgWeHWmCLkzDh1Ds0ravAU90T45oonF9boql08HLLLLdPI2yaxWsW7sNWkNy+4uqwZ5T/siBnyI4EZdC52ASdIVK6xOhQkT9jgttYx96PWBaVERNKtn8zY/zKBH1j/xBwkalODboBMpW48+kJnuLouPLPk0tgkgXcHLMH1OuZq79QNWdi2KUVZ7dIyE7wTeLHFfJcuE7hXbZf627/PdZb62LhXTy041l5+XqlbPYvTLcwNzaV6uMOzJdcMf4XhPvL1gYLnwXGA+z2u82VYZk5xX73Av8Wm7MJ2dFxnGNVg4oMeXlXAij0b4PoyH4B2ihMa/UvGGLDAMXr8v1pgcGFM=,iv:HduvtoWzXq3BV3BkCEd8mLAKb+/ueEVWQabJdoFsIqo=,tag:6GvzkKlVHGXQCSe2slPfJA==,type:str]
    sftp.json: ENC[AES256_GCM,data:+WqdOfH4iSMFFNOgn7GIE33MBWjzWxwjZYg91KnkPxij24py2iHp7S2JAno9ALvFvPEFX6fstPv8HQ92ZEOuMtKMhSYSGCyUTEir0LkHOA8F+ZP/acALLMWSaGId+lLmN9kl4gH0t2ZU3d3G1uWHiViVNV0hxpd1eBwUh501t+1CsHLkBJpemJlfDEqFUOZDaq6r/rsJKa43Z5uDMgL6tjlnCc/X72seM1MbynqzLxg9fLRn2ZAKybrEAoDN+jthAlANY8yAFgvSTEG25xfabPKpWMg17ygJiuYDPAJlsrZaCKFoWdwhjuCpsCn8AY529pTHcJvspkZ+xlAfxLeZ2ubBQyH3TXZfKg==,iv:npN4sdnoTcbNDFvRSN2Qpgv4SfeGTKlBC+/LPgFjkRE=,tag:ZNEWQmgiIOiGMjkmQ88ihA==,type:str]
kind: Secret
metadata:
    name: config
    namespace: sftp
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-09-06T21:20:51Z'
    mac: ENC[AES256_GCM,data:L3BwaOe++u448i9S7ePiBfsx1tkN+D+mUgZsEkx+BYonhLsHnuS0MnSkvNAIAyJe8poh0O38AJC92ANY7If2sFEoOCx+b7kfSWxPbugyQMZnH/dHuQp51AMY6+WqWA9dfIief4Hie9kd0WCVPQFvtf/VFGAQCtEHF4uVDIyT4U8=,iv:SoSm1AEsndsQAl5WUPXnhOATDy0sQfSQhZVVuXzYo1w=,tag:FaYH618OmLT7hLjLC0SRHw==,type:str]
    pgp:
    -   created_at: '2026-09-06T21:20:50Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAYDmO2CVrvJvI8zEcW8yEBGio4jSqJjgMM+9voePMDh8w
            pmVbt0rzZWbowQ+Iav1TM9TFjnn8FKfjaAmVOIX1p30X6m3psUUG+e4bkRcmwubD
            0l4BznlhV7gazOdLinOQyG27aTIQqCoNeOu0NvYnfYz54Z0Es7ugP/2gqA577oO4
            NZZVVFvIpsJz4RiBJ5R0Il1nEU12OZp2B6tFm41Iwxa/vzr5ET9QWVTc3MIYxiEj
            =a9Fy
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
