apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: karpenter-proxmox
resources:
  - namespace.yaml
  - provider-config.yaml
  - proxmoxidentity.yaml
  - proxmoxnetworkbridge.yaml
  - secret.yaml
# - talostemplate.yaml