apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: karpenter-proxmox
resources:
  - https://github.com/sergelogvinov/karpenter-provider-proxmox/raw/refs/heads/main/docs/deploy/karpenter-provider-proxmox.yml
  - https://raw.githubusercontent.com/sergelogvinov/proxmox-cloud-controller-manager/main/docs/deploy/cloud-controller-manager-talos.yml
  - namespace.yaml
  - provider-config.yaml
  - proxmoxidentity.yaml
  - secret.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            nodeSelector: null
            containers:
              - name: karpenter-provider-proxmox
                image: ghcr.io/shokohsc/karpenter-provider-proxmox@sha256-d6058ef2d7618629d8572f284fe647681dda75a28cc2d934c880010526d3d81c
                volumeMounts:
                  - mountPath: /etc/ssl/certs/ca-certs.pem
                    subPath: ca-certs.pem
                    name: tls
            affinity:
              nodeAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 1
                    preference:
                      matchExpressions:
                        - key: topology.kubernetes.io/zone
                          operator: In
                          values:
                            - metal
            volumes:
              - name: tls
                configMap:
                  name: homelab-ca
                  defaultMode: 0644
            tolerations:
              - effect: NoSchedule
                key: node.kubernetes.io/nuc
                operator: Exists
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/name=karpenter-provider-proxmox
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            containers:
              - name: proxmox-cloud-controller-manager
                volumeMounts:
                  - mountPath: /etc/ssl/certs/ca-certs.pem
                    subPath: ca-certs.pem
                    name: tls
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution: null
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 1
                    preference:
                      matchExpressions:
                        - key: topology.kubernetes.io/zone
                          operator: In
                          values:
                            - metal
            volumes:
              - name: cloud-config
                secret:
                  secretName: karpenter-provider-proxmox
              - name: tls
                configMap:
                  name: homelab-ca
                  defaultMode: 0644
            tolerations:
              - effect: NoSchedule
                key: node.kubernetes.io/nuc
                operator: Exists
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/name=proxmox-cloud-controller-manager
