apiVersion: platform.${publicDomain}/v1alpha1
kind: ProxmoxIdentity
metadata:
  name: karpenter-proxmox
spec:
  user: karpenter-proxmox@pve
  passwordSecretRef:
    namespace: karpenter-proxmox
    name: karpenter-proxmox-credentials
    key: password
  userGroups:
    - karpenter-proxmox
  aclPath: /
  tokenName: karpenter-proxmox
  groupName: karpenter-proxmox
  roleName: karpenter-proxmox
  privileges:
    - Datastore.Allocate
    - Datastore.AllocateSpace
    - Datastore.AllocateTemplate
    - Datastore.Audit
    - Mapping.Audit
    - Mapping.Use
    - Sys.Audit
    - Sys.AccessNetwork
    - SDN.Audit
    - SDN.Use
    - VM.Audit
    - VM.Allocate
    - VM.Clone
    - VM.Config.CDROM
    - VM.Config.CPU
    - VM.Config.Memory
    - VM.Config.Disk
    - VM.Config.Network
    - VM.Config.HWType
    - VM.Config.Cloudinit
    - VM.Config.Options
    - VM.PowerMgmt
    - Pool.Audit
    - Pool.Allocate
  groupRoles:
    - karpenter-proxmox
