apiVersion: platform.${publicDomain}/v1alpha1
kind: ProxmoxNetworkBridge
metadata:
  name: karpenter-proxmox
spec:
  name: vmbr1
  nodeName: genji
  ports:
    - nic1
  vids: "10 20 40 50 100"
  vlanAware: true
