apiVersion: v1
stringData:
    config.yaml: ENC[AES256_GCM,data:iYqxWI7qP/pKiN6qqk7GBk4mN9E0GSizUfk6TaH1z+ww7CpU/a2MF0/nPT0ZoHSymP1569KJQDA2J22QY7qpYbRvinr286NrtDxsqeqbSFG3zN0pfGJSnXf9cBvhHiKu4rlHzU5r7uyZVYmoPfdga42D24ZebxinJsqfcADTMWQ62eEHkL8+h9CHQXzpIjJHdAQUsEbX45V1qIrb9vkQEgpLcpTcvj9UbzNPg/80K0VE8YALLZ8hchUvCYQ6hwbEcA10UvvyS8Oz60ALw6w=,iv:P1sRmXDFLYf16kbo3jQVOSkjcnSVCzWxOphB+iB/8D4=,tag:Mg1VN/QTpp0zDLANKNWMhA==,type:str]
kind: Secret
metadata:
    name: karpenter-provider-proxmox
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-14T22:36:57Z'
    mac: ENC[AES256_GCM,data:7HshnTnOIyNnwcBZITiP3t8MP3AbCd2dtKzG27GNo1DoZ93L8MiLo8EZ2Bepm3FaPjHqxyIDke3k4NolJOGH5fveOWJiEjVKtQUQQzNlm/wN6xIWzKyCRlMh9bOkhEq3UMaa9jrEBFe0IagSzMJFLlaspcLod+PxqvpKj6ucwig=,iv:GnELiNz2cif1r7POpyK2eGa76QbXMdbKkYvinQqvMgQ=,tag:ke50JPwMaIo3NsSYXtzIRA==,type:str]
    pgp:
    -   created_at: '2026-07-14T22:36:56Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAjshnLfJpF/7oaTi9jEHqCgSKdFglBcHqbWSZ+V1HKlQw
            nFCWdB0UDREYY91Wmdp0Q1Bgpzw011TaeM4s8gBE4zcN9pz6UR/3mV9qvbdQQ2BI
            0l4BJhErqmNfybyX+iyr4fKt0rS3WQmAilJFxoxOivsPBS3obIQZz3W754irwnzn
            /MtNFLMEJ1nECesVpqcZAQjgwS6DeNXe+NlI3EGplbV7oSQHv8mamjQAH/7hB7uI
            =my/3
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:Ij83XNMPbtu2rmriH7BjsCOLUMb/5Xpzdz3yuQ==,iv:3qxQwB7KHk+jNEFyK6mABKsJfPcxnLdETpu5Xb+i0V0=,tag:or8lfa+pXnXmajy30PR+sQ==,type:str]
    password: ENC[AES256_GCM,data:6JT4p8Fh9F9EFC9XF1+BNvS3vYfQs3Tv,iv:rS+S9VUZURdGfLSR0j8/qSW8LX9S2LyJ0jtp99wGqZM=,tag:ndzjs7cQPImawLFxSHF3uw==,type:str]
kind: Secret
metadata:
    name: karpenter-proxmox-credentials
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-14T22:36:57Z'
    mac: ENC[AES256_GCM,data:7HshnTnOIyNnwcBZITiP3t8MP3AbCd2dtKzG27GNo1DoZ93L8MiLo8EZ2Bepm3FaPjHqxyIDke3k4NolJOGH5fveOWJiEjVKtQUQQzNlm/wN6xIWzKyCRlMh9bOkhEq3UMaa9jrEBFe0IagSzMJFLlaspcLod+PxqvpKj6ucwig=,iv:GnELiNz2cif1r7POpyK2eGa76QbXMdbKkYvinQqvMgQ=,tag:ke50JPwMaIo3NsSYXtzIRA==,type:str]
    pgp:
    -   created_at: '2026-07-14T22:36:56Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAjshnLfJpF/7oaTi9jEHqCgSKdFglBcHqbWSZ+V1HKlQw
            nFCWdB0UDREYY91Wmdp0Q1Bgpzw011TaeM4s8gBE4zcN9pz6UR/3mV9qvbdQQ2BI
            0l4BJhErqmNfybyX+iyr4fKt0rS3WQmAilJFxoxOivsPBS3obIQZz3W754irwnzn
            /MtNFLMEJ1nECesVpqcZAQjgwS6DeNXe+NlI3EGplbV7oSQHv8mamjQAH/7hB7uI
            =my/3
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
