apiVersion: v1
data:
    config.yaml: ENC[AES256_GCM,data:Cay3DbfU5YqW50Cwe7mpmmGgQinx1ISmbn6FP2BHh4RXqeEb0qhNpOUXCwi6hGJrqLz2cYxEARNBkiEm9yqzUfV1N1Dgf11HSMBw9vTcW4vfKcFRj1otO8pTL/8yzoVufzCbf/7dd4RafGRbxezeAczmQTBPkFe5aqPRzR5w1iXYLAUDGwTVi5hfFwDIdR3vvD9rnldSSZJrsE9oOfXq+YvXD7NSAD9xA/HHRNH9ka4RXiunmTegQjLFQ7wTPyjhZV7W/tBpde4Uov+rch9ZaWIXZb2P9E3Y5EfPzAMF0F3VW5LBGwvQZPp3gqf9DOyVoAoz7jWPMi9amc0oyv8NupL7ARMVdzMNZZUyrGRknHPtl0RilySZaw==,iv:qhjgsp/5eYp79BmVJaGX0WPfzAQNowSQyOxPN13l1+E=,tag:Fcd1mlEGdMY5dUf9fV8+HQ==,type:str]
kind: Secret
metadata:
    name: karpenter-provider-proxmox
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-12T17:32:23Z'
    mac: ENC[AES256_GCM,data:qU19q4/pAz/exrkqB9wxRvKtu9QvUZt/01cc+WIN9eeqJh6tK2XS2d9HPRHyqmNfePS0/jR6jI4ztj1FDgUXQCyeKt5+jgxVVQZmijSzjWOSB1+GfEdv8gtGe03gxQMJEYgDOtjTP9nh5tmu1IVANxQaQ3hnuGDOtntTkwhmcVY=,iv:mel4SLlrIaufoATlFVts0xdsFkU3RwiSPpGG9b9unZ0=,tag:2Hk+CQIAIKy/9p/V7QmrEA==,type:str]
    pgp:
    -   created_at: '2026-07-12T17:32:22Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAZWKVkzW/crYoOs1t1zDU1PaTGikitDvE2LDGrcUb3k0w
            bm9IpoDKAKBzLIo8oCC+TMV75y1d0gX9XkvpfR5nuNITM+cwVnjEyWys7PS1SkI5
            0l4Bg8CD5iNixsnmxz/jwrOE4/JdEfDfDAqgC+549k/U3LsWa5HJHChatTdMFJ3l
            OmzxcB/iwdSwWzx2oVqXx3TJWXaUJkgb8NZuzpDu1D0WXBWdyyRz5EJoqQMO00Oe
            =oadu
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:2nLyT5cfcA5X+4beOh+RIJu5FCaYT7pzvt/d0A==,iv:6hbs//Bd9rC3PKz+LEE7xLFk1W2zxXHvp0BXJ7fH0G4=,tag:hWXLWODyrk282qERBXSFtQ==,type:str]
    password: ENC[AES256_GCM,data:U4Fqh7J5Y3sAqfqc/Q8E9JFuSaWhn43h,iv:XS8nMNpiG1m8nTRMicuHKGQ4EiAUSjBZCf1B8lHu7Yg=,tag:3YL/GIC+t1EFNW+iNvpBlg==,type:str]
kind: Secret
metadata:
    name: karpenter-proxmox-credentials
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-12T17:32:23Z'
    mac: ENC[AES256_GCM,data:qU19q4/pAz/exrkqB9wxRvKtu9QvUZt/01cc+WIN9eeqJh6tK2XS2d9HPRHyqmNfePS0/jR6jI4ztj1FDgUXQCyeKt5+jgxVVQZmijSzjWOSB1+GfEdv8gtGe03gxQMJEYgDOtjTP9nh5tmu1IVANxQaQ3hnuGDOtntTkwhmcVY=,iv:mel4SLlrIaufoATlFVts0xdsFkU3RwiSPpGG9b9unZ0=,tag:2Hk+CQIAIKy/9p/V7QmrEA==,type:str]
    pgp:
    -   created_at: '2026-07-12T17:32:22Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAZWKVkzW/crYoOs1t1zDU1PaTGikitDvE2LDGrcUb3k0w
            bm9IpoDKAKBzLIo8oCC+TMV75y1d0gX9XkvpfR5nuNITM+cwVnjEyWys7PS1SkI5
            0l4Bg8CD5iNixsnmxz/jwrOE4/JdEfDfDAqgC+549k/U3LsWa5HJHChatTdMFJ3l
            OmzxcB/iwdSwWzx2oVqXx3TJWXaUJkgb8NZuzpDu1D0WXBWdyyRz5EJoqQMO00Oe
            =oadu
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
