apiVersion: v1
stringData:
    config.yaml: ENC[AES256_GCM,data:3tOZzt/yaOCuCocjEXO61eb5A5nHgLyHgSzzj3TnwZyPG79zk8Szhn1e2lWas8mOoPft1phgaonx2RPcZe98wqP5YOSfu5j+NkGvHQZwoaE8Xqvd1gTZ1U3mk1Ljb189rgp6wdC2KlauwI7gmKUIfFUqzKXwgXVi5tpyVP1ESELq4akj3Gjs+yt3rE1RC2erEtm3v11eVD5mLTU84eX0p7hcb5aNaMLKq911X2htSOynaMXpu+co8IzS3sd1iVmhejHQmzdLFyyIYejGotoZQakTIZLDEnX8ulMneD6foMtXXQ==,iv:2TQtoQlat2hfwPENOay7V67mPIU+gZb0PDVuSz9WYBs=,tag:RKmDB1u+XAZYC3UH6Sc05A==,type:str]
kind: Secret
metadata:
    name: karpenter-provider-proxmox
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-14T22:22:25Z'
    mac: ENC[AES256_GCM,data:qSnebaLgfXjAQlgpPjpRc3H2yQ9zoh6JHt8Bywmu5PSYLqAOEYhIe2ueCOgLJOW0NmpBrXmiP4KnpF4no58QQNzqfTNxr2dvPIO/Mu0xI0EESAYT3oW8iO9k7pdHPfM3wn4HMTXu4yGuz5k06GOxwyvsvXA6umQ6cPurKRJgSQ4=,iv:RARL0P+AAxU3fraScxSiNdiTsKg1QNhzuMILsqwUCDY=,tag:z1zuGHVF4hEEKAmEz10stQ==,type:str]
    pgp:
    -   created_at: '2026-07-14T22:22:24Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdADMEdjLe9yf7KgMFCTMkqlo0ask6k/dLjuwQXWT9RDhgw
            ySnpVYANrnXqEhaLU27z7oATUsxnmTuYvX/6pgkU1Kyb7//q7YOteIddhTu3C9W6
            0l4BXqvTW0G4P2fGmHKiZzKcb23kdwIh5w/2rqNRntg6FNgaNW7bbSvAQfANVIV0
            PQfAVXQFOyjCiQF+fRFoUCcWTLjtKD/KUIZQ++YgLebfxCx73wgHKOjc+m1UAtFa
            =0b8p
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:/tvADTOJHKM9i0fzYe7MkqHR+84OqtAxT6s7cQ==,iv:WEcwwiwtxKSHPum8IzjJoWLJsHq8LWeoKklnD+HyEZQ=,tag:g/1zhYboN46NAfG+pesVlw==,type:str]
    password: ENC[AES256_GCM,data:ykXOXve6UOXtsF8f0XPGaD6OBBD9eaAX,iv:F1SbkwO+H4PbeDzFK1i6rdGywusQb8/O/T2TFVrQSDQ=,tag:E6DjuTlU7JDysLkvoRkDSQ==,type:str]
kind: Secret
metadata:
    name: karpenter-proxmox-credentials
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-14T22:22:25Z'
    mac: ENC[AES256_GCM,data:qSnebaLgfXjAQlgpPjpRc3H2yQ9zoh6JHt8Bywmu5PSYLqAOEYhIe2ueCOgLJOW0NmpBrXmiP4KnpF4no58QQNzqfTNxr2dvPIO/Mu0xI0EESAYT3oW8iO9k7pdHPfM3wn4HMTXu4yGuz5k06GOxwyvsvXA6umQ6cPurKRJgSQ4=,iv:RARL0P+AAxU3fraScxSiNdiTsKg1QNhzuMILsqwUCDY=,tag:z1zuGHVF4hEEKAmEz10stQ==,type:str]
    pgp:
    -   created_at: '2026-07-14T22:22:24Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdADMEdjLe9yf7KgMFCTMkqlo0ask6k/dLjuwQXWT9RDhgw
            ySnpVYANrnXqEhaLU27z7oATUsxnmTuYvX/6pgkU1Kyb7//q7YOteIddhTu3C9W6
            0l4BXqvTW0G4P2fGmHKiZzKcb23kdwIh5w/2rqNRntg6FNgaNW7bbSvAQfANVIV0
            PQfAVXQFOyjCiQF+fRFoUCcWTLjtKD/KUIZQ++YgLebfxCx73wgHKOjc+m1UAtFa
            =0b8p
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
