---
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: platform-proxmox
  annotations:
    meta.crossplane.io/maintainer: Platform Team
    meta.crossplane.io/description: Proxmox RBAC management via Crossplane and OpenTofu
spec:
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-opentofu
      version: ">=v1.1.4"
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: enable-psa
spec:
  deploymentTemplate:
    spec:
      revisionHistoryLimit: 0
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                capabilities:
                  drop:
                    - ALL
              env:
                # - name: TF_VAR_proxmox_ve_username
                - name: PROXMOX_VE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: root-credentials
                      key: username
                # - name: TF_VAR_proxmox_ve_password
                - name: PROXMOX_VE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: root-credentials
                      key: password
              resources:
                requests:
                  cpu: 10m
                  memory: 64Mi
                limits:
                  cpu: 1000m
                  memory: 512Mi
              volumeMounts:
                - mountPath: /etc/ssl/certs/ca-certificates.crt
                  subPath: ca-certs.pem
                  name: tls
                - mountPath: /tmp
                  name: work
          volumes:
            - name: tls
              configMap:
                name: homelab-ca
                defaultMode: 0600
            - name: work
              emptyDir:
                medium: Memory
          tolerations:
            - key: "node.kubernetes.io/nuc"
              operator: "Exists"
              effect: "NoSchedule"
