apiVersion: platform.${publicDomain}/v1alpha1
kind: ProxmoxIdentity
metadata:
  name: crossplane
spec:
  user: crossplane@pve
  passwordSecretRef:
    namespace: crossplane-system
    name: crossplane-credentials
    key: password
  userGroups:
    - crossplane
  aclPath: /
  tokenName: crossplane
  groupName: crossplane
  roleName: crossplane
  privileges:
    - Sys.Audit
    - Sys.Modify
    - Group.Allocate
    - Realm.AllocateUser
    - Permissions.Modify
    - User.Modify
  groupRoles:
    - crossplane
