apiVersion: platform.shokohsc.com/v1alpha1
kind: ProxmoxRole
metadata:
  name: crossplane
spec:
  role: crossplane
  privileges:
    - Datastore.Allocate
    - Datastore.AllocateSpace
    - Pool.Allocate
    - VM.Allocate
    - VM.Clone
    - VM.Config.CDROM
    - VM.Config.CPU
    - VM.Config.Cloudinit
    - VM.Config.Disk
    - VM.Config.Memory
    - VM.Config.Network
    - VM.Config.Options
    - VM.Config.HWType
    - VM.PowerMgmt
    - VM.Console
    - SDN.Use
    - Sys.Audit
# ---
# apiVersion: platform.shokohsc.com/v1alpha1
# kind: ProxmoxGroup
# metadata:
#   name: crossplane
# spec:
#   group: crossplane
#   roles:
#     - crossplane
---
apiVersion: platform.shokohsc.com/v1alpha1
kind: ProxmoxUser
metadata:
  name: crossplane
spec:
  user: crossplane@pve
  passwordSecretRef:
    namespace: crossplane-system
    name: crossplane-credentials
    key: password
  groups:
    - crossplane
  aclPath: /
---
apiVersion: platform.shokohsc.com/v1alpha1
kind: ProxmoxToken
metadata:
  name: crossplane
spec:
  name: crossplane
  user: crossplane@pve
