---
apiVersion: virtualenvironmentcontainer.proxmoxbpg.crossplane.io/v1alpha1
kind: EnvironmentContainer
metadata:
  name: roadhog-nfs
spec:
  forProvider:
    description: Managed by Crossplane
    features:
      - nesting: true
    mountPoint:
      - path: /mnt/shared
        volume: /mnt/bindmounts/shared
    networkInterface:
      - name: veth0
    nodeName: roadhog
    unprivileged: true
    startup:
      - order: "5"
  providerConfigRef:
    name: proxmox
