---
apiVersion: virtualenvironmentcontainer.proxmoxbpg.crossplane.io/v1alpha1
kind: EnvironmentContainer
metadata:
  name: genji-nfs
spec:
  forProvider:
    description: Managed by Crossplane
    # mountPoint:
    #   - path: /mnt/data
    #     volume: tank/my_dataset
    networkInterface:
      - name: veth0
    nodeName: genji
    startup:
      - order: "5"
    tags:
      - nfs
      - crossplane
  providerConfigRef:
    name: proxmox
