apiVersion: virtualenvironmentvm.proxmoxbpg.crossplane.io/v1alpha1
kind: EnvironmentVM
metadata:
  name: windows-ten-ltsc
spec:
  forProvider:
    agent:
      - enabled: true
    cpu:
      - cores: 4
        sockets: 4
        type: host
    description: Managed by Crossplane
    disk:
      - datastoreId: local-lvm
        size: 100
        interface: virtio0
        fileFormat: raw
        iothread: true
    cdrom:
      - enabled: true
        fileId: local:iso/windows-ten.iso
        interface: ide2
    bootOrder:
      - scsi0
      - ide2
    machine: q35
    onBoot: false
    hostpci:
      device:
        id:
        xvga: true
    # kvmArguments:
    memory:
      - dedicated: 4096
    name: windows-ten-ltsc
    networkDevice:
      - bridge: vmbr1
        model: virtio
        enabled: true
        vlanId: 50
    nodeName: roadhog
    tags:
      - crossplane
      - windows
  providerConfigRef:
    name: proxmox
