---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: valkiriaaquaticamendi-provider-proxmox-bpg
spec:
  package: xpkg.upbound.io/valkiriaaquaticamendi/provider-proxmox-bpg:v1.15.0
  runtimeConfigRef:
    name: enable-psa
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: enable-psa
spec:
  deploymentTemplate:
    spec:
      revisionHistoryLimit: 0
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                capabilities:
                  drop:
                    - ALL
              resources:
                limits:
                  cpu: 100m
                  memory: 64Mi
