---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-opentofu
spec:
  package: xpkg.upbound.io/upbound/provider-opentofu:v1.1.4
  runtimeConfigRef:
    name: enable-psa
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: enable-psa
spec:
  deploymentTemplate:
    spec:
      revisionHistoryLimit: 0
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                capabilities:
                  drop:
                    - ALL
              env:
                - name: TF_VAR_proxmox_ve_username
                  valueFrom:
                    secretKeyRef:
                      name: creds
                      key: username
                - name: TF_VAR_proxmox_ve_password
                  valueFrom:
                    secretKeyRef:
                      name: creds
                      key: password
              resources:
                requests:
                  cpu: 10m
                  memory: 64Mi
                limits:
                  cpu: 1000m
                  memory: 512Mi
              volumeMounts:
                - mountPath: /etc/ssl/cert.pem
                  subPath: ca-certs.pem
                  name: tls
                - mountPath: /tmp
                  name: work
          volumes:
            - name: tls
              configMap:
                name: homelab-ca
                defaultMode: 0600
            - name: work
              emptyDir:
                medium: Memory
          tolerations:
            - key: "node.kubernetes.io/nuc"
              operator: "Exists"
              effect: "NoSchedule"
