---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: valkiriaaquaticamendi-provider-proxmox-bpg
spec:
  package: xpkg.upbound.io/valkiriaaquaticamendi/provider-proxmox-bpg:v1.15.0
  runtimeConfigRef:
    name: enable-psa
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: enable-psa
spec:
  deploymentTemplate:
    spec:
      revisionHistoryLimit: 0
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                capabilities:
                  drop:
                    - ALL
              resources:
                requests:
                  cpu: 10m
                  memory: 64Mi
                limits:
                  cpu: 1000m
                  memory: 256Mi
              volumeMounts:
                - mountPath: /etc/ssl/certs
                  name: tls
                - mountPath: /tmp
                  name: work
          volumes:
            - name: tls
              configMap:
                name: homelab-ca
                defaultMode: 0600
            - name: work
              emptyDir:
                medium: Memory
          tolerations:
            - key: "node.kubernetes.io/nuc"
              operator: "Exists"
              effect: "NoSchedule"
