apiVersion: v1
kind: Secret
metadata:
    name: creds
type: Opaque
stringData:
    credentials: ENC[AES256_GCM,data:HvdxcTleE46J4chwmKpkamJ+htEhGz0NVk1rfW5ZfaMC21tfw0SNujsMhEPbfS1PcKn7Nue6TYBXlZG8ALMMv2sHHHvoPDqXGRI9vWDKwpArnD45gTaoNcsSR1njjUapE2iA3KNCmpAi,iv:7UuIcq9ROOV61mB2gOkaHzgBIbziwDg2+MHEBM2yspw=,tag:moCJtRdl64S+4XFlxGTI4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-06-10T15:21:21Z'
    mac: ENC[AES256_GCM,data:+SXWzrk5DWT3wQrlUdLNKDvd6POYUnOxcibSk2P4jriC3gz+1IIkmo9nXFul/QYWNwqO0Vd6m7iXgC04xjMaj31rTMk2S0tn6TkZR8gWZKTX1DPtYh1wqoo1ugFHdJpmOWAJRNC5JToVYnzM1Bwz6mVu7T5INPTMXdrajk5+5Xo=,iv:XAEae3gkztHgQlBOFNMrYFhWXpmx26RScHOUNhlDDmY=,tag:+Q3m7mo28OPTAMUqhhOxOw==,type:str]
    pgp:
    -   created_at: '2026-06-10T15:21:20Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAXTll5J1ACWLxnqA63ERDb1AvHNhcN0YN2MFAYs/f0zsw
            5/oq48ZVhWapTb2FHTjHGlpMbcVspfKf++mEtXU2Dyb1Q9shIrY1SOyyD6MC+tAq
            0l4BTtBR9FrBbfyDiJMMmBdymfvxrmiRK7lH+TZzAmCtCXuihfFISnQRjjf4qt8B
            87QPibhoTe4RkdlvgtYkjVKBCitQ2BUz/Ej++39QS2bJ5OBs3ZP/OWKZKeNHLg6x
            =kWcA
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
