apiVersion: v1
data:
    username: ENC[AES256_GCM,data:VPBQy/iRyqtaE8RQKMbKYVDIBeg=,iv:ghoWIhYcmW3kox86fW7zXC8SwUZCmClNGM97tJwSKSc=,tag:hSetp4assRddU+Ejx0ytrg==,type:str]
    password: ENC[AES256_GCM,data:DPEqKMLsNPJvW+xhqWBWRw==,iv:59nmL/geoEIiNVUpBYmZoopMJUYZWMfZMTiu792067c=,tag:v4sAzVuPZg57fZgawGeHJw==,type:str]
kind: Secret
metadata:
    name: crossplane-credentials
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-10T08:53:22Z'
    mac: ENC[AES256_GCM,data:zu9djNatvqzvSVHzR8wWwAY22SYneS/4FY9+CMTLxqXyjZjsb5Mf9udn5DuSqfteGgHoD9tbR2oMgyMfIL52+4qGPpNIjILh9j9g9V1frFmVIMbN7iFS3JiOxYW9iG+GXUYdrXwFpGOhqJY17mYAsbk91FpkoEW7Tof1rVspH28=,iv:g+d476+yMwxgo7Bk7zrRSv3eddYNwfCpWhT4Bc2ZTCA=,tag:8t1SLUNANk7CSCYAt29B1Q==,type:str]
    pgp:
    -   created_at: '2026-07-10T08:53:21Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAzJRceiRuSYMTB/+4+VaB7ZrXF8fiGTh0XAt3ZcpEgk8w
            KZ41Q+icHy5T1P3Ay/Idj+LhXAbN8FjGumktI6FCaS6smbE4WTMst9AN9gMMgXfO
            0l4Bdf1eFb4+wP+DcgJk078Xa5IBJp2O2HI2JCopxhTr7eWCQttXNKKilSnmpIeR
            SU/RPNLiFpXNHBDVS+FS7qGF/MuBFw+QNs0guslHwYFzrelmmGx9DRvsn53l6S3E
            =1R62
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:+rwiQPNQzzuIv9xu,iv:zSIcuTr/9i1jCQVyr7TI8YJZznZ3IC9V3Tl5YYEk6YU=,tag:VakqBDAjtHDKbrb++bKySw==,type:str]
    password: ENC[AES256_GCM,data:m/P3iWPv7VyDn2Ic,iv:tJf4XaOrH8kWb6cqPpYad4vp0Yn+suyf+Da4Te5zYGE=,tag:npcpdXb7IbSTUWuGxQRtgQ==,type:str]
kind: Secret
metadata:
    name: root-credentials
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-10T08:53:22Z'
    mac: ENC[AES256_GCM,data:zu9djNatvqzvSVHzR8wWwAY22SYneS/4FY9+CMTLxqXyjZjsb5Mf9udn5DuSqfteGgHoD9tbR2oMgyMfIL52+4qGPpNIjILh9j9g9V1frFmVIMbN7iFS3JiOxYW9iG+GXUYdrXwFpGOhqJY17mYAsbk91FpkoEW7Tof1rVspH28=,iv:g+d476+yMwxgo7Bk7zrRSv3eddYNwfCpWhT4Bc2ZTCA=,tag:8t1SLUNANk7CSCYAt29B1Q==,type:str]
    pgp:
    -   created_at: '2026-07-10T08:53:21Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAzJRceiRuSYMTB/+4+VaB7ZrXF8fiGTh0XAt3ZcpEgk8w
            KZ41Q+icHy5T1P3Ay/Idj+LhXAbN8FjGumktI6FCaS6smbE4WTMst9AN9gMMgXfO
            0l4Bdf1eFb4+wP+DcgJk078Xa5IBJp2O2HI2JCopxhTr7eWCQttXNKKilSnmpIeR
            SU/RPNLiFpXNHBDVS+FS7qGF/MuBFw+QNs0guslHwYFzrelmmGx9DRvsn53l6S3E
            =1R62
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
