apiVersion: v1
stringData:
    crossplane: ENC[AES256_GCM,data:PyuggEQ4yvxRket8I2UgNDRJ+c5+x4+JOsNBKDX0LXwQxHXnWRwN1P3J0+pdFWO80vDIPqCI2zg58Qb1ImHV+QQ6w2C9NJ0fkagLNvaJW/ls0n9GOOBuQ8YUTmS8qtTydLuGgKjjPk1zZN1VLVYEyU9S+L2FQj4o69FT/44Vg6wFe+xBvxY=,iv:O0IR362NQ624+TBwNiEZYw7k2oOcH2v/c4708l+cOs0=,tag:UU3HX0QkCrkTb46X0sWgUw==,type:str]
    root: ENC[AES256_GCM,data:4hNEZyTWPb74WE546oOOBGw0FRe0ZyA1+eOO+NblhovS9Fel14rBb7NjNQ4/SitG7e9Ka3yTbMjsdFwHQSXAe83w5MRAKV/3W1oS+ZvYBWgNsB4kVwO3VnLMQ4xN4LY1hXRtrzUWJBtTkviYWCCAhuJK9SSrQKNJbQsYwWAZ,iv:vzdkePaKMkLGh3lF63UveeB/5lufTQ8f91KpE2iRPic=,tag:2hHxDHz5I/l/Zjsmq5Qqow==,type:str]
kind: Secret
metadata:
    name: creds
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-09T19:19:24Z'
    mac: ENC[AES256_GCM,data:DBGELq6LyZopn65nFo56yzjgOiOoKEvMMp53nsmtCq46a8tuzgZmHvrBZZ/78RVAvaycBic4U1ISOuT0ctWXsKJZ8hz8JdGly/FyYVvo9U2svAW8wDt/ghyHLRujF39nacTlUftLTleUSj1a8k0Mcid2iRQ13OWbihNVjmb0zXY=,iv:fmB6UrCy67/nntdkmQ5erEnwUb8cEs6GHvn/57qbpIU=,tag:selET46/g+uqXcu4xjSlqA==,type:str]
    pgp:
    -   created_at: '2026-07-09T19:19:23Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAtpEnre1NAv2oUtkvicXLwtfp24lAk+XVVR4+UfQCIwQw
            1mlxYUFfWqzieYUL73zfDJiRlfeFqrDqlIIVb5dEsCoOQY8pBcjsPB74aBh0LaBT
            0lEBDmg+3T0fuhdhUnWGdt1KV/MEUMNJ20qSACYPtOzZFtWtAipMK7GSb/MSPZqh
            5+GWq7JQTq80W0Hg3W+5IGz9vDV2iP+OaBSkTE80tk1nEKI=
            =r46/
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:yC+8kwVt+CsmxhSAYq14Qg==,iv:kHDpG+Ms3XRs+CUPYqtFTVqXwK/EzJaDza+bbqpBttQ=,tag:hTxH7f4Zd0qi1rs0i3GKNg==,type:str]
kind: Secret
metadata:
    name: crossplane-credentials
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2026-07-09T19:19:24Z'
    mac: ENC[AES256_GCM,data:DBGELq6LyZopn65nFo56yzjgOiOoKEvMMp53nsmtCq46a8tuzgZmHvrBZZ/78RVAvaycBic4U1ISOuT0ctWXsKJZ8hz8JdGly/FyYVvo9U2svAW8wDt/ghyHLRujF39nacTlUftLTleUSj1a8k0Mcid2iRQ13OWbihNVjmb0zXY=,iv:fmB6UrCy67/nntdkmQ5erEnwUb8cEs6GHvn/57qbpIU=,tag:selET46/g+uqXcu4xjSlqA==,type:str]
    pgp:
    -   created_at: '2026-07-09T19:19:23Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DFjJ7f9c9iWkSAQdAtpEnre1NAv2oUtkvicXLwtfp24lAk+XVVR4+UfQCIwQw
            1mlxYUFfWqzieYUL73zfDJiRlfeFqrDqlIIVb5dEsCoOQY8pBcjsPB74aBh0LaBT
            0lEBDmg+3T0fuhdhUnWGdt1KV/MEUMNJ20qSACYPtOzZFtWtAipMK7GSb/MSPZqh
            5+GWq7JQTq80W0Hg3W+5IGz9vDV2iP+OaBSkTE80tk1nEKI=
            =r46/
            -----END PGP MESSAGE-----
        fp: CA2DD399363326254636047B16327B7FD73D8969
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
